### ISSUE TITLE
No intellisense for file.write

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/python-language-server#1000]
@xiaofeng0123 commented on [Mon Apr 22 2019](https://github.com/Microsoft/vscode-python/issues/5399)

Visual Studio Code - Insiders: 1.34.0-insider
python-insider: 2019.4.6962-rc
python version: Python 3.7.3 64bit
Install Anaconda

Repro steps:
1.Git clone https://github.com/qubitron/pydemo
2.Open Anaconda Prompt window
3.Cd pydemo
4.Run py -3 setup.py
5.Set "python.jediEnabled" to "false" in "Settings.json"
6. Create a new folder named "newapp" and open this folder
7. Create a virtual env using "py -3 -m venv env"
8. Set current python environment to virtual env
9. Install "requests" package
10. Create a py file named "stackoverflow.py"
11. Input below code:
import requests
request=requests.get("https://drive.google.com/uc?export=download&id=1_9On2-nsBQIw3JiY43sWbrF8EjrqrR4U")
with open("survey2017.zip","wb") as file:
      file.write

Actual Result:
No intellisense for file.write
![image](https://user-images.githubusercontent.com/41426540/56491527-73a18b80-651b-11e9-8711-5972fed5d711.png)

Expect Result:
Completion for file.write should be shown
![image](https://user-images.githubusercontent.com/41426540/56491645-d1ce6e80-651b-11e9-854b-33abb61c3c46.png)

**Comment by jakebailey** [comment]
This was #997, but @xiaofeng0123 closed it.
