### ISSUE TITLE
Python Tools Server crashing due to libssl in Ubuntu 19.04 when used with VS Code Python Extension

### ISSUE THREAD

**Issue by ahnafalrafi** [Microsoft/python-language-server#1005]
- VS Code version: 1.33.1
- Extension version: 2019.3.6558
- OS and version: Ubuntu 19.04, Kernel: 5.0.0-13-generic
- Python version: 3.7.3

### Expected behavior

Python file opened, server starts with no crashes. Intellisense works properly

### Actual behavior

Python file opened. Python tools server crashes 5 times within 3 minutes and is not restarted anymore. Intellisense does not work

### Steps to reproduce:

1.  Open python file with python estension installed

### Logs

Starting Microsoft Python language server.
No usable version of the libssl was found
[Info  - 1:35:45 PM] Connection to server got closed. Server will restart.
No usable version of the libssl was found
[Info  - 1:35:45 PM] Connection to server got closed. Server will restart.
No usable version of the libssl was found
[Info  - 1:35:46 PM] Connection to server got closed. Server will restart.
No usable version of the libssl was found
[Info  - 1:35:47 PM] Connection to server got closed. Server will restart.
No usable version of the libssl was found
[Error - 1:35:47 PM] Connection to server got closed. Server will not be restarted.

### Extra Information

I checked to see if libssl was installed: yes, with both libssl1.1 and libssl-dev. I believe the last comment in [Issue #474](https://github.com/Microsoft/python-language-server/issues/474) about libssl1.0 being required is what is causing this

**Comment by jakebailey** [comment]
The language server is written in C# and compiled using the .NET Core toolchain; we are limited by what they support. We can't really do anything about this until that toolchain updates other than to recommend installing the right libraries, which includes libssl1.0 for now.

**Comment by jakebailey** [comment]
See also: dotnet/core#2526

**Comment by jakebailey** [comment]
Seems like dotnet/core#2555 says 2.2.106 is available; I'm going to try a build and push to all of the channels if it succeeds.

**Comment by jakebailey** [comment]
0.2.62 has been published to all channels, and has been built with 2.2.106, which should handle libssl1.1 just fine (tested on my machines).
