### ISSUE TITLE
No usable version of the libssl was found

### ISSUE THREAD

**Issue by Tiedye** [Microsoft/python-language-server#1006]
Getting this error when starting vscode

```
No usable version of the libssl was found
Connection to server got closed. Server will restart.
```

<details>
<summary>Version Info</summary>
Extension version: 2019.3.6558
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 5.0.0-13-generic
</details>
<details>
<summary>System Info</summary>
Ubuntu 19.04 (Pop_!OS)

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 3088)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.44GB (0.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by jakebailey** [comment]
#1005, #474

**Comment by Tiedye** [comment]
This seems related Microsoft/vscode-python#2211

**Comment by Tiedye** [comment]
Ha 4 mins to slow
