### ISSUE TITLE
LS getting out of sync with text buffer and showing errors

### ISSUE THREAD

**Issue by qubitron** [microsoft/python-language-server#1009]
Gives me unresolved errors on older version of the text:
![image](https://user-images.githubusercontent.com/17804393/56631271-711d5f80-6609-11e9-9fa6-422f5e0039b9.png)

Version 0.2.62.0

**Comment by MikhailArkhipov** [comment]
https://github.com/microsoft/python-language-server/pull/1227 probably fixed this as it was possible to try and retrieve document content while document was being updates as a result of editing. Please reopen if you see this in 0.3.18+ builds
