### ISSUE TITLE
microsoft.python.languageserver CPU usage +350%!!! on MacOSX

### ISSUE THREAD

**Issue by NiNJAD3vel0per** [Microsoft/python-language-server#1021]
**microsoft.python.languageserver CPU usage +350%!!! on MacOSX**

**VScode version: Version 1.33.1 (1.33.1)**

I know this is known issue, but there is no proper solution to resolve this issue on Macos.

How can I turn off microsoft.python.languageserver? this is  buggy like Windows95/98/XP/7 !!!

**Comment by MikhailArkhipov** [comment]
Try setting `python.jediEnabled` to `true`. Otherwise folding into #891.
