### ISSUE TITLE
Go to defintion not working with transitive imports 

### ISSUE THREAD

**Issue by thomasgassmann** [microsoft/python-language-server#1028]
I have a setup similar to the following:

**`a.py`:**
```python
from b import Foo

Foo().bar()
```

**`b.py`:**
```python
from c import Foo
```

**`c.py`:**
```python
class Foo:

    def bar(self):
        pass
```

With an import like this, the Python Language Server says `No defintiion found for bar`, even though it shows up with IntelliSense.

![image](https://user-images.githubusercontent.com/16067344/56991050-0931c080-6b97-11e9-843c-e1034420e52c.png)

![image (1)](https://user-images.githubusercontent.com/16067344/56991047-0767fd00-6b97-11e9-8a88-06c74a39fa9c.png)

**Comment by starship863** [comment]
I have similar problem. But in my case, the go to definition does not work for any imports, not only the transitive imports.

The intellisense works in my case. It is really strange that only the go to definition is not working.

**Comment by starship863** [comment]
> I have similar problem. But in my case, the go to definition does not work for any imports, not only the transitive imports.
> 
> The intellisense works in my case. It is really strange that only the go to definition is not working.

Update: my issue is resolved in daily build 0.2.67

**Comment by MikhailArkhipov** [comment]
Most probably #1064

**Comment by MikhailArkhipov** [comment]
Appears to work, most probably fixed by https://github.com/microsoft/python-language-server/pull/1065
