### ISSUE TITLE
Analysis never completes if user code continues to be modified

### ISSUE THREAD

**Issue by jakebailey** [microsoft/python-language-server#1034]
```python
import tensorflow as tf
tf.nn.max_pool()
tf.keras.layers
```

Once the LS starts, keep hitting `.` then backspace to trigger completion on `tf.keras.layers`. At about 15 seconds, the names appear, but after that the analysis is stuck at the same number of items remaining until things stop being modified and the analysis is allowed to complete.

The log is filled with lots of these:

```
Analysis version 1709 has been completed in 7878.7207 ms with 902 entries analyzed and 418 entries skipped.
Analysis version 3311 has been completed in 1469.8799 ms with 805 entries analyzed and 1635 entries skipped.
Analysis version 3317 has been completed in 216.9737 ms with 108 entries analyzed and 2162 entries skipped.
Analysis version 3318 has been completed in 769.442 ms with 492 entries analyzed and 1764 entries skipped.
```

**Comment by AlexanderSher** [comment]
Analysis completes, but contains modules that aren't needed: https://github.com/microsoft/python-language-server/issues/975
