### ISSUE TITLE
Difference in results.

### ISSUE THREAD

**Issue by CMLL** [microsoft/python-language-server#1035]
I've noticed sometimes that the completion results vary sometimes after a long time since a LS reload. I notice this from time to time, but this is the latest that I remember to took a shot of the issue to open an issue. 

It occurs from time to time, but not pretty often, and I think is related to how long a code instance is open and how many files get opened and closed. Easiest way to clear it is by doing a window reload, and the the LS process will show the correct completions after the analysis is done.

![2019-05-01_22-37](https://user-images.githubusercontent.com/3720126/57048724-b1618b00-6c64-11e9-951d-0a59b91856b0.png)

![2019-05-01_22-38](https://user-images.githubusercontent.com/3720126/57048725-b32b4e80-6c64-11e9-8fc8-45329e9b55ba.png)

I know is pretty vague information, but is a pretty hard bug to reproduce. I'll try to gather more info on this in the future.

I'm using 2 extra values to internal libraries in the `python.autoComplete.extraPaths`

**Comment by jakebailey** [comment]
That first screenshot looks like completion for the global scope, which may be a desync like in #1012 or #1009.

**Comment by MikhailArkhipov** [comment]
Desync was fixed some time ago.
