### ISSUE TITLE
Both Python language server and Jedi language engine started

### ISSUE THREAD

**Issue by ClodoaldoPinto** [Microsoft/python-language-server#1037]
VS Code 1.33.1 
Python 3.7.3
Python extension 2019.4.12954
Windows 10 Enterprise 1709 16299.1087
Behind an enterprise proxy

The Python extension log shows both Python language server and Jedi Python language engine starting:
Starting Microsoft Python language server.
Starting Jedi Python language engine.

Are both really running? How do I find out?

**Comment by MikhailArkhipov** [comment]
Usually you'd see `Microsoft.Python.LanguageServer*` process running (or `dotnet Microsoft.Python.LanguageServer.dll` if it is a debug build.

**Comment by ClodoaldoPinto** [comment]
> Usually you'd see `Microsoft.Python.LanguageServer*` process running (or `dotnet Microsoft.Python.LanguageServer.dll` if it is a debug build.

I don't see those processes in the task manager.

**Comment by jakebailey** [comment]
I've seen this happen a number of times on my machine. I believe that the extension will fall back to Jedi if it thinks the LS didn't start. Reloading "fixes" it, but I haven't been able to reliably reproduce it to know what's going on. It's hard to say if we're crashing, or if the extension has a bug.

**Comment by ClodoaldoPinto** [comment]
[-1556829371516.log](https://github.com/Microsoft/python-language-server/files/3139864/-1556829371516.log)

**Comment by MikhailArkhipov** [comment]
Sounds like
```
[Extension Host] Python Extension: Get language server folder name, Class name = f, Arg 1: <Uri:c:\Users\deafi.clodoaldo\Documents\Visual Studio Code\Python\filecmp.py>, Return Value: undefined TypeError: Cannot read property 'version' of undefined
	at f.getLanguageServerFolderName (C:\Users\deafi.clodoaldo\.vscode\extensions\ms-python.python-2019.4.12954\out\client\extension.js:83:112747)
	at process._tickCallback (internal/process/next_tick.js:68:7)
t.log @ console.ts:134
console.ts:134 [Extension Host] Python Extension: Failed to ensure language server is available, Class name = p, Arg 1: <Uri:c:\Users\deafi.clodoaldo\Documents\Visual Studio Code\Python\filecmp.py>, Return Value: undefined TypeError: Cannot read property 'version' of undefined
	at f.getLanguageServerFolderName (C:\Users\deafi.clodoaldo\.vscode\extensions\ms-python.python-2019.4.12954\out\client\extension.js:83:112747)
	at process._tickCallback (internal/process/next_tick.js:68:7)
t.log @ console.ts:134
console.ts:134 [Extension Host] Python Extension: Failed to activate language server, Class name = p, Arg 1: <Uri:c:\Users\deafi.clodoaldo\Documents\Visual Studio Code\Python\filecmp.py>, Return Value: undefined TypeError: Cannot read property 'version' of undefined
	at f.getLanguageServerFolderName (C:\Users\deafi.clodoaldo\.vscode\extensions\ms-python.python-2019.4.12954\out\client\extension.js:83:112747)
	at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by DonJayamanne** [comment]
@ClodoaldoPinto
Looks like something had give wrong with the install.
Please could you uninstall the python extension, exit VSCode completely, or delete the folder `C:\Users\deafi.clodoaldo\.vscode\extensions\ms-python.python-2019.4.12954` then reinstall the extension.

**Comment by jakebailey** [comment]
For what it's worth, this happens to me a couple times a week with a local copy, and reloading fixes it every time; no reinstallation or recopying anything.

**Comment by ClodoaldoPinto** [comment]
Reinstalled and the further I can go is with "http.proxyStrictSSL": false and "http.proxySupport": "override" where it fails to download but shows the path to the language server package:

[-1556891577790.log](https://github.com/Microsoft/python-language-server/files/3142171/-1556891577790.log)

I can download  http://pvsc.azureedge.net/python-language-server-stable/Python-Language-Server-win-x64.0.2.66.nupkg from the browser but can't find out how to install it from file.

**Comment by ClodoaldoPinto** [comment]
> I can download http://pvsc.azureedge.net/python-language-server-stable/Python-Language-Server-win-x64.0.2.66.nupkg from the browser but can't find out how to install it from file.
Is there a vsix version of that file?

**Comment by ClodoaldoPinto** [comment]
I managed to get it working by using a mobile connection.

**Comment by MikhailArkhipov** [comment]
Since this is really Python extension issue as LS does not download itself :-) Can you please open an issue wat https://github.com/Microsoft/vscode-python/issues

**Comment by MikhailArkhipov** [comment]
@ClodoaldoPinto - since Ls not an extension, there is no vsix. However, nupkg is just a zip and all the extension does is unpacking it into `languageServer.0.2.*` folder. Just `languageServer` would also work but the extension won't be able to track the version.
