### ISSUE TITLE
Missing keys datetime and time.

### ISSUE THREAD

**Issue by CMLL** [microsoft/python-language-server#1039]
Noticed that I was getting some unresolved datetime and time imports. Enabled trace logging and found this alert on the logs after the analysis is done.

![image](https://user-images.githubusercontent.com/3720126/57109704-b0446280-6d25-11e9-9549-78fe67ef723d.png)

![image](https://user-images.githubusercontent.com/3720126/57109745-d0742180-6d25-11e9-80a0-0670c15a5a39.png)

Seems to be missing Typeshed pyi file for some libraries. Weirdly some of the alerts that the log mentions do work correctly, eg, simplejson and fnmatch.

![image](https://user-images.githubusercontent.com/3720126/57109829-0a452800-6d26-11e9-8d3c-3acda4fc7e66.png)

I'm using Python 2.7.15 on a virtualenv with 0.2.71 LS version. A reload fixed the issue for datetime and time modules.

**Comment by mdalpi** [comment]
![](https://user-images.githubusercontent.com/6289699/57324245-e2671300-70dd-11e9-8954-e0a8580204b4.png)

Getting almost the same, so far problems with `time` and `itertools`
Language Server 0.2.66.0
Python 3.7.3

**Comment by AlexanderSher** [comment]
@mdalpi, can you check on Language Server 0.2.74 from beta channel if the issue is still there?

**Comment by mdalpi** [comment]
> @mdalpi, can you check on Language Server 0.2.74 from beta channel if the issue is still there?

No issues on 0.2.74 so far. 😄
