### ISSUE TITLE
Opening second file with PyQt5 import reanalyzes more than it should

### ISSUE THREAD

**Issue by jakebailey** [microsoft/python-language-server#1049]
Using the example in #821, create a conda environment (venv might work) with the specified packages. Add one file with the contents specified in that issue. In a second file, do:

```python
from PyQt5 import QtCore

QtCore.QProcess()
```

Now, start VSC with the first file open (the one that imports pandas). The analysis runs and completes, analyzing PyQt5 in the process.

Open the second file, and PyQt5, pandas, and more are all reanalyzed again (and the memory usage increases, though that's inconsistent).

Log:

[pandas-pyqt5-log.txt](https://github.com/Microsoft/python-language-server/files/3149573/pandas-pyqt5-log.txt)

**Comment by AlexanderSher** [comment]
Is it on the latest master?

**Comment by jakebailey** [comment]
Yep, found this while doing some profiling.
