### ISSUE TITLE
Language server crashes with in application dependencies manifest error

### ISSUE THREAD

**Issue by qubitron** [microsoft/python-language-server#1054]
```
Starting Microsoft Python language server.
Error:
  An assembly specified in the application dependencies manifest (Microsoft.Python.LanguageServer.deps.json) was not found:
    package: 'runtime.win-x64.Microsoft.NETCore.App', version: '2.2.4'
    path: 'runtimes/win-x64/lib/netcoreapp2.2/System.Linq.Parallel.dll'
[Info  - 8:26:59 PM] Connection to server got closed. Server will restart.
```
That happens 5 times and language server doesn't start.

This is on insiders:
```
Version: 1.34.0-insider (user setup)
Commit: 473af338e1bd9ad4d9853933da1cd9d5d9e07dc9
Date: 2019-05-01T00:22:05.899Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
```

Python extension version 2019.4.12954.

**Comment by qubitron** [comment]
Looks like this is triggered when editing and saving a .env file in the workspace root

**Comment by jakebailey** [comment]
As far as I know, there shouldn't be a link between those two, except that the extension should restart the LS when the environment changes (as the extension starts the LS with all of the specified environment variables).

Can you try deleting your language server download and letting the extension redownload it?

**Comment by qubitron** [comment]
Now I'm getting a different error when editing and saving the .env file, I get a "Connection got disposed" message popping up.

```
Starting Microsoft Python language server.
Downloading https://pvsc.azureedge.net/python-language-server-stable/Python-Language-Server-win-x64.0.2.66.nupkg... complete
Unpacking archive... done
[Info  - 9:29:58 AM] GetCurrentSearchPaths C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1008.0_x64__qbz5n2kfra8p0\python.exe 
[Info  - 9:29:59 AM] Python search paths:
[Info  - 9:29:59 AM]     c:\program files\windowsapps\pythonsoftwarefoundation.python.3.7_3.7.1008.0_x64__qbz5n2kfra8p0\dlls
[Info  - 9:29:59 AM]     c:\program files\windowsapps\pythonsoftwarefoundation.python.3.7_3.7.1008.0_x64__qbz5n2kfra8p0\lib
[Info  - 9:29:59 AM]     c:\program files\windowsapps\pythonsoftwarefoundation.python.3.7_3.7.1008.0_x64__qbz5n2kfra8p0
[Info  - 9:29:59 AM]     c:\users\dantaylo\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages
[Info  - 9:29:59 AM]     c:\program files\windowsapps\pythonsoftwarefoundation.python.3.7_3.7.1008.0_x64__qbz5n2kfra8p0\lib\site-packages
[Info  - 9:29:59 AM] Configuration search paths:
[Info  - 9:30:02 AM] Microsoft Python Language Server version 0.2.66.0
[Info  - 9:30:02 AM] Initializing for C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1008.0_x64__qbz5n2kfra8p0\python.exe
[Info  - 9:30:24 AM] GetCurrentSearchPaths C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1008.0_x64__qbz5n2kfra8p0\python.exe 
[Info  - 9:30:25 AM] Python search paths:
[Info  - 9:30:25 AM]     c:\program files\windowsapps\pythonsoftwarefoundation.python.3.7_3.7.1008.0_x64__qbz5n2kfra8p0\dlls
[Info  - 9:30:25 AM]     c:\program files\windowsapps\pythonsoftwarefoundation.python.3.7_3.7.1008.0_x64__qbz5n2kfra8p0\lib
[Info  - 9:30:25 AM]     c:\program files\windowsapps\pythonsoftwarefoundation.python.3.7_3.7.1008.0_x64__qbz5n2kfra8p0
[Info  - 9:30:25 AM]     c:\users\dantaylo\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages
[Info  - 9:30:25 AM]     c:\program files\windowsapps\pythonsoftwarefoundation.python.3.7_3.7.1008.0_x64__qbz5n2kfra8p0\lib\site-packages
[Info  - 9:30:25 AM] Configuration search paths:
[Error - 9:30:26 AM] Server initialization failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\dantaylo\.vscode-insiders\extensions\ms-python.python-2019.4.12954\out\client\extension.js:1:111388)
	at Object.dispose (C:\Users\dantaylo\.vscode-insiders\extensions\ms-python.python-2019.4.12954\out\client\extension.js:1:187369)
	at module.exports.t.BaseLanguageClient.stop._connectionPromise.state.g.Stopping._onStop._onStop.resolveConnection.then.e.shutdown.then (C:\Users\dantaylo\.vscode-insiders\extensions\ms-python.python-2019.4.12954\out\client\extension.js:1:184420)
[Error - 9:30:27 AM] Server initialization failed.
```

Clone this repo: https://github.com/Microsoft/python-sample-tweeterapp
Copy .env-sample to .env
Edit .env file save, repeat a few times and the error pops up.

**Comment by jakebailey** [comment]
I think this is an extension bug, two language servers got started and one was thrown away.

**Comment by jakebailey** [comment]
https://github.com/microsoft/vscode-python/blob/f590f9c89ae5ee31f33bc66626e9f8279ea17763/src/client/activation/languageServer/analysisOptions.ts#L49

But, it should be getting debounced, and your `.env` file doesn't contain `PYTHONPATH`, so it should end up getting ignored anyway. `const envPythonPath = vars.PYTHONPATH;` probably should have been `const envPythonPath = vars.PYTHONPATH || '';`, though...

**Comment by qubitron** [comment]
@DonJayamanne should we move this to the extension per jake's comments?

**Comment by DonJayamanne** [comment]
> I think this is an extension bug, two language servers got started and one was thrown away.

We don't start two servers anymore.
We kill existing instances before starting a new instance.

> But, it should be getting debounced

Yes, it is getting debounced.

> probably should have been const envPythonPath = vars.PYTHONPATH || '';, though.

Agreed. But this should not be the cause of the original problem. As we do resolve it as being an empty string, see here (where it is used):
```python
this.envPythonPath = vars.PYTHONPATH || '';
        if (this.envPythonPath !== '') {
            const paths = this.envPythonPath.split(this.pathUtils.delimiter).filter(item => item.trim().length > 0);
            searchPaths.push(...paths);
        }
```
https://github.com/microsoft/vscode-python/blob/f590f9c89ae5ee31f33bc66626e9f8279ea17763/src/client/activation/languageServer/analysisOptions.ts#L95

> Server initialization failed

@jakebailey can we introduce a custom command that can be used to kill the language server gracefully. I.e. prevent it from throwing such errors when its being killed deliberately.

**Comment by qubitron** [comment]
Would it make sense to not have language server throw any error notifications at all? Unless there's an action the user can take it should fail gracefully and restart, no need to throw red notifications up, the error can still be logged to the output.

**Comment by jakebailey** [comment]
It's not the language server that's throwing errors, these messages come from the language server client that runs in the extension. This is happening because the extension is restarting the language server because it detects a configuration change (env vars cannot be changed on the fly). That change doing something is actually wrongful in your example, because PYTHONPATH is not set (so the check should just skip over), but does expose an issue where multiple LSs end up running.

What I think might be going on is that we haven't yet returned from our `initialize` call, and the extension likely issues a shutdown request, which we cannot respond to until we have returned from initialize, so something is timing out. It shouldn't take 30 seconds to do an initialize, though, so I might be wrong about how this is occurring.

See: https://github.com/microsoft/vscode-languageserver-node/blob/04c4f6549d97487375aeb4ad0a43f060fb714c0c/client/src/client.ts#L2900

**Comment by jakebailey** [comment]
@DonJayamanne I think you can just issue an `"exit"` request, and the process will exit. This is certainly not graceful, though.

**Comment by jakebailey** [comment]
I just tested, and adding `|| ''` does make it stop restarting unnecessarily, though I've been unable to get it to update so quickly as to dispose the connection. Maybe it only happens on resource constrained systems, or is related to that other thing @qubitron has been seeing where the startup takes too long.

**Comment by MikhailArkhipov** [comment]
Old issue, closing. since then .NET Core was updated to 3.1 with fewer native dependencies.
