### ISSUE TITLE
Unresolved Import

### ISSUE THREAD

**Issue by luabud** [microsoft/python-language-server#1061]
@Anti-Distinctlyminty commented on [Mon May 06 2019](https://github.com/microsoft/vscode-python/issues/5563)

## Environment data

- VS Code version: 1.33.1
- Extension version (available under the Extensions sidebar): 2019.4.12954
- OS and version: Windows_NT x64 10.0.17134
- Python version (& distribution if applicable, e.g. Anaconda): 2.7.11 64-bit

## Expected behaviour

With `python.autoComplete.extraPaths` set correctly, modules should import without issue.

## Actual behaviour

I receive a `Unresolved import 'moduleName'` when using syntax of the form
`import workspace_folder.module as alt_name`
_and_ if the .code-workspace file is in the same directory.
e.g.
![Code_2019-05-06_15-24-33](https://user-images.githubusercontent.com/1378483/57228023-16293680-7013-11e9-8a18-1f19ce5f6dac.png)

## Steps to reproduce:
1. Extract the following to a suitable location:
[myLib.zip](https://github.com/Microsoft/vscode-python/files/3148114/myLib.zip)
2. Inside myLib, open the Import_Bug.code-workspace file
3. Go to workspace settings and change the `python.autoComplete.extraPaths` to the folder containing myLib.
4. open libFunctions.py and see that `import myLib.importMe as im` has an unresolved import error.

I am aware that the organization of this workspace is sub-optimal, with the code-workspace file being inside the python library folder. However, with all paths being set correctly, the import should still succeed.

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

Blank.

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

Blank.

---

@luabud commented on [Thu May 09 2019](https://github.com/microsoft/vscode-python/issues/5563#issuecomment-491006896)

Issue moved to [microsoft/python-language-server #1060](https://github.com/microsoft/python-language-server/issues/1060) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jakebailey** [comment]
#1060?
