### ISSUE TITLE
Remove SHA1 signing

### ISSUE THREAD

**Issue by huguesv** [microsoft/python-language-server#1062]
Make the appropriate changes to sign only with SHA2 certs. See microbuild email on this topic for cert names to use.

**Comment by MikhailArkhipov** [comment]
What needs to change exactly? We don't have direct SHA references

```xml
        <Authenticode Condition="%(Extension) == '.nupkg'">NuGet</Authenticode>
        <Authenticode Condition="%(Extension) != '.nupkg'">Microsoft</Authenticode>
```

**Comment by huguesv** [comment]
`Microsoft` needs to change to `Microsoft400`
