### ISSUE TITLE
Some signatures in tooltips are unnecessarily duplicated

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/python-language-server#107]
For example, `os.path.exists`

![image](https://user-images.githubusercontent.com/12820357/45719439-3627ea80-bb55-11e8-87e1-be4c434181ee.png)

**Comment by MikhailArkhipov** [comment]
This is an issue with overloads. `exists` has multiple implementations for different platforms which causes function to look like it has multiple signatures. Second issue is with merging signatures since in some cases (such as typeshed) original function may not have parameter types and another overload come with them. This needs some improvements to overload handling as well as to comparisons. Bigger than originally thought.

**Comment by jakebailey** [comment]
This should be fixed. The original example:

![image](https://user-images.githubusercontent.com/5341706/52746222-e0d1f700-2f95-11e9-96f1-f05d8e45e12d.png)

`re.compile`, which has two overloads:

![image](https://user-images.githubusercontent.com/5341706/52747304-5b037b00-2f98-11e9-8444-83e4803e7aba.png)

Though I think we may only be displaying the first overload in the hover. That's not too much of a big deal, as `@overload` is more an artifact of backwards compatible signatures in older builtins.
