### ISSUE TITLE
isn't there something to do for PEP 570 / Python-3.8.0a4 compatibility ?

### ISSUE THREAD

**Issue by stonebig** [microsoft/python-language-server#1070]
Inside this class, with Python-3.8.0a4, there will be a new parameter:
   co_posonlyargcount # Python3.8 with PEP570

https://github.com/microsoft/python-language-server/blob/7ec9561deeb1b53cb3e24e996a5229a1015fe886/src/Analysis/Ast/Impl/Typeshed/stdlib/3/types.pyi#L39..L42

see example 
https://github.com/cloudpipe/cloudpickle/pull/267/files

**Comment by jakebailey** [comment]
We have a copy of typeshed in the repo, which just needs to be updated. Unfortunately we might have to do some preprocessing to deal with newer changes like  https://github.com/python/typeshed/commit/1fddec3f90891412322d5581c371f1955c96973f which will make the completion for parameters look pretty bad.

**Comment by jakebailey** [comment]
Note that we don't have parser support for the new `\` token for specifying the end of positional arguments, so that needs to be done first.

That CodeType is unfortunate, as it changes that type in a backwards incompatible way (much like the subject of https://bugs.python.org/issue36751 which will also break our use of `inspect`).

**Comment by stonebig** [comment]
Why don't you expose your problem on bugs.python.org ?

**Comment by jakebailey** [comment]
I'll look into opening an issue there when I have a chance.

**Comment by stonebig** [comment]
After beta1, chances are slim to get an API tweak.

**Comment by jakebailey** [comment]
I guess from our POV, the only trouble here would be if the stubs don't declare the type conditionally (and that we don't support as granular comparisons for `sys.version` as in that PR, which can be fixed).

This is in `types.pyi`, which is something we do analyze, as opposed to the `typing` module which we implement in C#. I mistakenly thought this was in `typing` at first glance, which would be a bigger issue to try and declare.

**Comment by jakebailey** [comment]
I'm going to close this in favor of #1371, since that's the actual issue.
