### ISSUE TITLE
pylint breaks silently when load-plugins=pylint_django in .pylintrc

### ISSUE THREAD

**Issue by SHxKM** [microsoft/python-language-server#1071]
After I commented the following on #129 (an important one in and of itself), I was advised by @jakebailey to file it as a bug:

> ```python 
> from django.db.models import Q  # notice F isn't imported
> #...
> cls.get_artists_with_subs().order_by(F("last_refreshed"))
> ```
> 
> VSCode doesn't see any problem with this (until we get an error when this code is run).
> 
> Pycharm, on the other hand, complains immediately:
> 
> <img width="284" alt="Screen Shot 2019-05-11 at 23 17 25" src="https://user-images.githubusercontent.com/6573474/57574508-fcd51f80-7442-11e9-9685-44cf7921a82f.png">

While adding more details to this supposed bug, I discovered that when `load-plugins=pylint_django` is present in a `.pylintrc` file - linting fails silently, and **errors aren't displayed at all** (even those unrelated to Django). I've also tried changing `pylintArgs`/`pylintPath` in my workspace settings, to no avail.

I have made sure `pylint-django` is pip installed.

**Additional details:**
At least two SO thread ([1](https://stackoverflow.com/questions/53304116/enabling-pylint-django-plugin-in-vscode-pylint-stop-working) | [2](https://stackoverflow.com/questions/54922752/pylint-load-plugins-fails-in-vs-code)) indicate I'm not alone.

**Comment by SHxKM** [comment]
This was due to a faulty .pylintrc file (no section header). It's interesting though that pylintArgs wouldn't work. I'm leaving this open if VSCode staff would like to investigate further but **for me the issue is resolved**.

**Comment by jakebailey** [comment]
I think you might be confusing the extension and the langauge server, then. The language server does not run pylint, it implements its own checks based on the analysis it does. By default, these warnings are enabled and will show. If `F` does not exist, then by default, the langauge server will give a warning (and it will be squiggled in the editor), which is what I believed you were referring to being missing.

If your issue is with pylint and its interaction with the extension (which is what those SO posts imply), you might be better off opening an issue there: https://github.com/Microsoft/vscode-python

**Comment by jakebailey** [comment]
And if you're not getting the message, that's what we're interested in, though I'd want to check that you have the language server enabled, the diagnostics not disabled, and your version, first.

**Comment by SHxKM** [comment]
>  it implements its own checks based on the analysis it does. By default, these warnings are enabled and will show. If F does not exist, then by default, the langauge server will give a warning (and it will be squiggled in the editor)

Well, without `pylint` VSCode shows errors even for valid Django references; I thought this was a known issue.

Anyway, I understand now this specific issue has nothing to do with the language server. Thanks for the prompt handling of this!

**Comment by jakebailey** [comment]
Either way, if you have Jedi disabled in VSC (i.e. are using the language server), then you should see similar messages without needing pylint or saving, if that's what you're interested in.
