### ISSUE TITLE
Python language server not displaying in console ?

### ISSUE THREAD

**Issue by SheepDomination** [microsoft/python-language-server#1072]
After following the steps from [this](https://github.com/microsoft/vscode-python/issues/3977) page; the output console is not giving me the version of the python-language server ?

**Comment by MikhailArkhipov** [comment]
What does appear in the output window?

**Comment by SheepDomination** [comment]
@MikhailArkhipov nothing ?

**Comment by MikhailArkhipov** [comment]
And if you switch back to Jedi, do you see `Starting Jedi...`? Does the extension generally work, such as commands available, you can select Python in the status bar, etc?

**Comment by SheepDomination** [comment]
When Jedi is enabled; there continues nothing showing up in the `output` of the terminal ?
>Does the extension generally work, such as commands available, you can select Python in the status bar, etc?
Any command specifically ?I usually select python by changing the language mode.

**Comment by jakebailey** [comment]
Not the output of the terminal, the Output panel, like:

![image](https://user-images.githubusercontent.com/5341706/57733733-1057d480-7655-11e9-910f-4ae27c33b223.png)

**Comment by SheepDomination** [comment]
> Not the output of the terminal, the Output panel, like:
> 
> ![image](https://user-images.githubusercontent.com/5341706/57733733-1057d480-7655-11e9-910f-4ae27c33b223.png)

There is nothing shown in my `output` window as seen in your screen shot ?

**Comment by jakebailey** [comment]
Can you show me a screenshot of what you're seeing, then? If you have `Python` selected in the dropdown on the right of the output panel, you should see something. Either Jedi is enabled (and what Mikhail said above gets printed), or info about the language server if Jedi is not enabled.

**Comment by MikhailArkhipov** [comment]
I mean UI elements typically appearing when Python extension is installed and activated, such as 
![image](https://user-images.githubusercontent.com/12820357/57734977-097e9100-7658-11e9-8070-c838cf1e5b70.png)

**Comment by SheepDomination** [comment]
Here is the screen shot; I hope it helps. 
https://i.postimg.cc/PJXPkPH4/pythonjedi.png

**Comment by MikhailArkhipov** [comment]
OK, so Jedi does start. Now change to LS and post screenshot - you can just copy image and paste it here.

**Comment by SheepDomination** [comment]
![LS](https://user-images.githubusercontent.com/6827459/57736226-2d040480-7675-11e9-9ed0-42f5569d9075.png)

The setting; `python.autoComplete.preloadModules` is not valid in the language server.  How do I load a pre-loaded modules namespace ?

**Comment by MikhailArkhipov** [comment]
Well the version is visible, it is `0.2.74`. You don't need to preload anything.

**Comment by jakebailey** [comment]
We don't have that feature; as far as I know that is a feature implemented by the extension, which is deprecated and only worked in Jedi (see Microsoft/vscode-python#1704, https://github.com/microsoft/vscode-python/blob/master/CHANGELOG.md#201890-9-oct-2018).

We could do something similar, but if you have a performance issue we'd appreciate specific issues about those to better improve things overall.

**Comment by jakebailey** [comment]
Closing, as the original issue about the LS not having output doesn't seem to be the case.
