### ISSUE TITLE
PEP hint does not work in Python 2.7

### ISSUE THREAD

**Issue by MikhailArkhipov** [microsoft/python-language-server#1073]
Use python 3.6 interpreter ("Python 3.6.6" from Anaconda). It works

![image](https://user-images.githubusercontent.com/12820357/57722274-e42f5a00-763a-11e9-9f8b-164c4c5cd6b4.png)

Use python 2.7 interpreter ("Python 2.7.16" from Anaconda). It does not work, no popup :(
if I do y = 3 then it deduces type to int and I see the popup completion again

**Comment by MikhailArkhipov** [comment]
This is b/c internally expression is extracted and parsed as annotation but since parser is created off current configuration it is 2.7 and hence is unable to parse type annotations. The fix is to always parse hints as 3.x.

**Comment by makail** [comment]
I did a quick step through of the source, it's constructing the fragment `x: int` to pass to the parser which then fails this check: 
Parse.cs:918
`if (PeekToken(TokenKind.Colon) && (_stubFile || _langVersion >= PythonLanguageVersion.V36)) {`
It's explicitly checking the python version there.

**Comment by MikhailArkhipov** [comment]
The fix was to always parse as 3.6+

**Comment by makail** [comment]
I just scrolled up after I posted! Awesome, good work.
