### ISSUE TITLE
Instance variable showing up as class variable.

### ISSUE THREAD

**Issue by ericsnowcurrently** [Microsoft/python-language-server#108]
See https://github.com/Microsoft/vscode-python/issues/2530.

In recent view is different. Some variables appear to be missing in function scopes

![image](https://user-images.githubusercontent.com/12820357/46560038-1e679a80-c8a7-11e8-85e0-ad842c5803e0.png)

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/python-language-server/pull/521 should address these.

**Comment by jakebailey** [comment]
Mostly, though I've noticed that the walker I wrote doesn't seem to process class variables (which I'll open a bug for separately).
