### ISSUE TITLE
Intellisense parameter info is incorrectly formatted if declaration is too long

### ISSUE THREAD

**Issue by karrtikr** [microsoft/python-language-server#1086]
@jeffreykxiao commented on [Wed Jan 23 2019](https://github.com/microsoft/vscode-python/issues/4127)

## Environment data

- VS Code version: 1.30.2
- Extension version (available under the Extensions sidebar): 2018.12.1
- OS and version: Windows 10 Pro
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.8 64-bit
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Relevant/affected Python packages and their versions: N/A

## Expected behaviour

![good](https://user-images.githubusercontent.com/2986354/51650823-1144f780-1fcd-11e9-8a07-0ada0b35b9bb.PNG)
Parameter info is correctly displayed

## Actual behaviour

![bad](https://user-images.githubusercontent.com/2986354/51650844-21f56d80-1fcd-11e9-91a4-ad172aca6ba5.PNG)
Too many parameters: incorrect display. Trailing params are parsed into docstring section. Putting extra parameters on newlines such that each line is under 70 characters doesn't help. 

![sad](https://user-images.githubusercontent.com/2986354/51650864-35a0d400-1fcd-11e9-9050-da7b26844003.PNG)
Function declaration is too long: incorrect display. 

---

@karrtikr commented on [Thu Feb 14 2019](https://github.com/microsoft/vscode-python/issues/4127#issuecomment-463719613)

Can you please confirm if you are using language server, or jedi? (Check value of `python.jediEnabled` in settings.json).
Also, could you provide the code?

---

@jeffreykxiao commented on [Thu Feb 14 2019](https://github.com/microsoft/vscode-python/issues/4127#issuecomment-463872182)

Can't provide the code unfortunately, but disabling jedi solves the problem.

---

@danalf67 commented on [Tue May 07 2019](https://github.com/microsoft/vscode-python/issues/4127#issuecomment-490244485)

I have exactly the same issue in the parameter hints. I use the jedi setting because the language server is worse (all line breaks are removed after the signature). Example source code for getting the error:
import shutil
shutil.copytree()

**Comment by jakebailey** [comment]
I guess I don't know what the bug here is. The original issue seemed to be coming from Jedi, and disabling fixed it, then a new comment which says they have the same issue with the LS, but actually comments on line breaks being removed, though I get:

![image](https://user-images.githubusercontent.com/5341706/57791985-d9d09700-76f2-11e9-826f-10a14349a82e.png)

Which seems fine (other than the indented block that we can't exactly infer is supposed to be code).
