### ISSUE TITLE
Plugin underscores incorrect parameter

### ISSUE THREAD

**Issue by karrtikr** [microsoft/python-language-server#1087]
@qmmp123 commented on [Fri Dec 07 2018](https://github.com/microsoft/vscode-python/issues/3590)

Plugin underscores incorrect parameter
![screenshot_20181208_040232](https://user-images.githubusercontent.com/6360702/49670073-56a17a00-fa9e-11e8-8a64-9740b643dab0.png)

---

@brettcannon commented on [Mon Dec 10 2018](https://github.com/microsoft/vscode-python/issues/3590#issuecomment-445930780)

The screenshot is showing that `date` from `datetime.date` is highlighted instead of `date` from the parameter name.

---

@karrtikr commented on [Mon Dec 24 2018](https://github.com/microsoft/vscode-python/issues/3590#issuecomment-449760512)

Hey @qmmp123, I can't reproduce this. Can you send me the code sample with the function definition?

---

@qmmp123 commented on [Wed Dec 26 2018](https://github.com/microsoft/vscode-python/issues/3590#issuecomment-449987789)

@karrtikr 
> Hey @qmmp123, I can't reproduce this. Can you send me the code sample with the function definition?

Sure

```
import datetime

def some_func(date: datetime.date):
    pass


some_func( #type here and get incorrect behaviour ) 
```

---

@brettcannon commented on [Wed Jan 02 2019](https://github.com/microsoft/vscode-python/issues/3590#issuecomment-451001461)

@karrtikr this doesn't have an action label, e.g. "needs upstream fix". Could you add the appropriate one?

**Comment by MikhailArkhipov** [comment]
https://github.com/microsoft/python-language-server/issues/1038, #679.
