### ISSUE TITLE
No linter errors when forgetting to import something

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/python-language-server#1093]
@rchiodo commented on [Mon Apr 15 2019](https://github.com/microsoft/vscode-python/issues/5295)

I had code like so:

```
def print_variables(capsys):
    path = os.path.dirname(os.path.abspath(__file__))
    file = os.path.abspath(os.path.join(path, '../../datascience/getJupyterVariableList.py'))
    if execute_script(file):
        read_out = capsys.readouterr()
        return json.loads(read_out.out)
    else:
        raise Exception('Printing variables failed.')
```

I had forgotten to import os

I expected the linter would find this?

**Comment by MikhailArkhipov** [comment]
![image](https://user-images.githubusercontent.com/12820357/58116450-27e11100-7bb1-11e9-9b11-5d2d375488ff.png)

?

**Comment by MikhailArkhipov** [comment]
Seems to work, feel free to reopen if still broken for you.
