### ISSUE TITLE
High CPU usage on Mac OS X after latest upgrade, constant errors

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/python-language-server#1095]
@mishaker commented on [Mon May 13 2019](https://github.com/microsoft/vscode-python/issues/5618)

The same as: 
https://github.com/microsoft/vscode-python/issues/4728

I installed the beta version but still the same. 

CPU stays more than 100% and my mac is blocked.

**Comment by jakebailey** [comment]
A repo that reproduces this would be useful.

**Comment by MikhailArkhipov** [comment]
Feel free to reopen if you have issues with 0.2.86+.
