### ISSUE TITLE
StackOverflowException with PyMySQL==0.7.11

### ISSUE THREAD

**Issue by AZLisme** [microsoft/python-language-server#1100]
The language server raises StackOverflowException and won't start up, if my code imports pymysql. The code itself runs well, just the language server keep crashes.

+ Environment: macOS Mojave 10.14.4
+ Python: 2.7.15 with pyenv and virtualenv
+ VSCode: 1.34.0 (1.34.0) a622c65b2c713c890fcf4fbf07cf34049d5fe758
+ Microsoft Python Language Server version 0.2.82.0
+ Installed PyMySQL==0.7.11 and import it from code.

Debug info from python outputs:
```
[Info  - 11:42:33 AM] Microsoft Python Language Server version 0.2.82.0
[Info  - 11:42:33 AM] Initializing for /Users/xxxx/.pyenv/versions/2.7.15/bin/python
Process is terminating due to StackOverflowException.
```

**Comment by MikhailArkhipov** [comment]
Any specific code fragment you can provide?

**Comment by AZLisme** [comment]
> Any specific code fragment you can provide? Or just `import pymysql` reproes it?

yeah, just `import pymysql` reproes it.
