### ISSUE TITLE
Undefined variable with type declaration

### ISSUE THREAD

**Issue by SaschaSchlemmer** [microsoft/python-language-server#1101]
Environment: macOS Mojave 10.14
Python: 3.7.2
VSCode: 1.33.1
Microsoft Python Language Server version 2019.4.12954

The build-in linter (I disabled all other linters like flake8, pylint, mypy, etc.) complains about undefined variables in class bodies when type definition and assignment are split.

```python
class A:

    i: int
    i = 0
```
<img width="453" alt="Bildschirmfoto 2019-05-20 um 12 08 58" src="https://user-images.githubusercontent.com/35063695/58017692-248e4c80-7b01-11e9-8567-d62833c87ce7.png">

**Comment by MikhailArkhipov** [comment]
The bug actually in definition/references tracking as analysis sees `i = 0` as definition rather than picking `i: int` as root definition and `i = 0` as a reference.
