### ISSUE TITLE
No parameter intelligence for classes

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/python-language-server#1104]
@SimantoR commented on [Sun Apr 21 2019](https://github.com/microsoft/vscode-python/issues/5397)

## Environment data

- VS Code version: 1.33.1
- Extension version (available under the Extensions sidebar): 2019.3.6558
- OS and version: macOS 10.14.4
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.2
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv
- Relevant/affected Python packages and their versions: TensorFlow=2.0.0a0

## Expected behaviour

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/34289663/56474221-5f915780-6451-11e9-8f47-76d030580b88.gif)

## Actual behaviour

![ezgif com-video-to-gif-2](https://user-images.githubusercontent.com/34289663/56474226-7041cd80-6451-11e9-9c4b-e4936104dcdf.gif)

---

@ericsnowcurrently commented on [Mon Apr 22 2019](https://github.com/microsoft/vscode-python/issues/5397#issuecomment-485556506)

Hi @SimantoR, thanks for letting us know about this problem.  First off, I'm guessing that you have the "Expected" and "Actual" switch above. :)  As to the problem, are you using Jedi or the new language server (see #3977)?

---

@SimantoR commented on [Mon Apr 22 2019](https://github.com/microsoft/vscode-python/issues/5397#issuecomment-485591919)

Its the language server in use right now. Jedi does show the parameters. Well more like what ever fits in the box width-wise, rest is underput by the description. But with the language server (that analyzes for a bit), no parameters. I noticed this while using the classes under `keras.layers`

**Comment by jakebailey** [comment]
I believe this is #983.
