### ISSUE TITLE
Find Reference doesn't find all references

### ISSUE THREAD

**Issue by karrtikr** [microsoft/python-language-server#1114]
@LittleLittleCloud commented on [Tue May 21 2019](https://github.com/microsoft/vscode-python/issues/5711)

## Environment data

- VS Code version: 1.33
- Extension version (available under the Extensions sidebar): latest
- OS and version: windows 10
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.6
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A

## Steps to reproduce:

Python language server is being used.

1. Clone Repo from https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode?path=%2FFlaskServers&version=GBmaster

2. Open that folder in vscode, then goto amlflask/common/utils.py
3. Do a "Find all reference" on function `extract_from_workspace_uri`
4. it should show all references in the left pane, instead only part of references are shown

## Logs

```
clean
```   

---

@karrtikr commented on [Tue May 21 2019](https://github.com/microsoft/vscode-python/issues/5711#issuecomment-494591468)

Please provide a sample repository so we can reproduce the issue. The repo is not accessible.

**Comment by LittleLittleCloud** [comment]
you can find a sample repository [here](https://github.com/LittleLittleCloud/mini-repo/blob/master/README.md)

**Comment by LittleLittleCloud** [comment]
Turns out it's a Jedi problem, language server works fine! Thank you @karrtikr
