### ISSUE TITLE
Errors do not disappear after closing the file

### ISSUE THREAD

**Issue by Astrantia** [microsoft/python-language-server#1117]
Is this the correct place for this issue? If a file contains errors and I close it, the problems do not disappear from the problems pane in visual studio code.

**Comment by MikhailArkhipov** [comment]
What version of the LS are you using? It is displayed in the output at startup time.

**Comment by Astrantia** [comment]
> What version of the LS are you using? It is displayed in the output at startup time.

[Info  - 4:29:36 AM] Microsoft Python Language Server version 0.2.84.0

**Comment by MikhailArkhipov** [comment]
Do you happen to have reasonably reliable repro? Does it happen all the time or just occasionally?

**Comment by MikhailArkhipov** [comment]
Been a long time, reopen if this is still a problem.
