### ISSUE TITLE
Automatically closing brackets not supported

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/python-language-server#112]
Microsoft/vscode-python#1772

Don said this was something that required language server support.

**Comment by MikhailArkhipov** [comment]
This is actually not about auto-closing brackets. Auto-close is when user types `(`, editor adds `)`. This is VS Code internal thing, we do not control it - same for quotes. #1772 is about auto-inserting `()` on completion of function names. I.e. `print` completes to `print()` with caret inside `(|)`.

**Comment by MikhailArkhipov** [comment]
Dupe of #35
