### ISSUE TITLE
Display format of function preview is buggy

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/python-language-server#1121]
@wSemis commented on [Fri May 17 2019](https://github.com/microsoft/vscode-python/issues/5657)

Issue Type: <b>Bug</b>

How to reproduce:
* `from numpy import std`
* Hold command and hover mouse on `std`, scoll to the Parameter section

Expected:
* Display in markdown manner

Actual:
* Display as of python syntax highlight

System: MacOS Mojave

Extension version: 2019.4.12954
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.6.0

---

@DonJayamanne commented on [Fri May 17 2019](https://github.com/microsoft/vscode-python/issues/5657#issuecomment-493507820)

Please could you provide a screen sample of the problem.
Also are you using the language server or Jedi?
To find this out please open the `Python` output panel and scroll to the top and copy and paste the contents here

---

@wSemis commented on [Wed May 22 2019](https://github.com/microsoft/vscode-python/issues/5657#issuecomment-495053842)

The screen sample of the problem is as below.
The Python output info is pasted.

```
Starting Microsoft Python language server.
[Info  - 4:19:41 PM] GetCurrentSearchPaths /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 
[Info  - 4:19:41 PM] Python search paths:
[Info  - 4:19:41 PM]     /private/var/folders/(path partially omitted)/jpgqiyar.udg
[Info  - 4:19:41 PM]     /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7
[Info  - 4:19:41 PM]     /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload
[Info  - 4:19:41 PM]     /Users/(username)/Library/Python/3.7/lib/python/site-packages
[Info  - 4:19:41 PM]     /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
[Info  - 4:19:41 PM] Configuration search paths:
[Info  - 4:19:43 PM] Microsoft Python Language Server version 0.2.74.0
[Info  - 4:19:43 PM] Initializing for /Library/Frameworks/Python.framework/Versions/3.7/bin/python3
```

![image](https://user-images.githubusercontent.com/28519124/58223653-2f3d2180-7d4d-11e9-9506-2106e3225288.png)

**Comment by jakebailey** [comment]
#613
