### ISSUE TITLE
Use stubs for compiled modules

### ISSUE THREAD

**Issue by karrtikr** [microsoft/python-language-server#1123]
@ztytotoro commented on [Tue May 21 2019](https://github.com/microsoft/vscode-python/issues/5719)

## Environment data

- VS Code version: 1.35.0-insider
- Extension version (available under the Extensions sidebar): 2019.4.12954
- OS and version: Windows 10 Enterprise 1803
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.1(Miniconda3 4.5.12 64-bit)
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
- Relevant/affected Python packages and their versions: lxml

## Expected behaviour

```py
from lxml import etree

def funcname(fileName):
    file = open(fileName)
    content = file.read()
    xml = etree.XML(content)
    xml. # No intellisense here
```

---

@karrtikr commented on [Wed May 22 2019](https://github.com/microsoft/vscode-python/issues/5719#issuecomment-494930083)

Please inform if you're using Language server or Jedi, i.e check the value of `python.jediEnabled` in `settings.json`.

Also, please provide output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

---

@ztytotoro commented on [Thu May 23 2019](https://github.com/microsoft/vscode-python/issues/5719#issuecomment-495161933)

> Please inform if you're using Language server or Jedi, i.e check the value of `python.jediEnabled` in `settings.json`.
> 
> Also, please provide output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

@karrtikr I'm using Language server, the `python.jediEnabled` is unchecked

And the output:
```log
Starting Microsoft Python language server.
[Info  - 6:20:49 PM] GetCurrentSearchPaths C:\Users\TZhou\AppData\Local\Continuum\miniconda3\python.exe 
[Info  - 6:20:49 PM] Python search paths:
[Info  - 6:20:49 PM]     c:\users\tzhou\appdata\local\continuum\miniconda3\dlls
[Info  - 6:20:49 PM]     c:\users\tzhou\appdata\local\continuum\miniconda3\lib
[Info  - 6:20:49 PM]     c:\users\tzhou\appdata\local\continuum\miniconda3
[Info  - 6:20:49 PM]     c:\users\tzhou\appdata\local\continuum\miniconda3\lib\site-packages
[Info  - 6:20:49 PM]     c:\users\tzhou\appdata\local\continuum\miniconda3\lib\site-packages\win32
[Info  - 6:20:49 PM]     c:\users\tzhou\appdata\local\continuum\miniconda3\lib\site-packages\win32\lib
[Info  - 6:20:49 PM]     c:\users\tzhou\appdata\local\continuum\miniconda3\lib\site-packages\pythonwin
[Info  - 6:20:49 PM] Configuration search paths:
[Info  - 6:20:53 PM] Microsoft Python Language Server version 0.2.82.0
[Info  - 6:20:53 PM] Initializing for C:\Users\TZhou\AppData\Local\Continuum\miniconda3\python.exe
```

**Comment by MikhailArkhipov** [comment]
The module is compiled. Scraper could not extract return type
```python
def XML(text, parser):
    'XML(text, parser=None, base_url=None)\n\n    Parses an XML document or fragment from a string constant.\n    Returns the root node (or the result returned by a parser target).\n    This function can be used to embed "XML literals" in Python code,\n    like in\n\n       >>> root = XML("<root><test/></root>")\n       >>> print(root.tag)\n       root\n\n    To override the parser with a different ``XMLParser`` you can pass it to\n    the ``parser`` keyword argument.\n\n    The ``base_url`` keyword argument allows to set the original base URL of\n    the document to support relative Paths when looking up external entities\n    (DTD, XInclude, ...).\n    '
    pass
```

However, typeshed has a stub in `stdlib\2and3\xml\etree`. Currently we don't used stubs for compiled modules, but we probably should. #533 is related.

**Comment by moltubakk** [comment]
Hi! I just started testing lxml.etree in VS code today. I've been so impressed by the python language support for most other stuff, so I'm wondering whether a newcomer is doing something wrong, or if this is still an issue, 2 years later.

**Comment by jakebailey** [comment]
This repo is no longer actively maintained.

https://devblogs.microsoft.com/python/python-in-visual-studio-code-september-2021-release/#microsoft-python-language-server-end-of-life-november-2021

**Comment by judej** [comment]
Thank you for the report. This project is no longer active. If you are using the Python language server in VSCode, the language server you are using is Pylance and please the http://github.com/microsoft/pylance-release to report issues. 

If you are using Visual Studio, then, please use http://github.com/microsoft/PTVS to report issues.

thank you
