### ISSUE TITLE
How do I get visual studio code to load the modules of the pyd file

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/python-language-server#1125]
@SheepDomination commented on [Fri May 17 2019](https://github.com/microsoft/vscode-python/issues/5660)

How do I get a module to load so when I load a class from the module I can trigger intellisense (`ctrl+space`) and I will see suggestions of that class ?

---

@DonJayamanne commented on [Fri May 17 2019](https://github.com/microsoft/vscode-python/issues/5660#issuecomment-493506494)

Please could you fill in the issue template to provide the missing information.
Also please provide a sample code for the problem.
Finally are you using language server or not?

---

@SheepDomination commented on [Fri May 17 2019](https://github.com/microsoft/vscode-python/issues/5660#issuecomment-493642026)

Yes, I am using the language server.

## Environment data

- VS Code version: 1.34.0
- Extension version (available under the Extensions sidebar): 4.5
- OS and version: Windows10
- Python version (& distribution if applicable, e.g. Anaconda): 2.7.11
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A 

## Expected behaviour
Upon loading a module by means of `python.autoComplete.extraPaths` I expected would load all the modules.  Then within code, I would begin typing a class within the module, then when using the keyboard short-cut `ctrl+space` (intellisense) I would be prompt with suggestions with the corresponding documentation ?

## Actual behaviour
When I begin typing a class of the loaded module once again by the setting `python.autoComplete.extraPaths`, then using `ctrl+space` there is no prompt with suggestions with the corresponding documentation of the module ?

## Steps to reproduce:
Open workspace or user settings; add the following setting, `"python.autoComplete.extraPaths": ` add the path of a location to a pyd or py file; restart vscode.

---

@DonJayamanne commented on [Sat May 18 2019](https://github.com/microsoft/vscode-python/issues/5660#issuecomment-493685526)

> python.autoComplete.extraPaths, then using ctrl+space there is no prompt with suggestions with the corresponding documentation of the module ?

Please could you provide a sample github repo with screenshots of the error so we can better understand the problem. Right now you are proofing a solution, that's fine, however if you provided the actual problem with samples we can help you better.

---

@SheepDomination commented on [Sat May 18 2019](https://github.com/microsoft/vscode-python/issues/5660#issuecomment-493711741)

There isn't an error per se rather how come visual studio code is not loading the modules from the *pyd* file so one can access all the classes then when a class is created, I can trigger intellisense to load up the corresponding documentation of the classes for the module ? 

How do I get visual studio code to load the modules of the *pyd* file ? That is the main question, and I hope I can get help on solving.

---

@DonJayamanne commented on [Mon May 20 2019](https://github.com/microsoft/vscode-python/issues/5660#issuecomment-494156132)

Are you using the language server or Jedi.
When you open the `Python` output panel do you see the work `Starting Jedi` or `Starting Microsoft Language Server`?

---

@SheepDomination commented on [Mon May 20 2019](https://github.com/microsoft/vscode-python/issues/5660#issuecomment-494225427)

> Are you using the language server or Jedi.
> When you open the `Python` output panel do you see the work `Starting Jedi` or `Starting Microsoft Language Server`?

*Starting Microsoft Language Server*.

**Comment by MikhailArkhipov** [comment]
Compiled modules are loaded automatically as long as they can be found using regular Python search rules. Compiled modules are processed by generating pyi stubs and caching the stubs for subsequent use. There is no need to specify anything additional as long as you have correct search paths.

**Comment by SheepDomination** [comment]
@MikhailArkhipov What do you mean by *Python search rules* ?

**Comment by MikhailArkhipov** [comment]
https://docs.python.org/2/tutorial/modules.html#the-module-search-path
