### ISSUE TITLE
Autocompleting `pandas.` uses 1/2 GB of memory

### ISSUE THREAD

**Issue by memeplex** [microsoft/python-language-server#1128]
I just did a clean launch of vscode and tried to autocomplete `pandas.` as shown in the screenshot:

![image](https://user-images.githubusercontent.com/2845433/58364308-0a4dc900-7e89-11e9-89bf-cebe245fe02d.png)

Memory usage is absurdly high. I can easily reproduce this by repeating the same steps.

I'm using:

1. Arch Linux, everything up to date.
2. Code 1.34.0
3. Python Extension  2019.4.12954
4. Python Language Server from the beta channel (I updated it minutes ago).
5. Python 3.7.3

**Comment by memeplex** [comment]
Also, each time I restart code it takes a long time to re-analyze everything (and reload everything into memory!), it's like it doesn't cache anything between sessions and has a long initialization time.

**Comment by memeplex** [comment]
Compare with jedi:

* It's using less than 200MB with both numpy and pandas imported.
* Startup latency is less than 10 seconds.

**Comment by MikhailArkhipov** [comment]
Caching is part of https://github.com/microsoft/python-language-server/issues/472. Considering memory, Jedi is only for completions. Rename is handled by rope, symbols by ctags and linting by pylint. LS actually combines them all. 500 MB is not particularly different from other comparable engines.

**Comment by MikhailArkhipov** [comment]
Since we have #832, folding into #472 for caching.

**Comment by memeplex** [comment]
Fair enough, thanks for explaining. When I disable Jedi in my settings, does it mean that everything else you listed above is disabled also so that pls takes care of everything?

**Comment by MikhailArkhipov** [comment]
Yes, LS takes over the entire editor.
