### ISSUE TITLE
Can't jump to method or have intellisense from parent while using super()

### ISSUE THREAD

**Issue by aaveidt** [microsoft/python-language-server#1130]
If i use super().method() to call to parent class method, there is no intellisense or argument completion.

Then it's impossible to click to that method.

But if i use self / cls, it works.

<img width="486" alt="Screen Shot 2019-05-28 at 12 59 39 PM" src="https://user-images.githubusercontent.com/5781080/58454394-875a9600-8148-11e9-8f18-4ea5414e339d.png">

<img width="433" alt="Screen Shot 2019-05-28 at 12 58 24 PM" src="https://user-images.githubusercontent.com/5781080/58454467-bec94280-8148-11e9-8b0d-f1c927338fe8.png">

**Comment by jakebailey** [comment]
Fixed by #1702.
