### ISSUE TITLE
Python 3.7 - f-strings do not work as expected

### ISSUE THREAD

**Issue by shivendra90** [microsoft/python-language-server#1131]
I have come to know that this issue needs to be posted under the language server repo. Specifically, while working with f-strings, the python extension should work fine but I'm getting a `SyntaxError` for every f-string command. While the issue should not be felt for those using Py 3.5 and above interpreters, there's a closed issue where the OP is using 3.6.

It's simple to reproduce:
```
string = "world"
print(f"Hello {string}!")
```
Expected output should be:
```
Hello world!
```
Here I'm getting the `SyntaxError: invalid syntax` message. I have checked my code, there are no missing quotations or parentheses. The extension version currently in use is `2019.4.12954`. I've also checked the language server and updated it by deleting the original folder allowing vscode to download the latest one; still the error persists.

**Comment by MikhailArkhipov** [comment]
Are you getting error at runtime? I don't see any syntax errors reported by the LS parser with 3.6 or 3.7:

![image](https://user-images.githubusercontent.com/12820357/58494683-831f8000-812a-11e9-8585-937836b198bd.png)

![image](https://user-images.githubusercontent.com/12820357/58494734-9f232180-812a-11e9-8553-2ecfb75999f1.png)

**Comment by MikhailArkhipov** [comment]
The extension does not control how Python executes your code. Try to run code directly in Python console and see if it works.

**Comment by geauxtigers** [comment]
I am having this same problem.

My system is as follows:

**Windows 10**
Version 1803 OS Build 17134.950

**WSL**
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.6 LTS
Release:        14.04
Codename:       trusty

**VS Code**
Version: 1.37.1 (system setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134

**Extensions WSL-Installed**
Name: Code Runner
Version: 0.9.14

Name: Git History
Version: 0.4.6

Name: GitLens — Git supercharged
Version: 9.9.3

Name: Heroku
Version: 1.2.6

Name: Python
Version: 2019.8.30787

Name: VS Color Picker
Version: 1.0.0

**Issue**
When running the same code as shown above on Windows (with both Python 3.6 and 3.7) the code executes without an error being sent to the output pane.  However on both 3.6. and 3.7 in Windows WSL, I get a `SyntaxError: invalid syntax` in the output pane.  Running the same code under WSL from the VS Code terminal results with no errors.

Error Shown:
![image](https://user-images.githubusercontent.com/8951542/63607815-02d9b100-c599-11e9-8651-b4aec63aa4af.png)

But No Error When Run In Terminal
![image](https://user-images.githubusercontent.com/8951542/63607869-243a9d00-c599-11e9-8dbf-9b60f9e86746.png)

Can this issue be re-opened?

**Comment by Ajithvajrala23** [comment]
I am having the same error.
I am running on Ubuntu 18, using python 2.7

**Comment by jakebailey** [comment]
This is not a language server issue (it's the extension or someone else who runs the code), and Python 2.7 doesn't support f-strings (so it would make sense in any context to error out for them). If you have an issue with running code, please report it on the extension's repo.

**Comment by manishpandey65** [comment]
Getting Same Error with Python3.7.7. This is specifically for this version

**Comment by ReneeR-dot** [comment]
I have python 3.9 and it is not accepting the fstring command. This is what im trying to write (btw just started to learn python, if you can explain in beginner terms, thank you) 

first_name = "ada"
last_name = "lovelace"
full_name = f'{first_name} {last_name}'
print(full_name)

Then I get a syntax error:
 print(f " {first_name} {last_name} ")
                                                          ^
SyntaxError: invalid syntax
[Finished in 0.113s]

I am also using atom as my text editor if that helps, pls and thank you in advance.

**Comment by cimo95** [comment]
I have the same issue with python 3.7 windows 10
why the answer is just for that who said using python 2.7?

**Comment by jakebailey** [comment]
This repo is no longer actively maintained. Consider trying pylance/pyright or JediLSP.
