### ISSUE TITLE
'match' objects don't get autocompletion

### ISSUE THREAD

**Issue by malmaud** [microsoft/python-language-server#1152]
Using language server 0.2.90.0

The only autocomplete offered at the end of this buffer is the alphabetical list of symbols.

```python
import re

m=re.match(r'a','a')
m.
```

<img width="500" alt="Screen Shot 2019-05-31 at 9 54 43 PM" src="https://user-images.githubusercontent.com/987837/58743873-babe4e80-83ee-11e9-8f50-d066573fbedc.png">

**Comment by MikhailArkhipov** [comment]
Probably related to #1015. List above is standard VSC 'words' list, not LS completions.

**Comment by MikhailArkhipov** [comment]
Folding into #1015
