### ISSUE TITLE
Docstring from functools.wraps()'ed object not returned

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/python-language-server#116]
Microsoft/vscode-python#2596

Basically if you use `functools.wraps()` it updates the docstring of the wrapped function, but the language server doesn't seem to special-case this situation.

**Comment by MikhailArkhipov** [comment]
![image](https://user-images.githubusercontent.com/12820357/52322727-06a43e00-298f-11e9-9e02-ea43cc023719.png)

![image](https://user-images.githubusercontent.com/12820357/52322744-191e7780-298f-11e9-8018-456cf737b377.png)

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/python-language-server/pull/546
