### ISSUE TITLE
Scraped Houdini pyc does not expose docs

### ISSUE THREAD

**Issue by jakebailey** [microsoft/python-language-server#1165]
See #1081. They're there in the pyc file, but I can't directly import the pyc given as it depends on specific paths existing on the system I don't have. (Namely, `C:/cygwin/home/prisms/builder-new/Nightly16.5CMake/dev/hfs/houdini/python2.7libs\hou.py`).

**Comment by SheepDomination** [comment]
The *pyc* file is the only file which contains the corresponding documentation; the problem is the python language server unlike Jedi is not loading this documentation, I'll check if there is other files associated but I doubt it.

**Comment by SheepDomination** [comment]
I have a *.pyd file would that help ?

**Comment by jakebailey** [comment]
No, we do not read pyd files. They are not normally shipped with packaged libraries, and pyc files should contain all of the info needed (if we are able to import them at all, which is what the scraper should be doing here).

**Comment by SheepDomination** [comment]
@jakebailey Do you want the pyd file to test with the scraper as on my end it's not working ?

**Comment by jakebailey** [comment]
No, the pyd file won't help, as the language server doesn't read them; a pyc file that is importable should be enough.

We'll investigate this when we have the time, but at the moment there are other more pressing bugs we're trying to fix. I'll ask for info when I need it. Thanks.

**Comment by SheepDomination** [comment]
Is there any way to control the size of the window as shown [here](https://github.com/microsoft/python-language-server/issues/1081#issuecomment-498690736) ?

**Comment by jakebailey** [comment]
Not that I know of. microsoft/vscode#14165

**Comment by SheepDomination** [comment]
Thanks. 👍

**Comment by SheepDomination** [comment]
The docs get exposed, but importing a module causes an `unable to import` error; even though I'm loading the modules using `PYTHONPATH` in the environment file ?

**Comment by SheepDomination** [comment]
I was able to get the docs to be exposed a few months ago.

**Comment by jakebailey** [comment]
Thanks for the update. I'll close this for now until something else comes up.
