### ISSUE TITLE
 [Feature Request] methods and column names completions in editor

### ISSUE THREAD

**Issue by StevenLi-DS** [microsoft/python-language-server#1167]
https://github.com/microsoft/vscode-python/issues/5882

> 1. When typing in the main editor, there are no completions for column names but there are completions when using the input windows in interactive windows:
> 
> ![vs](https://user-images.githubusercontent.com/33796896/58809549-29b3c700-85ea-11e9-840d-a40d88d740fe.gif)
> 
> 1. The method completions (e.g., `.dropna()`) in the interactive windows only show up for `DataFrame` not `Series`. Meanwhile, the editor does not seem to have completions for those common methods at all.
> 
> ![vs1](https://user-images.githubusercontent.com/33796896/58810056-210fc080-85eb-11e9-89d3-8351af929a02.gif)
> 
> ```
> Version: 1.34.0 (user setup)
> Python Extension: 2019.5.17517
> Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
> Date: 2019-05-15T21:59:37.030Z
> Electron: 3.1.8
> Chrome: 66.0.3359.181
> Node.js: 10.2.0
> V8: 6.6.346.32
> OS: Windows_NT x64 10.0.17763
> ```

**Comment by jakebailey** [comment]
The interactive window uses an IPython kernel, so is able to actually inspect the live members of a datatype. The column names can only be determined at runtime, not statically, so the column names aren't something we could determine just by looking at the source code (which is all the language server has).

The fact that we're missing some members of things returned by `load_dataset`/`read_csv` is a known issue (#981) and should be improved.

**Comment by rchiodo** [comment]
I believe this is also second order autocomplete? 

Like this:

df.iloc[0]. <-- This shows nothing.

where as this does:

r = df.iloc[0]
r. <-- THis lists out the series attributes.

**Comment by jakebailey** [comment]
That shouldn't happen; those should be functionally equivalent. The only reason why they'd  behave differently would be if `r` is reassigned somewhere (since we don't have dataflow analysis).

**Comment by rchiodo** [comment]
Ah it seems like the evaluation of iloc is done by jupyter, not by the language server. And jupyter doesn't support second order completions. This is actually a jupyter issue.

**Comment by jakebailey** [comment]
I'm going to close this for now; it's a bit out of scope for the language server as a static analyzer of Python code to dip into data files to figure out what pandas will have in its objects. The interactive window should provide some live info.
