### ISSUE TITLE
MoveClass test fails

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/python-language-server#117]
Incorrect setting of analysis (old version wins) due to threading issues.

**Comment by MikhailArkhipov** [comment]
#93

**Comment by MikhailArkhipov** [comment]
Fails again

**Comment by AlexanderSher** [comment]
Test fails because change bfa142d1795428c9814a15c045dcc51d2e1bbe16 that has fixed the issue was partially undone. Rescheduling may become infinite on large projects (e.g.: https://github.com/Microsoft/ptvsd)

**Comment by MikhailArkhipov** [comment]
Actually, it is unclear if we need this test. In verifies that analyzer collects various signatures of the same function with different parameters from function calls and stores them as overloads. I.e. in
```python
def foo(a, b)
```
if finds all `foo(1, 2)` and `foo('a', 'b')` and presents that function may return string or int. IMO, there is not much value here, signature just shows argument names, there is no need to show all variety of actual calls. For example, C# does not show all possible signatures of
```cs
object Some(object o)
```
calculated from actual types passed to the method.

**Comment by MikhailArkhipov** [comment]
N/A with the new code base
