### ISSUE TITLE
Language Server Returns All Modules Upfront -> Slow Module Import Autocomplete

### ISSUE THREAD

**Issue by Jma353** [microsoft/python-language-server#1170]
I noticed when using this language server with VS Code that initial autocomplete with `import ...` or `from ...` returns **all modules in the workspace / searched paths** initially.  Is this expected?  In a larger project with a large number of modules (both in site-packages and in `searchPaths` directories) this module # can be extremely large, and can lead to a slow autocomplete experience, given the editor is handling a large amount of completion results.

I also noticed that the server always returns `isIncomplete = false` `CompletionList` results. 

Does the language server have a setting to afford the following behavior: 
1. I type `import my_modu`
2. The language server only suggests modules of the form `my_module_1`, `my_module_2`, etc. rather than: `my_nested_module_path.another_layer.my_module_1`, `another_module.my_module_2`, ... etc.

**Comment by MikhailArkhipov** [comment]
`isIncomplete = false` means LS will provide documentation for items later. It does not mean the list is incomplete. LS protocol does not support dynamic list population like VS SDK, for example.

**Comment by Jma353** [comment]
@MikhailArkhipov my bad, you're right about `isIncomplete`, thanks for the clarification. 

Sounds a lot like #864 (similar bothered workflow that users reported).  Is there a workaround?  Can there be an option to not have the language server return every possible module, fully-qualified module (for example, just the root-level module, e.g. if there's modules `a.*`, just return `a` initially)?  I have to believe this might be an issue in Python projects with some larger dependencies installed in their virtual environment, or when there's **lots** of dependencies in general.

**Comment by jakebailey** [comment]
@Jma353 We've made some improvements in the import system since you opened this issue. Is it still too slow?

(Closing for now, but feel to reopen if it's still too slow.)
