### ISSUE TITLE
All references are not listed when using ms language server

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/python-language-server#1174]
@jahan01 commented on [Wed Jun 05 2019](https://github.com/microsoft/vscode-python/issues/5917)

## Environment data

- VS Code version: latest
- Extension version (available under the Extensions sidebar): 2019.5.18426
- OS and version: Mac Os
- Python version (& distribution if applicable, e.g. Anaconda): 3.6 (Anaconda)
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
- Language Server (more info #3977): Language Server

`constants.py`
```python
VARIABLE1 = 'afad'
VARIABLE2 = 'dcef'
```

`use.py`
```python
from vscode_test.constants import *
from vscode_test import constants

print(VARIABLE1)
print(constants.VARIABLE2)

print(VARIABLE2)
print(constants.VARIABLE1)

```

## Expected behaviour

All usages of the symbol to be listed under references when `Right click -> Find All References` on `VARIABLE1` in `constants.py`

## Actual behaviour

Doesn't list all usages when ms language server is used.
Usage of `print(constants.VARIABLE1)` in `use.py`  isnt listed.

Looks like if symbol is imported directly, the reference is listed. If the symbol referenced via modules it isn't listed.

This issue seems to be recurring - why not have some tests for this ?

When Jedi is enabled it works as expected.

![image](https://user-images.githubusercontent.com/566264/58970523-30119100-87ec-11e9-83ce-4fbf904bfc31.png)

**Comment by MikhailArkhipov** [comment]
Slightly simplified
```python
from .constants import *
import constants

print(VARIABLE1)
print(constants.VARIABLE2)

print(VARIABLE2)
print(constants.VARIABLE1)
```

**Comment by MikhailArkhipov** [comment]
So the problem is that since expression is not assigned (i.s. as opposed to `x = func(a)`, none of the parts participate in analysis downstream, the arguments are not evaluated and hence reference is not added. Reference to `VARIABLE*` is added by the linter when it is looking up defined/undefined variables.

**Comment by MikhailArkhipov** [comment]
Adding cost to eval arguments in all cases.
