### ISSUE TITLE
Gibberish undefined variable.

### ISSUE THREAD

**Issue by CMLL** [microsoft/python-language-server#1181]
Are these type of errors handled by the LS? I'm not sure why but from time to time I get some weird message about undefined variables with code that's not present. Usually reloading fixes the issue and it doesn't happen again. I have no hard evidence of why it happens but seems to have more often when typing occurs when the background analysis is in process.

![image](https://user-images.githubusercontent.com/3720126/59069553-0d907e00-88a7-11e9-855c-53f9433de068.png)

**Comment by MikhailArkhipov** [comment]
Probably same as #1009

**Comment by MikhailArkhipov** [comment]
https://github.com/microsoft/python-language-server/pull/1227 probably fixed this as it was possible to try and retrieve document content while document was being updates as a result of editing. Please reopen if you see this in 0.3.18+ builds
