### ISSUE TITLE
Libraries completing general.

### ISSUE THREAD

**Issue by CMLL** [microsoft/python-language-server#1182]
As mentioned in https://github.com/microsoft/python-language-server/issues/1157
triggering an auto completion into a standard library or config search library shows the general completion list on LS version 0.2.98.0.

General results of triggering autocompletion on an empty string.
![image](https://user-images.githubusercontent.com/3720126/59124714-f3f74100-894f-11e9-8307-5ac7eee5bab6.png)

Results of triggering completion on hashlib, os and sys.
![image](https://user-images.githubusercontent.com/3720126/59124781-19844a80-8950-11e9-936b-c211524c5070.png)

![image](https://user-images.githubusercontent.com/3720126/59124846-49335280-8950-11e9-9dcf-dce3c2083cce.png)

![image](https://user-images.githubusercontent.com/3720126/59124968-91527500-8950-11e9-92d6-20dd8ae9569c.png)

There was a moment when getting a completion of sys. got me a different result, which seemed correct, but that was maybe 1 in 15 or more attempts that worked, all other times it was like the above image.
![image](https://user-images.githubusercontent.com/3720126/59124902-6a943e80-8950-11e9-8fc5-11dfe8608d14.png)

The behaviour was the same if I forced the completion by pressing the key shortcut (Ctrl + Space) in my particular case (think that's the default one) or if I typed the `.` and let the completion happen organically.

Edit:
It also happens with recently declared variables. Same as with modules, most of the times it shows the incorrect completions and sometimes shows the correct ones.
![image](https://user-images.githubusercontent.com/3720126/59126897-b8f80c00-8955-11e9-9860-f1843dd70086.png)

Also happens with 0.2.96.

**Comment by dark-eyes** [comment]
Yes, I got the same problem here. 
When the python language server was upgraded to 0.2.96, the python intellisense became unusable again.
![图片](https://user-images.githubusercontent.com/40535112/59252659-227e6000-8c5f-11e9-9a9f-6505c02a59cd.png)
![图片](https://user-images.githubusercontent.com/40535112/59252698-35913000-8c5f-11e9-8549-a64d9d75e250.png)

**Comment by MikhailArkhipov** [comment]
There are tests for this and 0.2 is long past. Feel free to reopen if it happens.
