### ISSUE TITLE
Imports/types not resolved in `if TYPE_CHECKING` blocks

### ISSUE THREAD

**Issue by jaens** [microsoft/python-language-server#1185]
Given the following code:

```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import some_module

def some_fn(arg: "some_module.SomeType") -> None:
    var = arg.some_instancevar
```

There is no type shown on hover over `var` and Ctrl+click (Go to Definition) does not work for `arg.some_instancevar`.

I guess this is because the imports inside `TYPE_CHECKING` are not actually loaded/resolved?

<details><summary>Extension information:</summary>

Microsoft Python Language Server version 0.2.96.0

Name: Python
Id: ms-python.python
Description: Linting, Debugging (multi-threaded, remote), Intellisense, code formatting, refactoring, unit tests, snippets, and more.
Version: 2019.5.18875
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-python.python
</details>

**Comment by jakebailey** [comment]
The typing module is implemented within the language server, and I don't think we do anything with TYPE_CHECKING (and likely never will), but regardless goto def should work there. I think goto def working is probably unrelated to TYPE_CHECKING itself. Do you have a test project that reproduces this (past this short code example)?

**Comment by jaens** [comment]
Can't really reproduce it in a simple project... but it looks like this has more to do with the fact that those type definitions are from `.pyi` files rather than the conditional import. Let me try to boil it down.

**Comment by jaens** [comment]
Okay, I think I got it. It's related to the types being declared as strings, which is one requirement for using the `if TYPE_CHECKING` import style. Let me file another bug.
