### ISSUE TITLE
Dynamic Analysis and Intellisense

### ISSUE THREAD

**Issue by Astrantia** [microsoft/python-language-server#1188]
Hi. Not an issue per se, probably more of a question or a feature request. Will python language server be ever able to infer types dynamically and suggest intellisense/type checking accordingly? Don't want to sound mean, but currently the language server is really not offering any good experience when working with big famous modules (selenium, pytorch, and many, many more). The language server is only good for basic python workspaces, but as soon as something dynamic comes in, neither intellisense nor type inference work at all. Is this planned to be supported in future, or it's something python language server will never try to tackle?

Stubbing these popular libraries is not really a solution, because when trying to write code involving those libraries, such as deriving a class from base classes, analysis breaks on that code, so yeah stubbing is not really an answer I'm looking for.

**Comment by jakebailey** [comment]
Inferring things is exactly what the analysis does (unless I's misunderstanding what you mean by "infer"), but Python code (especially popular libs) do things that are very difficult to analyze. If you have specific examples of things that do not work, please report them as issues so we can figure out what makes those cases not work properly.

If by "dynamic" you mean types generated at runtime, then it really depends. We have some prototype work to call out to python to get info that is not statically available, but types which pop up are not easy to deal with (like Django models, which use all sorts of Python tricks).
