### ISSUE TITLE
[MS Language Server] Go to definition fails to find definition

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/python-language-server#1189]
@amittleider commented on [Fri Jun 07 2019](https://github.com/microsoft/vscode-python/issues/5943)

## Environment data

- VS Code version: 1.35.0
- Extension version (available under the Extensions sidebar): 2019.5.18875
- OS and version: Ubuntu 18.04
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.7 64 bit
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
- Language Server (more info #3977): Jed/Language Server

## Expected behaviour
When I go to a definition of `render_template` I get jumped to the definition of `render_template`

## Actual behaviour
Error message No definition found for `render_template`.

## Steps to reproduce:
1. Use flask repo
2. Go to `blog.py`
3. Line 25, go to definition of `render_template`

**Comment by MikhailArkhipov** [comment]
1. Cloned `flask`
2. Set `python.autocomplete.extraPaths` to include path to `flask\src`.
3. Opened `flask` folder.
4. Opened `blog.py` from `examples\tutorial\flaskr`.

Goto def works, opens `templating.py`.

![image](https://user-images.githubusercontent.com/12820357/59293534-39f42380-8c34-11e9-874e-f2710d47fb99.png)

Perhaps missing step (2) caused imports to end up unresolved?

**Comment by amittleider** [comment]
Maybe I forgot to select the correct python interpreter. I can actually jump to the definition now, even without step 2.
