### ISSUE TITLE
Refactor: Rename variable results in "Task Cancelled" (with MS Language Server)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/python-language-server#1190]
@amittleider commented on [Fri Jun 07 2019](https://github.com/microsoft/vscode-python/issues/5942)

## Environment data

- VS Code version: 1.35.0
- Extension version (available under the Extensions sidebar): 2019.5.18875
- OS and version: Ubuntu 18.04
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.7 64 bit
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
- Language Server (more info #3977): Language Server

## Expected behaviour
The "Rename Variable" function will fail with the error message in the bottom left saying "Task Cancelled". I have tried in the Flask repo and there is no problem, but there is a problem with my repo. I cannot provide my repo for repro of the bug, so if someone has some ideas about logs we can check or how to make a minimal repro, let me know and I will try. There is a gift below showing the behavior.

![VSCodeLSCantRename](https://user-images.githubusercontent.com/1625951/59098920-035f9580-8922-11e9-89ac-2bc2d86c477b.gif)

## Actual behaviour

VSCode stalls trying to rename a variable. Sometimes ending with the message "Task Cancelled" in the bottom right corner of the window.

## Steps to reproduce:
1. Any ideas on this are appreciated. Might we have logs somewhere so we can know how to produce a minimal repro?

## Logs
Logs in the JS console don't look meaningful. However, I see a message in the 'Log (Extension Host)' window, which could be related:

```
ms-python.python-2019.5.18875/out/client/extension
[2019-06-07 12:33:12.457] [exthost] [error] Error: Cannot resolve tree item for element 0/0:wa_trading
	at define.resolveTreeNode.a.asPromise.then.then.e.getChildren.then (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:481:281)
```

**Comment by jakebailey** [comment]
@amittleider If you still have this issue, please let us know. The performance of the LS has improved since filing and rename might not get canceled.
