### ISSUE TITLE
Cache directory being created in working dir

### ISSUE THREAD

**Issue by DoronCohen** [microsoft/python-language-server#1197]
After running vscode for a couple of minutes a cache directory is being created in current working directory:

```
>>> find XDG_CACHE_HOME -type d
XDG_CACHE_HOME
XDG_CACHE_HOME/Microsoft
XDG_CACHE_HOME/Microsoft/Python Language Server
XDG_CACHE_HOME/Microsoft/Python Language Server/stubs.v1
XDG_CACHE_HOME/Microsoft/Python Language Server/stubs.v1/fkxs6FR2vIxVMD6bGutN1USV2QjWKNwi3BzHSOZtRuQ=
XDG_CACHE_HOME/Microsoft/Python Language Server/stubs.v1/LgbfmimuQOxkaUOhWt86-a6UEZUhN49v8qHZjyfHw4M=
XDG_CACHE_HOME/Microsoft/Python Language Server/stubs.v1/Bvya4K4-GLH2i4NWRpAyMUq7YjAAx3zy6-S1-9a015w=
XDG_CACHE_HOME/Microsoft/Python Language Server/stubs.v1/Lv_r0NwWzsSjLwRvPyKrxpzqqTnPMtYb31q-UVhL4Kw=
XDG_CACHE_HOME/Microsoft/Python Language Server/stubs.v1/p8W2262ywVKsMMr1VzB8G-WDALt_ZdyQ7utOeG24C5A=
XDG_CACHE_HOME/Microsoft/Python Language Server/stubs.v1/9Ngt_AwaF3wf90KUJJ_PCa9z4w36Mfb38NiqlR6soXc=
XDG_CACHE_HOME/Microsoft/Python Language Server/stubs.v1/P1Dufw8hnPKVkyIo7zY9sRNcLyKx27yQCmbUZpBAwac=
XDG_CACHE_HOME/Microsoft/Python Language Server/stubs.v1/V4oqU-UJXFexaOAOz5GPtRmw9_zQrhQ0N1IUE3sz_qE=
XDG_CACHE_HOME/Microsoft/Python Language Server/stubs.v1/dvMmx3GWTeFuvAwXeMb1IoE3sAzAcWH0zT-e9dkXI1Y=
XDG_CACHE_HOME/Microsoft/Python Language Server/stubs.v1/-WScKTdY4Z7QTBZjxdeAYNNLv1DXgp885dB0wlhKxP4=
XDG_CACHE_HOME/Microsoft/Python Language Server/stubs.v1/Qbx4EfzOrkuCcrmOh7Q4GfrW-EBj_641nXBzvpnI0So=
XDG_CACHE_HOME/Microsoft/Python Language Server/stubs.v1/42KVlI6x54osDCJU6OGhuKHdMtyyC-1e_wcq964-oyw=
XDG_CACHE_HOME/Microsoft/Python Language Server/stubs.v1/Q7clfiPhnxeY0yyGKP0z_n1KdrtiaEygl2bBWqtuDt4=
```

This started a few days ago. my guess is that someone forgot to add `$` to the environment variable.

**Comment by alexkillen** [comment]
I'm getting this too. I'm on Ubuntu, here's the VS Code About:

Version: 1.35.0
Commit: 553cfb2c2205db5f15f3ee8395bbd5cf066d357d
Date: 2019-06-04T01:13:26.790Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-51-generic

**Comment by jakebailey** [comment]
Bug here: https://github.com/microsoft/python-language-server/blob/91e912c2761e940c171f490cb64bbb08b5c9999d/src/Analysis/Ast/Impl/Caching/CacheFolders.cs#L75

`xdgCacheHomePath` needs to be the path, not `xdgCacheVarName`.

**Comment by Septatrix** [comment]
I'm getting this bug as well, though only when using the snap version.

Extension version (ms-python.python): 2019.5.18875
VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:13:26.790Z)
OS version: Linux x64 5.0.0-16-generic snap

**Comment by bayudwiyansatria** [comment]
i've got the same issues, and have XDG_CACHE_HOME in my working directory.
Version: 1.35.0
Commit: 553cfb2c2205db5f15f3ee8395bbd5cf066d357d
Date: 2019-06-04T01:13:26.790Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 5.0.0-16-generic-snap.

And still not get updated yet.

**Comment by jakebailey** [comment]
The fix was just merged and built into daily. If you want it now, you can switch up, but I expect that we'll push out to the stable channel soon.

```json
"python.analysis.downloadChannel": "daily"
```
