### ISSUE TITLE
No completion in namespace packages

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/python-language-server#12]
```
.
├── projecta
│   └── foo
│       ├── bar
│       │   └── __init__.py
│       └── __init__.py
└── projectb
    └── foo
        ├── baz
        │   └── __init__.py
        └── __init__.py
```

test.py:
```
import projectA.foo
import projectA.foo.bar
import projectB.foo
import projectB.foo.baz

projectA.
```
![image](https://user-images.githubusercontent.com/12820357/39330695-3cf1d9fe-4957-11e8-99d9-7c36ebc77d95.png)

Jedi:
![image](https://user-images.githubusercontent.com/12820357/39330648-1fb33f36-4957-11e8-8d5f-bac8a9d707ea.png)

PyCharm:
![image](https://user-images.githubusercontent.com/12820357/39330711-510b0ece-4957-11e8-921c-4b9c7fc814e9.png)

**Comment by rafales** [comment]
I'm running into the same problem. I'm using "native" namespace packages (as defined in PEP-0420, without __init__.py).

I've set up project structure according to this official sample: https://github.com/pypa/sample-namespace-packages/tree/master/native

I have installed those packages via `pip install -e`.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/python-language-server/pull/361
