### ISSUE TITLE
`cls` in classmethods of derived classes always refers to the parent class (rather than the derived one)

### ISSUE THREAD

**Issue by davidwallacejackson** [Microsoft/python-language-server#120]
Easier to explain with an example:

```python
class Foo:
    @classmethod
    def get_an_instance(cls):
        return cls()

class Bar(Foo):
    pass

my_bar = Bar.get_an_instance()
```

In VSCode w/ Python plugin 2018.8.0, `my_bar` is typed as a `Foo`, while I'd expect it to be typed as a `Bar`.

**Comment by MikhailArkhipov** [comment]
![image](https://user-images.githubusercontent.com/12820357/52322584-8d0c5000-298e-11e9-81db-8f2992d80ba5.png)
