### ISSUE TITLE
Intellisense does not work in VS Code Insiders

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/python-language-server#1206]
Interesting bug in Language Server + VS Code Insider.
**Same bug doesn't appear in the following:**
* LS + VS Code Stable
* Jedi + VS Code Stable
* Jedi + VS Code Insider

```python
import sys

print(sys.executable)
sys
```

1. After the `sys` word, entering the character `.` , now we get auto completions.
1. Set the cursor at `print(sys.exe` & pressing `ctrl+space`, then we get auto completions.
1. Now, go back to step 1 and try entering `.` after `sys`, and you won't get any completions!!!

To get completions working again I need to force completions to appear using `ctrl+space`

**Comment by jakebailey** [comment]
I can't reproduce this with:

```
Version: 1.36.0-insider (system setup)
Commit: 11b88a3323878a98b418e4efca77e7afabd50d01
Date: 2019-06-17T05:17:47.485Z
Electron: 4.2.4
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

**Comment by DonJayamanne** [comment]
Yes, looks like something was fixed in the Insiders issue.
I cannot replicate this with the latest version of VSC insiders.
Thanks
