### ISSUE TITLE
Class autocomplete not working.

### ISSUE THREAD

**Issue by wangjiancn** [microsoft/python-language-server#1208]
Model is a Django Model Class,objects is inherit from Manager
![image](https://user-images.githubusercontent.com/37948697/59610223-83b89e80-914b-11e9-9f4e-69046bd42d66.png)

BaseModel has intelligence autocomplete
![image](https://user-images.githubusercontent.com/37948697/59610354-c9756700-914b-11e9-9cba-02b8d197e44d.png)

But Tag not working.
![image](https://user-images.githubusercontent.com/37948697/59610392-e27e1800-914b-11e9-96c3-bcfa28bda88f.png)

Maybe config is rong.

```
"python.jediEnabled": false,
 "python.autoComplete.extraPaths": [
        "./blog"
 ]
```

**Comment by jakebailey** [comment]
This seems to work for me now:

![image](https://user-images.githubusercontent.com/5341706/66671903-e4e01280-ec11-11e9-9985-1d443ac824ce.png)

For reference, better Django model support is #129.
