### ISSUE TITLE
Does PythonAnalyzer support parallel analysis?

### ISSUE THREAD

**Issue by lostmsu** [Microsoft/python-language-server#123]
I am running the analyzer on rather big Python project, using a single instance of `PythonAnalyzer`. I enqueue all modules to be analyzed in advance, as soon as they are parsed (which I can easily do in parallel), then call `AnalyzeQueuedEntries`.

I have two problems:
1) queue size seems to be going up and down, but never reaches 0 in reasonable time. I am wondering if I am doing something wrong (like not limiting some analysis parameter), or is there a bug in my PTVS build (I use master branch tip). Visual Studio seems to be able to show useful information way faster.
2) the whole analysis process seems to only use one CPU core, so I am curious if there's a way to parallelize it.

**Comment by MikhailArkhipov** [comment]
Yes, current analysis is a queue on a single thread. The problem is that modules need to be analyzed in order (i.e. modules that import A are analyzed after it). I can imagine that if structure of a specific project allows it (perhaps there are clusters of modules that do no reference each other), you could split it and run several analyzers in parallel.

**Comment by lostmsu** [comment]
@m-chau what about the queue size? Why does it go up and down? Is it because an iteration of analysis discovers something, that might affect dependent modules, which causes them to be re-queued for the next iteration? Is there a guarantee, that this process will ever stop? I tried running it for a while on some project, and on the first sight there does not seem to be much difference in analysis results after 30 seconds and 1h. It also never completed before I run out of patience after 1h.

**Comment by MikhailArkhipov** [comment]
@lostmsu - yes, it is dynamic, so mode units can get queued depending on changes. There is analysis limit that can be set. Now, we did see reports that analysis supposedly never changes. If you have project or repro case that you could share, we'd appreciate it.
