### ISSUE TITLE
`self.` is not required to access class variables inside the class

### ISSUE THREAD

**Issue by jakebailey** [microsoft/python-language-server#1231]
![image](https://user-images.githubusercontent.com/5341706/59867458-17a08b00-9343-11e9-82e2-7ef00c922351.png)

`self.` should be required to access the instance variable. This is likely happening because the variable is "in" the scope.

Notably, this isn't just a completion thing, and affects the analysis:

![image](https://user-images.githubusercontent.com/5341706/59867634-939ad300-9343-11e9-8af1-194436b875c6.png)

But the tooltip displayed is different in the `self.` case:

![image](https://user-images.githubusercontent.com/5341706/59867733-db215f00-9343-11e9-8333-06f180ddef64.png)

Also, for class variables:

```python
val = 1234

class Foo:
    val = "str"

    def foo(self):
        print(val)


Foo().foo()
```

`val` in `foo` is `1234`, not "str", but:

![image](https://user-images.githubusercontent.com/5341706/59868180-16705d80-9345-11e9-8584-94ccfa395bfa.png)

This also affects the completion list:

![image](https://user-images.githubusercontent.com/5341706/59868221-37d14980-9345-11e9-9864-3a2b4247c334.png)

`self.val` is the right way to access the one in the class.

**Comment by MikhailArkhipov** [comment]
Basically same as #1233

**Comment by MikhailArkhipov** [comment]
Affects persistence. In
```python
from typing import Optional
class A: ...

class B:
    def __init__(self, A: Optional[A]):
        self.name = name

    @property
    def A(self) -> int:
```
type parameter of `__init__ ends up being property.
