### ISSUE TITLE
When enabled, extension creates XDG_CACHE_HOME in workspace directory

### ISSUE THREAD

**Issue by dj2kenne** [microsoft/python-language-server#1244]
## Environment data

- VS Code version: 1.35.1
- Extension version (available under the Extensions sidebar): 2019.5.18875
- OS and version: Ubuntu Linux 18.04
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.8 64-bit
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Relevant/affected Python packages and their versions: N/A
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info #3977): true

## Expected behaviour

VS Code extension does not create files in workspace directory, except possibly in .vscode directory.

## Actual behaviour

A directory named XDG_CACHE_HOME appears in the workspace directory shortly after starting .vscode.

## Steps to reproduce:
1. Install and enable Python extension.
2. Start code in a workspace directory.
3. Wait about 10 seconds.
4. Observe that there is now a directory named XDG_CACHE_HOME in the workspace directory.

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
Starting Microsoft Python language server.
[Info  - 12:09:46 PM] Analysis cache path: XDG_CACHE_HOME/Microsoft/Python Language Server
[Info  - 12:09:47 PM] GetCurrentSearchPaths /usr/bin/python3 
[Info  - 12:09:47 PM] Python search paths:
[Info  - 12:09:47 PM]     /usr/lib/python3.6
[Info  - 12:09:47 PM]     /usr/lib/python3.6/lib-dynload
[Info  - 12:09:47 PM]     /home/davidkennedy/.local/lib/python3.6/site-packages
[Info  - 12:09:47 PM]     /usr/local/lib/python3.6/dist-packages
[Info  - 12:09:47 PM]     /usr/lib/python3/dist-packages
[Info  - 12:09:47 PM] Configuration search paths:
[Info  - 12:09:47 PM] Microsoft Python Language Server version 0.2.96.0
[Info  - 12:09:47 PM] Initializing for /usr/bin/python3
```

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
XXX
```

**Comment by MikhailArkhipov** [comment]
Same as #1197. I believe the fix is in `daily` and/or `beta` channels.

**Comment by jakebailey** [comment]
@dj2kenne If you need this now you can set one of:

```json
"python.analysis.downloadChannel": "beta"
```

```json
"python.analysis.downloadChannel": "daily"
```
