### ISSUE TITLE
intellisense does not work class class variable __list

### ISSUE THREAD

**Issue by mryo0826** [microsoft/python-language-server#1251]
## Environment data

- VS Code version: 1.35,1
- Extension version (available under the Extensions sidebar): 2019.5.18875
- OS and version: Windows7
- Python version (& distribution if applicable, e.g. Anaconda): python 
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Relevant/affected Python packages and their versions: Python 3.7.3
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info #3977):  Language Server

## Expected behaviour
```
class Op:
    __EQ = "0"
    __NOT_EQ = "1"
    __OP_LIST = [__EQ]

    @classmethod
    def print_EQ(cls):
        print(cls.__EQ)

    @classmethod
    def print_NOT_EQ(cls):
        print(cls.__NOT_EQ)

    @classmethod
    def print_is_numeric_operatior(cls, ope):
        print(ope in cls.__OP_LIST)

    @classmethod
    def is_numeric_operator(cls, ope):
        return ope in cls.__OP_LIST


Op.print_EQ()
Op.print_NOT_EQ()
Op.print_is_numeric_operatior("0")
print(Op.is_numeric_operatior("0"))
```
intellisense does not work　` cls.__OP_LIST`

## Actual behaviour

intellisense work　` cls.__OP_LIST`

**Comment by MikhailArkhipov** [comment]
It does not appear outside b/c of the leading `__` so the bug is that variable should appear when referenced inside the class.
