### ISSUE TITLE
Pylint with venv doesn't work properly 

### ISSUE THREAD

**Issue by UncleKo** [microsoft/python-language-server#1255]
Issue Type: <b>Bug</b>

When I use python and pylint with venv,  pylint doesn't work correrctly. Some works partly with putting codes with red but no PROBLEMS showing in detail; some doesn't work at all. When I change pythonPath to system one(/usr/bin), it seems to work fine. (With Insiders, it's working fine even without saving.)

Language Server Version:
"Output - Python" just saying
##########Linting Output - pylint#########

CO. Mr. Tyreke White 

Extension version: 2019.5.18875
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.94GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2201)|
|Memory (System)|7.91GB (2.94GB free)|
|VM|0%|
</details>

**Comment by jakebailey** [comment]
Are you sure this is related to the language server? We do not run pylint. Did you mean to file an issue on the extension? https://github.com/Microsoft/vscode-python

**Comment by UncleKo** [comment]
I am not sure. Because Mr. Tyreke White asked me to put the problem here by Email after I gave the feedback, I put it here. Should I move this to there?

**Comment by jakebailey** [comment]
It seems that way, yes. I can't move it there myself, and they have different reporting requirements, so I'd go to: https://github.com/microsoft/vscode-python/issues/new/choose
