### ISSUE TITLE
* imported functions are not overwritten by functions of the same name

### ISSUE THREAD

**Issue by benbenji** [microsoft/python-language-server#1257]
When I type tf.tuncated ,the server show out the deprecated formation of the function truncated_normal just as the picture shows:
<img width="821" alt="image" src="https://user-images.githubusercontent.com/2499988/60171679-a595dd80-983d-11e9-803f-ca1ba48ef5b0.png">
I cleanly remembered one of the previous versions of the python-language server can complete all the options of this functions to be choosed by users ,so I am confused very much that whether it is a bug or the problem of my computer.Can any body help me? Thank you very much the version of my tensorflow is 1.12.0 ,my hardware is macOs mojave 10.14

**Comment by jakebailey** [comment]
Are you saying that this function shouldn't show up at all? What behavior are you expecting here?

**Comment by benbenji** [comment]
> Are you saying that this function shouldn't show up at all? What behavior are you expecting here?

No man，I mean the server show the wrong formation of this function with the wrong parameters which has been already deprecated by tensorflow, the right parameters is truncated_normal(shape, steddv,mean ....)  ,it is totally different with that picture,and it is really not convenient.

**Comment by jakebailey** [comment]
Following the definition back, the function that we're finding is in `gen_random_ops.py`, which looks like:

```python
def truncated_normal(shape, dtype, seed=0, seed2=0, name=None):
```

But we should be finding the one in `random_ops.py`, which looks like:

```python
def truncated_normal(shape,
                     mean=0.0,
                     stddev=1.0,
                     dtype=dtypes.float32,
                     seed=None,
                     name=None):
```

This is because `random_ops.py`, does:

```python
from tensorflow.python.ops.gen_random_ops import *
```

So gets the first function, but the redefinition doesn't seem to have occurred.

**Comment by jakebailey** [comment]
With #1433:

![image](https://user-images.githubusercontent.com/5341706/62976187-e25b6b00-bdd0-11e9-9235-21d6ac665701.png)

**Comment by benbenji** [comment]
Hello man @jakebailey  in my computer this bug still happens, I have already update python server in vscode market.

**Comment by MikhailArkhipov** [comment]
The changes are not in the stable download channel yet, they are in beta.
