### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by petrosschilling** [microsoft/python-language-server#1262]
Microsoft Python Language Server version 0.3.20.0

Requirements.txt
```
mypy==0.710
typing-extensions==3.7.4 
arrow==0.13.1
beautifulsoup4==4.7.1
binaryornot==0.4.4
certifi==2019.3.9
chardet==3.0.4
Click==7.0
cookiecutter==1.6.0
docx-mailmerge==0.4.0
future==0.17.1
hashids==1.2.0
idna==2.7
Jinja2==2.10
jinja2-time==0.2.0
livereload==2.5.1
lxml==4.3.2
MarkupSafe==1.1.1
mysqlclient==1.3.14
numpy==1.14.5
pandas==0.24.2
pdfkit==0.6.1
peewee==3.0.18
poyo==0.4.2
pycrypto==2.6.1
python-dateutil==2.6.1
python-docx==0.8.10
python-http-client==3.1.0
pytz==2018.7
requests==2.20.1
sendgrid==6.0.5
six==1.11.0
soupsieve==1.8
termcolor==1.1.0
tornado==6.0.1
urllib3==1.24.1
uWSGI==2.0.18
Werkzeug==0.14.1
whichcraft==0.5.2
xlrd==1.2.0
xmltodict==0.11.0
Pillow==6.0.0
eway-rapid-python
hypothesis

-e git+https://github.com/mattelectric/simplerr#egg=simplerr
```

LS is using 100% of CPU and leaking memory overtime.
<img width="819" alt="Screen Shot 2019-06-28 at 10 15 54 am" src="https://user-images.githubusercontent.com/5184353/60308785-d1c07400-998d-11e9-9b09-e6dccf5c8b1f.png">

I also noticed that it keeps analyzing in background forever.
<img width="268" alt="Screen Shot 2019-06-28 at 10 18 00 am" src="https://user-images.githubusercontent.com/5184353/60308838-0b917a80-998e-11e9-8a2f-da6d682de743.png">

I am using Remote SSH and IntelliCode extensions.

Might be related to  #1157 and #869

**Comment by petrosschilling** [comment]
Temporary solution i'm using is uninstalling IntelliCode and enabling jedi on settings.json
`"python.jediEnabled": true,`

**Comment by melkayam92** [comment]
Same here.
Started to happen since last update for me, memory + cpu very high usage.

**Comment by jakebailey** [comment]
Is there a complete piece of code we can test past just the requirements?

**Comment by petrosschilling** [comment]
> Is there a complete piece of code we can test past just the requirements?

Hey Jake. The problem occurs the moment I open a python file in VSCode. I was monitoring the process and as soon as I open a python file it skyrockets to 100% GPU.

I can give you a piece of code but I'm not sure how it would help.

**Comment by petrosschilling** [comment]
> Is there a complete piece of code we can test past just the requirements?

Hey Jake. The problem occurs the moment I open a python file in VSCode. I was monitoring the process and as soon as I open a python file it skyrockets to 100% GPU.

I can give you a piece of code but I'm not sure how it would help.

**Comment by petrosschilling** [comment]
Closed the issue by mistake :(

**Comment by petrosschilling** [comment]
#1291 Seems related

**Comment by jakebailey** [comment]
With that issue fixed, I'd appreciate it if you could try things with 0.3.27+, which you can get in the daily build:

```
"python.analysis.downloadChannel": "daily"
```

Currently 0.3.38.

**Comment by petrosschilling** [comment]
Sure! I will be able to test this on Monday morning and will be posting feedback in here.

Thanks for the effort guys. The community really appreciates it.

**Comment by petrosschilling** [comment]
The issue has been fixed!

Thanks to everyone involved.
