### ISSUE TITLE
It is downloaded after every fresh boot

### ISSUE THREAD

**Issue by Gr3Kidd3r** [microsoft/python-language-server#1268]
I'm on an Ubuntu 16.04 machine and every time I fresh boot my laptop (restart or shutdown) the python language server is downloaded.
Is there any workaround for this?

**Comment by jakebailey** [comment]
The VS Code extension downloads the language server. The language server doesn't download itself. You'll have to ask on the extension's issue tracker. https://github.com/Microsoft/vscode-python

**Comment by Gr3Kidd3r** [comment]
Thanks for quick response, happy coding :smile:
