### ISSUE TITLE
Language server goto definition issue

### ISSUE THREAD

**Issue by OutOfFocus4** [microsoft/python-language-server#1274]
Issue Type: <b>Bug</b>

Create a Python file with the following code:

```python
from django.test import TestCase


class MyTestCase(TestCase):
	def test_example(self):
		with self.assertRaises(ZeroDivisionError):
			value = 1 / 0
		self.assertNotEqual(value, 1)
```

Right-click on `assertRaises` and select 'Go to Definition'. A message will appear saying "No definition found for 'assertRaises'".

I have attached the output from the language server.

[langserver_output.log](https://github.com/microsoft/vscode-python/files/3355169/langserver_output.log)

This issue does not occur when using jedi. I also encountered this issue using Visual Studio Code on MacOS.

Extension version: 2019.6.22090
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:27:31.086Z)
OS version: Linux x64 4.15.0-54-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2061)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|2, 2, 1|
|Memory (System)|7.68GB (3.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by MikhailArkhipov** [comment]
https://github.com/microsoft/python-language-server/pull/1482
