### ISSUE TITLE
High memory usage on remote connection

### ISSUE THREAD

**Issue by JavaCS3** [microsoft/python-language-server#1280]
I found remote server gets really slow because python language server consumed 99% memory.
It's really easy to meet this case when I use vscode remote for a long time. I'm not sure if this related to sometimes "jump to definition" no response or "Jedi is enabled" on remote side.

Update: 
"Disable Jedi" on remote side not working

![image](https://user-images.githubusercontent.com/4168698/60641526-b9a19680-9e5e-11e9-91d5-e7b63517dddb.png)

**Comment by jakebailey** [comment]
If you have a code sample/list of requirements, that would be helpful. https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#filing-an-issue

**Comment by jakebailey** [comment]
We just built 0.3.22, which is available in the beta/daily channels. It contains some fixes which we believe will help solve some of the leaks. You can set this and reload to update:

```
"python.analysis.downloadChannel": "beta"
```

**Comment by jakebailey** [comment]
We've made a number of improvements since the issue was filed. I'm going to close this for now, but if you are able to provide more info on what code is being analyzed, we can reopen this and take a look.
