### ISSUE TITLE
How does this compare to pyls?

### ISSUE THREAD

**Issue by ianpan870102** [microsoft/python-language-server#1284]
As titled, I am choosing between this python-language-server and the one maintained here: (https://github.com/palantir/python-language-server). I'd love to know the differences between these 2 implementations. Cheers!

**Comment by SKalt** [comment]
According to https://langserver.org/#implementations-server, both have LSP feature parity.  Past that, I think you'll have to write your own benchmarks or UX comparison.

**Comment by jakebailey** [comment]
Just from the design point of view:

- Ours is written in C#, compiled with .NET Core to native code that executes, versus being in Python itself. This has performance implications (GIL, concurrency, etc), as well as distribution/platform support differences.
- That language server is a slew of different libraries hooked together to provide a single language server (jedi for completion, rope for rename, pylint/flake8 for linting, etc), while we're a single codebase in C# that does all of the above in a single structure. We have our own parser, symbol indexing, and so on. The differences with Jedi its own list (very different decisions and functionality in some cases).

The tool that works best for you will depend on a number of things; if you're using the VS Code Python extension with Jedi enabled, you're likely to get about the same functionality as the other language server, though some things are deferred until file save, like syntax checking. You can always see what works or doesn't work in both; if something doesn't work with our language server, please do file an issue!

**Comment by jakebailey** [comment]
I'm going to close this to keep it off the tracker (as it's not actionable), but feel free to followup if you'd like.

**Comment by ianpan870102** [comment]
Sure, thanks for the detailed explanation!

**Comment by osener** [comment]
> compiled with .NET Core to native code that executes

Are the binaries published somewhere? [Sublime Text](https://github.com/microsoft/python-language-server/blob/master/Using_in_sublime_text.md) instructions depend on having .NET Core installed.

Or is it the `.dll` that's native and it's tricky to build a self-contained executable? I'm interested in having something easily distributable for Windows, macOS and Linux.

**Comment by jakebailey** [comment]
There is no official build location at the moment, other than the blob storage used to give the VS Code extension its download (which is unstable, and we delete builds from there periodically). C# needs a runtime, so the choices are to either `dotnet publish` and bundle the runtime (what we do), or have an any-playform single download but require an external dotnet installation (not easy at the moment).
