### ISSUE TITLE
Unresolved relative import error

### ISSUE THREAD

**Issue by vari** [microsoft/python-language-server#1287]
I'm aware that there are other unresolved import error issues, but from what I've seen, none of them seem to cover the issue I'm running into.

## Environment data

- VS Code version: 1.35.1 (stable)
- Extension version (available under the Extensions sidebar): 2019.6.22090
- OS and version: Ubuntu 18.04
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.8
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A (though I have seen this occur even with a venv setup)
- Relevant/affected Python packages and their versions: N/A
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info #3977): Language Server (`"python.jediEnabled"` is set to false)

## Expected behaviour

Relative imports in subdirectory of workspace /project folder should not result in a warning / error.

## Actual behaviour

The relative import gives the warning "Unresolved import"

## Steps to reproduce:
1. Create a new directory, let's call it `test_import`.
2. Setup the directory as follows:

```
test_import/
    |---abc.py
    |---tests/
            |---conftest.py
            |---test_sample.py
```

Contents of `abc.py`:
```
import tests.test_sample

class Dummy:
    pass

```

Contents of `conftest.py`:
```
class OtherClass:
    pass

```

Contents of `test_sample.py`:
```
import conftest
from conftest import OtherClass

class Tester(OtherClass):
    pass

```
3. Notice that the `conftest` import gives the "Unresolved import" warning message when you open the `test_import` folder in VSCode and open the `test_sample.py` file in the editor.

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
Starting Microsoft Python language server.
[Info  - 3:35:29 p.m.] Analysis cache path: /home/var/.cache/Microsoft/Python Language Server
[Info  - 3:35:29 p.m.] GetCurrentSearchPaths /usr/bin/python3 
[Info  - 3:35:30 p.m.] Interpreter search paths:
[Info  - 3:35:30 p.m.]     /usr/lib/python3.6
[Info  - 3:35:30 p.m.]     /usr/lib/python3.6/lib-dynload
[Info  - 3:35:30 p.m.]     /home/var/.local/lib/python3.6/site-packages
[Info  - 3:35:30 p.m.]     /usr/local/lib/python3.6/dist-packages
[Info  - 3:35:30 p.m.]     /usr/lib/python3/dist-packages
[Info  - 3:35:30 p.m.] User search paths:
[Info  - 3:35:30 p.m.] Microsoft Python Language Server version 0.3.20.0
[Info  - 3:35:30 p.m.] Initializing for /usr/bin/python3
```

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

-> If the information provided above is not sufficient for investigating the issue, let me know and I will add the output from the `Console` panel as a separate post.

**Comment by AlexanderSher** [comment]
If `test_import` is a root directory, then `import conftest` is invalid for Python 3, cause none of the imports in `test_sample.py` are relative. Correct import code should be:
```
import tests.conftest
from .conftest import OtherClass
```

**Comment by vari** [comment]
Ah right, thanks for pointing that out. The reason I thought this was wrong was because I had my PYTHONPATH setup in such a way that the imports gave no problems when the code was actually run.
