### ISSUE TITLE
Support Django object models

### ISSUE THREAD

**Issue by brettcannon** [microsoft/python-language-server#129]
Microsoft/vscode-python#2271

**Comment by karthiknadig** [comment]
From feedback:

> Please see screenshots below from PyCharm and VS Code respectively.
> ![image](https://user-images.githubusercontent.com/3840081/47315707-32770000-d5fa-11e8-9958-1f8b2e3b6f8c.png)
> ![image](https://user-images.githubusercontent.com/3840081/47315733-402c8580-d5fa-11e8-9ed1-15c81b98507e.png)
> As you can see the list of hints in PyCharm is more accurate.
> This is also the case below when accessing a django model's fields.  PyCharm is able to detect that the value will actually be a string whereas VS Code only knows it as a CharField.
> ![image](https://user-images.githubusercontent.com/3840081/47315758-4de20b00-d5fa-11e8-86a8-7c6750350283.png)
> ![image](https://user-images.githubusercontent.com/3840081/47315788-58040980-d5fa-11e8-8179-857080d0bce3.png)

**Comment by SHxKM** [comment]
This would be lovely. Also , recognizing import errors specific to Django:

```python 
from django.db.models import Q  # notice F isn't imported
#...
cls.get_artists_with_subs().order_by(F("last_refreshed")
```

VSCode doesn't see any problem with this ^ 

Pycharm, on the other hand, complains:

<img width="284" alt="Screen Shot 2019-05-11 at 23 17 25" src="https://user-images.githubusercontent.com/6573474/57574508-fcd51f80-7442-11e9-9685-44cf7921a82f.png">

**Comment by jakebailey** [comment]
F not being warned seems like a bug; we'd appreciate it if you could make a new issue so we can fix it.

**Comment by elahmo** [comment]
Has there been any work regarding this?

Go to definition is a hit and miss with Python/Django, in most cases I have to search for `class xxx(` or `def property(` in order to find the definition.

**Comment by alexruimy** [comment]
Same here. This has been a problem with the language server for years.

**Comment by jakebailey** [comment]
There's a pretty tremendous amount of work in this item; Django models are all metaclass based where everything is generated at runtime, requiring us to essentially reimplement Django again in the analysis as special cases. There are stubs which provide richer info, but require a much better understanding of `typing` in general (which don't have complete).

Either way, if we aren't actively updating an issue, then there aren't any updates.

**Comment by HarshilPatel007** [comment]
the new jedi 0.17.1 release now supports Django Meta Classes and added Django Stubbs.
If possible upgrade it to the newer version and harness the power of it into vscode-python.

**Comment by MikhailArkhipov** [comment]
LS does not use Jedi, so this issue is for the Python extension.

**Comment by HarshilPatel007** [comment]
> LS does not use Jedi, so this issue is for the Python extension.

Ohh, I though my query is mentioned here so I think it is related.

**Comment by system32uwu** [comment]
No updates on this? It's really frustrating having to check the documentation for every single property or method I want to use, I just want to press ctrl + space and get to know the things I can use and don't depend on myself to type it correctly...

**Comment by jakebailey** [comment]
This repo is no longer actively maintained or published. Consider using Pylance or Jedi, and filing issues for missing functionality appropriately. Pylance in particular ships stubs for Django which may help.

**Comment by judej** [comment]
Thank you for the report. This project is no longer active. If you are using the Python language server in VSCode, the language server you are using is Pylance and please the http://github.com/microsoft/pylance-release to report issues. 

If you are using Visual Studio, then, please use http://github.com/microsoft/PTVS to report issues.

[devblogs.microsoft.com/python/python-in-visual-studio-code-september-2021-release/#microsoft-python-language-server-end-of-life-november-2021](https://devblogs.microsoft.com/python/python-in-visual-studio-code-september-2021-release/#microsoft-python-language-server-end-of-life-november-2021)

thank you
