### ISSUE TITLE
Request: Please test thoroughly before releasing any new version of language server

### ISSUE THREAD

**Issue by kaushall** [microsoft/python-language-server#1292]
Dear Team,

Thank you so much for the wonderful software product and the team behind it. But after facing some major issues with python language server recently we cannot relay on it anymore. It is not much stable and it will break the flow with every new release. Also there is no option to downgrade the python language server.

I'm requesting you guys, if possible please test the python language server thoroughly before releasing any new version.

Once again thank you soo much!

**Comment by jakebailey** [comment]
We do test everything we release. We kept 0.3 back for about a month testing and fixing things, and 0.3.20 (the most recent stable) in daily/beta channels for a while itself making sure everything was working well. The recent CPU/memory usage issues were reported at the end of last week (the holiday weekend), a while after it was released to everybody. Issues do happen, and we try to prevent and fix them as much as we can, but there's always a chance of something being missed.

Your issue, #1291, may have improved with the most recent PR merged. See there for info.
