### ISSUE TITLE
"Undefined variable" with multiple assignment and unpacking

### ISSUE THREAD

**Issue by jekbradbury** [microsoft/python-language-server#1293]
Seems like the combination of multiple assignment and unpacking assignment confuses the parser or symbol tracker. Examples like this code:
```
a = b, _ = [0, 1]
print(b)
```
are giving me `Undefined variable: 'b'`

**Comment by gramster** [comment]
Thanks, we are investigating.

**Comment by moshe** [comment]
also not working:
```
[info], [nodes] = get_info()
```
shows `Undefined variable: 'info'Python(undefined-variable)` for both info and nodes

**Comment by MikhailArkhipov** [comment]
0.4.18+
