### ISSUE TITLE
Collections module works in 2.7 but not in 3.6

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/python-language-server#13]
3.6
```python
import collections
collections.deque(). #<- nothing
```

2.7
![image](https://user-images.githubusercontent.com/12820357/43804633-8dea3b62-9a51-11e8-9d19-f79bf5155a27.png)

Might be b/c typeshed `typeshed\stdlib\3\collections\__init__.py` vs `typeshed\stdlib\2\collections.pyi`

**Comment by jakebailey** [comment]
I can't seem to reproduce this. Tested in 3.6 and 3.7 against master.

![image](https://user-images.githubusercontent.com/5341706/46829226-0c2ba780-cd52-11e8-9e40-39c4dc56d70a.png)
