### ISSUE TITLE
Unresolved imports with Django

### ISSUE THREAD

**Issue by Aninstance** [microsoft/python-language-server#1303]
I'm getting "unresolved import" warnings when coding Django, despite my imports correctly resolving when the app is run.

I'm running the 'snap' version of VScode, on Ubuntu 18.04, version as per:

`Version: 1.36.1
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:55:08.091Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.18.0-25-generic snap`

See the below screenshot for an example of the warnings. Note that `articles.models` is underlined. The warning in the associated popup toast reads: "unresolved import 'articles.models' Python(unresolved-import)"

![image](https://user-images.githubusercontent.com/6099727/60977860-12be6e00-a328-11e9-8068-0315eb1163e1.png)

My workspace settings.json:

```
{
    "python.jediEnabled": false,
    "python.linting.pep8Enabled": true,
    "python.linting.pylintArgs": [
      "--load-plugins",
      "pylint_django"
  ],
    "python.formatting.provider": "autopep8",
    "python.linting.pylintEnabled": true,
    "python.linting.enabled": true,
    "python.venvPath": "${workspaceFolder}/backend",
    "python.pythonPath": "backend/venv/bin/python3.7"
}
```

Note: Changing the python.pythonPath to the full filesystem path makes no difference to the issue.

I may be missing something or otherwise screwed up the configuration somehow, or this could be a bug. Either way, I've worked though various potential solutions today, to no avail. Changing `python.jediEnabled` from `false` to `true` obviously mitigates the issue (being that the python-language-server is disabled).

**Comment by jakebailey** [comment]
The language server assumes imports will be relative to the workspace folder, but your code assumes that they start in `./backend/src`. You need to set extraPaths (or PYTHONPATH) to reflect this. See: https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#unresolved-import-warnings

For example:

```
"python.autoComplete.extraPaths": ["./backend/src"]
```

Or:

```
PYTHONPATH=./backend/src
```

**Comment by Aninstance** [comment]
@jakebailey Ah, got it. That did the trick. Magic! Thanks for that.
