### ISSUE TITLE
Python Language Server never finish initializing for virtual env in remote docker

### ISSUE THREAD

**Issue by messi-yang** [microsoft/python-language-server#1310]
## Environment data

- VS Code version: 1.36.1
- Extension version (available under the Extensions sidebar): 2019.6.24221
- OS and version: Mac OS 10.14.5
- Python version (& distribution if applicable, e.g. Anaconda): 2.7.12
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv
- Relevant/affected Python packages and their versions: XXX
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info #3977): 
Language Server

## Expected behaviour
Initializing for /edx/app/edxapp/venvs/edxapp/bin/python can finish and something like IntelliSense, linting, code navigation, code formatting can work 

## Actual behaviour

Initializing for /edx/app/edxapp/venvs/edxapp/bin/python never finishes, so the language server doesn't work? But if I enable Jedi, IntelliSense, linting, code navigation, code formatting are all ok.

## Steps to reproduce:
1. Attach VS Code in running Docker container
2. It should open a new window, and then choose the interpreter in the status bar. I choose the virtualenv python interpreter.
3. Language Server doesn't work for IntelliSense, linting, code navigation, code formatting. 

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

Starting Microsoft Python language server.
[Info  - 2:21:56 AM] Analysis cache path: /root/.cache/Microsoft/Python Language Server
[Info  - 2:21:56 AM] GetCurrentSearchPaths /edx/app/edxapp/venvs/edxapp/bin/python 
[Info  - 2:21:57 AM] Interpreter search paths:
[Info  - 2:21:57 AM]     /edx/app/edxapp/venvs/edxapp/lib/python2.7
[Info  - 2:21:57 AM]     /edx/app/edxapp/venvs/edxapp/lib/python2.7/lib-dynload
[Info  - 2:21:57 AM]     /usr/lib/python2.7
[Info  - 2:21:57 AM]     /usr/lib/python2.7/plat-x86_64-linux-gnu
[Info  - 2:21:57 AM]     /usr/lib/python2.7/lib-tk
[Info  - 2:21:57 AM]     /edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages
[Info  - 2:21:57 AM]     /edx/app/edxapp/venvs/edxapp/src/oppia-xblock
[Info  - 2:21:57 AM]     /edx/app/edxapp/venvs/edxapp/src/officemix
[Info  - 2:21:57 AM]     /edx/app/edxapp/venvs/edxapp/src/schoolyourself-xblock
[Info  - 2:21:57 AM]     /edx/app/edxapp/venvs/edxapp/src/concept-xblock
[Info  - 2:21:57 AM]     /edx/app/edxapp/venvs/edxapp/src/audio-xblock
[Info  - 2:21:57 AM]     /edx/app/edxapp/venvs/edxapp/src/animation-xblock
[Info  - 2:21:57 AM]     /edx/app/edxapp/venvs/edxapp/src/xblock-vectordraw
[Info  - 2:21:57 AM]     /edx/app/edxapp/venvs/edxapp/src/xblock-activetable
[Info  - 2:21:57 AM]     /edx/app/edxapp/venvs/edxapp/src/acid-xblock
[Info  - 2:21:57 AM]     /edx/app/edxapp/venvs/edxapp/src/code-block-timer
[Info  - 2:21:57 AM]     /edx/app/edxapp/venvs/edxapp/src/codejail
[Info  - 2:21:57 AM]     /edx/app/edxapp/venvs/edxapp/src/django-wiki
[Info  - 2:21:57 AM]     /edx/app/edxapp/venvs/edxapp/src/done-xblock
[Info  - 2:21:57 AM]     /edx/app/edxapp/venvs/edxapp/src/edx-jsme
[Info  - 2:21:57 AM]     /edx/app/edxapp/venvs/edxapp/src/parse-rest
[Info  - 2:21:57 AM]     /edx/app/edxapp/venvs/edxapp/src/pygeoip
[Info  - 2:21:57 AM]     /edx/app/edxapp/venvs/edxapp/src/pystache-custom
[Info  - 2:21:57 AM]     /edx/app/edxapp/venvs/edxapp/src/rate-xblock
[Info  - 2:21:57 AM]     /edx/app/edxapp/venvs/edxapp/src/xblock-google-drive
[Info  - 2:21:57 AM]     /edx/app/edxapp/edx-platform/common/lib/calc
[Info  - 2:21:57 AM]     /edx/app/edxapp/edx-platform/common/lib/capa
[Info  - 2:21:57 AM]     /edx/app/edxapp/edx-platform/common/lib/chem
[Info  - 2:21:57 AM]     /edx/app/edxapp/edx-platform/common/lib/dogstats
[Info  - 2:21:57 AM]     /edx/app/edxapp/edx-platform
[Info  - 2:21:57 AM]     /edx/app/edxapp/edx-platform/common/lib/safe_lxml
[Info  - 2:21:57 AM]     /edx/app/edxapp/edx-platform/common/lib/sandbox-packages
[Info  - 2:21:57 AM]     /edx/app/edxapp/edx-platform/common/lib/symmath
[Info  - 2:21:57 AM]     /edx/app/edxapp/edx-platform/openedx/core/lib/xblock_builtin/xblock_discussion
[Info  - 2:21:57 AM]     /edx/app/edxapp/edx-platform/common/lib/xmodule
[Info  - 2:21:57 AM]     /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages
[Info  - 2:21:57 AM] User search paths:
[Info  - 2:26:07 AM] Microsoft Python Language Server version 0.3.20.0
[Info  - 2:26:07 AM] Initializing for /edx/app/edxapp/venvs/edxapp/bin/python

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
XXX
```

**Comment by jakebailey** [comment]
Since this issue was transferred, could you take a look at https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#filing-an-issue and provide some extra info as to your setup?

The language server has seen a lot of development since this issue was filed, and some updated logs would be helpful.

**Comment by jakebailey** [comment]
I'm going to close this for now, but if you have more info in the future on a newer version, feel free to open a new issue with our template or reopen this with more info.
