### ISSUE TITLE
.editorconfig

### ISSUE THREAD

**Issue by lostmsu** [Microsoft/python-language-server#132]
Can you guys please add `.editorconfig` in addition to, or even to replace omnisharp.json. I think `.editorconfig` is supported more widely.

**Comment by rv404674** [comment]
Hi @lostmsu. I am a newcomer and I would like to take up this issue.

**Comment by lostmsu** [comment]
@rv404674 no, `.editorconfig` has different format, for example: https://kent-boogaart.com/blog/editorconfig-reference-for-c-developers

Here's a more detailed reference: https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017

To get the idea of what should be there, you can look at `omnisharp.json` file, but its format is completely different (though names will be similar).

I think the hardest step will be to define naming styles (e.g. fields to start with '_', and similar), but you can skip that for the initial try.

**Comment by rv404674** [comment]
hey @lostmsu, i have made the .editorconfig file, but i am not able to push it. There is an error coming
''
remote: Permission to Microsoft/python-language-server.git denied to rv404674.
fatal: unable to access 'https://github.com/Microsoft/python-language-server.git/': The requested URL returned error: 403
"

**Comment by rv404674** [comment]
hey @lostmsu , i have made a new .editorconfig file, with your suggestions. Can you take a look when you get some time. Thanks.
