### ISSUE TITLE
PLS reanalyzes everything when test files changes

### ISSUE THREAD

**Issue by lephuongbg** [microsoft/python-language-server#1329]
After I save any changes to a test file, the python extension will run `Discovering tests` and at the same time PLS will reanalyzes everything. PLS doesn't do that after I save non-test files though.

I'm on daily channel of PLS, current version 0.3.30.0.

**Comment by MikhailArkhipov** [comment]
I guess your test files folder is somehow recognized as library code. Please provide your search paths and extra paths setting.

**Comment by lephuongbg** [comment]
Just got new version of PLS. Now at 0.3.35.0. This one seems to not trigger reanalyzation on test file change though. Will use it for a few days first before confirming that this bug can be closed.

```
[Info  - 8:59:36 AM] Interpreter search paths:
[Info  - 8:59:36 AM]     /home/username/Projects/myproject/api/.venv/lib/python3.7
[Info  - 8:59:36 AM]     /home/username/Projects/myproject/api/.venv/lib/python3.7/lib-dynload
[Info  - 8:59:36 AM]     /usr/lib/python3.7
[Info  - 8:59:36 AM]     /home/username/Projects/myproject/api/.venv/lib/python3.7/site-packages
[Info  - 8:59:36 AM] User search paths:
[Info  - 8:59:36 AM]     /home/username/Projects/myproject/api
[Info  - 8:59:47 AM] Microsoft Python Language Server version 0.3.35.0
```

**Comment by jakebailey** [comment]
Yes, before #1306 we were (incorrectly) watching the wrong thing, likely that `api` folder. Past that PR, we should only be watching what we display as "interpreter paths" for changes (e.g. pip installing new packages).

**Comment by jakebailey** [comment]
I'm going to close this; as far as I can tell the PR did fix this in all of the cases I've seen, since the watching is no longer on PYTHONPATH/extraPaths.
