### ISSUE TITLE
Is there a common place where PLS will store its InterpreterConfiguration?

### ISSUE THREAD

**Issue by lostmsu** [Microsoft/python-language-server#133]
In PTVS I could enumerate available Python installations by getting `IInterpreterRegistryService` from Visual Studio's `CompositionContainer`. Will something like that be available in PLS?

**Comment by MikhailArkhipov** [comment]
No. Language server receives its configuration from the client application. When interpreter changes, LS is restarted. It is up to the client app to determine and handle configuration.

**Comment by lostmsu** [comment]
What about discovery of installed interpreters?

**Comment by MikhailArkhipov** [comment]
It is up to the client application. LS does not do it.
