### ISSUE TITLE
@property outside of class definition causes NRE

### ISSUE THREAD

**Issue by CTrando** [microsoft/python-language-server#1335]
ex:

```
@property
def foo(self):
    return 123
```

causes an NRE because declaringType is null for functions outside of a class scope, and in the constructor for PythonPropertyType we do not check for null declaring type.

**Comment by jakebailey** [comment]
Doesn't even have to be outside of a class; scikit-learn's deprecation util library hits this:

```python
class deprecation:
    def _decorate_property(self, prop):
        msg = self.extra

        @property
        def wrapped(*args, **kwargs):
            warnings.warn(msg, category=DeprecationWarning)
            return prop.fget(*args, **kwargs)

        return wrapped
```

`declaringType` is null.

**Comment by jakebailey** [comment]
I'm not entirely sure how properties work now, but we may need to stop attaching them to any one type, and just let their existence as a member of something else be enough to distinguish them.

**Comment by MikhailArkhipov** [comment]
We can either not create the odd property or make it a standalone function if there is no declared type. I guess problem is that it gets member type of property or method and that implies declaring type. 

Generally we don't handle classes or inner functions inside other functions very well in master atm. I fixed a number of this cases in persistence branch.
