### ISSUE TITLE
PythonVersions NullReferenceException in many tests

### ISSUE THREAD

**Issue by davidwallacejackson** [Microsoft/python-language-server#134]
I get a number of errors trying to run `dotnet test` on master, most of which involve this exception and stack trace:

```
System.TypeInitializationException: The type initializer for 'Microsoft.PythonTools.Analysis.PythonVersions' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
Stack Trace:
    at Microsoft.PythonTools.Analysis.PythonVersions.GetCPythonVersion(PythonLanguageVersion version, InterpreterArchitecture arch) in /Users/davidjackson/git/python-language-server/src/Analysis/Engine/Test/PythonVersions.cs:line 150
   at Microsoft.PythonTools.Analysis.PythonVersions..cctor() in /Users/davidjackson/git/python-language-server/src/Analysis/Engine/Test/PythonVersions.cs:line 29
```

I'm on OSX, using `dotnet` v2.1.402 with Python 3.6.6 and 2.7.15 installed.

I've also tried to launch the unit tests from VS Code per the `CONTRIBUTING.md` file, but it seems to run the tests for the Python vscode extension rather than for the language server. I tried to open the project in VS2017 Community Edition on Windows, but received a fleet of errors saying that the project wasn't compatible with my version of Visual Studio and needed to be migrated.

**Comment by MikhailArkhipov** [comment]
Tests are supposed to run inside VS, not via dotnet.
The project is .NET Core so make sure you specify .NET cross-platform development in VS setup

![image](https://user-images.githubusercontent.com/12820357/46045714-4e5ab500-c0d3-11e8-9dc2-79eb2aff4839.png)

**Comment by davidwallacejackson** [comment]
I'll check and make sure I have .NET Core installed later today, and I'll report back. It might be good to clarify the CONTRIBUTING document, though, as it suggested to me that I could run the tests from inside VS Code, which didn't seem to work either.

**Comment by MikhailArkhipov** [comment]
You do can run tests from VS Code, but those will be _Python Extension tests_ related to the language server and not LS tests as we have here.
