### ISSUE TITLE
False positive redefinition warning

### ISSUE THREAD

**Issue by USSRLivesOn** [microsoft/python-language-server#1346]
The new redefinition logic from (I'm guessing) #1273 looks to have false positives for property attributes in classes. For example, from the [Python docs](https://docs.python.org/3.6/library/functions.html#property):

```python
class C:
    def __init__(self):
        self._x = None

    @property
    def x(self):
        return self._x

    @x.setter
    def x(self, value):
        self._x = value
```

This has a `function-redefined` warning on the second `def x`, but should not. It is valid code.

I assume it's the same issue, but this also impacts SQLAlchemy `hybrid_property`s:
```python
from sqlalchemy.ext.hybrid import hybrid_property

class Interval(object):
    @hybrid_property
    def radius(self):
        return 'foo'

    @radius.expression
    def radius(cls):
        return 'bar'
```

**Comment by MikhailArkhipov** [comment]
Looks like issue with the https://github.com/microsoft/python-language-server/pull/1273.

**Comment by last-partizan** [comment]
Another false positive example

```
from copy import copy

SOCIAL_LINK_GETTERS = {
    "facebook": lambda data: data["link"],
    "google": lambda data: data["link"],
    "github": lambda data: data["html_url"],
}
```

```
test.py:1:1 Error [Python function-redefined] Function already defined at line 1.
```

**Comment by jakebailey** [comment]
Yeah, #1273's changes likely just need to skip over the redefintion warning when `fd.Name` is null or empty, or `fd.IsLambda` is true (since all lambdas have the same `fd.Name`).
