### ISSUE TITLE
unsolved import

### ISSUE THREAD

**Issue by tfighting** [microsoft/python-language-server#1348]
I am using the language server with emacs,but I met a problem.
when I  invoked some "class" or "function"  from anohter file under the same folder,a warning(unsolved import) always occurred.
![2019-07-18 11-10-32 的屏幕截图](https://user-images.githubusercontent.com/48683803/61427013-22a10800-a94f-11e9-8118-78d4e16b4b2e.png)
![2019-07-18 11-37-35 的屏幕截图](https://user-images.githubusercontent.com/48683803/61427380-8546d380-a950-11e9-8137-7f59f916f032.png)

**Comment by bsandrow** [comment]
This basically looks like `~/new/my_projects/person/train` isn't in `sys.path`. I'm guessing that the server isn't being run with the current directory set to the directory containing the files. So you either need to add that directory to `PYTHON_PATH` (which gets added to `sys.path`) or you need to configure the server so that `.` is the correct directory when it runs.

You could test this by adding the following to the top of your `example2.py` file (before the import of `example1`):

```python
import os
import sys
sys.path.append(os.path.expanduser('~/new/my_projects/person/train'))
```

**Comment by jakebailey** [comment]
The language server doesn't actually use the working directory anywhere (to avoid issues like how VS Code run via a shortcut would have its working directory where the `exe` is), but instead relies on the workspace root given in the initialization. So long as that's correct, those imports should be fine.

**Comment by liuning0930** [comment]
I also have this issue. Except adding the directory to PYTHON_PATH, does have any other way to solve the issue?
And I also use:
`sys.path.insert(0, os.path.abspath(unittestRootDir))
sys.path.insert(0, './avsmusiccertificate/')
sys.path.append(os.path.abspath(unittestRootDir))
`
But the warning always display, hahahaha!

**Comment by jakebailey** [comment]
If you are using VS Code, have you read the troubleshootig entry? If you must use runtime `sys.path` modification and not PYTHONPATH, then you can try extraPaths. https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#unresolved-import-warnings

Modifying sys.path at runtime, especially when it's as complicated as you've written above (with function calls on variables) makes it extremely difficult to reason about statically.

**Comment by tfighting** [comment]
@bsandrow ,thanks for your answer!
In fact, ~/new/my_projects/person/train is always in sys.path and the programing still works well,but the warning that always displays leads to the completion doesn't work at all!

**Comment by tfighting** [comment]
@jakebailey ，thanks！
I have solved my probelm by adding .projectile file to the root workspace .
