### ISSUE TITLE
What does showAdvancedMembers mean?

### ISSUE THREAD

**Issue by Jma353** [microsoft/python-language-server#1349]
I noticed a [setting called `showAdvancedMembers`](https://github.com/microsoft/python-language-server/blob/fc77d427c34ad9036174ce42cf23c68af800a92f/src/LanguageServer/Impl/LanguageServer.Configuration.cs#L46) when poking around to see what setting inputs the language server takes in to enable customization of a user's experience.  

What does this setting mean?  Is it still used, or is it a relic of some since-removed code (b/c I can't see it referred to anywhere).

**Comment by Jma353** [comment]
I guess I could ask similar questions about other settings that are passed into the language server (e.g. `symbolsHierarchyDepthLimit`) - where are these used?  Github search [isn't turning up many results for me](https://github.com/microsoft/python-language-server/search?q=symbolsHierarchyDepthLimit&unscoped_q=symbolsHierarchyDepthLimit) - I only see defaults and the assignment of the variable.  I guess, in general, I'm wondering what settings this language server now accepts to customize its inner-workings (analysis, caching, etc.) as well as user-experience things (e.g. autocomplete with parens, outline depth, etc.)

**Comment by jakebailey** [comment]
All of those settings seem to be dead code and leftovers from the pre-rewrite language server. I believe `showAdvancedMembers` controlled when dunder methods would show. The symbols settings limited the symbol indexing (the outline, workspace search), but needed to move during the rewrite and instead get limited at request time rather than hardcoded.

There's a bunch of old setting cruft we could remove, just haven't had the time to yet.

**Comment by Jma353** [comment]
Nice - thanks for the answer! 

Follow-up request: it would be great if there was up-to-date docs w.r.t. what options can be passed to this language server (I guess one could read the code, but still). 

Closing as my original question was answered.

**Comment by jakebailey** [comment]
Yes, definitely. See also #469, #794, #1184, #1212, #1340. Our focus has been on getting things to work and fixing bugs, so docs and settings cleanups just haven't happened.
