### ISSUE TITLE
Embed in own project

### ISSUE THREAD

**Issue by gnimor** [microsoft/python-language-server#1351]
This is not really an issue but more like a question. I am trying to embed the option for python scripting in my own WPF application based on C#. The integration seems to work great and I am able to offer the user typing python code in my app. The only thing which is currently missing is some "basic" intellisense. 
So I thought it would be possible to use the language server in my application as well, but I am a little bit lost finding a good starting point. Is there a good example (possibly in C#) as a starting point to understand how to integrate the language server in an own application? It would also be helpful if someone tells me that this is the complete wrong approach - which I have in mind here?

**Comment by jakebailey** [comment]
Most of the functionality that powers "intellisense" (completion and others) is wrapped up in the language server serverside code that editors typically talk to, which makes it difficult to do something like embedding the language server within the same process. Currently, it might not be a good idea to approach like that, but could be possible with some effort

What you may want to consider is being a language server client and spawning a language server process to talk to. This is how VS Code, emacs, vim, etc, all use the language server. In C#, you can use the StreamJsonRpc library to make the calls, but you may also run into the issue of needing to re-implement some of the functionality that those editors have already done, i.e. sending the language server file open events, file changes, etc (which may actually be fine, given you're essentially implementing an editor).

As far as existing examples in C# (so back to the running in-proc), there isn't really much other than potentially looking at how we run tests on the language server. There, we make an analysis and then call the code the language server does to create completions. But, this doesn't exactly cover the end-to-end of a user modifying a file, all of the settings, etc, that you get "for free" by just being a client.

**Comment by MikhailArkhipov** [comment]
LSP: https://microsoft.github.io/language-server-protocol/specification

**Comment by gnimor** [comment]
Thanks for your help. I will take a closer look!
