### ISSUE TITLE
function-redefined raised on conditionally-defined code

### ISSUE THREAD

**Issue by brettcannon** [microsoft/python-language-server#1358]
E.g.
```python
if __debug__:
    def spam():
        return 42
else:
    def spam():  # Flagged as a redefinition.
        return -13
```
This is also a very common pattern when you use different code based on OS, whether a module is available, etc.

**Comment by jakebailey** [comment]
Since we don't have dataflow analysis / assignment ranges, I'm not entirely sure we can do this without a bunch of hacks... cc @CTrando

**Comment by brettcannon** [comment]
@jakebailey then I'm worried about the amount of false-positives this check is going throw.

**Comment by jakebailey** [comment]
Easy "fix" would be to skip out when we see that a def is inside an if/else/try/except/finally, which retains the old behavior.

**Comment by brettcannon** [comment]
@jakebailey maybe, although I still wonder if this check is worth it since it isn't an error to redefine a name, e.g. if you use `__prepare__` and a metaclass then you could legitimately do something like automatically apply `functools.singledispatch` to any method defined more than once.

**Comment by jakebailey** [comment]
At that point, are other linters which handle multiple-definition going to figure that out too? That seems pretty wild...
