### ISSUE TITLE
False positives for "inheriting from something that is not a class"

### ISSUE THREAD

**Issue by MartyBeGood** [microsoft/python-language-server#1361]
The Diagnostics for Inheriting from something that is not a class reports false positives when a library like [PonyORM](https://github.com/ponyorm/pony) creates classes dynamically.

MWE:
```python
from pony.orm import *
db = Database()
# You're supposed to have your entities inherit from db.Entity
# For reference, this gets created in pony/orm/core.py:746
class MyEntity(db.Entity): # Diagnostic warning because the python language server thinks we're not inheriting from a class
    mystr = Optional(str)

db.bind(provider='sqlite', filename='database.sqlite', create_db=True, create_tables=True)
```

**Comment by MikhailArkhipov** [comment]
Need to check what `db.Entity` evaluates to. Might be unknown which we should be permitting. @MartyBeGood - if it annoys you, you can turn the specific warning off either in settings or by adding `#noqa` to the line.
