### ISSUE TITLE
Inherited from class warnings on NamedTuple (implemented as specialized function)

### ISSUE THREAD

**Issue by cmcarey** [microsoft/python-language-server#1364]
**Language server version** Microsoft Python Language Server version 0.3.39.0

**Env** VSCode non insiders (though happens on insiders too), latest win10

Easiest issue to reproduce is related to inheriting from "non c;lass".  Here's some code that is *definitely fine* -
```python
from typing import NamedTuple

class X(NamedTuple):
    y: str
```

typing.NamedTuple is 100% a class.  This code has been in place for weeks and has been absolutely fine, and a few hours ago started throwing these warnings.

The other, harder to debug issue is that, again, all of a sudden and at no prompting, the language server doesn't seem to understand import paths at all.  I have the exact same workspace open as always, and yet every local import is unresolved.

I'm using latest VSCode, latest vscode-python extension, and I have Jedi disabled, so it's using python-language-server.

**Comment by jakebailey** [comment]
Probably the same as #1361.

As for not understanding import paths, that sounds like a different issue. We'd appreciate it if you could open a new issue with some info about that for us to look into.

**Comment by cmcarey** [comment]
> 
> 
> Probably the same as #1361.
> 
> As for not understanding import paths, that sounds like a different issue. We'd appreciate it if you could open a new issue with some info about that for us to look into.

Weird as it *just started happening* even though I don't see any releases of vscode-python.

RE the import issue, not sure what other information I can provide for that

**Comment by jakebailey** [comment]
The language server is released independently from the extension. The extension will download new versions of the language server as we release them.

For imports, see https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md

Specifically the sections on unresolved imports and how to report an issue.

**Comment by jakebailey** [comment]
@CTrando This is a case where the typing specialization is done as a function and not as a class. The linting message should probably just be checking to ensure that the declaring module of the bad type isn't from typing or specialized.

**Comment by cmcarey** [comment]
@CTrando fantastic, thank you.  How often do new builds go out with bugfixes?

**Comment by MikhailArkhipov** [comment]
After every PR they appear in "daily" channel. Changes get promoted up manually when we deem them baked enough.

**Comment by cmcarey** [comment]
Ah .. can I opt in to daily channel somehow?  This bug is pretty killer (every file shows as having errors because of it) for me

**Comment by jakebailey** [comment]
Set this and reload:

```
"python.analysis.downloadChannel": "daily"
```

But this lint fix is likely to go out very soon.

**Comment by cmcarey** [comment]
Great, thank you!

**Comment by MikhailArkhipov** [comment]
Well
```json
    "python.analysis.disabled": [
        "inherit-non-class"
    ]
```
should also work

**Comment by cmcarey** [comment]
> 
> 
> Set this and reload:
> 
> ```
> "python.analysis.downloadChannel": "daily"
> ```
> 
> But this lint fix is likely to go out very soon.

I don't actually have that as an option.  Disabling `inherit-non-class` did work though.
