### ISSUE TITLE
"Go to Symbol in Workspace..." errors out for scikit-learn

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/python-language-server#137]
Microsoft/vscode-python#2637

Check out scikit-learn, open a Python file to start the extension, hit `ctrl+t` and search for `KMeans`. You should end up in `sklearn/cluster/k_means_.py` at the `class KMeans` class. But instead you end up with an error of:
```
[Error - 3:48:02 PM] Request workspace/symbol failed.
  Message: Object reference not set to an instance of an object.
  Code: -32000 
[object Object]
```

I tried setting `"python.analysis.logLevel": "Trace"` but I didn't see anything useful to help with this.

**Comment by MikhailArkhipov** [comment]
Is it latest? Current insiders build does not download latest bits. Or did you build the LS?

**Comment by ogrisel** [comment]
How do you get the version information of the language server from the VS Code UI?

**Comment by MikhailArkhipov** [comment]
I guess I will add version info to the startup message.

**Comment by brettcannon** [comment]
@ogrisel a new release of the extension went out today which will download the latest bits to test automatically at most once a day.
