### ISSUE TITLE
metaclasses/inheriting from `type`

### ISSUE THREAD

**Issue by bmoyles** [microsoft/python-language-server#1377]
**Language server** 0.3.39.0 and also tried 0.3.40.0 from daily
**VSCode** 1.36.1
**Python** 3.7.3
**OS** Ubuntu 19.04

Using this simple example in a single file, no imports, etc:
```
class Foo(type):
    pass

class Bar(metaclass=Foo):
    pass
```

`Foo` is marked as inheriting from `type` which is not a class, similar to #1361 and #1364 
![image](https://user-images.githubusercontent.com/982180/61821761-dcdfb600-ae0c-11e9-9230-60cc215c2fe2.png)

And the signature/docstring info for `type` is completely missing:
![image](https://user-images.githubusercontent.com/982180/61822002-71e2af00-ae0d-11e9-8a08-3da390e94983.png)

For a more concrete example, I discovered this problem with the following:

```
import weakref

class PackageMeta(type):
    def __new__(cls, name, bases, attrs):
        pkg_class = super(PackageMeta, cls).__new__(cls, name, bases, attrs)
        pkg_class.__instances = weakref.WeakValueDictionary()
        return pkg_class

    def __call__(cls, name, version, arch):
        return cls.__instances.setdefault(
            (name, version, arch,),
            super(PackageMeta, cls).__call__(name, version, arch))
```
Same problem here wherein `PackageMeta` is flagged for inheriting from `type`
![image](https://user-images.githubusercontent.com/982180/61822072-9ccd0300-ae0d-11e9-9edc-c825977d9c3e.png)

but in this case, it's a bit more strange as the signature/docstring for `type` is now available but is wrong:
![image](https://user-images.githubusercontent.com/982180/61822120-b4a48700-ae0d-11e9-8da6-97a833f994f5.png)

and if you peek at the definition...
![image](https://user-images.githubusercontent.com/982180/61821545-59be6000-ae0c-11e9-8f9d-7c414147d263.png)
Its coming from `http.client.HTTPMessage` which inherits from `email.message.Message` -- neither of which are imported here.

**Comment by bmoyles** [comment]
Just noticed the hover dialogs disappeared while I was grabbing screenshots, fixing...

**Comment by CTrando** [comment]
Thanks for the bug. I'll look into it, sorry for inconveniences.

**Comment by bmoyles** [comment]
@CTrando Thanks for the fix! I grabbed the latest version and no longer see the inheritance error, but the latter problem I mentioned wherein the documentation for `type` is incorrect and is coming from `email.message.Message` by way of `http.client.HTTPMessage` for some reason... Go To Definition/Go To Declaration on `type` both take one to `http.client.HTTPMessage` inheriting from `email.message.Message`. I even tried to outsmart it by using `builtins.type` but no luck. Let me know if this should be in a separate issue or if this is not the right project...

**Comment by jakebailey** [comment]
I'd file a separate issue for this; Metaclass stuff is not something we have particularly strong support for in some cases. The fact that goto-def and goto-declaration behave the same is definitely odd, either way.

**Comment by jakebailey** [comment]
And if you have a minimal repro, that'd be the best.

**Comment by bmoyles** [comment]
@jakebailey sounds good, I'll make sure I can reproduce the doc/go-to problems and open a fresh issue. Thanks again!
