### ISSUE TITLE
False positive undefined variable when destructuring function return values

### ISSUE THREAD

**Issue by janosh** [microsoft/python-language-server#1382]
The language server complains about `var1` being undefined.

![fp](https://user-images.githubusercontent.com/30958850/61865374-04955380-aecb-11e9-8825-a9719667c7aa.png)

**Comment by jakebailey** [comment]
See also #1293. There are a few known issues with our unpacking logic.

**Comment by MikhailArkhipov** [comment]
0.4.18+
