### ISSUE TITLE
Incorrect "function-redefined" for methods with property & setter decorators

### ISSUE THREAD

**Issue by darrickyee** [microsoft/python-language-server#1383]
When defining a method as a property using the standard property decorator, defining the associated setter-decorated method results in a "function-redefined" error notification:

## Environment data

- VS Code version: 1.36.1
- Extension version (available under the Extensions sidebar): 2019.6.24221 (9 July 2019)
- OS and version: Windows 7 64-bit
- Python version (& distribution if applicable, e.g. Anaconda): 3.7, 2.7 (64-bit)
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Relevant/affected Python packages and their versions: N/A
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): Language server

## Expected behaviour

No error notification

## Actual behaviour

Error notification is shown (resulting in red symbols/files in the outliner & file tree), making it difficult to distinguish these cases from cases with actual errors.

My current workaround is to add "function-redefined" to the "python.analysis.disabled" property in my settings.json, but obviously this isn't ideal...

## Steps to reproduce:
(See screenshot)

![func_redefined](https://user-images.githubusercontent.com/18172544/61571279-2c666080-aa60-11e9-8d4b-2896d1408ad0.jpg)

**Comment by MikhailArkhipov** [comment]
@CTrando - linter messages should not be shown as errors, warnings is max severity. The message can be suppressed in settings.

**Comment by CTrando** [comment]
Ok I'm on it.
