### ISSUE TITLE
False positive: inherit-non-class on generic subclass

### ISSUE THREAD

**Issue by mplanchard** [microsoft/python-language-server#1390]
I get an `inherit-non-class` error on the following.

```py
import typing as t

T = t.TypeVar("T")

class GenericThing(t.Generic[T]):
    pass

# Inheriting 'GenericThing[str]', which is not a class.Python(inherit-non-class)
class SpecificThing(GenericThing[str]):
    pass
```

This usage is specified in [pep-560](https://www.python.org/dev/peps/pep-0560/) and executes at runtime in Python 3.6 with no problems

**Comment by jakebailey** [comment]
@CTrando Happens on master.

![image](https://user-images.githubusercontent.com/5341706/61914526-bcd7f180-aef5-11e9-910f-3e802c59fd36.png)

`GenericThing[str]` should be a type.

**Comment by jakebailey** [comment]
@mplanchard 	You can disable this diagnostic globally for now by setting:

```json
"python.analysis.disabled": [
    "inherit-non-class"
],
```

**Comment by james1293** [comment]
You can also disable per-line by appending `#noqa`.
