### ISSUE TITLE
Stub and compiled builtin module analysis is not LibraryAnalysis

### ISSUE THREAD

**Issue by MikhailArkhipov** [microsoft/python-language-server#1391]
Looks like we are not creating `LibraryAnalysis` for stubs or compiled modules which leads to ASTs remaining in memory.

**Comment by MikhailArkhipov** [comment]
Part of https://github.com/microsoft/python-language-server/pull/1372

**Comment by jakebailey** [comment]
Would my changes in #1402 have technically fixed this early?

**Comment by MikhailArkhipov** [comment]
Yes, please close
