### ISSUE TITLE
Unresolved Import on 3rd Party Installed Library, But Still Receiving Partial Autocomplete

### ISSUE THREAD

**Issue by mobiusklein** [microsoft/python-language-server#1392]
### Version Info

VSCode Version: 1.36.1
OS: Windows 10
Language Server Version: 0.3.40
Python: Anaconda 2.7

---------------------
When I import the library `pyteomics` or any of its submodules, I get an "unresolved-import" warning

![image](https://user-images.githubusercontent.com/1426041/61961769-1bed4300-af96-11e9-90c1-6e46889946d2.png)

 I know it is installed with `pip`
```
(base) C:\Users\jklein>pip list | grep pyteomics
pyteomics                          4.1
```
and the code successfully imports `pyteomics` and calls its functions.

What's more bizarre is that I can still get import suggestions while typing the import statement
![image](https://user-images.githubusercontent.com/1426041/61961729-04ae5580-af96-11e9-9ee0-225e4db4d20f.png)

Once the import statement is past the module name to import from, I do not get further autocomplete support.

If I import a name from a submodule, I *do* get intellisense:

![image](https://user-images.githubusercontent.com/1426041/61963271-3a087280-af99-11e9-8a9c-513a83ecf6e0.png)

This problem appears to be absent on Python 3.6.7, but the "Analyzing in background" queue never empties, so I do not know if that could be blocking the warning.

**Comment by jakebailey** [comment]
Does that code execute in Python 2? Python 2 and 3 have different rules about how modules can be imported, and our import resolver behaves differently between them based on those rules.

**Comment by mobiusklein** [comment]
It runs under either version of Python. I primarily run that codebase under Python 2 as well, so I'm certain its not missing. I have this problem with this module across machines as well.

**Comment by MikhailArkhipov** [comment]
LS does not run the code and has no ability to determine if exception is thrown. This is why on Python 2 you get squiggles (and clear on Python3):

![image](https://user-images.githubusercontent.com/12820357/65288967-c351a680-dafd-11e9-9c9d-a922b1651559.png)

On Python 2 and 3 root `pyteomics` does not resolve, but submodules do appear.
![image](https://user-images.githubusercontent.com/12820357/65289109-407d1b80-dafe-11e9-85e5-752ecf31209b.png)

This might be b/c `__init__.py` is not present in `Lib\site-packages\pyteomics`

**Comment by MikhailArkhipov** [comment]
0.4.24+
