### ISSUE TITLE
Rename variable sometimes fails when using the LanguageServer

### ISSUE THREAD

**Issue by cipri-tom** [microsoft/python-language-server#1393]
## Environment data

- VS Code version: 1.29.1
- Extension version (available under the Extensions sidebar): 2018.11.0
- OS and version: macOS Mojave 10.14.1
- Python version (& distribution if applicable, e.g. Anaconda): python 3.6.4 64-bit conda
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Relevant/affected Python packages and their versions:
   - Microsoft Python Language Server version 0.1.60.0

## Steps to reproduce:
1. Make new file, `test.py`
2. paste the following:
```python
def iadd_no_overflow(a, b):
    """Perform `a += b` on integer numpy arrays without overflowing"""
    dest += src
    dest[dest < src] = np.iinfo(dest.dtype).max
```
Note the file is dirty (not saved). The same happens if the file is saved.

3. Place cursor on `dest` and hit <kbd>F2</kbd> or choose `Rename symbol`. Enter `a` as name.

## Expected behaviour
All occurences of `dest` are changed into `a`

## Actual behaviour

Got a tooltip `Cannot rename`, and an error in the Output window:
## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
Starting Microsoft Python language server.
Microsoft Python Language Server version 0.1.60.0
Initializing for /Users/ciprian/miniconda3/bin/python
[Error - 12:12:43 PM] Request textDocument/rename failed.
  Message: Cannot rename
  Code: -32000 
   at Microsoft.Python.LanguageServer.Implementation.Server.Rename(RenameParams params, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.Rename(JToken token, CancellationToken cancellationToken)
```

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`):

Nothing. I mean, there are some `ERR` but from before. I put a `console.log` and then reproduce the error and nothing new appears in the console.

**Comment by MikhailArkhipov** [comment]
In the fragment above `dest` is undefined. The code below works OK. Closing.
```python
dest = 1
def iadd_no_overflow(a, b):
    """Perform `a += b` on integer numpy arrays without overflowing"""
    dest += src
    dest[dest < src] = np.iinfo(dest.dtype).max
```

**Comment by cipri-tom** [comment]
Ahh, nice catch 🎉 ! Thank you for the insight!!

The thing is, I want to change all instances of `dest` into `a`, and all instances of `src` into `b`, so of course it is undefined :) 
Am I abusing some refactoring powers? I'm not sure why renaming needs correct code. Does it use the syntax in order to modify only in the correct scope?

As a potential improvement, can we have some more verbose output instead of the _Cannot rename_ message?

**Comment by jakebailey** [comment]
Our analysis is powered by tracking variable assignments. Uses of variables that don't exist (have assignments) means that there's no current way to identify that some variable is the same as another, where it comes from, etc, as the variable doesn't "exist" except as a lookup that fails. Feasibly, we could try and use scope information to track which undefined variables are in use, but generally it complicates things.
