### ISSUE TITLE
Unified docstring get behavior

### ISSUE THREAD

**Issue by star2000** [microsoft/python-language-server#1398]
## I recommend unifying the docstring via inspect.getdoc.
I noticed that in addition to the built-in modules and dynamic link libraries,   
the docstrings of other modules come directly from the `__doc__` attribute.  
Uniform behavior helps future expansion.

**Comment by jakebailey** [comment]
The language server avoids executing any Python code. Calling out to inspect to get docstrings would mean executing any code that needs to have its documentation examined, which is slow (and dangerous). We do it already, but only for compiled libraries where there is no other option.

Taking `__doc__` if it can be statically determined may be possible, but it's unlikely that we're going to try and use the `inspect` library more than is strictly required.
