### ISSUE TITLE
Implement diff parser and diff to TextEdit[] converter

### ISSUE THREAD

**Issue by jakebailey** [microsoft/python-language-server#140]
All of the formatters output a diff which describes how to edit the file. This diff needs to be parsed and converted into a list of TextEdits. vscode-python does this already, and the code may be able to be reused. Alternatively, an existing diff parser could be pulled in from NuGet and then converted to TextEdits.

**Comment by AlexanderSher** [comment]
Can we reuse this: https://github.com/Microsoft/python-language-server/blob/master/src/Analysis/Engine/Impl/Intellisense/LinePreservingCodeReplacer.cs ?

**Comment by jakebailey** [comment]
I think that would work for formatting the document, but would operate differently than already done in vscode as it requires the language server to do the diff itself rather than just asking the formatter to produce it. I think vscode specifically runs diffs out-of-proc to avoid spending too much CPU time in the extension, but I'm not 100% sure. (See: https://github.com/Microsoft/vscode-python/blob/master/src/client/formatters/baseFormatter.ts#L48)

This is probably not an issue given the async nature of doing something in language server, but I also think it'd be nice to not duplicate functionality that the tooling already has. The fact that DocumentChange is exactly the same thing as a TextEdit but with different names (`InsertedText` -> `newText`, `ReplacedSpan` -> `range`) is definitely convenient.

Given that the LinePreservingCodeReplacer appears to require specifying the newline sequence (defaulting to CRLF), using it might take some extra logic to be sure that round-tripping the code doesn't screw with the endings (since a TextEdit may replace one line with many).

One thing to consider is that using diffs from the tooling would improve performance in the case of large files, especially those which are mostly formatted, since it's pretty straightforward to stream the document into the tool over stdin, then read a small patch back to work with (versus loading the file fully, unformatted and formatted, to then diff).

**Comment by jakebailey** [comment]
Closing per #10.
