### ISSUE TITLE
Go to directory in "Explorer" side bar for "Go to Definition" on package names in imports.

### ISSUE THREAD

**Issue by ericsnowcurrently** [microsoft/python-language-server#1412]
(see the first bullet under "**e2e/tests/conftest.py**" in https://github.com/microsoft/vscode-python/issues/5963#issuecomment-501029802)

Given the following files:

```
project/
    spam/
        eggs/
            __init__.py
            mod.py
        ham/
            mod.py
        mod.py  # defines a class named "Data"
```

## current behavior

For `from spam.mod import Data`, "Go to Definition" (after right-clicking) for "Data" works as expected, going to the class definition in the other file.  For "mod" it also works (since that is a module).  However, for "spam" it acts as though you right-clicked on "mod".

For `from spam.eggs import mod` (has a `__init__.py`), it works for "mod" (opens the file).  However, for both "spam" and "eggs" it says "no definition found".

For `from spam.ham import mod` (no `__init__.py`), it behaves the same as `from spam.eggs import mod`

## desired behavior

For packages, highlight and open the directory in the "Explorer" side bar:

* "spam" in `from spam.mod import Data`
* "spam" and "eggs" in `from spam.eggs import mod`
* "spam" and "ham" in `from spam.ham import mod`

**Comment by MikhailArkhipov** [comment]
It is not possible to open folder. LS actually does not know VS Code exists at all. `Go to definition` per [LSP ](https://microsoft.github.io/language-server-protocol/specification) returns [location](https://microsoft.github.io/language-server-protocol/specification#location)
```cs
    public sealed class Reference {
        public Uri uri;
        public Range range;
    }
```
where `Uri` is path to the *document* and `range` is text range inside the document. LSP has no definition for navigation to folders.
