### ISSUE TITLE
Numpy analysis is inconsistent from run to run

### ISSUE THREAD

**Issue by MikhailArkhipov** [microsoft/python-language-server#1414]
```python
import numpy
numpy.
```
Run analysis, look at icons in the completion list. Reload and run again - you get different set. Ex, 3 sequential runs (look at `AxisError`, `ALLOW_THREADS`, `DataSource`). [abc] icon actually means `Unknown`

![image](https://user-images.githubusercontent.com/12820357/62585625-7e83f000-b86e-11e9-930b-2805c447ac72.png)

![image](https://user-images.githubusercontent.com/12820357/62585631-86439480-b86e-11e9-8642-6c00e38df6da.png)

![image](https://user-images.githubusercontent.com/12820357/62585755-2a2d4000-b86f-11e9-92f9-bae7bf54c043.png)

**Comment by MikhailArkhipov** [comment]
I'll see if I can get better repro

**Comment by AeneasZhu** [comment]
How to fix https://github.com/microsoft/python-language-server/issues/1635 ?

**Comment by MikhailArkhipov** [comment]
There is no consistent fix. The problem is that analysis sometimes produces results as I showed and sometimes does not. It involves concurrency and circular dependencies between modules in numpy. You may try reloading window and see if the analysis result is different.

**Comment by MikhailArkhipov** [comment]
Partial PR https://github.com/microsoft/python-language-server/pull/1584, parts can be reused.

**Comment by MikhailArkhipov** [comment]
In favor of #1666

**Comment by jakebailey** [comment]
Closing per #1686.
