### ISSUE TITLE
Placeholder for Reopening #726 Issues importing time sys etc.

### ISSUE THREAD

**Issue by skbobade** [microsoft/python-language-server#1430]
I see the same problem today.

Version: 1.37.0 (user setup)
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Date: 2019-08-08T02:33:50.993Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by jakebailey** [comment]
Already tracked in #1345.

**Comment by jakebailey** [comment]
Please file your info there: https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#filing-an-issue
