### ISSUE TITLE
No definition found for 'method_name'

### ISSUE THREAD

**Issue by fabatera** [microsoft/python-language-server#1443]
'Go to definition or F12' was working well. Now it's just not working in this case.
I select  _base_test_method_ and hit F12. Message: No definition found for ''base_test_method"
```
from foo.bar.nono import base_test
class Class_A(base_test):
  def func(self):
#this is NOT going to definition
    self.base_test_method()

#this is going to definition
    base_test.base_test_method()
```

VS code version 1.36.0 or 1.37.0.
Extensions enabled: Python (nothing else)

**Comment by CTrando** [comment]
Related: #1356.
