### ISSUE TITLE
Language server won't run/install behind firewall

### ISSUE THREAD

**Issue by drafter250** [microsoft/python-language-server#1462]
In most tools like pip or conda I have to supply the proxy url and the root cert file for the cloud based proxy we are behind to properly connect to those repositories. However VScode states that it uses chromium's proxy settings. Now while extensions themselves will install, things like the language server wont install or it wan't run without an internet connection?

 I'm not sure if the Language server already comes bundled with VSCode or the python extension or its a separate install?

how can I either download and install the language server separately or configure the proxy setting to work with a root_cert.cer file?

**Comment by drafter250** [comment]
here are some of the errors from the developer tools console:
```
workbench.main.js:242 [Extension Host] Error Python Extension: 2019-08-20 10:25:35: Failed to initialize experiments, Class name = S, completed in 4037ms, , Return Value: undefined { [Error: tunneling socket could not be established, cause=Hostname/IP does not match certificate's altnames: Host: <redacted proxy url.com>. is not in the cert's altnames: DNS:*<redacted>.net, DNS:<redacted>.net, DNS:gateway.<redacted>.net, DNS:login.<redacted>.net	at ClientRequest.<anonymous> (<%USERPROFILE%>.vscode\extensions\ms-python.python-2019.8.30787\out\client\node_modules\request.js:210:233769)	at Object.onceWrapper (events.js:273:13)	at ClientRequest.emit (events.js:182:13)	at onerror (<%USERPROFILE%>AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\agent-base\index.js:100:9)	at callbackError (<%USERPROFILE%>AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\agent-base\index.js:122:5)	at process._tickCallback (internal/process/next_tick.js:68:7)] code: 'ECONNRESET' }
```

```
workbench.main.js:242 [Extension Host] Error Python Extension: 2019-08-20 10:25:56: Listing Nuget Packages, Class name = d, completed in 23201ms, Arg 1: "https://pvsc.blob.core.windows.net", Arg 2: "python-language-server-stable", Arg 3: "Python-Language-Server-win-x64", Arg 4: "https://pvsc.azureedge.net", Arg 5: <Uri:<%USER_PROJECT_PATH%>\<%USER_MODULE%>.py>, Return Value: undefined { [Error: connect ETIMEDOUT 52.239.159.228:80	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)]  errno: 'ETIMEDOUT',  code: 'ETIMEDOUT',  syscall: 'connect',  address: '52.239.159.228',  port: 80 }

**Comment by MikhailArkhipov** [comment]
Extension is a separate install. If LS option is sent, the extension downloads the LS bits. Generally manual installation of the LS is not something that is supported. Some extensions build their own from sources - emacs, vim, etc. LS does not download itself, it is stored in Azure CDN. For download issues within VS Code Python extension please open issue in https://github.com/Microsoft/vscode-python.
