### ISSUE TITLE
Disable automatically updating Python Language Server

### ISSUE THREAD

**Issue by Jalalx** [microsoft/python-language-server#1467]
How can I disable the auto-update feature of python language server? I need to update it whenever I want, not in the middle of my work or when I'm in a rush!

**Comment by MikhailArkhipov** [comment]
This is controlled by the client (extension) so please open issue in https://github.com/Microsoft/vscode-python

**Comment by huulien** [comment]
```
"python.autoUpdateLanguageServer": false,
```
add to `settings.json`
