### ISSUE TITLE
Analyzing over and over again

### ISSUE THREAD

**Issue by Lips7** [microsoft/python-language-server#1473]
OS bulid 18965 with WSL2
IntelliCode version 1.1.9
VSCode version 1.37.0
Why every time I open VSCode and it needs to analyze in background, only after that can I use the Intellicode feature.

**Comment by MikhailArkhipov** [comment]
B/c analysis is not cacheable so project is analyzed each time it is loaded. Caching is work in progress https://github.com/microsoft/python-language-server/issues/472.

**Comment by Lips7** [comment]
Then I hope it can read the .gitignore😅😅

**Comment by MikhailArkhipov** [comment]
What is listed in .gitignore? LS does not look into entire project, it starts with the file opened and load dependencies. Closed files are not looked into unless it is a dependency (such as you use, say, tensorflow, which is 3000+ files). One exception is find all references that does scan closed files for candidates.
