### ISSUE TITLE
when creating an HTML file VisualCode is setting the file as DjangoHTML 

### ISSUE THREAD

**Issue by yk3823** [microsoft/python-language-server#1476]
instead of HTML , that is why you cant get any html IntelliSense  and you must change manually to HTML !!! its a wrong behavior "*.html" must be a plain HTML file ! 

![image](https://user-images.githubusercontent.com/7591184/63596660-64fbdb80-c5c4-11e9-848b-2a23032b7af1.png)

**Comment by MikhailArkhipov** [comment]
Language server does not know which client (VS Code, Emacs, Vim, Sublime) it is working in and does not control VS Code in anyway. Please open issue in Python extension repo. https://github.com/Microsoft/vscode-python. Thanks.
