### ISSUE TITLE
numpy.random missing most members

### ISSUE THREAD

**Issue by AeneasZhu** [microsoft/python-language-server#1481]
![image](https://user-images.githubusercontent.com/44701446/63660062-5b9e8900-c7e7-11e9-9fc3-fe5715ac34d4.png)

numpy.random misses most member functions like normal, random, uniform, while only keeps RandomState

**Comment by gramster** [comment]
Thanks for reporting this. We will take a look.

**Comment by MikhailArkhipov** [comment]
Most probably #1414 

![image](https://user-images.githubusercontent.com/12820357/64465450-934be180-d0c1-11e9-8461-cce8f4672e51.png)

![image](https://user-images.githubusercontent.com/12820357/64465465-a5c61b00-d0c1-11e9-8c8f-a02399761c09.png)

**Comment by MikhailArkhipov** [comment]
Folding into #1414
