### ISSUE TITLE
hi can u please help me with the fact that VC cant recognize application without 

### ISSUE THREAD

**Issue by yk3823** [microsoft/python-language-server#1486]
editing settings.json 

attaching the following in order to solve the issue 
1. the issue -> 
![image](https://user-images.githubusercontent.com/7591184/63762839-35064e00-c8cc-11e9-8081-074cb586202b.png)
2. solving by adding .env file to the root folder including PYTHONPATH=FOLDER 
![image](https://user-images.githubusercontent.com/7591184/63762933-6717b000-c8cc-11e9-8857-48957dcb8944.png)
3. adding pythonenvfile to settings.json ->
![image](https://user-images.githubusercontent.com/7591184/63763004-8d3d5000-c8cc-11e9-94f5-beefb87b67d0.png)
4. restart VC 

WHAT AM I MISSING OR DOING WRONG ???

**Comment by MikhailArkhipov** [comment]
Does it work with the configuration above? Thanks.

**Comment by MikhailArkhipov** [comment]
Closing, feel free to reopen if still a problem.

**Comment by SnehashishGiri** [comment]
> Does it work with the configuration above? Thanks.

no its not working

**Comment by MikhailArkhipov** [comment]
@SnehashishGiri - it is several months old issue from a different account. If you see something similar, it does not mean the case is the same. Feel free to open a separate issue.
