### ISSUE TITLE
Couldn't find a valid ICU package installed on the system.

### ISSUE THREAD

**Issue by 0paIescent** [microsoft/python-language-server#1488]
# Environment Data

- VS Code Version: 1.37.1
- Extension Version: 2019.8.30787
- OS Version: NixOS Unstable 19.09pre190139
- Python Version: 3.7.4

Expected Behavior, Steps to Reproduce, and Logs match those described in microsoft/vscode-python#2967.

This is less of a *help me fix something*, and more of me just wondering what version of ICU is supported with vscode-python. I wasn't able to find anything relating to it in the extension source, but maybe I didn't look hard enough. I currently have ICU 64.2 but when loading the extension I'm told I don't have a valid version. I've since set `"python.jediEnabled": true` for the time being.

**Comment by MikhailArkhipov** [comment]
Yes, VS Code lays down compatible libicu. In other cases one may have to either

- install Linux dependencies manually: https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x. 
- install .NET Core 2.2+ runtime. 
- disable libicu lookup per #170.
