### ISSUE TITLE
Intellisense not working when iterating over typed collection

### ISSUE THREAD

**Issue by malmaud** [microsoft/python-language-server#1494]
This is with the daily download channel:

```python
from typing import List

def f(xs: List[str]):
    for x in xs:
        x.
```
The string methods are not being suggested after `x.`.

However, they *are* suggested after `xs[0].`

<img width="589" alt="Screen Shot 2019-08-28 at 7 42 48 PM" src="https://user-images.githubusercontent.com/987837/63899743-0c657d80-c9cc-11e9-8cf0-7e3278b7af92.png">

**Comment by gramster** [comment]
Thanks for reporting this. We will take a look.

**Comment by MikhailArkhipov** [comment]
0.4.18+
