### ISSUE TITLE
Missing numpy functions

### ISSUE THREAD

**Issue by AeneasZhu** [microsoft/python-language-server#1500]
![image](https://user-images.githubusercontent.com/44701446/64140592-80be7780-ce37-11e9-8932-b5907ac5c859.png)

![image](https://user-images.githubusercontent.com/44701446/64140660-d2ff9880-ce37-11e9-97c0-5f75077fd831.png)

I use Intellicode extension for code completion, but it misses most functions of numpy and pandas' DataFrame object's methods.

**Comment by MikhailArkhipov** [comment]
IntelliCode does not provide list of completions, it only rearranges completions that are provided by the language server. I.e., IC is not a completion engine.

**Comment by MikhailArkhipov** [comment]
@AeneasZhu - could you provide a bit more code, i.e. how `SimpleImputer` is imported and how `numeric_df` is defined. Thanks.

**Comment by AeneasZhu** [comment]
> @AeneasZhu - could you provide a bit more code, i.e. how `SimpleImputer` is imported and how `numeric_df` is defined. Thanks.

```py
from sklearn.preprocessing import SimpleImputer

numeric_df=pd.DataFrame()

```
I found the intellisence could not detect the unspecified variable type. If I specify `df:DataFrame=`, the intellisence could pop up.

**Comment by MikhailArkhipov** [comment]
![image](https://user-images.githubusercontent.com/12820357/65107938-43f09580-d98c-11e9-84de-5386af379e5a.png)

**Comment by MikhailArkhipov** [comment]
So `pd.DataFrame` appears to work (this is 0.4.20 on beta channel).

**Comment by MikhailArkhipov** [comment]
Closing, feel free to reopen if this is still a problem. There may be occasional issue b/c of #1414.
