### ISSUE TITLE
Go to Definition behaves inconsistently when importing a module in a package

### ISSUE THREAD

**Issue by sundresh** [microsoft/python-language-server#1504]
Go to Definition behaves inconsistently when importing a module in a package, in the following ways:
* On a line of the form `import package.module`, Go to Definition on the module reports "No definition found," while hovering over the module name gives a summary of the module. Whereas Go to Definition does work on the module name when using the form `from package import module [as name]`
* After the import line itself, in different cases, Go to Definition may jump to the import line, an intermediate import line the parent package of the module, or the source code of the module itself (all for the same parent package and child module).

The above behavior also applies to Peek Definition.

Note: In principle, I would be open to contributing a fix for this bug, but I don't know where to start, as I've only just started evaluating vscode-python.

## Environment data

- VS Code version: 1.37.1
- Extension version (available under the Extensions sidebar): 2019.8.30787
- OS and version: macOS 10.14.5
- Python version (& distribution if applicable, e.g. Anaconda): 2.7.10
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Relevant/affected Python packages and their versions: Any Python module or package that's nested within another package.
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): Language Server

## Expected behaviour

Example code:

```
1  import os.path
2  from os import path as os_path
3  print(os.path.basename('a/b/c')
4  print(os_path.basename('a/b/c'))
```

Expected behavior of right click → Go to Definition on...
* line 1, cursor right after the "s" in `os`: open `os.py` (i.e., the same behavior as when the cursor is right before the "o" or the "s" or when the cursor is right after "from os" on line 2)
* line 1, `path` in `import os.path`:
  * jump to the line `import posixpath as path` in `os.py` (the current behavior of right click → Go to Definition on `path and `os_path` on lines 3 and 4, respectively)
  * alternatively, directly open `posixpath.py` (i.e., the same behavior as on `path` or `os_path` on line 2) if an import is not considered a definition. This is a tradeoff between precision (being able to trace the steps involved in importing a symbol into an environment) and expediency (being able to jump to the actual definition of a symbol in fewer steps).
* line 3, `path` and line 4, `os_path`: jump to the corresponding line (to be consistent with right click → Go to Definition on `os` on line 3)

## Actual behaviour

Actual behavior of right click → Go to Definition on...
* line 1, cursor right after the "s" in `os`: moves the cursor just before `os` (similarly, Peek Definition shows the same file with `os` highlighted rather than showing `os.py`)
* line 1, `path` in `import os.path`: reports "No definition found for 'path'"
* line 3, `path` and line 4, `os_path`: jumps to the line `import posixpath as path` in `os.py`. This is an odd middleground that neither stops at the nearest import nor skips over all levels of imports to the actual definition.

## Steps to reproduce:

1. Create an empty directory, add a file named `example.py` with the following contents:
```
import os.path
from os import path as os_path
print(os.path.basename('a/b/c')
print(os_path.basename('a/b/c'))
```

2. Open the directory in VS Code

3. Inspect the code in `example.py` as described under expected/actual behavior above.

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

`View`→`Output` is grayed out

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

I don't see an option to enable `Developer Tools` under `Help`.

**Comment by MikhailArkhipov** [comment]
In symbol is imported, depending on the import form first navigation may go to the import statement effectively showing where variable is first declared in the file. Navigation from import statement then gets to the module source - if available. If module is compiled or a built-in, you may get "no definition is available" because effectively, there is no Python source.

**Comment by MikhailArkhipov** [comment]
Related https://github.com/microsoft/python-language-server/issues/1162

**Comment by MikhailArkhipov** [comment]
Here is how it may work:
`import os.path`
- caret on `os` => goes to os.py
- caret on `path` => goes to `import ntpath as path` in os.py - that's where `path` is defined.

`from os import path as os_path`
- caret on `os` => goes to os.py
- caret on `path` => goes to `import ntpath as path` in os.py.
- caret on `os_path` => goes to ntpath.py on Windows.

`print(os.path.basename('a/b/c'))`
- caret on `os` => goes to os.py
- caret on `path` => goes to `import ntpath as path` in os.py.
- caret on `os_path` => goes to ntpath.py on Windows (per #1162).

`print(os_path.basename('a/b/c'))`
- caret on `os_path` => goes to ntpath.py on Windows (per #1162).

**Comment by MikhailArkhipov** [comment]
Pending #1482

**Comment by MikhailArkhipov** [comment]
Part of https://github.com/microsoft/python-language-server/pull/1482. 0.4.16+.
