### ISSUE TITLE
VS Code language server linter not recognizing "additional-builtins" from .pylintrc

### ISSUE THREAD

**Issue by ababak** [microsoft/python-language-server#1523]
## Environment data

- VS Code version: 1.38.0
- Extension version (available under the Extensions sidebar): 2019.9.34474
- OS and version: CentOS Linux release 7.6.1810
- Python version (& distribution if applicable, e.g. Anaconda): 2.7.5 64-bit
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Relevant/affected Python packages and their versions: N/A
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): Language Server

## Expected behaviour

I am using custom builtin functions "_T" and "_N". Pylint is happy as soon as I add `additional-builtins=_T,_N` to `.pylintrc` (user or project) or `python.linting.pylintArgs`:
```
    "python.linting.pylintArgs": [
        "--additional-builtins=_T,_N",
    ]
```

I expect the "Python" linter (Python Language Server) to honor these linting settings.

## Actual behaviour
Unfortunately, the "Python" linter (Python Language Server) does not want to recognize these functions and shows tons of "undefined-variable" warnings.

![Screenshot from 2019-09-05 12-06-25](https://user-images.githubusercontent.com/11334363/64331189-075f8a00-cfdb-11e9-8b46-2cfe7f7dc0e0.png)

If I remove `.pylintrc` file I get errors from both `pylint` and `Python`:
![Screenshot from 2019-09-05 12-57-19](https://user-images.githubusercontent.com/11334363/64332686-a6858100-cfdd-11e9-9509-1fd1173098bb.png)

## Steps to reproduce:
1. Add `pylintArgs` setting to project config:
```
    "python.linting.pylintArgs": [
        "--additional-builtins=_T,_N",
    ]
```
2. Create a `test.py` file:
```
_S('Test')
_T('Test')
```

3. Note the "undefined-variable" warning coming from the "Python" linter but not from the "pylint":
![Screenshot from 2019-09-05 13-13-15](https://user-images.githubusercontent.com/11334363/64333318-f9ac0380-cfde-11e9-8925-0d85039c3140.png)

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)
```
User belongs to experiment group 'AlwaysDisplayTestExplorer - experiment'
User belongs to experiment group 'ShowPlayIcon - start'
> conda --version
> pyenv root
> python3.7 -c "import sys;print(sys.executable)"
> python3.6 -c "import sys;print(sys.executable)"
> python3 -c "import sys;print(sys.executable)"
> python2 -c "import sys;print(sys.executable)"
> python -c "import sys;print(sys.executable)"
> /bin/python -c "import sys;print(sys.executable)"
> conda info --json
Starting Microsoft Python language server.
> /bin/python -m pylint --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text ~/projects/amg/checker2/checkups/maya_references.py
cwd: ~/projects/amg/checker2
> /bin/python -m pylint --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text ~/projects/amg/checker2/checkups/maya_references.py
cwd: ~/projects/amg/checker2
##########Linting Output - pylint##########
> conda info --json
> conda --version
```

```
[Info  - 12:41:12 PM] Analysis cache path: /home/babak/.cache/Microsoft/Python Language Server
[Info  - 12:41:12 PM] GetCurrentSearchPaths /bin/python 
[Info  - 12:41:12 PM] Interpreter search paths:
[Info  - 12:41:12 PM]     /usr/lib64/python2.7
[Info  - 12:41:12 PM]     /usr/lib64/python2.7/plat-linux2
[Info  - 12:41:12 PM]     /usr/lib64/python2.7/lib-dynload
[Info  - 12:41:12 PM]     /home/babak/projects
[Info  - 12:41:12 PM]     /fstorage/projects/dev/maya2019.2-linux/lib/python2.7/site-packages
[Info  - 12:41:12 PM]     /home/babak/.local/lib/python2.7/site-packages
[Info  - 12:41:12 PM]     /usr/lib64/python2.7/site-packages
[Info  - 12:41:12 PM]     /usr/lib64/python2.7/site-packages/gtk-2.0
[Info  - 12:41:12 PM]     /usr/lib64/python2.7/site-packages/wx-2.8-gtk2-unicode
[Info  - 12:41:12 PM]     /usr/lib/python2.7/site-packages
[Info  - 12:41:12 PM] User search paths:
[Info  - 12:41:15 PM] Microsoft Python Language Server version 0.3.66.0
[Info  - 12:41:15 PM] Initializing for /bin/python
```

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:230 [Extension Host] Error Python Extension: 2019-09-05 13:15:47: [TypeError: Cannot convert object to primitive value	at Array.toString (native)	at module.exports.Object.getOwnPropertyNames.forEach.t (/home/babak/.vscode/extensions/ms-python.python-2019.9.34474/out/client/extension.js:1:13058)	at Array.forEach (<anonymous>)	at Object.l [as sendTelemetryEvent] (/home/babak/.vscode/extensions/ms-python.python-2019.9.34474/out/client/extension.js:1:12980)	at Object.sendSettingsTelemetry (/home/babak/.vscode/extensions/ms-python.python-2019.9.34474/out/client/extension.js:75:486059)	at Timeout.module.exports.r.value.s.timer.setTimeout [as _onTimeout] (/home/babak/.vscode/extensions/ms-python.python-2019.9.34474/out/client/extension.js:1:73751)	at ontimeout (timers.js:425:11)	at tryOnTimeout (timers.js:289:5)	at listOnTimeout (timers.js:252:5)	at Timer.processTimers (timers.js:212:10)]
t.log @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:230
/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:230 [Extension Host] (node:11119) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:230
```

**Comment by MikhailArkhipov** [comment]
Language server is not using pylint, it has custom linter which does not read pylint options. So I guess the request is to provide something similar to pylint options? Thanks

**Comment by ababak** [comment]
After reading the docs I got the impression that Language Server takes some settings from `.pylintrc`. If it’s not the case, then it will definitely help to have some sort of options. Otherwise it’s easy to miss a really important warning.

**Comment by MikhailArkhipov** [comment]
No, it does not. LS linter has its own options which are somewhat similar to pylint. LS linter generally speaking, is not a replacement for pylint since pylint is a large, mature product with many options.

**Comment by ababak** [comment]
May I ask you to point me to the documentation of available Language Server linter options?

**Comment by MikhailArkhipov** [comment]
https://github.com/microsoft/python-language-server/blob/master/README.md

**Comment by ababak** [comment]
Oh, I thought there were some other options similar to plint somewhere.
Thank you.
