### ISSUE TITLE
Type annotations for 'for' loop variables not recognized

### ISSUE THREAD

**Issue by malmaud** [microsoft/python-language-server#1528]
There's no LS suggestions for `x` here (on the nightly download channel):

```python
def f(xs: List):
    for x in xs:  # type: str        
        x.
```

This is the correct syntax for introducing a type annotation on variables introduced in `for` loops and is utilized by mypy and PyCharm.

**Comment by jakebailey** [comment]
Duplicate of #1026.

**Comment by malmaud** [comment]
Oops, sorry.
