### ISSUE TITLE
Hovering over `from typing import Callable` reads `Callabla`

### ISSUE THREAD

**Issue by jamesohortle** [microsoft/python-language-server#1535]
## Environment data

- VS Code version: 1.38.0
- Extension version (available under the Extensions sidebar): 2019.9
- OS and version: macOS Mojave 10.16.6
- Python version: 3.7.3
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
- Relevant/affected Python packages and their versions: `typing`
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): false

## Expected behaviour

Hovering over `Callable` in `from typing import Callable` should create a little tab saying `Callable`.

## Actual behaviour

The little tab says `Callabla`.

<img width="1680" alt="Screen Shot 2019-09-11 at 15 10 57" src="https://user-images.githubusercontent.com/50194055/64672896-bc94b500-d4a7-11e9-922d-80afdba33703.png">

## Steps to reproduce:
1. Make a Python file and write `from typing import Callable` and hover the cursor over `Callable`.

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
User belongs to experiment group 'ShowPlayIcon - control'
User belongs to experiment group 'ShowExtensionSurveyPrompt - enabled'
Starting Microsoft Python language server.
> conda --version
> pyenv root
> python3.7 -c "import sys;print(sys.executable)"
> python3 -c "import sys;print(sys.executable)"
> python3.6 -c "import sys;print(sys.executable)"
> python2 -c "import sys;print(sys.executable)"
> python -c "import sys;print(sys.executable)"
> ~/Desktop/batch_gairaigo/batch_gairaigo_env/bin/python -c "import sys;print(sys.executable)"
> conda info --json
> /usr/local/bin/mypy --ignore-missing-imports --follow-imports=silent --show-column-numbers ~/Desktop/batch_gairaigo/python/batch_gairaigo.py
cwd: ~/Desktop/batch_gairaigo
##########Linting Output - mypy##########
> conda info --json
> conda --version
```

## Hack
Restarting the extension seems to have solved it.

**Comment by jakebailey** [comment]
This is really weird. I can't find `Callabla` anywhere in the python source, stubs, or even pre-compiled modules. We haven't yet implemented `Callable` in our typing stuff, so it's not there either.

The only thing I can think of is if this were a desync, and maybe the file you were looking at said `Callabla` but was edited to say `Callable`, but the analyis hadn't yet finished to give the right info

**Comment by MikhailArkhipov** [comment]
Most probably #1543. Reopen if still happens.
