### ISSUE TITLE
super() being linted badly

### ISSUE THREAD

**Issue by luabud** [microsoft/python-language-server#1547]
@kcajf commented on [Mon Sep 16 2019](https://github.com/microsoft/vscode-python/issues/7409)

## Environment data

- VS Code version: 1.37.1
- Extension version (available under the Extensions sidebar): 2019.9.34911
- OS and version: Linux x64 4.16.11-100.fc26.x86_64
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.3 anaconda
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info #3977): Language server

## Expected behaviour

super() should be recognised

## Actual behaviour

super() is not recognised

![image](https://user-images.githubusercontent.com/4301021/64968139-30143900-d891-11e9-8768-2e421cfaddd1.png)

**Comment by jakebailey** [comment]
I can't seem to reproduce this. @kcajf Does the message go away on a reload? Can you show the language server version in use?

**Comment by MikhailArkhipov** [comment]
Probably b/c of `class Foo()` rather than `class Foo:` or `class Foo(object)`. There is no base so `super` goes undefined? However, I can't repro either in 3 or 2

![image](https://user-images.githubusercontent.com/12820357/65105644-700b1700-d98a-11e9-9a24-8048e9962301.png)

**Comment by MikhailArkhipov** [comment]
https://github.com/microsoft/python-language-server/pull/1702 might have fixed it since we now specialize `super`. Please reopen if this is still a problem. Thanks.
