### ISSUE TITLE
Go to method definition in Python modules fails with "No definition found for '<method_name>'" message

### ISSUE THREAD

**Issue by karrtikr** [microsoft/python-language-server#1554]
### _**Originally reported for Jedi but possible enhancement for Language server as well**_

@marius-nicolae commented on [Sat Sep 14 2019](https://github.com/microsoft/vscode-python/issues/7397)

Hi,

First of all, thank you, for your wonderful work. I like VS Code a lot but there is an issue I'd like to report. 

Usually, in Python modules, there are classes definitions with methods references but without calls with actual types. In this case, when trying to go to a method definition the VS Code displays a "No definition found for '<method_name>'" message as opposed to Pycharm which displays a menu with all possible methods definitions. Even if the Python file contains calls with actual objects the VS Code will go the first definition even if there are multiple possibilities.

## Environment data
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:30:08.229Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-58-generic

- Extension version (available under the Extensions sidebar): ms-python.python-2019.9.34911
- OS and version: Xubuntu 18.04
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.8 64 bits
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Relevant/affected Python packages and their versions: XXX
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info #3977): Jedi enabled

## Expected behaviour

VS Code should display a menu with all possible method definitions, with the ones defined in the current .py file on top

## Actual behaviour

Displays a "No definition found for '<method_name>'" message

## Steps to reproduce:
1. Unpack the attached archive - [test.tar.gz](https://github.com/microsoft/vscode-python/files/3612536/test.tar.gz)
2. Open the project folder
3. Open to the Test/test.py file
4. F12 on the Foo method reference from line 10

More details, on the attached animated gif. The following GIF is for Jedi and the expected behavior demonstrated in PyCharm. LS simply displays "No definition found"
![Go to method definition-2019-09-14 11-13](https://user-images.githubusercontent.com/28258950/64905958-416e1180-d6e8-11e9-9af5-ea0ef287932d.gif)

**Comment by MikhailArkhipov** [comment]
Could you provide version of the language server (it is displayed in the Output window). Extension version is unrelated since LS is not tied to any particular extension version. Thanks.

**Comment by karrtikr** [comment]
Here, `Microsoft Python Language Server version 0.3.76.0`.

**Comment by marius-nicolae** [comment]
The original report was made using Jedi but it manifests also with Language Server, both stable and latest versions. My current Language Server version is 0.3.76.

**Comment by MikhailArkhipov** [comment]
Since `obj` has no type, static analysis does not associate `obj` inside the function with either  `A` or `B` in
```python
class A:
    def Foo(self):
        print("A.Foo method")

class B:
    def Foo(self):
        print("B.Foo method")

def CallFoo(obj):
    obj.Foo()
```
So the feature would require adding some heuristics and searching which objects might has `Foo` method on them.

**Comment by MikhailArkhipov** [comment]
Same as #1413
