### ISSUE TITLE
Failing to Display Parameters or Arguments of Functions from Some Packages

### ISSUE THREAD

**Issue by AeneasZhu** [microsoft/python-language-server#1558]
![image](https://user-images.githubusercontent.com/44701446/65004379-c5193f80-d92e-11e9-81c6-0a2cf0ef7e19.png)
Unlike Jedi, Intellicode cannot display positonal parameters on functions of some packages like sklearn, imblearn, mxlend, etc. Can this problem be solved?

**Comment by jakebailey** [comment]
From MicrosoftDocs/intellicode#126, for reference.

**Comment by MikhailArkhipov** [comment]
They are known 
![image](https://user-images.githubusercontent.com/12820357/65287983-f85bfa00-daf9-11e9-89fc-cf831faad835.png)

but not being added to completion. Parameters should appear as `kernel=` entries, like in functions
![image](https://user-images.githubusercontent.com/12820357/65288029-23dee480-dafa-11e9-8ffc-f6199eb3ecca.png)

**Comment by MikhailArkhipov** [comment]
https://github.com/microsoft/python-language-server/pull/1583
0.4.28+
