### ISSUE TITLE
When will Tensorflow 1.15 and Tensorflow 2.0.0 be supported?

### ISSUE THREAD

**Issue by zhen8838** [microsoft/python-language-server#1564]
## Environment data

- Language Server version: languageServer.0.3.76
- OS and version: Window 10 18362 and Ubuntu 18.04 
- Python version (& distribution if applicable, e.g. Anaconda): Miniconda3 python 3.7.3

## Expected behaviour

Intellisense working well with TensorFlow 2.0 and Tensorflow 1.15 like Tensorflow 1.14.

####  Tensorflow 2.0.0rc1

Whatever I type, it can only prompt `_sys` module, And all variable types are `module`

![](https://i.ibb.co/H2WWrfR/tf2.gif)

####  Tensorflow 1.15rc1

Modules are not fully loaded

![](https://i.ibb.co/RN6Hd91/tf15.gif)

####  Tensorflow 2.0.0rc1

https://file.io/juxA1M

####  Tensorflow 1.15rc1

https://file.io/oJ4sOr

##  Additional lnformation

I hope this project will develop better.

**Comment by MikhailArkhipov** [comment]
Please see thread in https://github.com/microsoft/python-language-server/issues/818. TF 2.0 has dynamic custom system of exports so the only way for static analysis to figure out what is exported and what types are is to have stubs provided by the package developer.

**Comment by zhen8838** [comment]
OK, I'll wait for any updates.

**Comment by MikhailArkhipov** [comment]
Closing in favor of #818
