### ISSUE TITLE
Unresolved import when python file in subdirectory

### ISSUE THREAD

**Issue by Almenon** [microsoft/python-language-server#1599]
## Environment data

- Language Server version: 0.4.24.0
- OS and version: win 10
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.8

## Expected behaviour

import resolves

## Actual behaviour

unresolved import

## Logs

```
[Info  - 10:16:16 AM] Microsoft Python Language Server version 0.4.24.0
[Info  - 10:16:16 AM] Workspace root: c:\dev\misc\python-vscode-nested-folder-test
[Info  - 10:16:16 AM] Analysis cache path: C:\Users\almenon\AppData\Local\Microsoft\Python Language Server
[Info  - 10:16:16 AM] GetCurrentSearchPaths C:\Program Files\Python36\python.exe 
[Info  - 10:16:16 AM] Interpreter search paths:
[Info  - 10:16:16 AM]     c:\program files\python36\dlls
[Info  - 10:16:16 AM]     c:\program files\python36\lib
[Info  - 10:16:16 AM]     c:\program files\python36
[Info  - 10:16:16 AM]     c:\users\almenon\appdata\roaming\python\python36\site-packages
[Info  - 10:16:16 AM]     c:\program files\python36\lib\site-packages
[Info  - 10:16:16 AM] User search paths:
[Info  - 10:16:18 AM] Initializing for C:\Program Files\Python36\python.exe
Watching c:\program files\python36
Watching c:\users\almenon\appdata\roaming\python\python36\site-packages
[Info  - 10:16:18 AM] Analysis caching mode: None.
Opening document file:///c:/dev/misc/python-vscode-nested-folder-test/nestedFolder/a.py
Analysis of nestedFolder.a (User) queued. Dependencies: 
Analysis version 2 of 1 entries has started.
Analysis of nestedFolder.a (User) on depth 0 completed in 6.71 ms.
Analysis complete: 1 modules in 7.39 ms.
Analysis version 2 of 1 entries has been completed in 7.04 ms.
```

## Code Snippet / Additional lnformation

Extremely simply reproduction repo: https://github.com/Almenon/unresolved-import-demo

Note that going back to jedi fixes this error.

**Comment by jakebailey** [comment]
The issue here is the use of a workspace. The extension starts the LS telling it that the folder with the code-workspace file is the root, which we take as the import root, but the files assume that the import root is the folder of the workspace defined in the workspace file.

You may be able to work around this by setting extraPaths: https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#unresolved-import-warnings

My output after cloning that repo opening the workspace file:

```
Workspace root: c:\Users\jabaile\test_projects\issue1599\unresolved-import-demo
```

Confirming this behavior. If you just open up the "nestedFolder", then it'll work, and I'd think extraPaths too.

Doing more to help in this situation is more complicated. The extension starts one LS per workspace, and should probably be launching them with the root set to the workspace root, not the directory that the workspace file lives in.

**Comment by jakebailey** [comment]
Actually, that's not totally correct. I can see that your workspace file actually sets a workspace root of `"."`, which is equivalent to opening that directory.

This means that the import is failing because it's not rooted correctly, and the fix here is to use extraPaths just as though you had a src folder or similar, as in that linked issue.

**Comment by Almenon** [comment]
Yep, that fixes it, thanks! Can we leave this open as a feature request to automatically figure out python imports regardless of location or do you want me to create a new feature request ticket?

**Comment by MikhailArkhipov** [comment]
The problem here is that there is no real 'automatic' way. It depends which folder you run code from and if code modifies `sys.path` dynamically and other parameters. If we loosely import everything then the code that appears correct in the editor, imports appear resolved and completions work then suddenly throws at runtime since imports are no longer available.

**Comment by jakebailey** [comment]
I'm not sure we're going to do something as loose as "figure out imports regardless of location" without some defining what that is, and weighing the benefits of _not_ resolving imports in scenarios where they require extra setup even when running the code, or in scenarios where they'd never properly work. I opened #1602 to cover the scenario where a file is to be run as a script, though how we're going to handle that I'm unsure. There are known things to fix, as well (#443/#846/#1360).

As far as I can tell, Jedi is unique in the imports aspect, where it operates very, very loosely and will accept just about any import if it finds something that happens to match (even if it won't actually execute), including up and out of the workspace. PyCharm requires you to set "source roots" for unique folder structures, like we do (see the testing done in https://github.com/microsoft/python-language-server/issues/1160#issuecomment-512251175).

If you have a concrete project which you would like to work better out of the box, then that'd be good to file a bug against for potential improvement, but past that we'd need to examine a bunch of projects and come up with a cohesive plan.

We're already examining the import root / search path configuration for improvement at the moment as well, to better handle tools like pylint in the extension, as there are more tools than the language server that need to have this same information but don't.

**Comment by Almenon** [comment]
Alright, thanks for the long response :)

**Comment by Almenon** [comment]
I just ran into this issue again after reinstalling windows, it was frustrating. Eventually remembered this issue and fixed it. Thanks again for the fix. 

I should note I'm probably not the only one who ran into this problem. Any user of https://www.npmjs.com/package/python-shell, https://github.com/Submersible/node-python-bridge, or any library from another language that interfaces with python has a decent chance of storing a python file in a subfolder and running into this issue. I'm guessing certain devops repos with python scripts inside a subfolder (ex: ansible repos might have python scripts inside library folder) would also run the issue.

**Comment by fireattack** [comment]
@jakebailey 

> I'm not sure we're going to do something as loose as "figure out imports regardless of location" without some defining what that is

I totally agree we shouldn't go the Jedi way which is too loose, but I think it still can be improved a little bit in certain more defined scenario. 

Take the following example:

File structure:
(root)\sub01\a.py
(root)\sub01\b.py

a.py:
```python
from b import print_from_b

print_from_b()
```
b.py:
```python
def print_from_b():
    print('sub01 b.py')
```
To my knowledge, This kind of relative import seems to work fine no matter where your starting path is, at least on Windows:
```
F:\test>python sub01\a.py
sub01 b.py

F:\test>cd sub01

F:\test\sub01>python a.py
sub01 b.py

F:\test\sub01>C:

C:\>python F:\test\sub01\a.py
sub01 b.py
```

And there is no "dynamic" (like modifying `sys.path`) involved as @MikhailArkhipov has worried. 

I think our LS should at least support this kind out of box, without users to config any `extraPath` manually (there could be lots of subfolders.)

What do you think? If there is anything I overlooked also feel free to let me know.

Thanks!

**Comment by jakebailey** [comment]
Make a file `test/main.py`:

```python
from b import print_from_b

print_from_b()
```

And it will fail. Your two examples work because they are being run as scripts, which are special cases because the interpreter is adding their directory to `sys.path` at runtime. #1602

**Comment by fireattack** [comment]
Forgive me if I miss something obvious, If you put `main.py` at the root (`test`), of course it won't work isn't it? Since b is not in root, it's in /sub01

It should be 
```python
from sub01.b import print_from_b

print_from_b()
``` 

(And this works.)

**Comment by jakebailey** [comment]
Exactly. How are we supposed to know which way is the "correct" way to import `b`? How should we know which files are intended to be run as scripts and need special treatment? What if some files can be both libraries and scripts?

We chose the method where the workspace root is the canonical root, and anything extra needs to be configured. This works more often than it doesn't.

It's still an unsolved problem.

**Comment by fireattack** [comment]
I think I get your point now. This probably is a better example to show it:

`./main.py`:
```
from sub01.a import print_from_a

print_from_a()
```

modify ./sub01/a.py` to something like

```python
from b import print_from_b

def print_from_a():
    print_from_b()

if __name__ == "__main__":
    print_from_a()
```

Now this works with `python sub01/a.py` but not `python main.py`.

**Comment by jakebailey** [comment]
Right. And in our current setup, you'd open `a.py` in the editor and that import is squiggled to say that something might be wrong (which we view to be better than the opposite case, where we claim the import is fine and then you run it and it breaks).
