### ISSUE TITLE
Go to definition not working

### ISSUE THREAD

**Issue by wziww** [microsoft/python-language-server#1600]
![image](https://user-images.githubusercontent.com/29347227/65828183-b2a5eb00-e2ca-11e9-81e7-8031d4a6e7ec.png)

## Environment data

- Extension Version: (ms-python.python) 2019.9.34911   
- VScode Version: 1.38.1
- Python version: 2.7.16 64-bit
- OS: Darwin x64 18.0.0

## Expected behaviour

Go to definition while using  Nested Classes

## Actual behaviour

Cant go to definition

## Logs

```
```

## Code Snippet / Additional lnformation

```python
class test():
    class Test2():
        def Z(self):
            return
    A = Test2()

    def X(self):
        return


test.A.Z()

```

**Comment by jakebailey** [comment]
I can reproduce this.

**Comment by MikhailArkhipov** [comment]
Actually, `Z` does not appear to be part of `A`, that's why

![image](https://user-images.githubusercontent.com/12820357/65901725-9eff9080-e36d-11e9-9a75-515176b49860.png)
