### ISSUE TITLE
from typing import Callable doesnt trigger correct IntelliSense

### ISSUE THREAD

**Issue by hanpari** [microsoft/python-language-server#1607]
Issue Type: <b>Bug</b>

After 
from typing import C..

VS Code cannot offer Callable and others (see ipython picture import bellow). 

The same behaviour I checked on Python 3.7 and 3.6, on windows Python and Linux Python virtualized under Windows.
I confirmed the same issue on a different Window machine as well.

I checked Python source code whether Callable is listed in \_\_all\_\_ and everything seems fine.

Extension version: 2019.9.34911
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU 2020M @ 2.40GHz (2 x 2395)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.25GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

![obrazek](https://user-images.githubusercontent.com/7354817/65831897-6bb1f880-e2be-11e9-9450-b6e5b20b36b7.png)

Import works fine
![obrazek](https://user-images.githubusercontent.com/7354817/65831931-d2371680-e2be-11e9-83d1-41bb4ac58739.png)

IPython works as expected
![obrazek](https://user-images.githubusercontent.com/7354817/65831953-217d4700-e2bf-11e9-9237-74bf131e27a6.png)

**Comment by jakebailey** [comment]
This is #535. We implement the typing module in the LS directly (as it is a part of our type system), and some members have not yet been implemented.
