### ISSUE TITLE
unresolved import: using relative import

### ISSUE THREAD

**Issue by noppGithub** [microsoft/python-language-server#1612]
## **Question repo:**
https://github.com/noppGithub/ask-vscode-flask-docker

## **Environment data:**
**Version**: 1.38.1 (user setup)
**Commit**: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
**Date**: 2019-09-11T13:35:15.005Z
**Electron**: 4.2.10
**Chrome**: 69.0.3497.128
**Node.js**: 10.11.0
**V8**: 6.9.427.31-electron.0
**OS**: Windows_NT x64 10.0.17134
**VSCode Python extension**: "publisher": "ms-python", "version": "2019.9.34911"
**Python** version: Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)]
**Type of virtual environment used**: `python -m venv env` then `.\env\Scripts\activate`
**Other installed VSCode extension**:(name,publisher,version)

- azure-account_ms-vscode_0.8.4
- Bookmarks_alefragnani_10.5.0
- bracket-pair-colorizer_CoenraadS_1.0.61
- code-settings-sync_Shan_3.4.3
- gc-excelviewer_GrapeCity_2.1.32
- mssql_ms-mssql_1.6.0
- python_ms-python_2019.9.34911
- vscode-azureappservice_ms-azuretools_0.16.0
- vscode-azurefunctions_ms-azuretools_0.18.1
- vscode-docker_ms-azuretools_0.8.1
- vscode-icons_vscode-icons-team_9.4.0
- vscode-markdownlint_DavidAnson_0.30.2
- vscodeintellicode_VisualStudioExptTeam_1.1.9
- workspacesort_iciclesoft_1.5.8

## Issue:
I am developing an API using Python and Flask, Flask-restful, I have to create some customer classes and import to the `main.py` file when I run the code using my `launch.json` without any issue, but VS CODE will not do autocomplete, method list, variable list after typing `.` for the object that has `unresolved import` error.

Please note that my `main.py` is in `app` folder not in the root folder of the project and I want to copy the whole app folder to my Docker image when building the image. So this is the reason why I use relative import as shown in my code. You may check my `Dockerfile` in the repo to see what I am trying to do.

**Could you please guide me to solve this issue and then I can get autocomplete, Ctrl+Click to open my class object file, etc?**

Links that I have read before creating this issue:
- https://github.com/Microsoft/vscode-python/issues/5544
- https://github.com/microsoft/vscode-python/issues/5518
- StackOverflow

## Screen and Directory tree
![02](https://user-images.githubusercontent.com/21082770/65941009-2de6d880-e454-11e9-8455-9e7f5a85ac0d.PNG)
![03](https://user-images.githubusercontent.com/21082770/65941010-2e7f6f00-e454-11e9-9ae7-7d5c77b85ee8.PNG)
![01](https://user-images.githubusercontent.com/21082770/65941011-2e7f6f00-e454-11e9-9a63-475c51bb0889.PNG)

## Setting.json
```json
{
    "explorer.confirmDelete": false,
    "git.confirmSync": false,
    "git.autofetch": true,
    "window.zoomLevel": 0,
    "terminal.integrated.cwd": "",
    "git.enableSmartCommit": true,
    "workbench.iconTheme": "vscode-icons",
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "python.jediEnabled": false,
    "[markdown]": {
        "editor.quickSuggestions": true
    },
    "sync.forceUpload": true,
    "editor.minimap.enabled": true,
    "workbench.sideBar.location": "left",
    "breadcrumbs.enabled": false,
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
}
```

## Python Language server message from the Output tab
```log
[Info  - 2:11:44 PM] Microsoft Python Language Server version 0.4.24.0
[Info  - 2:11:44 PM] Workspace root: d:\np\ask-vscode-flask-docker
[Info  - 2:11:44 PM] Analysis cache path: C:\Users\nphantaw\AppData\Local\Microsoft\Python Language Server
[Info  - 2:11:44 PM] GetCurrentSearchPaths d:\np\ask-vscode-flask-docker\env\Scripts\python.exe 
[Info  - 2:11:45 PM] Interpreter search paths:
[Info  - 2:11:45 PM]     c:\users\nphantaw\appdata\local\programs\python\python36\dlls
[Info  - 2:11:45 PM]     c:\users\nphantaw\appdata\local\programs\python\python36\lib
[Info  - 2:11:45 PM]     c:\users\nphantaw\appdata\local\programs\python\python36
[Info  - 2:11:45 PM]     d:\np\ask-vscode-flask-docker\env
[Info  - 2:11:45 PM]     d:\np\ask-vscode-flask-docker\env\lib\site-packages
[Info  - 2:11:45 PM] User search paths:
[Info  - 2:11:46 PM] Initializing for d:\np\ask-vscode-flask-docker\env\Scripts\python.exe
[Info  - 2:11:46 PM] Analysis caching mode: None.
```

**Comment by jakebailey** [comment]
Those imports aren't relative imports, they're absolute imports. Since your import root is not the workspace root, you need to use extraPaths in order to set that `app` directory as an import root. See: https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#unresolved-import-warnings

**Comment by noppGithub** [comment]
> .classes import MyClass

If I do that(using `.classes import MyClass`), when I build a Docker image it won't work.
Please let me know if my Docker file is wrong.

**Comment by noppGithub** [comment]
> Those imports aren't relative imports, they're absolute imports. Relative imports would look like `from .classes import MyClass`.
> 
> Since your import root is not the workspace root, you need to use extraPaths in order to set that `app` directory as an import root. See: https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#unresolved-import-warnings

If I do that(using `.classes import MyClass`), when I build a Docker image it won't work.
Please let me know if my Docker file is wrong.

**Comment by jakebailey** [comment]
You don't have to do it, I was just referring to the title, which said that there were relative imports.

Because your workspace root is not your import root, you'll need to configure things to say where your imports are actually rooted from, i.e.:

```json
{
    "python.autoComplete.extraPaths": ["./app"]
}
```

**Comment by noppGithub** [comment]
> You don't have to do it, I was just referring to the title, which said that there were relative imports.
> 
> Because your workspace root is not your import root, you'll need to configure things to say where your imports are actually rooted from, i.e.:
> 
> ```json
> {
>     "python.autoComplete.extraPaths": ["./app"]
> }
> ```

It's works, Thank you so much.
I love you.

**Comment by jakebailey** [comment]
We're trying to do something like that generically, but there are so many different possibilities for import roots that it's difficult to handle every case. #1440 covered some of this, by adding `src/` if present (the vast majority of projects which do not put their python code at the top level). Django app layouts could be the next to try.

**Comment by noppGithub** [comment]
> We're trying to do something like that generically, but there are so many different possibilities for import roots that it's difficult to handle every case. #1440 covered some of this, by adding `src/` if present (the vast majority of projects which do not put their python code at the top level). Django app layouts could be the next to try.

Thank you so much, if anything I can do for help please feel free to tell me.
