### ISSUE TITLE
Publish to a NuGet feed

### ISSUE THREAD

**Issue by huguesv** [microsoft/python-language-server#1618]
Problems for PTVS:
- The PLS package files are uploaded to a CDN but they're not part of a NuGet feed, so standard NuGet references don't work.
- Old packages are sometimes deleted, breaking builds.

See https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-nuget?view=azure-devops for how to publish to pkgs.dev.azure.com.

FYI the division has phased out their usage of myget.org, now they're all using the above public artifacts hosting on ADO (for anything that isn't appropriate to go to nuget.org).

The ptvs branch was publishing to a storage account https://pvsc.blob.core.windows.net/vs-python-ls/index.json

**Comment by MikhailArkhipov** [comment]
Is it just for references or needs complete self-contained packages as does runtime? Complete package is per platform and each is ~30MB.

**Comment by huguesv** [comment]
We need to use it as both an SDK and as a Runtime. The SDK needs to be the 32-bit package because that's for use inside VS process. The runtime needs to be 64-bit or 32-bit depending on the user's machine.

So what I've been doing is extracting both 32-bit and 64-bit packages in separate folders:

```
PTVS/LanguageServer/x64/<PLS x64 assemblies>
PTVS/LanguageServer/x86/<PLS x86 assemblies>
```

I use the Codebase attribute point to the assemblies in the 32-bit subfolder so VS can load them in proc.  When starting the language server runtime, I just point to either 32-bit or 64-bit executable in appropriate subfolder.

That way I am avoiding having 3 copies (one for SDK, 2 for runtime).

But that will be a problem if we want to update the language server after VS has been installed. We would have to guarantee that the new language server remains SDK compatible if we're going to drop in replace a new one.

So if we need to update the runtime after install, I think it would be safer if that doesn't update the SDK files used in VS process. So keep the SDK assemblies in the same folder as all other PTVS assemblies, separate from the runtime subfolders, which would get overwritten with the download.

```
PTVS/<PLS x86 assemblies>
PTVS/LanguageServer/x64/<PLS x64 assemblies>
PTVS/LanguageServer/x86/<PLS x86 assemblies>
```

It's kind of annoying that there's no AnyCPU build but I suppose that's not possible when you want an executable generated, as opposed to launching with dotnet.exe?

**Comment by MikhailArkhipov** [comment]
LS package is self-contained, it does not need SDK or runtime. The discovery and download pattern exists in the Python extension: https://github.com/microsoft/vscode-python/tree/master/src/client/activation/languageServer with channels, versions, installation, etc.

I assume that only parser might be loaded in-proc. Analysis engine in-proc on 32-bit platform is basically useless b/c of the memory requirements.

**Comment by huguesv** [comment]
From Microsoft.Python.Analysis.Core, we use:
```
InterpreterArchitecture
ModulePath
```

Outside of those 2, we just need `Microsoft.Python.Parsing` and `Microsoft.Python.Core`.

They can be copied into our sources. I'd prefer not for `ModulePath` though.

**Comment by MikhailArkhipov** [comment]
OK. Let's see if we can move those to core or parser instead.
