### ISSUE TITLE
Crashing language server

### ISSUE THREAD

**Issue by martin-91x** [microsoft/python-language-server#1623]
## Environment data
[Error - 11:40:50 AM] Connection to server is erroring. Shutting down server.
[Error - 11:40:50 AM] Connection to server is erroring. Shutting down server.
[Error - 11:40:50 AM] Connection to server is erroring. Shutting down server.
/home/nvidia/.vscode-server-insiders/extensions/ms-python.python-2019.9.34911/languageServer.0.4.38/Microsoft.Python.LanguageServer: 1: /home/nvidia/.vscode-server-insiders/extensions/ms-python.python-2019.9.34911/languageServer.0.4.38/Microsoft.Python.LanguageServer: cannot create 5@@8J@8
@ @@@@@00pp@p@@@�0�0 �<�<a�<a� `=`=a`=a@@��@�@DD�<�<a�<aP�tdAA||Q�tdR�td�<�<a�<a  /lib64/ld-linux-x86-64.so.2GNU GNU@U�-��8*bn��h
�����!	
����j	Cֺ�|CE��:�2b���K���������qX�����:�����yIk���	}�4	`�s	��� - Q(A	~[!�I�	m1��
.;	/��	: Directory nonexistent
/home/nvidia/.vscode-server-insiders/extensions/ms-python.python-2019.9.34911/languageServer.0.4.38/Microsoft.Python.LanguageServer: 1: /home/nvidia/.vscode-server-insiders/extensions/ms-python.python-2019.9.34911/languageServer.0.4.38/Microsoft.Python.LanguageServer: ELF: not found
/home/nvidia/.vscode-server-insiders/extensions/ms-python.python-2019.9.34911/languageServer.0.4.38/Microsoft.Python.LanguageServer: 4: /home/nvidia/.vscode-server-insiders/extensions/ms-python.python-2019.9.34911/languageServer.0.4.38/Microsoft.Python.LanguageServer: _: not found
/home/nvidia/.vscode-server-insiders/extensions/ms-python.python-2019.9.34911/languageServer.0.4.38/Microsoft.Python.LanguageServer: 5: /home/nvidia/.vscode-server-insiders/extensions/ms-python.python-2019.9.34911/languageServer.0.4.38/Microsoft.Python.LanguageServer: ��: not found
/home/nvidia/.vscode-server-insiders/extensions/ms-python.python-2019.9.34911/languageServer.0.4.38/Microsoft.Python.LanguageServer: 6: /home/nvidia/.vscode-server-insiders/extensions/ms-python.python-2019.9.34911/languageServer.0.4.38/Microsoft.Python.LanguageServer: ���: not found
/home/nvidia/.vscode-server-insiders/extensions/ms-python.python-2019.9.34911/languageServer.0.4.38/Microsoft.Python.LanguageServer: 12: /home/nvidia/.vscode-server-insiders/extensions/ms-python.python-2019.9.34911/languageServer.0.4.38/Microsoft.Python.LanguageServer: ��	�%��G	�Efr	��	��@w/Db��	�	["
�	�"P����	�y	�"Qk	I���	X	�	�
�Ca�
�Ha�
�Ha�
 �Ca�

5@p: not found
/home/nvidia/.vscode-server-insiders/extensions/ms-python.python-2019.9.34911/languageServer.0.4.38/Microsoft.Python.LanguageServer: 13: /home/nvidia/.vscode-server-insiders/extensions/ms-python.python-2019.9.34911/languageServer.0.4.38/Microsoft.Python.LanguageServer: ��@�: not found
/home/nvidia/.vscode-server-insiders/extensions/ms-python.python-2019.9.34911/languageServer.0.4.38/Microsoft.Python.LanguageServer: 5: /home/nvidia/.vscode-server-insiders/extensions/ms-python.python-2019.9.34911/languageServer.0.4.38/Microsoft.Python.LanguageServer: Syntax error: Unterminated quoted string

- Language Server version: 0.4.38   
- OS and version: Windows 10 1809 / Ubuntu 18.04 Remote
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.8 (Remote)

## Expected behaviour

Running language server.

## Actual behavior

Language server crashes.

## Logs

User belongs to experiment group 'AlwaysDisplayTestExplorer - control'
User belongs to experiment group 'ShowPlayIcon - start'
> conda --version
> pyenv root
> python3.7 -c "import sys;print(sys.executable)"
> python3.6 -c "import sys;print(sys.executable)"
> python3 -c "import sys;print(sys.executable)"
> python2 -c "import sys;print(sys.executable)"
> python -c "import sys;print(sys.executable)"
> /usr/bin/python3 -c "import sys;print(sys.executable)"
> conda info --json
Starting Microsoft Python language server.
> /usr/bin/python3 -m pylint --max-line-length=120 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text ~/tensorRT_bench/main.py
cwd: ~/tensorRT_bench
> /usr/bin/python3 -m pylint --max-line-length=120 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text ~/tensorRT_bench/main.py
cwd: ~/tensorRT_bench
> /usr/bin/python3 -m pylint --max-line-length=120 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text ~/tensorRT_bench/common.py
cwd: ~/tensorRT_bench
> /usr/bin/python3 -m pylint --max-line-length=120 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text ~/tensorRT_bench/common.py
cwd: ~/tensorRT_bench
##########Linting Output - pylint##########
************* Module main
25,0,convention,line-too-long:Line too long (158/120)
61,0,convention,line-too-long:Line too long (151/120)
74,0,convention,line-too-long:Line too long (135/120)
77,0,convention,line-too-long:Line too long (170/120)
78,0,convention,line-too-long:Line too long (171/120)
82,0,convention,line-too-long:Line too long (171/120)
85,0,convention,superfluous-parens:Unnecessary parens after 'del' keyword
86,0,convention,superfluous-parens:Unnecessary parens after 'del' keyword
89,0,convention,line-too-long:Line too long (181/120)
91,0,convention,line-too-long:Line too long (177/120)
16,0,refactor,too-many-arguments:Too many arguments (6/5)
32,17,warning,unused-argument:Unused argument 'w_in'
32,23,warning,unused-argument:Unused argument 'h_in'
32,29,warning,unused-argument:Unused argument 'd_in'
32,35,warning,unused-argument:Unused argument 'kernel_size'
32,48,warning,unused-argument:Unused argument 'filter_k'
50,0,refactor,too-many-locals:Too many local variables (19/15)
5,0,warning,unused-import:Unused import sys
7,0,warning,unused-import:Unused import pycuda.autoinit
8,0,warning,unused-import:Unused pycuda.driver imported as cuda

------------------------------------------------------------------
Your code has been rated at 6.83/10 (previous run: 6.83/10, +0.00)

##########Linting Output - pylint##########
************* Module common
93,0,convention,superfluous-parens:Unnecessary parens after 'not' keyword
100,0,convention,line-too-long:Line too long (132/120)
60,4,warning,redefined-builtin:Redefining built-in 'FileNotFoundError'
1,0,convention,missing-module-docstring:Missing module docstring
62,0,convention,invalid-name:Function name "GiB" doesn't conform to snake_case naming style
62,0,convention,missing-function-docstring:Missing function or method docstring
65,0,warning,dangerous-default-value:Dangerous default value [] as argument
77,4,convention,invalid-name:Variable name "kDEFAULT_DATA_ROOT" doesn't conform to snake_case naming style
97,15,convention,invalid-name:Variable name "f" doesn't conform to snake_case naming style
101,4,refactor,no-else-return:Unnecessary "else" after "return"
82,10,warning,unused-variable:Unused variable 'unknown_args'
107,0,convention,missing-class-docstring:Missing class docstring
107,0,refactor,useless-object-inheritance:Class 'HostDeviceMem' inherits from object, can be safely removed from bases in python3
119,0,convention,missing-function-docstring:Missing function or method docstring
123,13,error,no-member:Module 'pycuda.driver' has no 'Stream' member
128,19,error,no-member:Module 'pycuda.driver' has no 'pagelocked_empty' member
129,21,error,no-member:Module 'pycuda.driver' has no 'mem_alloc' member
141,0,convention,missing-function-docstring:Missing function or method docstring
141,0,refactor,too-many-arguments:Too many arguments (6/5)
143,18,error,no-member:Module 'pycuda.driver' has no 'Event' member
144,16,error,no-member:Module 'pycuda.driver' has no 'Event' member
145,12,error,no-member:Module 'pycuda.driver' has no 'Event' member
146,10,error,no-member:Module 'pycuda.driver' has no 'Event' member
149,4,warning,expression-not-assigned:Expression "[cuda.memcpy_htod_async(inp.device, inp.host, stream) for inp in inputs]" is assigned to nothing
149,5,error,no-member:Module 'pycuda.driver' has no 'memcpy_htod_async' member
155,4,warning,expression-not-assigned:Expression "[cuda.memcpy_dtoh_async(out.host, out.device, stream) for out in outputs]" is assigned to nothing
155,5,error,no-member:Module 'pycuda.driver' has no 'memcpy_dtoh_async' member

------------------------------------------------------------------
Your code has been rated at 1.13/10 (previous run: 1.13/10, +0.00)

## Code Snippet / Additional lnformation

I'm running the insider version to work remotely on a Ubuntu 18.04 machine (Jetson). The language server was running fine until Wednesday.
I tried to delete the corresponding files in the python extension directory, but re-installing did not solve the issue.

**Comment by MikhailArkhipov** [comment]
What is the LS output? I.e. Output window => Python Language Server tab.

**Comment by MikhailArkhipov** [comment]
So this is remote, right? Looks like https://github.com/microsoft/python-language-server/issues/1595 and upstream dotnet issue.

**Comment by martin-91x** [comment]
Yes, it's installed on the remote system. 
The output of the language server is the first output in my post, i.e. the part under "Environment Data"

I'll take a look at the issue you posted but I didn't reply there since I have a totally different LS output (nothing with CoreCLR)

**Comment by martin-91x** [comment]
@MikhailArkhipov: I had a look at the issue but I think I have a different problem.  I don't use WSL instead my remote is a different system running Ubuntu 18.04.

**Comment by MikhailArkhipov** [comment]
It is still some sort of Linux remote so it is probably the same root cause.

**Comment by MikhailArkhipov** [comment]
@martin-91x could you look at https://github.com/dotnet/core-setup/issues/8496 and follow .NET Core folks suggestion for capturing the diagnostics? Thanks.

**Comment by MikhailArkhipov** [comment]
This does not appear to be LS issue as it doesn't even start. So folding into #1595.
