### ISSUE TITLE
Defining a lambda in a class member emits incorrect "self" warning

### ISSUE THREAD

**Issue by markedwards** [microsoft/python-language-server#1633]
## Environment data

- Language Server version: 0.4.38.0   
- OS and version: OS X 10.14.6
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.3 (Anaconda)

## Expected behaviour

No warning should be issued when defining a lambda function as the value of a class member.

## Actual behaviour

When defining a lambda as a class member, an incorrect warning is issued that the function should have "self" as the first argument:

`Method '<lambda>' should have 'self' as first argument.`

This also occurs if the lambda is a member of a member of a class.

## Code Snippet / Additional lnformation

```python
class TestClass:
    FOO = lambda x: 'foo'
```

**Comment by markedwards** [comment]
<img width="791" alt="Screenshot 2019-10-06 at 18 04 34" src="https://user-images.githubusercontent.com/454900/66272652-76dbca00-e864-11e9-92b9-cd6392285e4a.png">

**Comment by markedwards** [comment]
<img width="791" alt="Screenshot 2019-10-06 at 18 04 34" src="https://user-images.githubusercontent.com/454900/66272652-76dbca00-e864-11e9-92b9-cd6392285e4a.png">

**Comment by jakebailey** [comment]
Yep, we need to add IsLambda to IPythonFunctionType, then check that it's not a lambda in CheckValidFunction. Lambdas are just wrappers around functions in our parser, so the scope that lambda appears to exist in is the class scope, so is getting picked up as one and linted.

**Comment by MikhailArkhipov** [comment]
There is `IsLambda()` extension on `IPythonFunctionType` I believe.

**Comment by jakebailey** [comment]
That'd work, yeah. Funny that it just checks the function name being `<lambda>` though...

**Comment by markedwards** [comment]
Thanks for the quick fix guys!
