### ISSUE TITLE
documentHighlightProvider

### ISSUE THREAD

**Issue by astenman** [microsoft/python-language-server#1634]
I am using the language server via Emacs/LSP. Are there any plans to implement documentHighlightProvider?

**Comment by jakebailey** [comment]
No, but this could be done with some modification to our references code (to look only in the current file and not go searching in unopened ones at all).

**Comment by astenman** [comment]
An initial fix for this has been submitted in the PR

https://github.com/microsoft/python-language-server/pull/1767

**Comment by MikhailArkhipov** [comment]
PR was merged, so closing. Thanks for your contribution!
