### ISSUE TITLE
numpy packages still misses most methods

### ISSUE THREAD

**Issue by AeneasZhu** [microsoft/python-language-server#1635]
![image](https://user-images.githubusercontent.com/44701446/66314778-1d000080-e947-11e9-9fcb-34adc7e32340.png)

![image](https://user-images.githubusercontent.com/44701446/66314807-29845900-e947-11e9-8636-5a2a09f82dc9.png)

![image](https://user-images.githubusercontent.com/44701446/66314831-33a65780-e947-11e9-9782-7c8449a371e0.png)

Python language server still misses most numpy package's methods, especially the math operator methods and random methods.

**Comment by jakebailey** [comment]
Likely also #1414/#1621.

**Comment by MikhailArkhipov** [comment]
![image](https://user-images.githubusercontent.com/12820357/66356916-aac8f500-e921-11e9-930e-ae35a312cf1a.png)

Folding into #1414.
