### ISSUE TITLE
Text edit desync leading to invalid analysis/linting

### ISSUE THREAD

**Issue by rvinzent** [microsoft/python-language-server#1637]
## Environment data

```
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:31:32.854Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0
```
extension info
```
Name: Python
Id: ms-python.python
Description: Linting, Debugging (multi-threaded, remote), Intellisense, code formatting, refactoring, unit tests, snippets, and more.
Version: 2019.9.34911
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-python.python
```

python versions
```
- Python version (& distribution if applicable, e.g. Anaconda): `2.7`
- Type of virtual environment used: `virtualenv`
- Jedi or Language Server? `Language server`
```
## Expected behaviour

Linter should parse python files properly. I would expect the characters to not be backwards.

## Actual behaviour

<img width="414" alt="Screen Shot 2019-10-07 at 1 00 08 PM" src="https://user-images.githubusercontent.com/34038882/66344850-a5f54880-e903-11e9-9963-55d05dfbbbce.png">
The characters are displayed backwards and it throws an error.

All sorts of things start randomly throwing uninformative and incorrect errors:

<img width="728" alt="Screen Shot 2019-10-07 at 1 31 50 PM" src="https://user-images.githubusercontent.com/34038882/66346453-0df95e00-e907-11e9-9b77-262bd913d2ae.png">
<img width="747" alt="Screen Shot 2019-10-07 at 1 32 02 PM" src="https://user-images.githubusercontent.com/34038882/66346458-105bb800-e907-11e9-9ac9-8518bc2c1541.png">
<img width="784" alt="Screen Shot 2019-10-07 at 1 32 38 PM" src="https://user-images.githubusercontent.com/34038882/66346465-1356a880-e907-11e9-8937-55d0964622e9.png">
<img width="820" alt="Screen Shot 2019-10-07 at 1 32 55 PM" src="https://user-images.githubusercontent.com/34038882/66346470-15206c00-e907-11e9-83f6-a60854b40f33.png">
<img width="498" alt="Screen Shot 2019-10-07 at 1 55 04 PM" src="https://user-images.githubusercontent.com/34038882/66347862-2454e900-e90a-11e9-9de5-3d646b612675.png">

## Steps to reproduce:

Something in a recent update broke this, but I don't think anything in particular leads to this behavior on my end. I have a multi-root workspace configured with 2 python projects. And this generally tends to break everything related to this extension. Not sure if that could be relevant.

## Logs
```
[Info  - 10:13:01 AM] Microsoft Python Language Server version 0.4.38.0
[Info  - 10:13:01 AM] Workspace root: /Users/me/path/to/repo/
[Info  - 10:13:01 AM] Analysis cache path: /Users/me/Library/Caches/Microsoft/Python Language Server
[Info  - 10:13:01 AM] GetCurrentSearchPaths /Users/me/path/to/repo/env/bin/python 
[Info  - 10:13:01 AM] Interpreter search paths:
[Info  - 10:13:01 AM]     /Users/me/path/to/repo/env/lib/python2.7
[Info  - 10:13:01 AM]     /Users/me/path/to/repo/env/lib/python2.7/lib-dynload
[Info  - 10:13:01 AM]     /usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7
[Info  - 10:13:01 AM]     /usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
[Info  - 10:13:01 AM]     /usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
[Info  - 10:13:01 AM]     /usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
[Info  - 10:13:01 AM]     /usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
[Info  - 10:13:01 AM]     /Users/me/path/to/repo/env/lib/python2.7/site-packages
[Info  - 10:13:01 AM] User search paths:
[Info  - 10:13:07 AM] Initializing for /Users/me/path/to/repo/env/bin/python
[Info  - 10:13:08 AM] Analysis caching mode: None.
```
Also seeing this in the `Window` log:
```
[2019-10-06 16:35:12.742] [renderer1] [error] Unable to read file (Error: File not found (/Users/rvinzent/Library/Caches/Microsoft/Python Language Server/stubs.v2/U4Yfc1Srfa_KARMCmhJ_oe1y3D3LJt-FJ92ywfe1U1E=/python.pyi)): Error: Unable to read file (Error: File not found (/Users/rvinzent/Library/Caches/Microsoft/Python Language Server/stubs.v2/U4Yfc1Srfa_KARMCmhJ_oe1y3D3LJt-FJ92ywfe1U1E=/python.pyi))
    at b.<anonymous> (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1521:283)
    at Generator.throw (<anonymous>)
    at a (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:35:450)
```

**Comment by MikhailArkhipov** [comment]
Sounds like another issue like #1543

**Comment by MikhailArkhipov** [comment]
#1543 was fixed, feel free to reopen if you still see this. Thanks.

**Comment by Ark-kun** [comment]
It's not fixed.
It has happened to me many times in 2020.

https://github.com/microsoft/python-language-server/issues/2026#issuecomment-699583596

Happened again on
```
Version: 1.48.2 (user setup)
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:13:11.295Z (1 mo ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362
```

![image](https://user-images.githubusercontent.com/1829149/94356036-a15b0000-003e-11eb-93ec-5e0d69675d5b.png)
