### ISSUE TITLE
Add support for class method overrides 

### ISSUE THREAD

**Issue by johnybx** [microsoft/python-language-server#1641]
Hi,
It would be nice to have features simular to [pycharm](https://www.jetbrains.com/help/pycharm/overriding-methods-of-a-superclass.html) which show overriden methods of classes, suggest methods which can be overriden or should be (not implemented methods for example).
I did not find any issues or milestones related to this.

**Comment by jakebailey** [comment]
Can you provide some specific examples? We do have override support already through completions, where writing `def something` will recognize that the base class has a method and then complete to a placeholder which calls it.

I'm not entirely certain how we'd show that something is an override, at least from the LSP point of view, since there doesn't seem to be any way to make a visual indicator.

And by suggesting something that isn't implemented, do you mean something that's been marked as abstract by a base class, but has not yet been implemented to complete?

**Comment by johnybx** [comment]
Hi,
the complete on base class method works nicely but it would be useful to have some visual indicator that would show that method overrides base class method (for example pycharm has little bullet next to line number with arrow which indicates method override and also shows info about Class.method where class is name of base class as we can inherit from multiple classes).

By suggesting something that isn't implemented I mean when you use for example use abstractmethod decorator from abc. I would be nice to have suggestions or maybe some shortcut which would show little window which method should / could be implemented with option to add them like [this](https://www.jetbrains.com/help/phpstorm/implementing-methods-of-an-interface.html) 

These are probably more visual aspects but not sure though.

**Comment by imuxin** [comment]
Hi, all
I do really think the indicator of overwrote method is a good design for programming. And I made an example below, FYI.
![image](https://user-images.githubusercontent.com/47353892/71403430-b26b8080-266a-11ea-8377-f80445d45cdd.png)

**Comment by antonwnk** [comment]
+1, would be a very useful feature

**Comment by shrhawk-entertainer** [comment]
+1 waiting for this and it will be very helpful

**Comment by shrhawk-entertainer** [comment]
@jakebailey any updates?

**Comment by jakebailey** [comment]
No updates. This sort of thing is not in the language server specification. As far as I know, VS Code (our main user) doesn't have support for these sorts of sidebar icons in their UI other than for the built-in debugger, and without it being in the LSP specification we'd have to implement this custom.

Potentially, this could be a code lens, but those are much more space-wasting than an icon to the side.

**Comment by johnybx** [comment]
@jakebailey this issue was moved from LS by @karthiknadig so maybe you could give it second thought ?

**Comment by b99andla** [comment]
Just wanted to added another +1 on this, this is whats keeping us to move away from IntelliJ at the moment.

**Comment by swd543** [comment]
This would be a very useful feature +1

**Comment by dbulgakov7** [comment]
> This would be a very useful feature +1

+1

**Comment by adhikariravi** [comment]
+1

**Comment by abhinavg97** [comment]
+1

**Comment by j-pong** [comment]
+1

**Comment by Object905** [comment]
+1

**Comment by eugene-s** [comment]
+1

**Comment by farib-reasonal** [comment]
+1

**Comment by Cheng-2v** [comment]
+1,It would be a great feature add up and down arrow on children class method and parent class method.

**Comment by allania7med11** [comment]
+1

**Comment by jakebailey** [comment]
This repo is no longer actively maintained.

https://devblogs.microsoft.com/python/python-in-visual-studio-code-september-2021-release/#microsoft-python-language-server-end-of-life-november-2021

**Comment by jakebailey** [comment]
This repo is no longer actively maintained.

https://devblogs.microsoft.com/python/python-in-visual-studio-code-september-2021-release/#microsoft-python-language-server-end-of-life-november-2021
