### ISSUE TITLE
Implement on-type block formatting

### ISSUE THREAD

**Issue by jakebailey** [Microsoft/python-language-server#165]
The VS Code extension provides an on-type formatter that triggers on `:` which allows for block formatting. For example, you can hit colon after the `else` in the following code:

```python
if x:
    pass
    else
```

Which will then be reformatted into:

```python
if x:
    pass
else:
```

This functionality should be implemented in language server for feature parity. The language server may even be able to handle more cases correctly than the extension's use of regex, since we have access to an AST.

Since on-type formatting has only one entrypoint (`DocumentOnTypeFormatting`), that function would need to map trigger characters to the right handler. A nicety would be to have a Dictionary of handlers, then produce the `DocumentOnTypeFormattingOptions`'s trigger character members from that dictionary rather than needing to remember to change the characters in two different files.

Related to Microsoft/vscode-python#2714.

**Comment by MikhailArkhipov** [comment]
Also this https://github.com/Microsoft/vscode-python/issues/481
