### ISSUE TITLE
Go to definition doesn't work with files inside venv

### ISSUE THREAD

**Issue by aliev** [microsoft/python-language-server#1653]
## Environment data

- Language Server version: 0.4.58.0 
- OS and version: 10.15 (19A583)
- Python version (& distribution if applicable, e.g. Anaconda): 3.5.5, pyenv, venv

## Expected behaviour

Go to definition should work for venv files as well.

## Actual behaviour

Setup env:

```
mkdir Hello && cd Hello
pyenv shell 3.5.5
python -mvenv .env
source .env/bin/activate
pip install django
code .
```

Steps to reproduce:

Create new file main.py

Add new import:
from django.http import HttpResponse <- Click on "Go to definition from context menu"
...http/__init__.py will be opened
from django.http.cookie import SimpleCookie, parse_cookie <- Click on "Go to definition"
Nothing happens

## Logs

https://gist.github.com/aliev/c1cbeb1c9a9e687796e70ed297eecc0b

**Comment by MikhailArkhipov** [comment]
This is currently by design. We do not preserve content, AST (parse tree) or navigation information within libraries in order to conserve memory.

**Comment by MikhailArkhipov** [comment]
https://github.com/microsoft/python-language-server/issues/840 is primary
