### ISSUE TITLE
"Unresolved import" for import wrapped in try/except

### ISSUE THREAD

**Issue by ytimenkov** [microsoft/python-language-server#1663]
## Environment data

- VS Code version: Code 1.39.0 (9df03c6d6ce97c6645c5846f6dfa2a6a7d276515, 2019-10-09T06:58:04.439Z)
- Extension version (available under the Extensions sidebar): 2019.10.41019
- OS and version: OS version: Windows_NT x64 10.0.16299
- Remote OS version: Linux x64 5.0.0-31-generic
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.3 x64 Ubuntu 19.04
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Relevant/affected Python packages and their versions: N/A
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): `false`

## Expected behaviour
Extension correctly finds `ConfigParser` object and doesn't complain about unresolved import on the other branch

## Actual behaviour
I get 2 warnings:
```
module ConfigParser
unresolved import 'ConfigParser'Python(unresolved-import)
unresolved import 'ConfigParser'Python(unresolved-import)
```
It also doesn't work to disable warning *at this particular spot* with `# pylint disable=unresolved-import`. The warning is still shown.

## Steps to reproduce:
I write py2/py3 compatible code and have import like this:
```python
try:
    from configparser import ConfigParser
except ImportError:
    from ConfigParser import ConfigParser
```

**Comment by MikhailArkhipov** [comment]
LS does not look into pylint options. You can try `#noqa` instead.

**Comment by ytimenkov** [comment]
That helped. :thumbsup:

I think I saw "pylint" before and that's why got confused. Maybe I had errors coming from pylint.

If you don't plan to fix this pattern you may close the issue.

**Comment by MikhailArkhipov** [comment]
Since static analysis doesn't really know which path code will take on a particular version of Python, using `#noqa` is probably the only option here. Closing.
