### ISSUE TITLE
Intellisense and go to definition not working for external modules

### ISSUE THREAD

**Issue by bogh** [microsoft/python-language-server#1664]
The extension completion and search for definition doesn't work for modules located outside the main folder. 
I have a virtualenvironment setup with `pipenv` and I configured VSCode Python interpreter accordingly. For the modules inside the main workspace folder the completion and go to definition works, but for third party modules installed with `pipenv` doesn't work, it's like they don't get indexed. But Go to definition from main folder to external module works.

If I use Jedi, it all works ok.

## Environment data
- VS Code version: 1.38.1
- Extension version (available under the Extensions sidebar): 2019.10.41019
- OS and version: Linux x64 5.0.9-301.fc30.x86_64 (Fedora 30)
- Python version (& distribution if applicable, e.g. Anaconda): 3.7
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv with pipenv
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): Language Server

**Comment by MikhailArkhipov** [comment]
Same as #840. Modules outside of the workspace are considered libraries and in order to conserve memory file content, parse tree and navigation information is not preserved. This might be made into an option if memory consumption increase is not a concern.
