### ISSUE TITLE
"Go to definition" jumps to wrong function when importing multiple functions together

### ISSUE THREAD

**Issue by fireattack** [microsoft/python-language-server#1670]
## Environment data

- Language Server version:  0.4.58.0
- OS and version: Win7x64
- Python version (& distribution if applicable, e.g. Anaconda): vanilla Py 3.7

## Expected behaviour

Ctrl+lick "b" or "c" in test.py.

It should jump to definition of b or c.

## Actual behaviour

It jumps to definition of a.

![gifski](https://user-images.githubusercontent.com/4130991/66626556-4b3b4580-ebbe-11e9-9939-e1c8c5129b46.gif)

## Logs

```
Goto Definition in file:///d:/pytest/test.py at (1, 24)
Hover in file:///d:/pytest/test.py at (1, 24)
Goto Definition in file:///d:/pytest/test.py at (1, 23)
```

## Code Snippet / Additional lnformation

util.py:

```python
def a(name):
    pass

def b(url):
    pass

def c(text):
    pass
```

test.py:
```python
from util import a, b, c
```

**Comment by judej** [comment]
Thanks for the report. I've reproduced this. Will get it in the back log.

The go to definition works correctly when performed from a call the to imported function. This bug repros when the action is performed from the import line
