### ISSUE TITLE
Linter does not report undefined on += and similar operators

### ISSUE THREAD

**Issue by MikhailArkhipov** [microsoft/python-language-server#1671]
```python
dest += 1
```
![image](https://user-images.githubusercontent.com/12820357/66627905-fabdeb00-ebb1-11e9-94f7-b8ad50527067.png)

**Comment by jakebailey** [comment]
We don't consider assignment operators to be actual assignments, since they'd need to have some sort of assignment beforehand to then add to. We could make this more loose but it might be strange.

**Comment by bsandrow** [comment]
Shouldn't `dest` be marked as an undefined variable on the `+=` line if you want to keep that classification?

**Comment by jakebailey** [comment]
Yes, that's what this bug is about, that it should. The linter is likely just not walking the lefthand side of these augmented assignments.
