### ISSUE TITLE
Docstring tooltips show Microsoft.Python.Analysis.Type instead of default value for optional parameters

### ISSUE THREAD

**Issue by giahung24** [microsoft/python-language-server#1672]
Hello,
I don't know since when my VSC has had this bug. I have tried with different projects, venv, the issue remains the same.

## Environment data

- Language Server version: 0.4.58.0   
- OS and version: Ubuntu 18.04
- Python version (& distribution if applicable, e.g. Anaconda): 2.7 / 3.7 or any

## Actual behaviour
![image](https://user-images.githubusercontent.com/11850677/66639755-c41abb80-ec17-11e9-8e79-abf6b045c83d.png)

## Expected behaviour
defaut value `100` instead of `Microsoft.Python.Analysis.Values.PythonConstant`

```python
def hello(a, b=100, c={'a':4}):
    return a + b

if __name__ == "__main__":
    hello()
```

**Comment by jakebailey** [comment]
I can reproduce.

**Comment by jakebailey** [comment]
Bisects to #1614. Makes sense, since I changed the signature code.

**Comment by MikhailArkhipov** [comment]
`builder.Append(p.DefaultValue);` should be `p.DefaultValueString`

**Comment by jakebailey** [comment]
Yep, my bad.
