### ISSUE TITLE
Undefined variable for xrange in class definition

### ISSUE THREAD

**Issue by schlamar** [microsoft/python-language-server#1673]
## Environment data

- Language Server version: 0.4.58.0
- OS and version: Win 7 
- Python version: Python 2.7.15

## Expected behaviour

No error for the code snippet below.

## Actual behaviour

Error `Undefined variable: 'i'` on both lines with `i`.

## Code Snippet

```python
for j in xrange(1):
    print j


class Test(object):
    for i in xrange(1):
        print i
```

**Comment by schlamar** [comment]
Same issue with Python 3 and `range`.

**Comment by MikhailArkhipov** [comment]
Same as #910. You may try using `__init__` instead I guess.
