### ISSUE TITLE
Python tools server crashed (again)

### ISSUE THREAD

**Issue by jmwielandt** [microsoft/python-language-server#1689]
### VSCode info
- Version: 1.39.1 (user setup)
- Commit: 88f15d17dca836346e787762685a40bb5cce75a8
- Date: 2019-10-10T23:31:28.683Z
- Electron: 4.2.10
- Chrome: 69.0.3497.128
- Node.js: 10.11.0
- V8: 6.9.427.31-electron.0
- OS: Windows_NT x64 10.0.18362

### Extension info
- Name: Python
- Id: ms-python.python
- Description: Linting, Debugging (multi-threaded, remote), Intellisense, code formatting, refactoring, unit tests, snippets, and more.
- Version: 2019.10.41019
- Publisher: Microsoft
- VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-python.python

### Python info
- Python 3.7.4 - AMD64
- No virtual env.
- Jedi or Language Server? Language Server.

## Actual behaviour

![image](https://user-images.githubusercontent.com/37153467/66709727-a09f6000-ed40-11e9-9163-fc9039bc3902.png)

## Steps to reproduce:
1. Open any .py file with vscode.
2. Wait a few seconds.

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

<details>
<summary>Click me</summary>
<br/>

```
User belongs to experiment group 'ShowPlayIcon - start'
Starting Microsoft Python language server.
> conda --version
> pyenv root
> python3.7 -c "import sys;print(sys.executable)"
> python3.6 -c "import sys;print(sys.executable)"
> python3 -c "import sys;print(sys.executable)"
> python2 -c "import sys;print(sys.executable)"
> python -c "import sys;print(sys.executable)"
> py -3.7 -c "import sys;print(sys.executable)"
> py -3.6 -c "import sys;print(sys.executable)"
> py -3 -c "import sys;print(sys.executable)"
> py -2 -c "import sys;print(sys.executable)"
> ~\AppData\Local\Programs\Python\Python37\python.exe -c "import sys;print(sys.executable)"
> conda info --json
> ~\AppData\Local\Microsoft\WindowsApps\python3.exe c:\Users\Jose\.vscode\extensions\ms-python.python-2019.10.41019\pythonFiles\interpreterInfo.py
> ~\AppData\Local\Microsoft\WindowsApps\python3.exe c:\Users\Jose\.vscode\extensions\ms-python.python-2019.10.41019\pythonFiles\interpreterInfo.py
> ~\AppData\Local\Microsoft\WindowsApps\python3.exe c:\Users\Jose\.vscode\extensions\ms-python.python-2019.10.41019\pythonFiles\interpreterInfo.py
> ~\AppData\Local\Microsoft\WindowsApps\python3.exe c:\Users\Jose\.vscode\extensions\ms-python.python-2019.10.41019\pythonFiles\interpreterInfo.py
> ~\AppData\Local\Microsoft\WindowsApps\python.exe c:\Users\Jose\.vscode\extensions\ms-python.python-2019.10.41019\pythonFiles\interpreterInfo.py
> ~\AppData\Local\Microsoft\WindowsApps\python.exe c:\Users\Jose\.vscode\extensions\ms-python.python-2019.10.41019\pythonFiles\interpreterInfo.py
> ~\AppData\Local\Microsoft\WindowsApps\python.exe c:\Users\Jose\.vscode\extensions\ms-python.python-2019.10.41019\pythonFiles\interpreterInfo.py
> ~\AppData\Local\Microsoft\WindowsApps\python.exe c:\Users\Jose\.vscode\extensions\ms-python.python-2019.10.41019\pythonFiles\interpreterInfo.py
```
</details>

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

<details>
<summary>Image</summary>
<br>

![image](https://user-images.githubusercontent.com/37153467/66709902-e90c4d00-ed43-11e9-9c37-427a88b055de.png)

</details>

**Comment by jakebailey** [comment]
Please provide logs per https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#filing-an-issue

We'd need the language server logs.

**Comment by jmwielandt** [comment]
Hi!

This is what I get in "Python Language Server" _tab_.

<details>
<summary>Logs</summary>
<br>

```
Error:
  An assembly specified in the application dependencies manifest (Microsoft.Python.LanguageServer.deps.json) was not found:
    package: 'runtimepack.Microsoft.NETCore.App.Runtime.win-x64', version: '3.0.0'
    path: 'System.Private.DataContractSerialization.dll'
[Info  - 11:17:06] Connection to server got closed. Server will restart.
Error:
  An assembly specified in the application dependencies manifest (Microsoft.Python.LanguageServer.deps.json) was not found:
    package: 'runtimepack.Microsoft.NETCore.App.Runtime.win-x64', version: '3.0.0'
    path: 'System.Private.DataContractSerialization.dll'
[Info  - 11:17:06] Connection to server got closed. Server will restart.
Error:
  An assembly specified in the application dependencies manifest (Microsoft.Python.LanguageServer.deps.json) was not found:
    package: 'runtimepack.Microsoft.NETCore.App.Runtime.win-x64', version: '3.0.0'
    path: 'System.Private.DataContractSerialization.dll'
[Info  - 11:17:06] Connection to server got closed. Server will restart.
Error:
  An assembly specified in the application dependencies manifest (Microsoft.Python.LanguageServer.deps.json) was not found:
    package: 'runtimepack.Microsoft.NETCore.App.Runtime.win-x64', version: '3.0.0'
    path: 'System.Private.DataContractSerialization.dll'
[Info  - 11:17:06] Connection to server got closed. Server will restart.
Error:
  An assembly specified in the application dependencies manifest (Microsoft.Python.LanguageServer.deps.json) was not found:
    package: 'runtimepack.Microsoft.NETCore.App.Runtime.win-x64', version: '3.0.0'
    path: 'System.Private.DataContractSerialization.dll'
[Error - 11:17:06] Connection to server got closed. Server will not be restarted.

```

</details>

It seems like... there is a missing .dll? :thinking:

**Comment by jakebailey** [comment]
It seems like your install got corrupted somehow. Can you try following the directions here to delete the language server and force a re-download? https://github.com/microsoft/vscode-python/issues/3977

**Comment by jmwielandt** [comment]
Bc some reason, i had 2 different versions installed.

![image](https://user-images.githubusercontent.com/37153467/66858916-a6738c00-ef60-11e9-9d6d-0278e439b507.png)

After deleting both folders and reinstalling the extension, now it works.

Thanks you a lot!

PS: should i close this issue?

**Comment by MikhailArkhipov** [comment]
Yes you can. Have several versions is normal I think - older version is not used. However, there may be bugs both in VSC and in the extension with downloads and deleting things. Say, something was locked for some reason so new components got placed over old set with some dlls not deleted...

**Comment by jakebailey** [comment]
I'll close this, but at some point we should be trying to pin down where these sporadic corruptions come from and how we can try to prevent them.
