### ISSUE TITLE
unexpected token ' '

### ISSUE THREAD

**Issue by kobenauf** [microsoft/python-language-server#1690]
Issue Type: <b>Bug</b>

I copy/pasted code from OneNote:
```
def create_countries_vocab_file(data_file, countries_vocab_file):
    with open(data_file) as f:
        o = json.load(f)
```
The editor marks this with many errors.  Here are the errors that occur on the line starting with `with open`:
```
unexpected token ' '
unexpected token 'open'
unexpected token ' '
unexpected token 'as'
unexpected token ' '
unexpected token '<newline>'
```
And here is the json related to the first of those errors:
```
{
	"resource": "/home/kobenauf/code/atg/loggedoutrecommender.kubeflow/preprocess/create_vocab_files.py",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "parser-16",
	"severity": 8,
	"message": "unexpected token ' '",
	"source": "Python",
	"startLineNumber": 5,
	"startColumn": 9,
	"endLineNumber": 5,
	"endColumn": 10
}
```
If I delete the space between the `with` and `open`, i.e. the first error, and retype a space, all the errors on that line go away.  Throughout all the code I copied, I have to manually delete and replace spaces before errors, and that causes the errors to go away.

Extension version: 2019.10.41019
VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.18999
Remote OS version: Linux x64 4.19.72-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (4.83GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/kobenauf/code/atg/loggedoutrecommender.kubeflow --remote=wsl+Ubuntu|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.72-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|Memory (System)|14.51GB (13.15GB free)|
|VM|0%|
</details>

**Comment by jakebailey** [comment]
When you copy out of OneNote, it's very likely that it is not copying "real" ASCII spaces to your clipboard. VS Code doesn't do any sort of conversion, so I think your only option is to find and replace them with real spaces.

I would imagine that python itself would fail if you tried to run that script as well.

**Comment by MikhailArkhipov** [comment]
What happens if you first paste into Notepad and then to VSC?

**Comment by jakebailey** [comment]
Closing; I don't think this is behavior we can control as it's up to the editor to interpret the clipboard (which on Windows consists of plain/rich text).
