### ISSUE TITLE
Can the language server be installed manually?

### ISSUE THREAD

**Issue by scrawfor** [microsoft/python-language-server#1698]
When downloading the language server my connection resets (I suspect due to a proxy).  However I am able to download the `Python-Language-Server-linux-x64.0.4.71.nupkg` file successfully after launch.  Can I install this file manually?

**Comment by jakebailey** [comment]
@karthiknadig Not sure this is an LS issue; the language server doesn't download itself; the extension does.

**Comment by brettcannon** [comment]
@scrawfor we don't support installing the language server manually. You can try downloading without HTTPS by setting `"http.proxyStrictSSL": false` and see if that solves the problem for you.

**Comment by showgood163** [comment]
I'm in the same situation. I cannot downloading the language server w/ or w/o SSL. And I'm sure that
 the proxy setting is correct as I can update other plugins. I can get the package file but don't know where to put for vs code to install it. Could you provide some insights?

**Comment by MikhailArkhipov** [comment]
Basically from https://github.com/microsoft/python-language-server/blob/master/CONTRIBUTING.md

- Open Python extension sources folder in VS Code (there is `Open Extensions Folder` command)
- Open Python extension folder
- Create `languageServer` folder in the extension folder.
- Rename `.nupkg` to `.zip`
- Unzip contents with folders to `languageServer`
- In VS Code set setting `python.downloadLanguageServer` to false.
- In VS Code set setting `python.jediEnabled` to false.

**Comment by showgood163** [comment]
Thank you @MikhailArkhipov !
I've tried this method yesterday and failed. Now it seems to work.
The problem is, the extracted files may not have the right access, e.g. `Microsoft.Python.LanguageServer` is not excutable.
`chmod +x Microsoft.Python.LanguageServer` fixed it.

**Comment by MikhailArkhipov** [comment]
Yes, that's true. Extension indeed is doing `chmod` after download.

**Comment by 1470391328** [comment]
thank you for your answer, it works for me in China

**Comment by Abdelrahman-shrif** [comment]
any one can help me to  `chmod +x Microsoft.Python.LanguageServer` . i don't know how it work
