### ISSUE TITLE
Intellisense tooltip applies text formatting on source code

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/python-language-server#17]
https://github.com/Microsoft/vscode-python/issues/2225

## Environment data

- VS Code version: 1.25.1
- Extension version (available under the Extensions sidebar): 2018.7.0
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.0
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
- Relevant/affected Python packages and their versions: NA

## Actual behavior

The tooltip applies text formatting to the displayed code, e.g. wrapping text in underscores italicizes it.
![image](https://user-images.githubusercontent.com/5912012/43048337-bdfd560a-8dee-11e8-9595-525cdfad07e0.png)

## Expected  behavior

The tooltip shows the code as it is written in the source.

## Steps to reproduce:
1. Use the mypy linter
2. Define a variable in a class, using `self`, with underscores in its name
3. Assign a type to the variable with a type hint
4. Hover over it to see the Intellisense tooltip

**Comment by jakebailey** [comment]
Fixed in #596 and others.

![image](https://user-images.githubusercontent.com/5341706/52750061-f9470f00-2f9f-11e9-9fb3-ada429e018bb.png)

Generated tooltips from signatures will be enclosed in literal blocks, and docstrings should be properly escaped.
