### ISSUE TITLE
Standalone executable?

### ISSUE THREAD

**Issue by astenman** [Microsoft/python-language-server#172]
Are there any plans for a standalone executable version of the server? Right now I do only get a dll when I'm building the package. It would be nice to be able to use it as an LSP backend in Emacs.

**Comment by MikhailArkhipov** [comment]
The dll is the executable that simply runs via dotnet.exe. If you want complete .NET independent package, you can make one via dotnet publish. You can probably also download our complete packages same way Python extension to VS Code does. URLs are all in the source. You may want to ask MIcrosoft legal about license terms.
