### ISSUE TITLE
How to write Doc String for Enums ?

### ISSUE THREAD

**Issue by dschiller** [microsoft/python-language-server#1725]
I want to get the Doc String for every single Enum Item like ``Timing.Setup.LoginDialog`` if I hover them ( in this case I want to hover ``LoginDialog`` and see ``30 Seconds - Maximum Time..`` ) in VSCode.

Here the Example Code:

```
from enum import Enum


class Timing:

    class Setup(Enum):
        Open = 300  # 5 Minutes - Maximum Time the Setup Application needs to open
        LoginDialog = 30  # 30 Seconds - Maximum Time the Fadein of the Login Dialog needs
```

**Comment by jakebailey** [comment]
Is there some specification as to how enum member comments are supposed to work? It's possible to show this sort of documentation on enum members, but we'd have to know the "right" way to do it.

**Comment by MikhailArkhipov** [comment]
https://stackoverflow.com/questions/50473951/how-can-i-attach-documentation-to-members-of-a-python-enum

https://stackoverflow.com/questions/50473951/how-can-i-attach-documentation-to-members-of-a-python-enum/50473952#50473952

I guess

**Comment by lord-aceldama** [comment]
i, too am hoping for this feature to be implemented. (not useful, just bumping because pep8)

**Comment by aahnik** [comment]
Docs written is comments, is not supported in many places like `mkdocstrings`.

I propose that the docstring should be written in a normal fashion, here is an example.

```python

class APIErrorCode(str, Enum):
    """Enumerate API error codes."""

    Unauthorized = "unauthorized"
    """The bearer token is not valid."""

    RestrictedResource = "restricted_resource"
    """Given the bearer token used, the client doesn't have permission to
    perform this operation."""

    ObjectNotFound = "object_not_found"
    """Given the bearer token used, the resource does not exist.
    This error can also indicate that the resource has not been shared with owner
    of the bearer token."""
```

**Comment by michaelbrundage** [comment]
> I propose that the docstring should be written in a normal fashion, here is an example.

This is already the syntax used in [PEP-0258](https://peps.python.org/pep-0258/#attribute-docstrings)

**Comment by judej** [comment]
Thank you for the report. This project is no longer active. If you are using the Python language server in VSCode, the language server you are using is Pylance and please the http://github.com/microsoft/pylance-release to report issues. 

If you are using Visual Studio, then, please use http://github.com/microsoft/PTVS to report issues.

thank you
