### ISSUE TITLE
unresolved import xxx even though set "python.autoComplete.extraPaths"

### ISSUE THREAD

**Issue by 520Chris** [microsoft/python-language-server#1726]
LSP reports "unresolved import utils", even though I set "python.autoComplete.extraPath"

![image](https://user-images.githubusercontent.com/39628662/67855832-2fd4b200-fb4e-11e9-938f-16a13706f303.png)
![image](https://user-images.githubusercontent.com/39628662/67856039-a5d91900-fb4e-11e9-8961-f79770b1e3cb.png)

setting.json
```
{
    "files.watcherExclude": {
        "**/sysu_dataset/**": true,
    },
    "python.pythonPath": "/home/zjli/anaconda3/envs/person_search/bin/python",
    "python.autoComplete.extraPaths": [
        "./person_search_2/utils",
    ],
    "python.linting.pylintEnabled": true,
    "python.linting.enabled": false
}
```

- Language Server version: Latest
- OS and version: win10
- Python version (& distribution if applicable, e.g. Anaconda): Anaconda

## Expected behaviour

No warning

## Actual behaviour

LSP reports "unresolved import utils"

## Logs

```
[Info  - 7:33:31 PM] Analysis restarted.
[Info  - 7:41:30 PM] Reloading modules... 
[Info  - 7:41:30 PM] GetCurrentSearchPaths /home/zjli/anaconda3/envs/person_search/bin/python 
[Info  - 7:41:30 PM] Analysis caching mode: None.
[Info  - 7:41:31 PM] Interpreter search paths:
[Info  - 7:41:31 PM]     /home/zjli/anaconda3/envs/person_search/lib/python3.6
[Info  - 7:41:31 PM]     /home/zjli/anaconda3/envs/person_search/lib/python3.6/lib-dynload
[Info  - 7:41:31 PM]     /home/zjli/anaconda3/envs/person_search/lib/python3.6/site-packages
[Info  - 7:41:31 PM] User search paths:
[Info  - 7:41:31 PM]     /home/zjli/Desktop/213project/person_search_2/utils
[Info  - 7:41:31 PM] done.
[Info  - 7:41:31 PM] Analysis restarted
```

**Comment by 520Chris** [comment]
It is strange that the warning has gone when I set
```
"python.autoComplete.extraPaths": [
        "./person_search_2",
    ],
```
Can I set `python.autoComplete.extraPaths` to `./person_search_2/utils` instead of `./person_search_2`? I am lookinng forward your response, thank you very much.

**Comment by 520Chris** [comment]
@jakebailey Thanks for your response. I have read the TROUBLESHOOTING.md
I am so sorry that my description is not clear.
![image](https://user-images.githubusercontent.com/39628662/67924015-6233ed00-fbea-11e9-934b-5a7f0548e7eb.png)
I want to import the module named `utils` under the folder named `utils`.
According to https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#unresolved-import-warnings, I think it's enough to set `python.autoComplete.extraPaths` to `./person_search_2/utils`.
But unfortunately, it does not work, I have to set `python.autoComplete.extraPaths` to `./person_search_2`, that is **the parent folder of the parent folder**.
Is it by design? I am looking forward to your response, thank you.

**Comment by jakebailey** [comment]
Looking at your code, you write `import utils.utils`import utils.utils, which means that the parent directory of the first `utils`, i.e. `person_search_2`, is what you need to be adding to extraPaths. You don't want to use `person_search_2/utils` because you're not doing a plain `import utils`.

**Comment by 520Chris** [comment]
Thank you very much. Now I know where I was wrong.
I am sorry to waste your time on the fool question.
Greate repo, greate maintainer!
