### ISSUE TITLE
Got message "Hash code changed when merging AnalysisValues" with debug build

### ISSUE THREAD

**Issue by lostmsu** [Microsoft/python-language-server#173]
I wonder if it is an indication of some internal error potentially corrupting analysis?

It happens when I try to analyze installed tensorflow package. (e.g. pip install tensorflow-gpu, used version 1.10, then analyze site-packages/tensorflow).

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/python-language-server/pull/169 fixed it

**Comment by lostmsu** [comment]
@MikhailArkhipov I synced within the last 24 ours, it still hits it.
