### ISSUE TITLE
Unable to open a file in a egg file

### ISSUE THREAD

**Issue by asierralozano** [microsoft/python-language-server#1731]
## Environment data

- Language Server version: 0.4.71 
- OS and version: CentOs 7
- Python version (& distribution if applicable, e.g. Anaconda): 2.7.14 64-bit

## Expected behaviour

Get the Go To Definition working with egg files

## Actual behaviour

If I use the Go To Definition function with a module that it is inside an egg file, I'm getting the following error:
`Unable to open 'test.py': Unable to read file (Unknown (FileSystemError): Error: ENOTDIR: not a directory, stat '/home/users/alberto/testEnv/testPackage-py2.7.egg/myProject/foo/test.py').`

I can import that file without problems within a Python Terminal by:
`from myProject.foo import test`

If you need more info, please, let me know! :)

Thanks!

**Comment by jakebailey** [comment]
Does completion/documentation/etc work with the info that comes out of the module, or do you only have an issue when you try to goto definition?

Where does this error show, in the logs or as a UI element in VS Code?

**Comment by asierralozano** [comment]
> Does completion/documentation/etc work with the info that comes out of the module, or do you only have an issue when you try to goto definition?

I've double checked, and any of those elements works.


> Where does this error show, in the logs or as a UI element in VS Code?

A notification in the VsCode's lower right edge is appearing, just like a normal VSCode Notification :)

**Comment by jakebailey** [comment]
Right, so this is more of a VS Code thing than a language server thing. We correctly handle the egg files by analyzing their contents, but since they're not "real files", when we return the path to the file internal to the egg, VS Code doesn't know what to do with it because it doesn't look into egg files.

I'm not sure if there's a way to make the editor able to open these files, but we could at least recognize that a file is within an egg/zip and not offer a location for it to prevent the editor from trying and failing.

**Comment by MikhailArkhipov** [comment]
We could probably unzip file into temp before returning reference URI. Could then delete it when `didClose` comes.

**Comment by jakebailey** [comment]
That might cause other issues, because it's a file with a different location, which we'd then start to analyze (and it would exist in the wrong place and start getting import resolution problems).

**Comment by asierralozano** [comment]
Should I create this ticket in the VSCode Python extension repo then?

**Comment by MikhailArkhipov** [comment]
It is not an extension issue it is that VS Code itself is not drilling into egg/zip files for content. You can open ticket there I guess.

**Comment by asierralozano** [comment]
Sweet! Thanks guys, and sorry for the sound made here! :)

**Comment by jakebailey** [comment]
Just to shorten this link chain if anyone finds this issue: microsoft/vscode#75559
