### ISSUE TITLE
Import errors within try/except blocks

### ISSUE THREAD

**Issue by max-sixty** [microsoft/python-language-server#1733]
## Environment data

- Language Server version: Microsoft Python Language Server version 0.4.81.0   
- OS and version: macOS 10.15 (19A602)
- Python version (& distribution if applicable, e.g. Anaconda): '3.7.4 (default, Sep  7 2019, 18:27:02) \n[Clang 10.0.1 (clang-1001.0.46.4)]'

## Expected behaviour

We have optional dependencies that are imported in try-except blocks, so they're not errors. python-language-server raises a warning that they're unresolvable. 
I can understand this might be difficult in static analysis. That said, other (lesser) tools do evaluate those as OK, and there is a simple rule that if `ImportError`s are caught, they're not errors.

## Actual behaviour

unresolved import 'cdms2'

![image](https://user-images.githubusercontent.com/5635139/67986978-b054ea80-fc02-11e9-9d70-2b2ac37f21c4.png)

Reproducible from [`dataarray.py` on xarray master](https://github.com/pydata/xarray/blob/master/xarray/core/dataarray.py), if anyone wants a full repro

## Logs

https://gist.github.com/max-sixty/630b88f44038174dc46229edc51734b9

Thank you!

**Comment by max-sixty** [comment]
I see that https://github.com/microsoft/python-language-server/issues/1663 was a similar issue. Feel free to close. Though, again, while not simple, lesser tools do manage.

Thanks again for the awesome tool!

**Comment by jakebailey** [comment]
For our purposes, this would be about the same as #1663, yeah. `# noqa` should be working, however.

**Comment by MikhailArkhipov** [comment]
Since static analysis doesn't really know which path code will take on a particular version of Python, using #noqa is probably the only option here. Closing.
