### ISSUE TITLE
Specialize collections.namedtuple

### ISSUE THREAD

**Issue by lostmsu** [Microsoft/python-language-server#174]
I noticed PLS has a specialization for `typing.NamedTuple`, which is, essentially, `collections.namedtuple` under the hood. Should not be hard to add handling for the later.

I'd be interested on adding a specialization for `collections.namedtuple`, but I'd like to understand how to add new specializations. Initially, I though it will be as hard as creating a custom `CollectionsModuleInfo: BuiltinModule` similar to `TypingModuleInfo`, but then I found also `TypingTypeInfo` and its `Finalize` and `TypingTypeInfoFinalizer`, and a seemingly simple tasks seems convoluted now.

I'd also gladly work on making this exact task simpler in the future.

BTW, here's a commit, that adds a test case for the desired behavior: https://github.com/losttech/PLS/commit/0899a192b37fd5c005bfb88225261c7d43ae70af

**Comment by MikhailArkhipov** [comment]
Yes https://github.com/Microsoft/python-language-server/issues/15.

**Comment by lostmsu** [comment]
Sorry, obviously a duplicate then.
Still interested in how to work with it.

**Comment by MikhailArkhipov** [comment]
Most probably no longer applies after https://github.com/Microsoft/python-language-server/issues/425
