### ISSUE TITLE
Python incorrect linting in VSCode

### ISSUE THREAD

**Issue by SIGUSR97** [microsoft/python-language-server#1743]
## Environment data

- VS Code version: 1.39.2
- Extension version (available under the Extensions sidebar): 2019.10.44014
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): 3.8
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A

## Expected behaviour

![image](https://user-images.githubusercontent.com/52692296/68067629-19646b80-fd85-11e9-9ec8-28b66a25a542.png)

## Actual behaviour

![image](https://user-images.githubusercontent.com/52692296/68067625-fcc83380-fd84-11e9-9f71-2c8761567959.png)

I definitely have the module installed and the code runs alright, but this error in linting is kind of visually disturbing.

**Comment by jakebailey** [comment]
#955 is the message showing for `process`, however not finding `fuzzywuzzy` is another issue and I'd say to check https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#filing-an-issue first.

**Comment by jakebailey** [comment]
https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#unresolved-import-warnings is what I meant to link.

**Comment by MikhailArkhipov** [comment]
If module is not found, with https://github.com/microsoft/python-language-server/pull/1706 LS is not considering imported variable as undefined. It is probably not yet in stable.

**Comment by MikhailArkhipov** [comment]
Closing per https://github.com/microsoft/python-language-server/pull/1706. Feel free to reopen if you still see it. Thanks.
