### ISSUE TITLE
unresolved import unable to resolve local imports with IntelliCode/Python Language Server

### ISSUE THREAD

**Issue by omartin2010** [microsoft/python-language-server#1744]
Issue Type: <b>Bug</b>

When I enable the Microsoft Language Server (required for IntelliCode), then my local imports (for packages not pip installed), I get the error message that they are unresolved, and therefore I have many warnings in my files. 

Extension version: 2019.11.41015-dev
VS Code version: Code - Insiders 1.40.0-insider (93ee2fc3121b7f66ddf568c051f3bfff7db8d618, 2019-10-31T05:42:33.138Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (6.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jakebailey** [comment]
Check out https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#filing-an-issue first.

**Comment by omartin2010** [comment]
Good point, I've not been very vocal on the requirements for filing an issue and found the issue to be related to the [root of the folder I'm working on](https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#unresolved-import-warnings). Thanks for pointing me in the right direction...

**Comment by omartin2010** [comment]
however I thinks if it works with the jedi language server, it should work without adding a path statement to this one...

**Comment by jakebailey** [comment]
Actually, that's my bad, I linked the wrong section of the document. This issue was transferred, so I only meant to link you to https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#unresolved-import-warnings

**Comment by MikhailArkhipov** [comment]
@omartin2010 - it depends how loose importing system should go. Jedi is more relaxed than the Python spec. But at the same time this means code may or may not work at runtime.
