### ISSUE TITLE
WIKI documentation change for version download 

### ISSUE THREAD

**Issue by kis87988** [microsoft/python-language-server#1749]
## Environment data

- Wiki Documentation: 
Versioning and download chnnels
https://github.com/microsoft/python-language-server/wiki/Versioning-and-download-channels
## Expected behaviour
```mk
"python.insidersChannel": "off"

"python.insidersChannel": "weekly"

"python.insidersChannel": "daily"
```

## Actual behaviour
```mk
"python.analysis.downloadChannel": "stable"

"python.analysis.downloadChannel": "beta"

"python.analysis.downloadChannel": "daily"
```

## Logs

None

## Code Snippet / Additional lnformation

None

**Comment by jakebailey** [comment]
This isn't a documentation issue. The language server is versioned, released, and downloaded separately from the extension's versioning/releases. The top three are for the extension, the bottom three are for the language server. The default in the extension is "daily", but other extension insiders channels may choose the beta LS version.

**Comment by kis87988** [comment]
I see. How can I make sure it downloads language server **daily**?

**Comment by jakebailey** [comment]
Set `"python.analysis.downloadChannel": "daily"` and the extension will always download the daily build, and check for updates more frequently.
