### ISSUE TITLE
autocomplete doesn't work for non-ASC identifiers on Win7, and some cases on Mac

### ISSUE THREAD

**Issue by nobodxbodon** [microsoft/python-language-server#1751]
## Steps to cause the bug to occur
1. Below are the sample codes I used to reproduce the issue:
```
for 名字 in range(1, 10):
    # 有补全（Mac下），输入”名“
    print(名字)
```
When keying in the parameter of `print`, typing in the first character should trigger auto-complete, as the ASC identifier works.

## Actual & Expected behavior

This `名字` variable triggers auto-complete under Mac:
![中文补全Python_Mac成功](https://user-images.githubusercontent.com/392497/67903225-4405b880-fb28-11e9-8aba-130d0516053d.gif)
However a a different name `序号` doesn't work under Mac:
![中文补全Python_Mac失败](https://user-images.githubusercontent.com/392497/67903275-60095a00-fb28-11e9-9a52-f769ea402808.gif)

Additionally, neither case works under Windows 7.

### Your Jupyter and/or Python environment
*Please provide as much info as you readily know*
- **Jupyter server running:**                       Local | Remote | N/A
- **Extension version:**                               2019.10.44104-xxx
- **VS Code version:**                                1.39.2
- **Setting python.jediEnabled:**               true | false
- **Python and/or Anaconda version:**     3.7.3 under Mac, 3.6.5 under Win7
- **OS:**                                                     Windows | Mac
- **Virtual environment:**                           N/A

## Developer Tools Console Output

None.

**Comment by jakebailey** [comment]
I'm not sure that this is an LS issue as much as it would be a VS Code issue to do with when they choose to send the completion request in this scenario. For example, I can hit Ctrl-Space to manually trigger a completion request, and we behave as expected.

@xgdgsc If you hit Ctrl+Space after typing the first character, does the expected thing happen?

![image](https://user-images.githubusercontent.com/5341706/68233985-2ebfdc80-ffb5-11e9-86be-ac7fea1f9f8d.png)

**Comment by MikhailArkhipov** [comment]
I wonder what happens with the same character in, say, C# or C++.

**Comment by jakebailey** [comment]
I know that the input method in the issue isn't the Wubi method (I think this is macOS's pinyin mode), but it may be similar to microsoft/vscode#83428 as the input method replaces written text with another string.

**Comment by nobodxbodon** [comment]
@MikhailArkhipov TypeScript works under Mac for both cases as below, IIH.
名字：
![TS_名](https://user-images.githubusercontent.com/392497/68234883-10f37700-ffb7-11e9-8e37-f18e390955c5.gif)
序号：
![TS_序](https://user-images.githubusercontent.com/392497/68234897-1650c180-ffb7-11e9-9fe2-42ebfe28feb2.gif)

@jakebailey I'm using a third-party pinyin input method (Sogou), but I can test with other input method.

**Comment by jakebailey** [comment]
TS is somewhat special as it ships with VS Code (I think they're able to do things outside the LSP), so there might be a difference there.

**Comment by nobodxbodon** [comment]
@jakebailey thanks for informing. C++ seems to have the same issue under Mac (`序` doesn't get auto-completion):
![Cpp_名_序](https://user-images.githubusercontent.com/392497/68236525-2cac4c80-ffba-11e9-9659-4207201c91a2.gif)

Extension: ms-vscode.cpptools 0.25.1

**Comment by jakebailey** [comment]
Thanks for checking.

You may want to respond on microsoft/vscode#83428 or create a new issue on the VS Code repo with your info (and potentially a link here), as this seems to be a VS Code bug involving input methods that do text replacement, rather than something language specific that we can handle on our end.

**Comment by jakebailey** [comment]
I've linked this thread on their issue for more datapoints, but it's going to have to be a VS Code fix.
