### ISSUE TITLE
Endless loop in analysis with caching set to "system"

### ISSUE THREAD

**Issue by luabud** [microsoft/python-language-server#1758]
Sorry if it's a dupe 😁
## Environment data

- Language Server version: 0.4.96.0
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.3, venv

Background analysis gets stuck in an endless loop:

![LSloop](https://user-images.githubusercontent.com/45497113/68321706-08fb0c00-0077-11ea-82b8-2d159d0b7c3b.gif)

Packages installed in this environment: 

atomicwrites==1.3.0
attrs==19.2.0
Click==7.0
colorama==0.4.1
Flask==1.1.1
importlib-metadata==0.23
itsdangerous==1.1.0
Jinja2==2.10.1
MarkupSafe==1.1.1
more-itertools==7.2.0
numpy==1.17.3
packaging==19.2
pluggy==0.13.0
py==1.8.0
pyparsing==2.4.2
pytest==5.2.1
PyYAML==5.1.2
six==1.12.0
wcwidth==0.1.7
Werkzeug==0.15.6
zipp==0.6.0

**Comment by jakebailey** [comment]
Known issue, yes. Disable caching (or remove your config for it) as it's currently broken.

**Comment by jakebailey** [comment]
Leaving open, since we don't have a tracking issue for this yet.

**Comment by jakebailey** [comment]
Opened #1761 to disable caching altogether regardless of user setting, since looping is worse than a slow analysis (until we fix it).

**Comment by jakebailey** [comment]
Pushed to daily and beta, so the looping should go away for everyone on those channels. Stable never had this bug, so is safe (but we'll be upgrading stable soon anyhow, regardless of the status of caching, since stable never had it enabled by default).
