### ISSUE TITLE
IDocumentAnalysis.GlobalScope being null

### ISSUE THREAD

**Issue by heejaechang** [microsoft/python-language-server#1772]
check whether IDocumentAnalysis.GlobalScope should be never null and have EmptyGlobalScope (https://github.com/microsoft/python-language-server/blob/master/src/Analysis/Ast/Impl/Values/EmptyGlobalScope.cs) or it is fine to have null.

related to https://github.com/microsoft/python-language-server/pull/1770

**Comment by jakebailey** [comment]
It may also be the case that #1770 fixed an issue where the analysis itself was null, as that was also not checked.

**Comment by heejaechang** [comment]
good point. I will check that as well.
