### ISSUE TITLE
unresolved import from project root to ./src/... folder

### ISSUE THREAD

**Issue by wy193777** [microsoft/python-language-server#1789]
I already set up `PYTHONPATH=./ENV` on `.env` file. I also added `"python.autoComplete.extraPaths": ["./src"],` to `setting.json`, but still got no luck.

## Environment data

- Language Server version: 0.4.71.0   
- OS and version: Ubuntu 19.10
- Python version (& distribution if applicable, e.g. Anaconda): 3.7

## Expected behaviour

no unresolved imports errot

## Actual behaviour

There are errors.

## Logs

```
[Info  - 1:45:52 PM] Microsoft Python Language Server version 0.4.71.0
[Info  - 1:45:52 PM] Workspace root: /home/shenghang/code/jama-export-import-tool
[Info  - 1:45:52 PM] Analysis cache path: /home/shenghang/.cache/Microsoft/Python Language Server
[Info  - 1:45:53 PM] GetCurrentSearchPaths /home/shenghang/.cache/pypoetry/virtualenvs/jamaofflinetool-VIIe-dtA-py3.7/bin/python 
[Info  - 1:45:53 PM] Interpreter search paths:
[Info  - 1:45:53 PM]     /home/shenghang/.pyenv/versions/3.7.3/lib/python3.7
[Info  - 1:45:53 PM]     /home/shenghang/.pyenv/versions/3.7.3/lib/python3.7/lib-dynload
[Info  - 1:45:53 PM]     /home/shenghang/.cache/pypoetry/virtualenvs/jamaofflinetool-VIIe-dtA-py3.7/lib/python3.7/site-packages
[Info  - 1:45:53 PM]     /home/shenghang/.cache/pypoetry/virtualenvs/jamaofflinetool-VIIe-dtA-py3.7/src/swagger-client
[Info  - 1:45:53 PM] User search paths:
[Info  - 1:45:53 PM]     /home/shenghang/code/jama-export-import-tool/src
[Info  - 1:45:54 PM] Initializing for /home/shenghang/.cache/pypoetry/virtualenvs/jamaofflinetool-VIIe-dtA-py3.7/bin/python
```

## Code Snippet / Additional lnformation

![image](https://user-images.githubusercontent.com/2449450/68714814-7c0ff100-0555-11ea-8af5-ebf77a4fb97a.png)

![image](https://user-images.githubusercontent.com/2449450/68714853-93e77500-0555-11ea-8b3b-010234d3f9fc.png)

**Comment by jakebailey** [comment]
Adding `src` changes your import root to inside `src`, so an import that looks like `import src.something` won't work because you have a `src` directory. We actually detect `src` and expect that you're not prefixing your imports with `src.` (because that's really strange).

If you really want `src.` imports to work, then you want to not set `extraPaths` and instead disable our auto-detection by setting:

```
"python.analysis.autoSearchPaths": false
```

Same as #1615.

**Comment by wy193777** [comment]
Thanks, that's very helpful. I tried to change the `./src` folder name to other names but VSCode doesn't eliminate all errors right after I changed folder name.

**Comment by jakebailey** [comment]
Yes, renaming is a bit suspect in the LSP in general, especially renaming whole directories. If you make a big change it's best to reload to ensure that we don't think the modules are still there.
