### ISSUE TITLE
"unresolved import" issue again

### ISSUE THREAD

**Issue by schlamar** [microsoft/python-language-server#1791]
## Environment data

- Language Server version: 0.4.71.0
- OS and version: Windows 7
- Python version (& distribution if applicable, e.g. Anaconda): 2.7.17

## Expected behaviour

No issues on standard library modules like "operator" and "cPickle"

## Actual behaviour

Mentioned modules get sometimes reported as "unresolved import".

## Further information / possible workaround
I recently updated Python to 2.7.17 (from 2.7.15) and these issues popped up again. After I deleted all files from the cache (C:\Users\<uers>\AppData\Local\Microsoft\Python Language Server) everything seems fine. So this could be some cache invalidation issue. This might explain #1520 where this issue was gone after the path to the modules changed by using a symlink.

**Comment by jakebailey** [comment]
Can you try with the beta build (https://github.com/microsoft/python-language-server/wiki/Versioning-and-download-channels), and provide the logs the template requires 9https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#filing-an-issue)? The trace logs would provide insight to why imports aren't being resolved.

**Comment by schlamar** [comment]
@jakebailey As this issue is gone (for now) after deleting the cache I cannot provide trace logs. I have seen something like "cache file cannot be read" in the logs but I cannot remember in detail.

**Comment by MikhailArkhipov** [comment]
Please reopen then if it happens again.
