### ISSUE TITLE
Implement detection and reporting of unused imports

### ISSUE THREAD

**Issue by MikhailArkhipov** [microsoft/python-language-server#18]
https://github.com/Microsoft/vscode-python/issues/43
https://github.com/Microsoft/PTVS/issues/254

**Comment by MikhailArkhipov** [comment]
Adding some estimate. @AlexanderSher  - it needs further clarification.

**Comment by DonJayamanne** [comment]
Blocked by https://github.com/Microsoft/language-server-protocol/issues/500

**Comment by psarka** [comment]
The issue https://github.com/microsoft/language-server-protocol/issues/500 seems to be closed now, so should this be unblocked?

(Anxiously waiting for this feature!)

**Comment by jakebailey** [comment]
Not until LSP 3.15 is released, and then not until there's a client implementation for the feature.

https://github.com/microsoft/language-server-protocol/commit/4e17257ee79f0fa4658c988621e4811d6e658317

**Comment by micimize** [comment]
Would this include optional removal of said imports? Currently I'm using `autoflake` as a task which I then [trigger on save](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.triggertaskonsave), but this results in some "content of the file is newer" complaints.

<details>
<summary>task.json#tasks entry</summary>

```json
    {
      "type": "process",
      "label": "autoflake.removeUnusedImports",
      "command": "${command:python.interpreterPath}",
      "args": [
        "-m",
        "autoflake",
        "-i",
        "--remove-all-unused-imports",
        "${file}"
      ]
    },
```

</details>

**Comment by debonte** [comment]
@micimize what language server are you using? If you're using Pylance, head over to Pylance's issue tracker at https://github.com/microsoft/pylance-release/issues

**Comment by judej** [comment]
Thank you for the report. This project is no longer active. If you are using the Python language server in VSCode, the language server you are using is Pylance and please the http://github.com/microsoft/pylance-release to report issues. 

If you are using Visual Studio, then, please use http://github.com/microsoft/PTVS to report issues.

thank you
