### ISSUE TITLE
Reload loop when symlink in workspace path  

### ISSUE THREAD

**Issue by kuelumbus** [microsoft/python-language-server#1800]
## Environment data
Version: 1.41.0-insider
Commit: bf7d03bf88732af0b46e473c663c49e18e839f9c
Date: 2019-11-15T05:32:36.095Z
Electron: 6.1.4
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.0.0-36-generic snap

- Language Server version: Microsoft Python Language Server version 0.4.121.0 
- OS and version: Ubuntu 18.04 
- Python version (& distribution if applicable, e.g. Anaconda): python 3.7

## Expected behaviour

Finish analysis.

## Actual behaviour

LS gets stuck in reload loop when symlink in workspace path. Probably only relevant for Linux systems. 

### Reload loop

`ln -sr  /data/chris /home/chris/data`

```
[Info  - 3:59:15 PM] Workspace root: /home/chris/data/ml/Net
[Info  - 3:59:15 PM] GetCurrentSearchPaths /usr/bin/python3.7 
[Info  - 3:59:15 PM] Interpreter search paths:
[Info  - 3:59:15 PM]     /usr/lib/python3.7
[Info  - 3:59:15 PM]     /usr/lib/python3.7/lib-dynload
[Info  - 3:59:15 PM]     /home/chris/autocomplete
[Info  - 3:59:15 PM]     /home/chris/.local/lib/python3.7/site-packages
[Info  - 3:59:15 PM]     /data/chris/ml/Net
[Info  - 3:59:15 PM]     /usr/local/lib/python3.7/dist-packages
[Info  - 3:59:15 PM]     /usr/lib/python3/dist-packages
```

### No reload loop
```
[Info  - 8:12:55 PM] Workspace root: /data/chris/ml/Net
[Info  - 8:12:55 PM] GetCurrentSearchPaths /usr/bin/python3.7 
[Info  - 8:12:56 PM] Interpreter search paths:
[Info  - 8:12:56 PM]     /usr/lib/python3.7
[Info  - 8:12:56 PM]     /usr/lib/python3.7/lib-dynload
[Info  - 8:12:56 PM]     /home/chris/autocomplete
[Info  - 8:12:56 PM]     /home/chris/.local/lib/python3.7/site-packages
[Info  - 8:12:56 PM]     /usr/local/lib/python3.7/dist-packages
[Info  - 8:12:56 PM]     /usr/lib/python3/dist-packages
```

**Comment by jakebailey** [comment]
The watcher likely needs to resolve symlinks before it passes things into filesystem globbing.

**Comment by MikhailArkhipov** [comment]
File watch turned off by default in https://github.com/microsoft/python-language-server/pull/1841. 
LS 0.5.10+
