### ISSUE TITLE
Support function overload with Literal attributes

### ISSUE THREAD

**Issue by vemel** [microsoft/python-language-server#1802]
Return types for overloaded functions are incorrect for `Literal` type in function arguments.

Overload for non-literal types works great, so it would be great to have type discovery for `Literal` as well.

`mypy` handles this case correctly, so probably it could be used somehow. I am not sure if hover popup uses info from `mypy`.

### Steps to reproduce

1) Install `mypy`
2) Insert this code to a new file 

```python
from typing import Any
from typing_extensions import overload, Literal

@overload
def test(value: Literal["a"]) -> int:
    ...


@overload
def test(value: Literal["b"]) -> bool:
    ...


def test(value: Any) -> Any:
    if value == "a":
        return 5

    return True


test_a = test("a")
test_b = test("b")
```

3) Hover `test_a` and `test_b` variables to check types.

### Expected result

```
test_a: int
test_b: bool
```

### Actual result

```
test_a: bool
test_b: bool
```

**Comment by jakebailey** [comment]
Known issue, we don't support Literal (#1648), so our overload choice may not work.

**Comment by vemel** [comment]
@jakebailey thank you for additional info, it was hard for me to find the source of issue. I can take a look at it.

**Comment by jakebailey** [comment]
FWIW the new LS we released today has full typing support: https://devblogs.microsoft.com/python/announcing-pylance-fast-feature-rich-language-support-for-python-in-visual-studio-code/

**Comment by vemel** [comment]
Since the main LS is Pylance/Pyright, I think I can close this issue one year later :)
