### ISSUE TITLE
Using .so file in python project breaks Intellisense

### ISSUE THREAD

**Issue by seanngpack** [microsoft/python-language-server#1808]
## Environment data

- VS Code version: 1.40.1
- Extension version (available under the Extensions sidebar):2019.11.49689
- OS and version: macOS Catalina
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.4
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv and virtualenvwrapper
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): nope

## Expected behaviour

Intellisense & autocomplete should work normally

## Actual behaviour

Modules that import .so libraries do not have intellisense/autocomplete working

## Steps to reproduce:
I am using pyrealsense2 to demo this:

- build pyrealsense2 from source
- drag .so files to python main project root
- pip install -e .
- create new module `test.py` and at top `import pyrealsense2`
- autocomplete no longer works

**Comment by jakebailey** [comment]
We only support compiled modules which are explicitly libraries, i.e. those that exist outside the workspace. This is by design. Supporting this would be an enhancement, but we don't want to be executing user project code to inspect it.
