### ISSUE TITLE
Pandas dataframe plot showing up as "CachedAccessor"

### ISSUE THREAD

**Issue by Econ808** [microsoft/python-language-server#1810]
**Issue:** When using "trigger parameter hints" on an assigned `dataframe` with the `plot()` module no parameters show up

![image](https://user-images.githubusercontent.com/36441764/69424626-648cf100-0d29-11ea-9641-979ca9e121ea.png)

![image](https://user-images.githubusercontent.com/36441764/69424649-753d6700-0d29-11ea-9ae9-9d74f205b228.png)

**Expected behaviour**:  Show "signature". In the sample below I've used jupyterlab to print what I would expect as the shown parameters:
![image](https://user-images.githubusercontent.com/36441764/69425502-4de79980-0d2b-11ea-9c74-246a194a6aae.png)

**Comment by jakebailey** [comment]
Are you sure `pd.DataFrame.plot()` should work? `DataFrame` is a type, not an instance. I wouldn't expect us to work on that, since the function isn't on the class but an instance of the class.

**Comment by yunyoulu** [comment]
`pd.DataFrame.plot()` is a member dynamically assigned in `frame.py`@Ln7948 in Pandas 0.24.2.

I don't expect VSCode to show anything related to plotting, but it should have shown the docstring of the `pandas.core.accessor.CachedAccessor` class as long as it knows `plot` is a `CachedAccessor`.

However, the problem is that nothing is displayed, as indicated in the first screenshot.

**Comment by yunyoulu** [comment]
By the way, when I move my mouse cursor onto `CachedAccessor`, the hover tip says 'Code analysis is in progress...' while there is nothing in progress shown in the status bar.
![image](https://user-images.githubusercontent.com/7137182/70119687-deca4900-1638-11ea-9492-c98e6dd0f6ea.png)

**Comment by Econ808** [comment]
I'm closing this issue, as it probably relates more to the python.dataScience repository.

**Comment by yunyoulu** [comment]
@Econ808 I don't think it's unrelated to the language server. Why should Python DataScience cause code analysis to stuck forever?

**Comment by wookayin** [comment]
Is there any way for pyright or python-language-server to make documentation or function signature of lazy-loaded methods be displayed in LSP?
