### ISSUE TITLE
Add a flag to disable analysis

### ISSUE THREAD

**Issue by uriva** [microsoft/python-language-server#1814]
Hi, for me analysis running in the background means I can't work (the computer becomes too sluggish).

Can we have a flag that disables it?

I don't want to disable the entire extension because I need formatting.

(if this already exists - I couldn't find it...)

**Comment by jakebailey** [comment]
The analysis is everything the language server does. We would rather fix the underlying problems related to your issues (#1807) than offer a toggle to disable everything.

An option to not have any language features would be better asked on the extension's issue tracker.

You can still enable `jedi` in the extension as well by setting `"python.jediEnabled": true`.
