### ISSUE TITLE
Unable to open 'python3.pyi': unable to read file 

### ISSUE THREAD

**Issue by thavlik** [microsoft/python-language-server#1816]
Given the following imports from Tensorflow 2.0:
```
from tensorflow.keras.layers import Conv2D, Conv1D, Conv2DTranspose, Flatten, Dense, Reshape, Lambda, Permute, Activation, Flatten, Dropout, Concatenate, Input, InputLayer
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping, TensorBoard
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.models import Sequential, Model
```
Go To Definition on **any** of the imported items (e.g. Conv2D) produces the following error message in the bottom right hand corner of the window, then does nothing:
```
Unable to open 'python3.pyi': Unable to read file (Error: File not found (/Users/thomashavlik/Library/Caches/Microsoft/Python Language Server/stubs.v4/SwD-VoYLOHwzYthhqh16DEHw0XO2V4x9eu3sm2QM9OA=/python3.pyi)).
```

## Environment data

- VS Code version: 1.39.2
- Extension version (available under the Extensions sidebar): 2019.11.50794
- OS and version: Mac OS 10.15.1
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.5
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Relevant/affected Python packages and their versions: tensorflow 2.0.0
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): Broken for both Jedi and MS Language Server

## Expected behaviour

It should open the definition in the python source

## Actual behaviour

An error dialog appears in the bottom right hand corner of VS Code's main window. 

## Logs
No logs from console or output

**Comment by jakebailey** [comment]
There may have been some changes to goto-def that are leading to unresolved things going to the builtins, but #818 is the issue for tensorflow 2.0 (which has made some pretty impactful changes that make static analysis difficult).

**Comment by MikhailArkhipov** [comment]
Folding into #1563

**Comment by MikhailArkhipov** [comment]
This specific case is actually https://github.com/microsoft/python-language-server/issues/818. TF 2.0 has custom import system that LS is unable to handle. Goto definition issue is #1563 that is about attempt to navigate to an unknown item. Fixing #1563 will not make navigation work in the code above b/c custom import won't work anyway per #818.
