### ISSUE TITLE
Missing completion results  (but not docstrings) when indexing numpy top level modules

### ISSUE THREAD

**Issue by mjlbach** [microsoft/python-language-server#1819]
- Language Server version: 0.4.114
- OS and version: macOS Catalina 10.15/Linux (Fedora 30)
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.x/3.7.X

Neovim has added a built-in LSP support, and I've been working on getting the Microsoft Python Language Server working with it (see: https://github.com/neovim/nvim-lsp/pull/57). I've had issues with numpy printing docstrings in the MS-PYLS logs and failing to provide completion results, whereas other modules seem to work fine.

## Expected behaviour

MS-pyls provides numpy completion results. 

## Actual behaviour

MS-pyls yields module docstrings for numpy. 

## Logs
See the formatted output log [here](https://www.dropbox.com/s/2abv7bl2w8lbn79/vim-lsp-formatted.log?dl=0)

**Comment by jakebailey** [comment]
I guess I'm not seeing any issue in those logs. Those logs show a completion response, and each completion item includes a documentation field which contains the docstring for the item that the completion represents. "stdout" is the place where the LSP operates, so docstrings being in stdout seems normal (because the docstrings are a part of a usual response).

Numpy itself wouldn't be printing anything. Any python code we end up executing wouldn't be able to print to the LS's own stdout (if that were the case, we'd be fundamentally broken).

**Comment by mjlbach** [comment]
Ah sorry! I misread them (still an LSP novice). Apparently submodules are being completed but the top-level namespace isn't...
<img width="1392" alt="Screen Shot 2019-11-28 at 11 05 33 PM" src="https://user-images.githubusercontent.com/13316262/69850273-c79feb80-1233-11ea-8a52-46b0f5b6ed67.png">

**Comment by jakebailey** [comment]
If you use VS Code and run the language server, does it behave the same way in the same python environment? The only way that it should differ is if the neovim client isn't sending some required info (but if you've even gotten this far it's probably fine, though I should note that neovim should not be claiming to have markdown support if it's not going to render it...)

**Comment by mjlbach** [comment]
Yes, it works within VSCode with the same environment. Thanks for the catch! I fixed the formatting options so it wasn't requesting markdown. 

<img width="1136" alt="Screen Shot 2019-11-28 at 11 44 37 PM" src="https://user-images.githubusercontent.com/13316262/69852429-1b610380-1239-11ea-8174-53c786b5d4a7.png">

**Comment by jakebailey** [comment]
If it works in VS Code and not neovim, then I doubt that it's our bug. Maybe you're passing the wrong initialization options and getting the wrong interpreter/search paths.

I would recommend setting `"python.trace.server": "verbose"` in VS Code and reloading to observe the LSP messages to verify you're not missing some important config.

**Comment by mjlbach** [comment]
Hmm, the interpreter/search paths are identical across the vscode extension and the nvim-lsp. 

These are the only start options I'm passing to the LSP.

```lua
    log_level = lsp.protocol.MessageType.Warning;
    settings = {
      python = {
        analysis = {
          errors = {};
          info = {};
          disabled = {};
        };
      };
    };
    on_new_config = function(config)
      installer.configure(config)
    end;
    init_options = {
      interpreter = 
                {
                    properties= 
                    {
                        InterpreterPath=vim.fn.exepath("python");
                        Version=get_python_version();
                    };
                };
      displayOptions= {};
      analysisUpdates=true;
      asyncStartup=true;
```

I'll try to debut this further. I can't see exactly the initialization options passed from the vscode extension (I know they're [here](https://github.com/microsoft/vscode-python/blob/master/src/client/activation/languageServer/analysisOptions.ts#L138)) And it looks like the vim-lsp isn't returning the same logs as the built-in vscode client. For example, I don't see these lines

```
[Info  - 12:05:15 AM] Analysis caching mode: None.
Opening document file:///Users/michael/Repositories/mpls_test/main.py
Analysis of main (User) queued. Dependencies: numpy
Import:  numpy /Users/michael/.virtualenvs/python3/lib/python3.7/site-packages/numpy/__init__.py 
Analysis of numpy (Stub) queued. Dependencies: numpy.core._multiarray_umath (stub)
Code Action in file:///Users/michael/Repositories/mpls_test/main.py at (2, 3) - (2, 3)
```

Just the x out of x items completed log entry.

**Comment by mjlbach** [comment]
What's even stranger, is that the hover/documentation commands work for top-level modules like np.dot/np.abs that fail to show up in the completion results. I'm wondering if this is a bug in the LSP implementation since it seems to work fine in lsp-python-ms (emacs) and VScode

**Comment by mjlbach** [comment]
Fixed, issue with client timing out request
