### ISSUE TITLE
Recognize variables defined with walrus operator

### ISSUE THREAD

**Issue by wintersderek** [microsoft/python-language-server#1832]
The issue is related to microsoft/vscode-python#8530

With the addition of the new walrus operator in python 3.8, the vscode extension does not recognize variables defined with it.

This has the unfortunate side effect of showing a "problem" each time the variable is referenced.

I would like the extension to recognize the variable as defined so a "problem" is not shown for variables defined with the walrus operator.

![Issue](https://user-images.githubusercontent.com/40494740/70554802-cf249600-1b4b-11ea-8f41-d0ddc1f46fe0.png)

**Comment by jakebailey** [comment]
We do recognize variables declared via `:=` (since before 3.8 was out), so this seems to be a bug. We're probably not walking the `while` condition (potentially others) when checking for undefined variables.

**Comment by dlimpid** [comment]
Version 2020.2.63072

In this case, the first one is okay, but undefined-variable warnings are raised for second and third `p`.

```python
while (
    i > 0
    and self.heap[(p := parent(i))] < self.heap[i]  # type: ignore[operator]
):
    self.heap[i], self.heap[p] = self.heap[p], self.heap[i]
    i = p
```

![image](https://user-images.githubusercontent.com/3257214/74587212-2f93f000-5033-11ea-97a3-43cbc225e47a.png)

![image](https://user-images.githubusercontent.com/3257214/74587534-155c1100-5037-11ea-9a2a-1a5c5646ee90.png)

**Comment by MikhailArkhipov** [comment]
Trivial repro
```python
while(x := 1):
    y = x
```
