### ISSUE TITLE
Intellisense support for dataclasses

### ISSUE THREAD

**Issue by avilum** [microsoft/python-language-server#1835]
I have been developing in VS Code in Python > 3.7.
Dataclasses were introduced in version 3.7 as part of the standard library, due to vast usage of classes for models definitions (classes that simply hold data).

In python versions prior to 3.7, the best practice was:

```python
# Python < 3.7

class Example(object):
  def __init__(self, a:int, b: str):
    self._a = a
    self._b = b

  @property
  def a(self):
    return self._a

  @property
  def b(self):
    return self._b
```

Now, in python versions after to 3.7, the best practice is:

```python
# Python >= 3.7

@dataclass
class DataclassExample:
  a: int
  b: str
```

As you can see, in Python > 3.7 the models definition is much easier and the code is more clean.
I'm sure dataclasses will be widely used in the following years and versions of Python.

The intellisense for classes which are wrapped with the `dataclass` decorator doesn't work at all.
I didn't have any autocompletion for the fields nor for the base class's fields. These are the classes i work with, modify, store in the database. I rely heavily on dataclasses and i think the world is going towards them, because it's so much more real-world problem and the code is much more clean.

Thanks for your time if you read it this far,
I think it's pretty simple to implement the intellisense for dataclasses. What do you think?

**Comment by MikhailArkhipov** [comment]
So, what is broken exactly? I tried basic sample with language server (python.jediEnabled: false) and it appears to be OK

![image](https://user-images.githubusercontent.com/12820357/70729560-49722900-1cb8-11ea-9f1d-44bbea23e7d4.png)

**Comment by avilum** [comment]
You are right, It was a settings problem.
sadly i found a package ("importmagic") that messed up the autocompletion behaviour for the dataclasses, while other parts Intellisense worked as expected.
I disabled it now and it works great!

Sorry for the trouble.
If anyone runs into the same issue with other extensions in the future, my json.settings file looks like this:

```json
{
    "python.jediEnabled": false,
    "editor.quickSuggestions": {
        "other": true,
        "comments": false,
        "strings": false
    },
    "editor.acceptSuggestionOnCommitCharacter": false,
    "editor.acceptSuggestionOnEnter": "on",
    "editor.quickSuggestionsDelay": 10,
    "editor.suggestOnTriggerCharacters": true,
    "editor.tabCompletion": "on",
    "editor.suggest.localityBonus": true,
    "editor.suggestSelection": "recentlyUsed",
    "editor.wordBasedSuggestions": false,
    "editor.parameterHints.enabled": true,
}
````
