### ISSUE TITLE
It's difficult to use "Go to symbol" to navigate to a class method

### ISSUE THREAD

**Issue by maxrothman** [microsoft/python-language-server#1836]
If you're working with a file that has lots of identical method names (e.g. in Django Rest Framework), "Go to symbol in file" is practically unusable. If you search the method name, you'll get the list of all methods with that name and you'll have to scroll to the one in the desired class. If you search for the class name, you'll have to find the method in the class.

I'm not sure what the right solution is here, but one idea would be to prefix the method symbols with the class name, e.g. ClassName.method_name.

**Comment by MikhailArkhipov** [comment]
Thanks for reporting. Indexer needs to be updated.

**Comment by sstaley-hioscar** [comment]
Any movement on this?

**Comment by debonte** [comment]
@sstaley-hioscar, which Python language server are you using? Pylance?

**Comment by judej** [comment]
Thank you for the report. This project is no longer active. If you are using the Python language server in VSCode, the language server you are using is Pylance and please the http://github.com/microsoft/pylance-release to report issues. 

If you are using Visual Studio, then, please use http://github.com/microsoft/PTVS to report issues.

thank you
