### ISSUE TITLE
Support of PyQt5-stubs

### ISSUE THREAD

**Issue by zhangguofu** [microsoft/python-language-server#1854]
PyQt5-stubs make the PyCharm a really productive IDE, but it seems not supported in VS Code yet.
I tried to install PyQt5-stubs and add its path into "python.autoComplete.extraPaths" in settings.json but it does not work, as PyQt5-stubs internal structures are not the same as PyQt5. So in order to support it, extra adaption should be made.

**Comment by MikhailArkhipov** [comment]
Related #1533

**Comment by dietervansteenwegen** [comment]
I have no experience working on stubs/autocomplete/vsc plugins but I would like to have autocomplete for PyQt5 in VSC.
Is this something that is difficult to learn/figure out? If it is just copy/paste work I might be able to help.

**Comment by jakebailey** [comment]
As far as I'm aware, PyQt5 and such already ship with type stubs; if people aren't seeing them, then I'm not sure what's happening. All that is managed upstream.

**Comment by jakebailey** [comment]
Oops, this is the old language server repo; this project is no longer maintained and you should be using Pylance or Jedi at this point in VS Code (or pyright/jedi over lsp elsewhere).

**Comment by judej** [comment]
Thank you for the report. This project is no longer active. If you are using the Python language server in VSCode, the language server you are using is Pylance and please the http://github.com/microsoft/pylance-release to report issues. 

If you are using Visual Studio, then, please use http://github.com/microsoft/PTVS to report issues.

thank you
