### ISSUE TITLE
"Go to definition" doesn't work

### ISSUE THREAD

**Issue by duanyongli** [microsoft/python-language-server#1855]
## Environment data

- VS Code version: 1.41
- Extension version (available under the Extensions sidebar): 2019.11.50794
- OS and version: Ubuntu 18.04
- Python version (& distribution if applicable, e.g. Anaconda): python3.7
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
- Relevant/affected Python packages and their versions: open3d
- **can not jump into open3d.io.read_triangle_mesh. And even can not jump to "mesh" from line 3 to line 2.**
![Screenshot from 2019-12-26 19-56-16](https://user-images.githubusercontent.com/7546401/71475114-d3be9f00-2819-11ea-81e7-8e03a6605810.png)

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - control'
> conda --version
> pyenv root
> python3.7 -c "import sys;print(sys.executable)"
> python3.6 -c "import sys;print(sys.executable)"
> python3 -c "import sys;print(sys.executable)"
> python2 -c "import sys;print(sys.executable)"
> python -c "import sys;print(sys.executable)"
> ~/anaconda3/bin/python -c "import sys;print(sys.executable)"
> /usr/bin/python ~/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/interpreterInfo.py
> /usr/bin/python ~/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/interpreterInfo.py
> /usr/bin/python2.7 ~/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/interpreterInfo.py
> /usr/bin/python2.7 ~/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/interpreterInfo.py
> /usr/bin/python ~/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/interpreterInfo.py
> /usr/bin/python ~/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/interpreterInfo.py
> /usr/bin/python2.7 ~/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/interpreterInfo.py
> /usr/bin/python2.7 ~/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/interpreterInfo.py
> conda info --json
> conda env list
Starting Microsoft Python language server.
> conda info --json
> conda env list

**Comment by MikhailArkhipov** [comment]
0.5.30+
