### ISSUE TITLE
Python(parser-16) error for use of if condition in fstring

### ISSUE THREAD

**Issue by yumasheta** [microsoft/python-language-server#1862]
### Environment Data

    VS Code Version: 1.41.1
    OS: Linux x64 5.4.7-arch1-1
    Python Extension version: 2019.11.50794
    Microsoft Python Language Server version 0.5.10.0
    Python version: 3.8.1

### Description of the Problem

The following line of code produces two errors:
```python
f'{x if x == 1.0 else 0}'
```
```
unexpected token '=' Python(parser-16)
f-string: expecting '}' but found '1' Python(parser-16)
```

The use of fstrings as shown above is completely correct (syntax wise).

When using the default linting of the [vscode python extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python) with the 'jedi' engine, there is no error linted for the exact same line of code.

### Remarks

Also filed an issue at the [Microsoft intelliCode Extension](https://github.com/MicrosoftDocs/intellicode/issues):
[Link to issue](https://github.com/MicrosoftDocs/intellicode/issues/160)

**Comment by jakebailey** [comment]
A wild guess says this is something to do with my PR for #1102, #1548. I thought I had handled the cases for `==` and `!=`, but perhaps not. Skimming the tests, we don't seem to have one for `==` or `!=`, so that'd be an oversight.

**Comment by yumasheta** [comment]
I forgot to include, that `!=` also gives the same error.
And `>=`, `<=` both give these two errors:
```
unexpected EOF while parsing Python(parser-16)
unexpected EOF while parsing Python(parser-17)
```


Only `>` and `<` seem to work, which are both single character operators.

**Comment by jakebailey** [comment]
I think I see the bug, it's not skipping the second `=` in these tokens once it recognizes that it's a part of an operator and not just the new debug specifier.

**Comment by MikhailArkhipov** [comment]
0.5.30+
