### ISSUE TITLE
SQLAlchemy intellisense 

### ISSUE THREAD

**Issue by rpedrodasilva10** [microsoft/python-language-server#1865]
This is the continuation of microsoft/vscode-python#292, i'm opening a new issue as requested by @brettcannon on microsoft/vscode-python#292

## Environment data

- VS Code version: 1.41.1
- Extension version (available under the Extensions sidebar): 2020.1.57204
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.3
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv
- Relevant/affected Python packages and their versions: Flask-SQLAlchemy==2.4.1,SQLAlchemy==1.3.12

## Expected behaviour

List all available properties and methods.

## Actual behaviour

Can't recognize some methods (e.g: methods from the db object)

## Steps to reproduce:
[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. in some file.py

from flask_sqlalchemy import SQLAlchemy
db = SQLAlchemy()

db.Col  //Here the intellisense can't find the Column member

**Comment by MikhailArkhipov** [comment]
Reproducible. Need to look into analysis, the `SQLAlchemy` class appears to be fairly plain...

**Comment by MikhailArkhipov** [comment]
It looks like those methods are dynamically added. LS is a static analyzer and does not execute any Python code. Therefore members that are added dynamically, won't show up as static analyzer only sees what is declared in `SQLAlchemy(object)` and what is added in `__init__()`.

**Comment by rpedrodasilva10** [comment]
I got it. Thanks for your response @MikhailArkhipov.

**Comment by MikhailArkhipov** [comment]
Generally speaking, some systems, like Visual Studio, implement some support in some languages like C#, but in involves first actually including SQL project with schema into the solution so C# can pick it up and generate C# data source class from SQL schema and then C# intellisense picks it up as a regular C# object. Perhaps at some point Python tools will be able to provide something similar.
