### ISSUE TITLE
VSCode pyi files

### ISSUE THREAD

**Issue by VenoMpie** [microsoft/python-language-server#1866]
There's an issue with pyi files in VSCode, I have tried to get this working on 3 different machines with different extensions and all do the same.
PyCharm/Eclipse on the other hand works as expected.

Problem:
IntelliSense/Language Server is not working for pyi files in vscode
Variables pop up as just the name
When trying to use intellisense/code completion then there's nothing

Expected:
Hovering over a parameter should show "name: type" instead of just "name"
IntelliSense should be displayed when using a period on the variable name

Replicate:
Create a file called foo.pyi with the following code:
class Foo(object):
    def __init__(self, test: str) -> None: ...
    def test(self, test: int) -> int: ...

Create a file called foo.py with the following code:
class Foo(object):
    def __init__(self, test):
        pass
    def test(self, test):
        pass

This post didn't help as Jedi is already disabled and there's no more comments after that. https://stackoverflow.com/questions/53578365/does-vscode-support-python-pyi-files-for-intellisense

Intellisense and the language server works wonderful with normal python files, code completion happens, parses python 3 type hints perfect, etc. Just not with pyi files and we need to keep backward compatbility to 2.7 so I can't go and change all the functions to have type hints instead of stub files.

I have also tried to disable most of the non-python extensions for incase something interferes but to no effect.
Python specific installed extensions:
ms-python.python 2020.1.57204
visualstudioexptteam.vscodeintellicode 1.2.2

I have even installed MagicPython as I thought it was that

**Comment by MikhailArkhipov** [comment]
Sounds like https://github.com/microsoft/python-language-server/issues/1126

**Comment by VenoMpie** [comment]
Yes it is actually exactly the same, tried the same workarounds with the stub paths as well. Can be closed as duplicate of #1126 (seems like the searching I did for this issues wasn't sufficient to find that one :P)
