### ISSUE TITLE
New refactor function: move

### ISSUE THREAD

**Issue by sliwinski-milosz** [microsoft/python-language-server#1867]
Pycharm provides move functions/classes/variables from one file to another via refactor > Move (f6-keyboard shortcut) as described in https://stackoverflow.com/questions/56197088/auto-import-and-refactor-move-function-from-one-file-to-another-in-vscode.

Would be great to have similar functionality in Visual Studio Code.

**Comment by MikhailArkhipov** [comment]
Yes, good suggestion, thanks.

**Comment by nirradi** [comment]
+1

**Comment by cfgmr** [comment]
+1

**Comment by pengwk** [comment]
+1

**Comment by ymentha14** [comment]
+1

**Comment by wkerzendorf** [comment]
+1 - that is very important for me. Thanks :-)

**Comment by dwight-allstripes** [comment]
+1

**Comment by pengwk** [comment]
+1

**Comment by judej** [comment]
Thank you for the report. This project is no longer active. If you are using the Python language server in VSCode, the language server you are using is Pylance and please the http://github.com/microsoft/pylance-release to report issues. 

If you are using Visual Studio, then, please use http://github.com/microsoft/PTVS to report issues.

thank you
