### ISSUE TITLE
Python Intellisense autocomplete extremely slow

### ISSUE THREAD

**Issue by kevin-hv** [microsoft/python-language-server#1871]
OS: MacOS
OS Version: 10.15.2

VSCode Version: 1.41.1
Extension Version: 2019.11.50794
Python Version: Python 3.7.5

Using jedi : Yes

Conda environment: No

Problem:
Intelisense autocomplete takes forever to complete downloaded Python modules such as pandas (but other as well, numpy, scikit-learn...) under MacOS.

Steps to Reproduce:

1. Install python3 via Brew (brew install python3)
2. Install VSCode (either via Download from Official site or via Brew Cask)
3. Install pandas with pip3 (pip3 install pandas)
4. Create a new .py file and observe the behaviour attached below:

![](https://user-images.githubusercontent.com/44970281/71305059-c3986100-23ce-11ea-9e7c-737cfb7eca14.gif)

Does this issue occur when all other extensions are disabled?: Yes

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by MikhailArkhipov** [comment]
Is the about no completions on `data` which is a dynamically created object based on the CSV file contents and since LS is not running any code or read user data files, there are no completions. See #981.

Or is it about specific performance issues?

**Comment by kevin-hv** [comment]
Yupp, numpy. takes between 8 - 10 seconds to autocomplete. So is this behaviour is normal?

**Comment by jakebailey** [comment]
Only at startup. Once it completes, then it should be instant since the work is done.

**Comment by kevin-hv** [comment]
I see, it works like the way you describe @jakebailey

**Comment by MikhailArkhipov** [comment]
You can also try `"python.analysis.cachingLevel": "Library"` and see of cache works for you. It basically stores analysis of the library so next time you open VS Code it won't run the library analysis again.

**Comment by kevin-hv** [comment]
Thank you for your help.
