### ISSUE TITLE
Tensorflow 1.x intellisense/autocompletion not working

### ISSUE THREAD

**Issue by rsalunga29** [microsoft/python-language-server#1876]
## Environment data

- Language Server version: Microsoft Python Language Server 0.5.30.0  
- OS and version: macOS Catalina 10.15.1 (19B88)
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.5

## Expected behaviour

When `cmd + space` is triggered, a list of function recommendation should appear

## Actual behaviour
<img width="316" alt="Screen Shot 2020-01-21 at 3 23 56 AM" src="https://user-images.githubusercontent.com/20834464/72753014-b0abc300-3bfe-11ea-9948-5c9b18bd4d3f.png">

## Logs

```
XXX
```

## Code Snippet / Additional lnformation

I'm using Tensorflow 1.15

```python
XXX
```

**Comment by MikhailArkhipov** [comment]
`from` syntax implies modules. `from module.` provides list of submodules. Try
```python
import tensorflow
tensorflow.
```

**Comment by rsalunga29** [comment]
> `from` syntax implies modules. `from module.` provides list of submodules. Try
> 
> ```python
> import tensorflow
> tensorflow.
> ```

Still not working for me :/. Stand alone Keras works fine though but I'll try to upgrade to TF2.0 and see if intellisense/autocompletion will work.

**Comment by MikhailArkhipov** [comment]
2.0 won't work, see details in https://github.com/microsoft/python-language-server/issues/818. What are you getting in the example above?

**Comment by MikhailArkhipov** [comment]
Tensorflow is a sizeable library that, depending on install, can also pull in other large libraries like `pandas` or `scipy`, and it takes ~30s to analyze. So there won't be immediate completions.

![image](https://user-images.githubusercontent.com/12820357/73044940-c567a100-3e20-11ea-9600-a53752befb63.png)

You can try enabling caching by setting
```json
"python.analysis.cachingLevel": "Library",
```
then after the initial analysis results will be cached and next time you open the file tensorflow data will be fetched from cache. This is experimental option though.
