### ISSUE TITLE
Rename symbol fails, Unable to read file, path is garbage

### ISSUE THREAD

**Issue by Anvolne** [microsoft/python-language-server#1882]
Hello and good afternoon,

I am using Manjaro linux, installed vscode from package manager, the Python extension from vscode extensions (version 2020.1.58038), and the Language Server version is 0.5.30.0.
This is a (somewhat) fresh install, but it has been installed for about a year now, I only use it for the occasional programming. Everything is up to date according to `pacman` (the package manager).
The Rename Symbol command fails like so:
`Unable to read file (Error: File not found  ///mnt/data/development/programming/python/vótmábot/modules/core/bot.py/mnt/Data/Development/Programming/Python/vótmábot/modules/core/bot.py))`

It seems like it duplicated the whole path twice, also, only the second part is with correct character case.

Maybe I am overlooking some configuration value or something...
Thank you for your help

**Comment by Anvolne** [comment]
Oh also, it does the same with "Go To"s too...
`Unable to open 'logger.py': Unable to read file (Unknown (FileSystemError): Error: ENOTDIR: not a directory, stat '/mnt/Data/Development/Programming/Python/vótmábot/modules/core/utils/logger.py/mnt/Data/Development/Programming/Python/vótmábot/modules/core/utils/logger.py').`

**Comment by Anvolne** [comment]
Seems related to #1687 

I renamed the directory to not have unicode characters and it seems like it fixed it.
Sorry if this was a bit "spam"y :)

**Comment by MikhailArkhipov** [comment]
Yes, seems like a duplicate if https://github.com/microsoft/python-language-server/issues/1687.

**Comment by jakebailey** [comment]
Closing in favor of #1687.
