### ISSUE TITLE
Python Language Server updating every day?

### ISSUE THREAD

**Issue by Matelasse** [microsoft/python-language-server#1899]
I've set my update channel to daily, but I don't see any commits in this repository that often, so what is prompting it to update every day? Commits past month were scarce in this repository, but I  got updates almost everyday

**Comment by CMLL** [comment]
By any chance are you subscribed to the insiders build of the Python extension? If a new change is pushed to the extension it will create a new folder for that branch and that folder will download its own language server version. You can confirm this by going to the `~/.vscode/extensions`  and checking how many python extensions folder you have.

**Comment by MikhailArkhipov** [comment]
It updates when we change something, which may or may not be every day.

**Comment by MikhailArkhipov** [comment]
See also https://github.com/microsoft/python-language-server/issues/1990
