### ISSUE TITLE
Override methods of a superclass﻿

### ISSUE THREAD

**Issue by ad-m** [microsoft/python-language-server#1909]
> Hi guys,
> 
> I often override methods because Django :rofl: I was wondering if Code can help me override methods which whispers me. Like if I hit let's say SHIFT + Enter onto whispered row it would paste the original method definition.
> 
> Example:
> 
> I type:
> ```python
> def get_a
> ```
> 
> I get whispered:
> ![image](https://cloud.githubusercontent.com/assets/198654/23300165/b03166dc-fa84-11e6-8fad-a87773c70706.png)
> 
> I hit SHIFT + Enter and I get
> ![image](https://cloud.githubusercontent.com/assets/198654/23300209/dc817600-fa84-11e6-972b-37ace3ce818f.png)
> 
> Thank you and I'm sorry if this is duplicated task. I've looked around but found nothing.

This issue is migrated from https://github.com/Microsoft/vscode/issues/21343 . 

Available for Python in PyCharm (see https://www.jetbrains.com/help/pycharm/overriding-methods-of-a-superclass.html# ). Available for Java in Eclipse (see https://help.eclipse.org/2019-12/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Freference%2Fref-dialog-override-method.htm , example: https://www.youtube.com/watch?v=pFCvveNylmQ ).

**Comment by jakebailey** [comment]
What is the issue here? Is something not working? We do this override already (I think that's what your info shows).

**Comment by jakebailey** [comment]
Oops, hit the wrong button, meant to comment only.

**Comment by ad-m** [comment]
I created this issue because I noticed that the original report was closed as requiring implementation on the Python driver side.

At the same time, I am looking for a way to - as nicely as in PyCharm / Eclipse - generate code snippets that are used to override methods of superclass, because previous text editors got used to it and works for me.

I get the impression that Visual Studio Code for Python is sometimes (not always) able to generate a snippet to override a method. Such a snippet - in my opinion - should include calling the superior method.

I recorded a video to indicate what I mean as a limitation of Visual Studio Code:
![video](https://user-images.githubusercontent.com/3618479/74781243-6bcc8800-52a1-11ea-8794-97cc88d9236b.gif)

I have successfully generated an override for "get_queryset" (by writing "get_queryset <SHIFT+ENTER>"), but for the "retrieve" or "list" methods that ( https://github.com/encode/django-rest-framework/blob/335054a5d36b352a58286b303b608b6bf48152f8/rest_framework/viewsets.py#L222 -> https://github.com/encode/django-rest-framework/blob/0407a0df8a16fdac94bbd08d49143a74a88001cd/rest_framework/mixins.py#L37 ) failed. Ideally, in the context of the class it would be possible to call the window to select the methods that it wants to override (just like Eclipse).

For Django and the project using class-based-views (http://ccbv.co.uk/, https://docs.djangoproject.com/en/3.0/topics/class-based-views/) this seems important to me.

**Comment by jakebailey** [comment]
Are you sure you have the language server enabled? This should work fine.

![overrides](https://user-images.githubusercontent.com/5341706/74782772-f8068d00-5258-11ea-91ad-ee3ca7b79384.gif)

**Comment by ad-m** [comment]
Until now, I was impressed that I have everything running in Python, because, for example, the "Go to Definition" action works correctly etc. However, I installed "Visual Studio IntelliCode", which for the first time asked to start "Python Language Server". It seems that now Python is running more and it works.
