### ISSUE TITLE
auto complete does not deduce types of parameters of functions

### ISSUE THREAD

**Issue by shimondoodkin** [microsoft/python-language-server#1911]
auto complete does not deduce types of parameters of functions

python3

```
import turtule
bob=turtule.Turtle()

def function(bob)
    bob.f... << auto complete here dos not work

bob.f.. auto complete here works


function(bob)
```

**Comment by jakebailey** [comment]
This is working as designed. That function could be called with any parameter; the language server tries to not propagate types backwards from the callsite as they are inherently unreliable.

If you are certain that a function should take a specific type, we recommend annotating the function parameter to indicate that.

```python
import turtule
bob=turtule.Turtle()

def function(bob: turtule.Turtle)
    bob.f # now this will work
```

**Comment by shimondoodkin** [comment]
I actually like the editor and you made little ttle bugs in it.


Many people do not annotate.

Without this a lot of code not quickly workable...

**Comment by morganics** [comment]
@shimondoodkin I'm not a dev on the project, but the function as defined will not work as you expect - ```bob``` in the signature definition would overwrite the global ```bob```, so I'd suggest a different code snippet to highlight your issue as Pycharm isn't correct in this instance.

**Comment by jakebailey** [comment]
@morganics PyCharm is likely inferring the parameter type from the call site at the bottom of the screenshot; I doubt it's screwing up the scoping of the variable.

This is what we don't want to do, it's not reliable. The last time our analysis did something like this was over a year ago, so this behavior would not be new.
