### ISSUE TITLE
Downloading Python-Language-Server too slowly in China?

### ISSUE THREAD

**Issue by masx200** [microsoft/python-language-server#1916]
When using the python plugin "ms-python.python" in vscode,Downloading Python-Language-Server too slowly in China?

It takes at least tens of minutes to download it?

Have you considered providing a cdn download address?

Or provide a guide on how to download and install it myself.

```
Downloading https://pvsc.azureedge.net/python-language-server-stable/Python-Language-Server-win-x64.0.5.30.nupkg...

```

```
Downloading https://pvsc.azureedge.net/python-language-server-stable/Python-Language-Server-linux-x64.0.5.30.nupkg...
```

**Comment by coolskyboy** [comment]
I have the same problem,i could not download it

**Comment by yar999** [comment]
After download `*.nupkg` via Thunder, manually extract it to `~/.vscode/extensions/ms-python.python-2020.2.64397/languageServer.0.5.30`

```bash
unzip Python-Language-Server-linux-x64.0.5.30.nupkg -d ~/.vscode/extensions/ms-python.python-2020.2.64397/languageServer.0.5.30
```

Note that the version of Python-Language-Server and the version of ms-python are replaced with the currently used version.

**Comment by masx200** [comment]
> After download `*.nupkg` via Thunder, manually extract it to `~/.vscode/extensions/ms-python.python-2020.2.64397/languageServer.0.5.30`
> 
> ```shell
> unzip Python-Language-Server-linux-x64.0.5.30.nupkg -d ~/.vscode/extensions/ms-python.python-2020.2.64397/languageServer.0.5.30
> ```
> 
> Note that the version of Python-Language-Server and the version of ms-python are replaced with the currently used version.



Unzip to the directory under windows system.

`C:\Users\yourusername\.vscode\extensions\ms-python.python-2020.2.64397\languageServer.0.5.30`

**Comment by coolskyboy** [comment]
> 
> 
> After download `*.nupkg` via Thunder, manually extract it to `~/.vscode/extensions/ms-python.python-2020.2.64397/languageServer.0.5.30`
> 
> ```shell
> unzip Python-Language-Server-linux-x64.0.5.30.nupkg -d ~/.vscode/extensions/ms-python.python-2020.2.64397/languageServer.0.5.30
> ```
> 
> Note that the version of Python-Language-Server and the version of ms-python are replaced with the currently used version.
Thanks ,i get it

**Comment by Hanqing-Sun** [comment]
> > After download `*.nupkg` via Thunder, manually extract it to `~/.vscode/extensions/ms-python.python-2020.2.64397/languageServer.0.5.30`
> > ```shell
> > unzip Python-Language-Server-linux-x64.0.5.30.nupkg -d ~/.vscode/extensions/ms-python.python-2020.2.64397/languageServer.0.5.30
> > ```
> > 
> > 
> > Note that the version of Python-Language-Server and the version of ms-python are replaced with the currently used version.
> 
> Unzip to the directory under windows system.
> 
> `C:\Users\yourusername\.vscode\extensions\ms-python.python-2020.2.64397\languageServer.0.5.30`

Thanks for your solution.
I extracted the `.nupkg` to `~/.vscode/extensions/ms-python.python-2020.2.64397/languageServer.0.5.30` but vscode says: 
```
[Error - 0:00:00 PM] Starting client failed
Launching server using command /Users/USERNAME/.vscode/extensions/ms-python.python-2020.2.64397/languageServer.0.5.30/Microsoft.Python.LanguageServer failed.
```
It's a MacOS Catalina 10.15.3 with vscode 1.14.2, and the file does exist. Is there anything that I missed?
Thanks!

**Comment by Helixzhang** [comment]
> > > After download `*.nupkg` via Thunder, manually extract it to `~/.vscode/extensions/ms-python.python-2020.2.64397/languageServer.0.5.30`
> > > ```shell
> > > unzip Python-Language-Server-linux-x64.0.5.30.nupkg -d ~/.vscode/extensions/ms-python.python-2020.2.64397/languageServer.0.5.30
> > > ```
> > > 
> > > 
> > > Note that the version of Python-Language-Server and the version of ms-python are replaced with the currently used version.
> > 
> > 
> > Unzip to the directory under windows system.
> > `C:\Users\yourusername\.vscode\extensions\ms-python.python-2020.2.64397\languageServer.0.5.30`
> 
> Thanks for your solution.
> I extracted the `.nupkg` to `~/.vscode/extensions/ms-python.python-2020.2.64397/languageServer.0.5.30` but vscode says:
> 
> ```
> [Error - 0:00:00 PM] Starting client failed
> Launching server using command /Users/USERNAME/.vscode/extensions/ms-python.python-2020.2.64397/languageServer.0.5.30/Microsoft.Python.LanguageServer failed.
> ```
> 
> It's a MacOS Catalina 10.15.3 with vscode 1.14.2, and the file does exist. Is there anything that I missed?
> Thanks!

Some problem!

**Comment by masx200** [comment]
链接: https://pan.baidu.com/s/1JOGlM_3zA4WMJXGpOuoa6A 提取码: fcr7

**Comment by masx200** [comment]
> > > After download `*.nupkg` via Thunder, manually extract it to `~/.vscode/extensions/ms-python.python-2020.2.64397/languageServer.0.5.30`
> > > ```shell
> > > unzip Python-Language-Server-linux-x64.0.5.30.nupkg -d ~/.vscode/extensions/ms-python.python-2020.2.64397/languageServer.0.5.30
> > > ```
> > > 
> > > 
> > > Note that the version of Python-Language-Server and the version of ms-python are replaced with the currently used version.
> > 
> > 
> > Unzip to the directory under windows system.
> > `C:\Users\yourusername\.vscode\extensions\ms-python.python-2020.2.64397\languageServer.0.5.30`
> 
> Thanks for your solution.
> I extracted the `.nupkg` to `~/.vscode/extensions/ms-python.python-2020.2.64397/languageServer.0.5.30` but vscode says:
> 
> ```
> [Error - 0:00:00 PM] Starting client failed
> Launching server using command /Users/USERNAME/.vscode/extensions/ms-python.python-2020.2.64397/languageServer.0.5.30/Microsoft.Python.LanguageServer failed.
> ```
> 
> It's a MacOS Catalina 10.15.3 with vscode 1.14.2, and the file does exist. Is there anything that I missed?
> Thanks!

```shell
chmod 777 /home/m/.vscode/extensions/ms-python.python-2020.2.64397/languageServer.0.5.30/Microsoft.Python.LanguageServer

```

**Comment by Hanqing-Sun** [comment]
@masx200 Thanks dude, thanks!

```
chmod a+x /home/yourusername/.vscode/extensions/ms-python.python-2020.2.64397/languageServer.0.5.30/Microsoft.Python.LanguageServer
```
did the trick.

**Comment by 1470391328** [comment]
I download nupkg file, but i donot know how to unzip it on window or install it

**Comment by masx200** [comment]
> I download nupkg file, but i donot know how to unzip it on window or install it

use 7-zip to extract it

**Comment by masx200** [comment]
https://github.com/microsoft/vscode-python/issues/9324

**Comment by 1470391328** [comment]
> [microsoft/vscode-python#9324](https://github.com/microsoft/vscode-python/issues/9324)

thank you ！

**Comment by MikhailArkhipov** [comment]
There are steps in https://github.com/microsoft/python-language-server/blob/master/CONTRIBUTING.md how to set up LS as we do for debugging. Basically

- download nuget package
- create folder `languageServer` (does not have to be versioned)
- rename `.nupkg` to `.zip` and unzip to the folder.
- in VS Code set setting `python.downloadLanguageServer` to `false`.
- in VS Code set setting `python.jediEnabled` to `false`.

**Comment by MikhailArkhipov** [comment]
Closing since CDN is not LS issue. Manual installation steps are above and in https://github.com/microsoft/python-language-server/issues/1698

**Comment by helphi** [comment]
我整理了一份文档，见 <https://blog.csdn.net/feilinyongyuan/article/details/104964275>
