### ISSUE TITLE
Unable to start Python Language server after trying to update it.

### ISSUE THREAD

**Issue by mani2106** [microsoft/python-language-server#1918]
## Environment data

- Language Server version: 0.5.30.0   
- OS and version: 
Version: 1.42.1 (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 6.3.9600 (Windows 8.1)

- Python version (& distribution if applicable, e.g. Anaconda): Python 3.6.7 in a conda environment

Conda environment details:
(Text inside in yml format)
[skcrfsuite_env_v2.txt](https://github.com/microsoft/python-language-server/files/4253554/skcrfsuite_env_v2.txt)

## Expected behaviour

I tried to update the language server as mentioned [here](https://github.com/microsoft/vscode-python/issues/3977) and the language server was not able to start since that.

The language server should be able to start without error

## Actual behaviour

The language server crashes
![crashing](https://user-images.githubusercontent.com/20659733/75312744-dd4b9e00-5880-11ea-800f-29fb1b920f3e.png)

## Logs

I have attached the log files for the language server and python gathered from the output tab with trace level logging enabled.

[language server log.log](https://github.com/microsoft/python-language-server/files/4253434/language.server.log.log)
[python output log.txt](https://github.com/microsoft/python-language-server/files/4253435/python.output.log.txt)

**Comment by jakebailey** [comment]
You have library caching enabled. This is not recommended and not enabled by default. You should be able to remove the setting from your VS Code settings and the issue will go away.

**Comment by mani2106** [comment]
It works now on making the suggested change, Thanks
