### ISSUE TITLE
linux cannot download Python-Language-Server 0.5.31

### ISSUE THREAD

**Issue by yaegassy** [microsoft/python-language-server#1928]
0.5.31 is available for osx and win, but linux still seems to be 0.5.30.

**osx stable**

https://pvsc.blob.core.windows.net/python-language-server-stable?restype=container&comp=list&prefix=Python-Language-Server-osx-x64

**win stable**

https://pvsc.blob.core.windows.net/python-language-server-stable?restype=container&comp=list&prefix=Python-Language-Server-win-x64

**linux stable**  0.5.31 missing

https://pvsc.blob.core.windows.net/python-language-server-stable?restype=container&comp=list&prefix=Python-Language-Server-linux-x64

**Comment by jakebailey** [comment]
This should be fixed.
