### ISSUE TITLE
Analysis of peewee with the new LS never finishes

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/python-language-server#193]
https://github.com/Microsoft/vscode-python/issues/2682

_"Check out [peewee](https://github.com/coleifer/peewee). When the new LS tries to analyse the main file, peewee.py, it uses >100% of CPU and the RAM usage increases continuously (over 40GB at some point). This doesn't seem to complete, even after leaving it open and running for an hour. Things like the Go to symbol list never get rendered."_

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/python-language-server/pull/201

**Comment by stessaris** [comment]
I still have the RAM problem on OSX with Version 2018.9.0

**Comment by MikhailArkhipov** [comment]
@stessaris - how big is the RAM consumption? Runaway or large but stable?

**Comment by stessaris** [comment]
@MikhailArkhipov - over 5 GB (enough to bring my 8GB iMac to its knees with the rest of applications running), I got the feeling that is not growing a lot after that but I'll do some tests. The project is 20 files for a total of 6500 lines of code. No issues with Jedi

**Comment by MikhailArkhipov** [comment]
@stessaris - This bug is specifically about peewee, could you open another specific to your project please.

**Comment by GinRyan** [comment]
It's still happening in language-server.0.1.60 (on Windows 10 1803, VSCode 1.28.2)

![default](https://user-images.githubusercontent.com/2548560/48300111-9febc180-e512-11e8-9e7f-bba8430b8305.png)

There's just 5 python scripts in my project.

After I kill this process, it will launch again and auto increment  to 4GB even 10GB .Auto increment step by 10MB per sec.

I just import numpy and matplotlib in project.

**Comment by jakebailey** [comment]
@GinRyan As previously mentioned, this issue is specifically about peewee. If this is occurring for another project, I'd appreciate it if you opened a new issue (especially if you can share the project that causes the high memory usage so we can profile it).

**Comment by MikhailArkhipov** [comment]
0.2.16 is now available on beta channel. 
```json
"python.analysis.downloadChannel": "beta"
```

**Comment by NiNJAD3vel0per** [comment]
@MikhailArkhipov  
**What is this ? ""python.analysis.downloadChannel": "beta""**
Why we should put this odds line in setting.json without explanation ? 
My Mac is always +300% whenever turning of vscode with Python. This is not good !
