### ISSUE TITLE
Hide imports from "go to symbol in workspace"

### ISSUE THREAD

**Issue by ThiefMaster** [microsoft/python-language-server#1931]
For example, I have a class `User` which is defined in one file but imported in many others.
When I want to jump to the `User` symbol I obviously never want an import but the class itself.

Is there any way to exclude imports from "go to symbol in workspace"? If not, I think this would be a very useful feature!

**Comment by jakebailey** [comment]
#612 related (not show imports as symbols at all), but is there a reason you'd be using a workspace symbol search rather than a typical go-to-def or find-references?

**Comment by ThiefMaster** [comment]
I might not have code open that uses the symbol. Let's say my colleague asks me something about class `Foo`, and I need to check its code to answer his question. Then I'd like to be able to quickly go to the class using its name.
