### ISSUE TITLE
Support Django model objects in IntelliSense

### ISSUE THREAD

**Issue by DoofCoder** [microsoft/python-language-server#1934]
This case is similar to microsoft/vscode-python#1072

## Environment data

- VS Code version: 1.25.1
- Extension version (available under the Extensions sidebar): 2018.7.1
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): Anaconda Python 3.6.5
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Conda 
- Relevant/affected Python packages and their versions: Django 2.0.6

## Actual behavior

Intellisense/pylint do not offer autocompletion for a member variable inherited from a base class and shows it as a problem: E1101:Class 'Question' has no 'objects' member

The code runs exactly as intended without errors.

I am actually following the Django tutorial from the official site.

## Expected  behavior

The object's member should be shown in intellisense and it shouldn't log it as a problem

## Steps to reproduce:

It happens when following the tutorial from djangoproject.org:
https://docs.djangoproject.com/en/2.0/intro/tutorial03/

in section: Write views that actually do something:

```python
from django.http import HttpResponse
from .models import Question

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    output = ', '.join([q.question_text for q in latest_question_list])
    return HttpResponse(output)
```

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
Everything runs ok. there is actually nothing in output.
```   

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`)

```
System check identified no issues (0 silenced).
July 28, 2018 - 10:47:36
Django version 2.0.6, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[28/Jul/2018 10:47:43] "GET /polls/ HTTP/1.1" 200 11
```
Output from 'Problems'

```
{
	"resource": "/c:/Users/Ramon Leon/Documents/DjangoProjects/mysite/polls/views.py",
	"owner": "python",
	"code": "E1101",
	"severity": 8,
	"message": "E1101:Class 'Question' has no 'objects' member",
	"source": "pylint",
	"startLineNumber": 9,
	"startColumn": 28,
	"endLineNumber": 9,
	"endColumn": 28
}
```

**Comment by jakebailey** [comment]
Duplicate of #129.
