### ISSUE TITLE
Auto import broken for std modules

### ISSUE THREAD

**Issue by seik** [microsoft/python-language-server#1939]
## Environment data
- Language Server version: 0.5.31   
- OS and version: macOS
- Python version (& distribution if applicable, e.g. Anaconda): 3.8
- Using poetry 1.0.3

## Expected behaviour

Std modules don't get action for missing imports.

## Actual behaviour

Std modules should get the quick fix action with import option.

## Code Snippet / Additional lnformation

I've set up a simple project to reproduce this, a colleague checked and he was able to reproduce. It's running poetry with the env configured in the same folder as the project.

https://github.com/seik/python-language-server-bug-std-imports

Steps to reproduce:

- Open the project, and install everything with poetry: `poetry install`.
- Check the environment is configured in VSCode and everything is loaded.
- Close VSCode and reopen the project.
- In the `main.py` file the `csv` module should have the _quick fix_ action, close the file and reopen it. (Maybe the autoimport doesn't work in this step, closing the file and reopen ensures it fails)
- `csv` file now doesn't have the _quick fix_ action and all std modules are ignored when it comes to auto imports.

Related to #617 #625

**Comment by jakebailey** [comment]
I think there's a bug after #1896, which was recently-ish released to the public. Will have to investigate.

**Comment by MikhailArkhipov** [comment]
There was a regression and #1896 got reverted. Please try updated bits.

**Comment by seik** [comment]
Can confirm now is working under 0.5.43.

Closing this. Thanks!
