### ISSUE TITLE
When I set "python.jediEnabled": false, the declaration of the functions with mouse on its name is not correct

### ISSUE THREAD

**Issue by BobAnkh** [microsoft/python-language-server#1940]
# Environment Data

- VScode Version: 1.43.0 (system setup)
- OS: Windows_NT x64 10.0.18363
- Extension Version: Python 2020.2.64397
- Python version: 3.7.0(64-bit) with anaconda
- Type of virtual environment used: conda
- Jedi or Language Server: i set `"python.jediEnabled": false` in my settings.json

# Problem

I work fine before I installed the extension Visual Studio Intellicode which downloads something and sets `"python.jediEnabled": false` in my settings.json. Its something like this:

I `import torch` and write `torch.max(input=X, other=torch.tensor(0.0))`, when I put my mouse on the name of the function it shows like this:

![image](https://user-images.githubusercontent.com/44333669/76745063-2fad1a00-67b0-11ea-9b09-6feb5330a6b7.png)

Also I write my functions with declaration, which shows like this:

![image](https://user-images.githubusercontent.com/44333669/76745172-5ec38b80-67b0-11ea-91bc-ee2283419225.png)

But when `"python.jediEnabled": false` is added to my settings.json, things changed totallly:

First, the declaration of the function from what I import shows the mismatching one and I don't know if or how could I change it:

![image](https://user-images.githubusercontent.com/44333669/76745466-de515a80-67b0-11ea-9fba-ec23337c8613.png)

It is also different from what shows up when typing: (it shows automatically the 3rd of the total 4)

![image](https://user-images.githubusercontent.com/44333669/76746308-448aad00-67b2-11ea-98a5-48f0b705c27d.png)

![image](https://user-images.githubusercontent.com/44333669/76746290-3f2d6280-67b2-11ea-85d8-11b28f0d1b8d.png)

Second, the declarations of my function become like this:

![image](https://user-images.githubusercontent.com/44333669/76745639-2cfef480-67b1-11ea-9dce-ba6c189b6216.png)

They are all in one row.

Then I just comment `"python.jediEnabled": false` with `//` in front of it and reload the window on instructions, everything goes back to before. So I think what causes my problem should be related to `"python.jediEnabled": false`

But I don't know what actually causes my problem and is there something I should do or configure to solve the problem(as I want to use Visual Studio Intellicode)? Or is it a bug? Or is more information I should provide?

Thanks for concerning my  problem!

**Comment by MikhailArkhipov** [comment]
The Python extension has two completions/signatire/tooltip providers you can use. One is [Jedi ](https://jedi.readthedocs.io/en/latest/)engine and another is Microsoft Python Language Server (i.e. this project). IntelliCode requires the latter as it depends on specific data structures provided by MPLS. Language server does not show data identically to Jedi, so this is normal. Both components have limitations in different areas so which one to use depends on a specific project.

**Comment by jakebailey** [comment]
You've listed multiple issues.

The signature is changing because the language server is using the signature in the stub provided by pytorch. This is by design; the stub author should improve their stubs if it's not accurate enough for your use.

You also show multiple overloads for a function, but maybe we're picking the wrong one. You'd have to look at all four to see if one looks to match better.

The last is a display issue, where we use a different mechanism to convert docstringsd to markdown (IIRC jedi in VS Code just copies over the text as-is, so you're seeing a different issue where the wrong text is monospaced).

**Comment by BobAnkh** [comment]
Ok, thank you for explaining the situation for me, I believe things will be improved in the future for better user experience.
