### ISSUE TITLE
Disable automatic insertion of imports

### ISSUE THREAD

**Issue by mivade** [microsoft/python-language-server#1941]
Autocompletion in VS Code sometimes results in import statements getting inserted in alphabetical order at the top of the file I am working on. [From what I can tell](https://stackoverflow.com/a/60677521/6628184) this is not currently possible to disable. While I understand the utility of this behavior, I find it causes me more trouble than it's worth (e.g., selecting the wrong autocompletion result can lead to flake8 errors because imports get inserted that are quickly no longer needed). Please allow this feature to be disabled.

**Comment by jakebailey** [comment]
The language server does not use completions to auto-add imports, it uses quickfixes.

You should be able disable quickfixes in your editor specifically for python by setting:

```json
"[python]": {
    "editor.lightbulb.enabled": false
}
```

**Comment by jakebailey** [comment]
If you are seeing import suggestions in completions, then that is strange as we have not implemented that (and a screenshot would help).

**Comment by MikhailArkhipov** [comment]
Been a while, closing, assuming that suggesting above worked. Thanks.
