### ISSUE TITLE
Reduce diagnosticPublishDelay default

### ISSUE THREAD

**Issue by mjbvz** [microsoft/python-language-server#1944]
Issue Type: <b>Bug</b>

**Problem**
`python.analysis.diagnosticPublishDelay` defaults to 1000 milliseconds. This feels like quite a long time in practice, especially while waiting for an error you just fixed to be clear 

**Proposal**
Reduce the default value. Unless there's some reason this needs to be so high, a lower default provide the majority of users who will never change the default with a more responsive editing experience. Advanced users can still increase it if they want/need to
 
JS/TS users a default delay of around 200ms. If we get another document update before we finish computing the errors, we cancel the ongoing diagnostics request and queue up a new one

Extension version: 2020.4.68060-dev
VS Code version: Code - Insiders 1.44.0-insider (efd7548df65de8e775015b67863190e6bd4934fc, 2020-03-13T06:01:51.669Z)
OS version: Darwin x64 19.3.0

**Comment by MikhailArkhipov** [comment]
You can set it to the desired value. Actually, it is set to 1 sec by user requests: people did not want to see squiggles right away and error list updating and possibly flickering on every type.

**Comment by mjbvz** [comment]
Yes I understand it is configurable. But I suspect few people are changing this and the current default makes it seem like server is slow recomputing diagnostics. Some delay while the document is changing is good but 1sec feels surprisingly long in practice

**Comment by jakebailey** [comment]
Just to provide perspective, microsoft/vscode-python#2270 was the original issue. Back then, the only way to get diagnostics errors (syntax, lints) was from `pylint` or similar on save.

Given we've had real live syntax checking for a while, perhaps we should consider lowering this as I expect many users are more comfortable with seeing info earlier. May be useful to go see what other languages (TS, C#, etc) are doing in their LS/analysis implementations.

**Comment by MikhailArkhipov** [comment]
Perhaps 400 ms?

**Comment by jakebailey** [comment]
Sure, though I also wouldn't be opposed to 200ms if that's the debounce other languages are using. I haven't had time to try and find that out for myself.

**Comment by MikhailArkhipov** [comment]
0.5.46
