### ISSUE TITLE
Auto-Suggestion not working properly.

### ISSUE THREAD

**Issue by babul7154** [microsoft/python-language-server#1973]
Auto-Suggestion(like print function,array,arange,asarray and many more) is not working in properly .
I am using
 Version: 1.43.2 (system setup)
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
![print](https://user-images.githubusercontent.com/46845524/77761991-de7a1180-705e-11ea-9e67-c38f2c32b5b4.PNG)
![undefined variable](https://user-images.githubusercontent.com/46845524/77761994-e043d500-705e-11ea-8e7f-e1e5be03f087.PNG)
![arange](https://user-images.githubusercontent.com/46845524/77768740-ea6ad100-7068-11ea-89d2-4447406de0ff.png)

**Comment by jakebailey** [comment]
Please, do not delete the template. We require more information than just screenshots. The logs are important, mainly which interpreter is being used (if that happened to break).

https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#filing-an-issue

**Comment by babul7154** [comment]
I file this issue to https://github.com/microsoft/python-language-server/issues/1976.
When I change enviornment from python 3.7.7(Anaconda) to python 3.7.3 it works fine,so i think It is caused by python version.

**Comment by jakebailey** [comment]
Closing in favor of #1976, but you didn't exactly fill out the template there either. We need the logs...
