### ISSUE TITLE
Python jedi intellisense  is  stuck on  loading  after you preview the function document with the shortcut key

### ISSUE THREAD

**Issue by 1470391328** [microsoft/python-language-server#1978]
版本: 1.43.2 (system setup)
提交: 0ba0ca52957102ca3527cf479571617f0de6ed50
日期: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Some function documents that are not recognized by Jedi will cause Jedi to be stuck in the loading state for a long time.  expecially for 'pyi' file.  

For example ,  If you write the  code, “from PyQt5.QtWidgets import QApplication” ，and through the shortcut key to view the function document of QApplication, Jedi will be stuck in the loading state. Of course, this problem is not limited to pyqt5 module. Some  functions in other modules that are not recognized by Jedi will cause the same problem.

Although I found a similar problem in vscode python, I didn't get an effective reply. Maybe I should raise this problem here

Here is a  GIF demo file：

![GIF 2020-4-1 11-06-34](https://user-images.githubusercontent.com/33288114/78095468-a6c9eb80-7409-11ea-84b9-96ac94e4b71b.gif)

**Comment by jakebailey** [comment]
This isn't Jedi, this is the language server. They are different things. Are you sure you're using the language server and not jedi? You deleted our template, which includes important info we need to see what the issue is. https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#filing-an-issue

**Comment by 1470391328** [comment]
I am sorry.😂
