### ISSUE TITLE
Can't infer loop variable's type in a for-loop over file object

### ISSUE THREAD

**Issue by escape0707** [microsoft/python-language-server#1980]
## Environment data

- VS Code version: 1.44.0-insider Commit: d7d1147d6b764a48b789000c03088ee9afabcd8a
- Extension version (available under the Extensions sidebar): 2020.4.70601-dev
- OS and version: Windows_NT x64 10.0.18363
- Python version (& distribution if applicable, e.g. Anaconda): CPython 3.8.2
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): `false`
- Value of the `python.languageServer` setting: Microsoft

## Expected behavior

For the code below:

```py
f = open("numbers.txt", "r")
for line in f:
    arr = map(int, line.split())
```

Hover mouse on `line` should get `line: str`. And type `line.` should get suggestions like `split`, `strip`, etc.

![image](https://user-images.githubusercontent.com/11014745/78095400-69fdf480-7409-11ea-8e9f-a5ac336c870e.png)

![image](https://user-images.githubusercontent.com/11014745/78095379-5bafd880-7409-11ea-8110-c08e6d34107e.png)

## Actual behavior

None of these happens.

![image](https://user-images.githubusercontent.com/11014745/78095437-8732c300-7409-11ea-98e7-bf5b7a8bb606.png)

![image](https://user-images.githubusercontent.com/11014745/78095454-974aa280-7409-11ea-8324-84f67a2a72e0.png)

**Comment by asianboii-chen** [comment]
Hi, have you found a workaround to this besides manually declaring the type before a loop? This problem has now started to annoy me a lot too.

Thanks!

**Comment by escape0707** [comment]
@asianboii-chen Hi, you can try out Microsoft new language server Pylance, it doesn't have this problem anymore. I'm going to close this issue.
