### ISSUE TITLE
Find all References does not search in subdirectories

### ISSUE THREAD

**Issue by PhilipMay** [microsoft/python-language-server#1988]
## Environment data

- VS Code version: Version: 1.41.1
- Extension version (available under the Extensions sidebar): Version: 1.41.1
- OS and version: macOS 10.15.2
- Python version (& distribution if applicable, e.g. Anaconda): conda 3.6

When I use the "Find All References" function it seems only to find references in scripts in the same folder. The extension does not seem to look into subdirectories.

Is this known?

**Comment by MikhailArkhipov** [comment]
Looks like https://github.com/microsoft/python-language-server/pull/1686 broke it. Before

![image](https://user-images.githubusercontent.com/12820357/78722719-eb102c80-78de-11ea-8e72-22f8390cd254.png)

With the loop handling when I modify a file AND the file is a loop, then analysis runs on more than one file and it looks that sometimes `AddReference` does not go to the right place.

**Comment by jakebailey** [comment]
What's interesting is that presumably jedi/rope didn't handle this either, so this seems pretty exceptional.

**Comment by PhilipMay** [comment]
@AlexanderSher could you please have a look into this issue? @MikhailArkhipov sais it might be connected to a PR you have been involved. See here: https://github.com/microsoft/python-language-server/pull/1686

**Comment by jakebailey** [comment]
Alex is no longer working on this codebase. There's no reason to specifically ping people, we can handle that ourselves.

**Comment by PhilipMay** [comment]
> Alex is no longer working on this codebase. There's no reason to specifically ping people, we can handle that ourselves.

Great. I am sorry. Did not intend to interfere with your team processes.

**Comment by PhilipMay** [comment]
Hi, any updates or progress on this topic?
Thanks
Philip

**Comment by MikhailArkhipov** [comment]
0.5.51 in daily channel

**Comment by PhilipMay** [comment]
So this is fixed? Great! Thanks. 

How to I install this fixed version with VSCode?
When will it be released officially?

**Comment by MikhailArkhipov** [comment]
LS is updated independently from VS Code. It is already out in daily channel. If all good, we promote to `beta` and then to `stable`. Set
```json
"python.analysis.downloadChannel": "daily"
```
then restart. You should get 0.5.51.
