### ISSUE TITLE
Maintanance Status?

### ISSUE THREAD

**Issue by Matelasse** [microsoft/python-language-server#1990]
Commits have dropped lately, what's the status of the maintenance?

**Comment by gramster** [comment]
Thanks for asking! We are currently evaluating new approaches to static analysis that we think can provide a better user experience. We are not planning on adding new features while we complete this process, but we are still making bug fixes so please continue filing & upvoting issues that affect you.

**Comment by Matelasse** [comment]
@gramster Any updates regarding the evaluations? OSS appreciates transparency :ballot_box_with_check:

**Comment by gramster** [comment]
We should be in public preview very soon for Visual Studio Code. Visual Studio integration will happen after that.

**Comment by gramster** [comment]
Here we go for Visual Studio Code! Please try it out and let us know what you think.

https://devblogs.microsoft.com/python/announcing-pylance-fast-feature-rich-language-support-for-python-in-visual-studio-code/

It will be some time before we can bring this to Visual Studio but we plan to do so.
