### ISSUE TITLE
Unable to import packages within the same namespace

### ISSUE THREAD

**Issue by asierralozano** [microsoft/python-language-server#1994]
## Environment data

-   VS Code version: 1.44
-   Extension version (available under the Extensions sidebar): 2020.3.71659
-   OS and version: MacOS 10.15.4
-   Python version (& distribution if applicable, e.g. Anaconda):3.7.7 64-bit
-   Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): Language Server
-   Value of the `python.languageServer` setting: Microsoft

# Description

I have the following minimal structure in a multi-folder workspace: 
```
.
├── package_one
│   └── foo
│       └── bar
│           └── boo
│               ├── __init__.py
│               └── test_one.py
└── package_two
    └── foo
        └── test
            ├── __init__.py
            └── test_two.py
```

If I try to `from foo.test import test_two` within `test_one.py`, I got an `Unresolved import` error.

Probably I'm missing some multi-folder workspace information, but I'm guessing that, If I'm working in a structure like this, VSCode will expand the search for modules and packages in every folder root of the workspace, and not just in the PYTHONPATH folders.
Should I use a .env file for this scenario?

Thanks!

**Comment by jakebailey** [comment]
See: https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#unresolved-import-warnings

You're importing things relative to each of those folders. You'll have to explicitly add them as paths. The extension launches one LS per workspace, and each individual LS doesn't know that there's another folder that it needs to consider for import roots.

**Comment by asierralozano** [comment]
Thanks @jakebailey!
It looks like I was missing that info.
