### ISSUE TITLE
typeshed that built in Language Server is outdated.

### ISSUE THREAD

**Issue by linw1995** [microsoft/python-language-server#1995]
## Environment data

-   VS Code version: 1.44.1
-   Extension version (available under the Extensions sidebar): 2020.3.71659
-   OS and version: MacOS 10.15.4
-   Python version (& distribution if applicable, e.g. Anaconda): XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Relevant/affected Python packages and their versions: XXX
-   Relevant/affected Python-related VS Code extensions and their versions: XXX
-   Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): XXX
-   Value of the `python.languageServer` setting: XXX

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
XXX
```

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
XXX
```

**Comment by MikhailArkhipov** [comment]
https://github.com/microsoft/python-language-server/issues/1371
