### ISSUE TITLE
Unresolved imports always remain for third party packages

### ISSUE THREAD

**Issue by johntmyers** [microsoft/python-language-server#1996]
Issue Type: <b>Bug</b>

When starting a fresh project:

- create a venv
- set the venv to active, my settings are:

```
{
    "python.pythonPath": "venv/bin/python3"
}
```

- install some packages, I've installed `smart_open`, `requests`, and `pandas`

- code runs fine, it can find the packages as they are installed on the venv

Extension version: 2020.3.71659
VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:47:00.296Z)
OS version: Darwin x64 19.3.0

Here's my warnings along with the venv clearly selected...

![image](https://user-images.githubusercontent.com/9696606/79466172-38b92300-7fca-11ea-8ac6-d8f6814b4529.png)

**Comment by jakebailey** [comment]
See: https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md

Set `"python.analysis.watchSearchPaths": true` to reenable watching dependencies.

**Comment by johntmyers** [comment]
This is now a non-valid setting?

**Comment by jakebailey** [comment]
The setting is valid, it's just not exposed in the extension's settings UI.

**Comment by johntmyers** [comment]
So just to be clear, seeing it greyed out w/ this warning is expected behavior?

![image](https://user-images.githubusercontent.com/9696606/84534536-1422b400-acb8-11ea-8e41-2f0d69b389b7.png)

**Comment by jakebailey** [comment]
Yes.

**Comment by jsynowiec** [comment]
@jakebailey After one of the recent updates to either vscode, language-server or python extension, this no longer works ☹️. Both `python.analysis.watchSearchPaths` and `python.jediEnabled` settings are grayed-out and reported as unknown and a new setting is now available: `python.languageServer`.

With 
```
  "python.jediEnabled": false,
  "python.languageServer": "Microsoft",
  "python.analysis.watchSearchPaths": true,
```

Now all modules are reported as unresolved (it worked some time ago, when those settings were still _known_.

<img width="479" alt="image" src="https://user-images.githubusercontent.com/1029142/84882686-ea8ad380-b08f-11ea-821e-e0fdea48f4b9.png">

Imports are being resolved and their members available for autocompletion when using Jedi.

**Comment by MikhailArkhipov** [comment]
Correct, `python.jediEnabled` is no longer in use since it is sufficient to have `"python.languageServer": "Jedi"` or `"python.languageServer": "Microsoft"`. 

However, import resolution is completely unrelated to said settings. Settings only control which engine (Jedi or this LS) is activated.
