### ISSUE TITLE
Changes to Python virtualenv packages does not reflect in autocomplete or linter

### ISSUE THREAD

**Issue by kumarvaradarajulu** [microsoft/python-language-server#2003]
## Environment data

-   VS Code version: 1.44.2
-   Extension version (available under the Extensions sidebar): 2020.3.71659
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.1
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv
-   Relevant/affected Python packages and their versions: N/A
-   Relevant/affected Python-related VS Code extensions and their versions: vscode-python
-   Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): Language server
-   Value of the `python.languageServer` setting: Microsoft

## Expected behaviour

When a package is installed or removed from the virtual env, autocomplete suggestions should pop up or linting errors should be displayed respectively

## Actual behaviour

For newly installed packages autocomplete suggestions doesn't show up and for removed packages there are no linting errors

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

  1. Open a Python code base workspace.
  2. Change interpreter to any virtualenv
  3. Install any new package to the virtual env
  4. Try to import the new package and use in any python file, Auto complete suggestions do not show up instead linting errors are shown.

Upon restart of the window, it works fine.

**Comment by jakebailey** [comment]
This is expected behavior. If you want to watch the installed packages, see: https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md

#1996
