### ISSUE TITLE
bash: fork: retry: Resource temporarily unavailable

### ISSUE THREAD

**Issue by gaozhidf** [microsoft/python-language-server#2017]
## Environment data

- VSCode Version: 1.43.2
- Local OS Version: MacOS 10.15.4
![image](https://user-images.githubusercontent.com/5724898/79428302-8f3d5600-7ff8-11ea-9645-34d29650b131.png)
- Remote OS Version: Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
- Remote Extension/Connection Type: SSH

## Actual behaviour

1. vscode(almost python-language-server) created too much processes in my remote server, and make it resource temporarily unavailable
```
bash: fork: retry: Resource temporarily unavailable
bash: fork: retry: Resource temporarily unavailable
bash: fork: retry: Resource temporarily unavailable
bash: fork: retry: Resource temporarily unavailable
bash: fork: Resource temporarily unavailable
bash: wait_for: No record of process 2393
bash: fork: retry: Resource temporarily unavailable
bash: fork: retry: Resource temporarily unavailable
```
![image](https://user-images.githubusercontent.com/5724898/79427800-d70fad80-7ff7-11ea-847b-7a9daabe77b7.png)
![image](https://user-images.githubusercontent.com/5724898/79427853-e7c02380-7ff7-11ea-90e1-977035ac394b.png)

## Logs

```
XXX
```

## Code Snippet / Additional lnformation

```python
XXX
```

**Comment by gaozhidf** [comment]
also open the same issue(https://github.com/microsoft/vscode-remote-release/issues/2774) in vscode-remote-release

**Comment by jakebailey** [comment]
You ran `ps -eLf`, which shows threads. Each of those threads appear to be associated with the same LS process (17042). The language server doesn't fork (except perhaps to call out to python, which on UNIX-y systems is fork/exec).

Can you run `ps` without the flag that displays threads (or use a tool like `htop`) to confirm that it's really only a single LS process?

**Comment by MikhailArkhipov** [comment]
Does not seem to be LS related. There is no forking in the code. Sounds like VSC remoting issue.

**Comment by gaozhidf** [comment]
Sorry, so late to reply. 
@jakebailey it's only one LS process, but too many threads. And it took about 1 hour to make thread count from 4904 to 2139.
![image](https://user-images.githubusercontent.com/5724898/81541778-3b7b1e00-93a6-11ea-9fc8-ed02abc730ba.png)

**Comment by jakebailey** [comment]
Similar to #2007, then. Making too many threads. Thanks for checking.
