### ISSUE TITLE
Python language server eats my 10g+ memory

### ISSUE THREAD

**Issue by hujianxin** [Microsoft/python-language-server#202]
+ Python version: 3.7
+ Pipenv
+ Latest vscode 1.27.2 (1.27.2)
+ Latest vscode python

<img width="1394" alt="wx20181006-000650 2x" src="https://user-images.githubusercontent.com/9526904/46546600-12f28e80-c8fc-11e8-8125-1d74e5792b85.png">

**Comment by MikhailArkhipov** [comment]
#193

**Comment by MikhailArkhipov** [comment]
0.2.16 is now available on beta channel. 
```json
"python.analysis.downloadChannel": "beta"
```
