### ISSUE TITLE
PEP544, inheriting Protocol show error: Inheriting 'Protocol', which is not a class.

### ISSUE THREAD

**Issue by potens1** [microsoft/python-language-server#2021]
## Environment data

-   VS Code version: 1.44.2
-   Extension version (available under the Extensions sidebar): 2020.4.76186
-   OS and version: Arch
-   Python version (& distribution if applicable, e.g. Anaconda): python 3.8 (but should produce the same if typing_extensions are installed)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): pipenv
-   Relevant/affected Python packages and their versions: typing, mypy, typing_extensions
-   Relevant/affected Python-related VS Code extensions and their versions: XXX
-   Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): same result, tried both
-   Value of the `python.languageServer` setting: Microsoft

## Expected behaviour

No error should be raised since it is defined in PEP Protocol must be used this way

## Actual behaviour
error in Problems view:
Inheriting 'Protocol', which is not a class.

## Steps to reproduce:
from [PEP544](https://www.python.org/dev/peps/pep-0544/#defining-a-protocol)
```python
from typing import Protocol

class SupportsClose(Protocol):
    def close(self) -> None:
        ...
```
[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

Nothing relevant

</p>
</details>

<br />

<details>

<summary>
Output from <code>Console</code> under the <code>Developer Tools</code> panel (toggle Developer Tools on under <code>Help</code>; turn on source maps to make any tracebacks be useful by running <code>Enable source map support for extension debugging</code>)
</summary>

<p>
Hemmm, coredump opening the devtool under arch, too new kernel or glibc, have to investigate if it's electron side or vscode one (but I guess nothing relevant there either)

</p>
</details>

Please, if you correct the issue, could you do it that even on python version before 3.8, if using `typing_extensions` it work also ? (typing extensions were used by mypy before 3.8, I think: https://mypy.readthedocs.io/en/latest/protocols.html#simple-user-defined-protocols)

**Comment by karrtikr** [comment]
Looks like it's coming from the Python Language server.

**Comment by potens1** [comment]
Hello,
This is not to bump the issue, but, since it's coming from the language server, should not it be marked as "bug" ?

**Comment by MikhailArkhipov** [comment]
`typing` is implemented in code rather than actual parsing of the module so this is https://github.com/microsoft/python-language-server/issues/535. `Bug` is when something is supposed to work but doesn't. In this case `typing` support is not fully implemented by (current) design.

**Comment by MikhailArkhipov** [comment]
#535.
