### ISSUE TITLE
No help displayed in IntelliSense window for PySide2 modules

### ISSUE THREAD

**Issue by haimat** [microsoft/python-language-server#2023]
## Environment data

-   VS Code version: 1.44.2
-   Extension version (available under the Extensions sidebar): 2020.4.76186
-   OS and version: Ubuntu 18.04 LTS or Windows 10 (happens in both)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.2 64-bit (from Ubuntu's `apt`)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): n/a
-   Relevant/affected Python packages and their versions: PySide2 5.14.2.1 (installed via `pip`)
-   Relevant/affected Python-related VS Code extensions and their versions: n/a
-   Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): Language Server
-   Value of the `python.languageServer` setting: Microsoft

## Expected behaviour

Usually in the IntelliSense popup window I can see the name of the suggested attributes or methods etc., including parameters and a description of the item.

## Actual behaviour

For `PySide2` methods only very spare information is given:

![image](https://user-images.githubusercontent.com/6633976/81184843-2fabe800-8fb1-11ea-8f4b-f56b6c8bb650.png)

## Steps to reproduce:

Just install `PySide2`via `pip` and start to code.

**Comment by jakebailey** [comment]
QT is compiled code; it's likely the stub for it does not contain any documentation (or, if no stub, then the stub we scrape from a direct inspection doesn't contain a docstring either). If you go-to-def, where does this take you?

**Comment by haimat** [comment]
@jakebailey Indeed, it is a binary library, an `.so` file.
Is there any chance I can get those doc strings, or am I out of luck here?

**Comment by jakebailey** [comment]
We have a script which runs and tries to do its best to pull out the documentation. It's likely that what you see is all that is actually inside the .so file. You may be able to verify that it's the same by opening a REPL and running `help` on the method to see if it differs.

**Comment by haimat** [comment]
Well you are right, I am afraid there is not much info there with `help` either :(

**Comment by jakebailey** [comment]
Thanks for checking. Unfortunately we can't show docs that aren't there... The solution will have to be for that library to include more info in their compiled modules, or better yet ship type stubs with corresponding documentation.
