### ISSUE TITLE
Occasional tooltip failure: `Cannot read property 'createOnigString' of undefined`

### ISSUE THREAD

**Issue by narfanar** [microsoft/python-language-server#2024]
## Environment data

- Language Server version: 0.5.45.0
- OS and version: Windows 10 build 1909 local / Ubuntu 14.04 remote
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.7
- Other: Remote SSH to Ubuntu 14.04 LTS

## Expected behaviour

Tooltips always work.

## Actual behaviour

Tooltips occasionally fail and stop trying. No `Loading...` or anything else shows.

## Logs

```
-- Need to replicate.
```

## Code Snippet / Additional Information
```python
XXX
```

**Comment by MikhailArkhipov** [comment]
There is no such function in LS and by camel case naming it looks like JS/TS code.

**Comment by narfanar** [comment]
The message is from the dev console.

But it shows every time the tooltips start failing.
