### ISSUE TITLE
Getting unresolved-import on random lines (without import statements)

### ISSUE THREAD

**Issue by bjtho08** [microsoft/python-language-server#2035]
I have recently started experiencing false positives for "unresolved import" on random lines (sometimes even spanning two lines) for nonexisting imports.

## Environment data

- Language Server version: 0.5.50.0 
- OS and version: Ubuntu 16.04
- Python version: Python 3.8.2 64-bit

## Expected behaviour

The following code should be free of any errors:

```python
1    def scan_run(self):
2
3        '''The high-level management of the scan procedures
4        onwards from preparation. Manages round_run()'''
5        # pylint: disable=protected-access,import-outside-toplevel
6        import yaml
7        import pickle
8        from os.path import isfile
9        from tqdm import tqdm
10
11       from .scan_prepare import scan_prepare
12       self = scan_prepare(self)
13
14       # initiate the progress bar
15       if self.allow_resume:
16           self.pbar = tqdm(total=max(self.param_object.param_index)+1,
17                            disable=self.disable_progress_bar,
18                            initial=self.param_object.param_index[0])
19       else:
20           self.pbar = tqdm(total=len(self.param_object.param_index),
21                            disable=self.disable_progress_bar)
```

## Actual behaviour

The following erros are listed:
![unresolved-code](https://user-images.githubusercontent.com/885853/81904434-9047b000-95c3-11ea-8815-e490d86dc886.png)
![unresolved-import](https://user-images.githubusercontent.com/885853/81904341-6d1d0080-95c3-11ea-907b-cc0050506888.png)

None of the imports mentioned actually exist and neither does the import statements. Not in this file or any other.

**Comment by MikhailArkhipov** [comment]
Same as #2026
