### ISSUE TITLE
The Python Tools server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by kttn8769** [microsoft/python-language-server#2036]
## Environment data

- Language Server version: ??? (select 'Python' does not show anything in the console)
- OS and version: Windows 10 1919
- Python version (& distribution if applicable, e.g. Anaconda): 3.8.2 64 bit

## Expected behaviour

Python language server starts on opening an python file

## Actual behaviour

An pop-up says "The Python Tools server crashed 5 times in the last 3 minutes. The server will not be restarted." and language server won't start.

Re-installataion of Python extension did not help.

**Comment by jakebailey** [comment]
You'll have to provide the logs from the language server output window. The issue template would have included it, but I think you filled out your own. https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#filing-an-issue

**Comment by MikhailArkhipov** [comment]
Closing since there is no additional information available.
