### ISSUE TITLE
No syntax highlighting for custom class python

### ISSUE THREAD

**Issue by ramank775** [microsoft/python-language-server#2037]
As suggested [here](https://github.com/microsoft/vscode/issues/97910#issuecomment-630019335)
supporting the custom class highlighting requires semantic highlighting support.

Current behaviour
![image](https://user-images.githubusercontent.com/24293550/82052927-16561a80-96da-11ea-9820-1dee80c70348.png)

Expected behaviour
Just like the builtin class has highlight introduced the same for the custom class.

**Comment by jakebailey** [comment]
#1903
