### ISSUE TITLE
go to definition in calls into 3rd party libraries

### ISSUE THREAD

**Issue by myFree** [microsoft/python-language-server#2038]
I created my python environment using the below commands

```
mkdir gym
python3 -m venv gym
cd gym
source bin/activate
pip3 install pybullet
```
I have set these additional settings in the vscode python language server

```
python interpreter: ./bin/python3
python.venvPath: /home/repos/gym 
```

However; vs-code is not able to navigate to functions defined in 3rd party libraries (pybullet in my specific case)

Do I need to take additional steps to resolve the dependencies within vscode?

**Comment by MikhailArkhipov** [comment]
It depends if library has source in Python or is it compiled. There is nowhere to navigate to if library is compiled C++.

Also, please see https://github.com/microsoft/python-language-server/issues/1917.

**Comment by myFree** [comment]
Thank you for the rapid response

And yes; I think you are correct in pointing out there is very little python in the pybullet

I'm making slightly better progress cloning and navigating the C++ repo.

Thanks again
