### ISSUE TITLE
TestData should be platform independent

### ISSUE THREAD

**Issue by jakebailey** [Microsoft/python-language-server#204]
Right now, tests will fail to access `TestData` outside of Windows. There seem to be some path handling issues in `TestData.cs` and `PathUtils.cs`. The former hardcodes some `\` separated paths, and the latter seems to reimplement a bunch of things from `Path` and also do some trickery with forcing paths to be separated by `\`.

- Hardcoded path strings (like `src\UnitTests\TestData`) should be explicitly converted to the style of the platform running the tests.
- `PathUtils.cs` should be rewritten to not play around with the path separator, instead just being some helpers against the platform-independent path handling code from `Path`.

**Comment by AlexanderSher** [comment]
First issues is simple, you just use `Path.Combine("src", "UnitTests", "TestData")`.
As for the second issue, `TestData.GetTempPathUri` should be removed completely, and `GetTempPath()` should be simplified for the remaining call.
