### ISSUE TITLE
Autocompletion not working for numpy

### ISSUE THREAD

**Issue by kramarov-evg** [microsoft/python-language-server#2043]
## Environment data

-   VS Code version: 1.45.1
-   Extension version (available under the Extensions sidebar): 2020.5.78807
-   OS and version: Linux Mint 19.3
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Relevant/affected Python packages and their versions: numpy==1.18.1
-   Relevant/affected Python-related VS Code extensions and their versions: No
-   Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): Jedi
-   Value of the `python.languageServer` setting: Microsoft

## Expected behaviour

Autocompletion for `numpy.random.u` should return at least `uniform`, as it's obviously there
![image](https://user-images.githubusercontent.com/38880539/82303075-206e6680-99c3-11ea-9b09-13f0b583cc37.png)
Here's an output from interactive console in gnome-terminal upon pressing `Tab`
![image](https://user-images.githubusercontent.com/38880539/82303304-704d2d80-99c3-11ea-89f7-5a3b0b1ddf9d.png)

## Actual behaviour

`uniform` is not listed along with many other functions
![image](https://user-images.githubusercontent.com/38880539/82303480-ab4f6100-99c3-11ea-8500-963f3e1d363f.png)
And even after typing `numpy.random.u` there are no suggestions
![image](https://user-images.githubusercontent.com/38880539/82303566-c8842f80-99c3-11ea-919d-67633819c5d3.png)

## Steps to reproduce:

1. create conda environment with python==3.7.7 and numpy `conda create -n test python==3.7.7 numpy` and set it as active in `vscode`
2. Create test file (`test.py` in my case)
3. Enter some code containing numpy import mine is
```python
import numpy
a = numpy.random.u
```
4. Trigger automplete (`Ctrl+Space`)
![err_repr](https://user-images.githubusercontent.com/38880539/82305042-d2a72d80-99c5-11ea-9413-54a17d833af1.gif)

***However*** this doesn't happen when I use `virtualenv` environment

**Comment by rsokl** [comment]
See #1847

**Comment by jakebailey** [comment]
Yes, thanks.
