### ISSUE TITLE
Local stubs files autocomplete not working but go to definition does

### ISSUE THREAD

**Issue by Luis-Palacios** [microsoft/python-language-server#2047]
## Environment data

- Language Server version: 0.5.50.0   
- OS and version: Mac OS Catalina 10.15.4
- Python version: 3.8.2

## Expected behaviour

Autocomplete should display available properties in the stub file

## Actual behaviour

Autocomplete does not display available properties in the stub file

## Python Language Server Logs

```
Analysis of main (User) queued. Dependencies: test
Completions in file:///Users/luispalacios/source/repos/stub-autocomplete-example/main.py at (3, 4)
Analysis version 206 of 1 entries has started.
Analysis of main (User) on depth 0 completed in 0.14 ms.
Analysis complete: 1 modules in 0.56 ms.
Analysis version 206 of 1 entries has been completed in 0.43 ms.
[Info  - 4:20:39 PM] Predictions: add, setLevel, update, register, uppercase, data, connectionCls, append, send, refresh, log, exec_, run, register_opts, requires, addHandler, set, lower, run_doctest, setName
[Info  - 4:20:39 PM] Time taken to get predictions: 12 ms, Memory increased: 90112 bytes
[Info  - 4:20:39 PM] Deep learning IntelliCode recommendations service returned in 13 millis
IntelliCode identified 0 likely completion items.
Code Action in file:///Users/luispalacios/source/repos/stub-autocomplete-example/main.py at (3, 4) - (3, 4)
Code Action in file:///Users/luispalacios/source/repos/stub-autocomplete-example/main.py at (3, 4) - (3, 4)
```

## Code Snippet / Additional lnformation
Consider three files on the root directory:

* test.py
* test.pyi
* main.py 

**Test.py**
```python
class Foo():
    pass
```

**Test.pyi**
```python
class Foo():
    prop_1 = ... # type: typing___Text
    prop_2 = ... # type: typing___Text
```

**main.py**
```python
from test import Foo

foo = Foo()
foo. [no autocomplete for prop_1 or prop_2]
```

![image](https://user-images.githubusercontent.com/4844997/82503474-9acbe300-9ab6-11ea-874c-e1c647f80289.png)

![image](https://user-images.githubusercontent.com/4844997/82503554-bb943880-9ab6-11ea-9f25-55a4bdecaf92.png)

I'm guessing the stub file is being read because got to definition works

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/4844997/82504355-66f1bd00-9ab8-11ea-9986-1fd37ad3bc58.gif)

I tried adding extrapaths for autocomple but still doesn't work:
**settings.json**
```json
{
    "python.jediEnabled": false,
    "python.autoComplete.extraPaths": ["."]
}
``` 

And last if I set jediEnabled: true autocomplete does work:

![image](https://user-images.githubusercontent.com/4844997/82504457-af10df80-9ab8-11ea-9437-0430dfa58fef.png)

Why not directly add typing on the .py file itself? Well, this is actually a very reduced example to demonstrate the issue, I'm actually in a very similar setting like the one described here #2020. I'm generating classes from proto file trough protoc which uses metaclasses and autocomplete is not available however the dropbox team created a nice plugin to also generated the stubs files side by side but VS Code is not giving me autocompletion

**Comment by jakebailey** [comment]
This is covered under #1126/#2020, which has a WIP PR that isn't ready (as there are some difficulties when having two files to manage for a single user module).

**Comment by Luis-Palacios** [comment]
@jakebailey please correct me if I'm wrong but browsing trough existing issues and comments it seems to me that I could work around this If I were to have this auto-generated (code and stubs) as installed modules? Because I already have a private library that is installed trough pip and I could put the code and stubs there if that solves my issue

**Comment by jakebailey** [comment]
Yes, or define a specific extraPath where stubs are contained (thus also classifing it as library code).

The issue happens if the code is considered "user code", i.e. editable code. We can't handle it if you need to edit it without a full reload.
