### ISSUE TITLE
PythonVersions cannot be constructed on macOS

### ISSUE THREAD

**Issue by jakebailey** [Microsoft/python-language-server#205]
The `GetCPythonVersion` calls in `PythonVersions.cs` throw `NullReferenceException`, starting from where tests access `Required_Python36X` (and other versions), i.e. when the static class gets constructed. This causes all of the tests which use this class (most of them) to fail, as they cannot access the `PythonVersion` instance needed to, say, construct a `Server`.

This prevents testing on macOS and likely also Linux. (`cd src; dotnet test`)

**Comment by AlexanderSher** [comment]
`IPythonInstallPathResolver` is simply implemented only for windows.

**Comment by MikhailArkhipov** [comment]
We don't currently support `dotnet test`.

**Comment by jakebailey** [comment]
Seems that way. I get similar (but not the same) messages from PythonVersions running `dotnet test` on Windows. There other issues doing `dotnet test` like `UnitTests` targeting `netstandard` instead of `netcore` and missing some NuGet packages which I think are preventing it from running, but that's probably a different problem altogether than missing Python detection for OSs other than Windows during testing.
