### ISSUE TITLE
Python Intellisense stops working

### ISSUE THREAD

**Issue by rsalunga29** [microsoft/python-language-server#2051]
## Environment data

- Language Server version: 0.5.50.0   
- OS and version: macOS 10.15.3 (19D76)
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.5 (in Virtualenv)

## Expected behaviour

`Cmd + Space` should show autocomplete suggestions.

My Python setup for this project is in `venv` folder, I'm using VirtualEnv package. I also have specifieid in `.vscode/settings.json` to use the Python version in the `venv` folder.

I have to reload my VSCode just for it to work again, this has also been a recurring issue where I already reported multiple times from months ago, and still no response on how to fix this. This is getting more and more annoying every time.

## Actual behaviour

No autocomplete suggestions, Python intellisense stops completely. See below:
<img width="448" alt="Screen Shot 2020-05-26 at 4 32 38 AM" src="https://user-images.githubusercontent.com/20834464/82841905-425b7200-9f0a-11ea-93d9-f246990250ef.png">

## Logs

```
XXX
```

## Code Snippet / Additional lnformation

```python
XXX
```

**Comment by jakebailey** [comment]
Pretty sure this is #1900 (which you opened). We don't need two issues for the same bug.

As in https://github.com/microsoft/python-language-server/issues/1900#issuecomment-603045509 it may be multi-root, but in neither issue have you provided any logs or the info to look into this.
