### ISSUE TITLE
use ctrl + click jump to definition as deep as pycharm can do

### ISSUE THREAD

**Issue by fitzlm** [microsoft/python-language-server#2052]
Vscode can't jump to definition as deep as pycharm can do.

For example:
```python
from django.shortcuts import render
```

when i use 'ctrl + click' on "render", it can jump to the render function, but when 
i click the method "render_to_string()" inside render function, it can not jump to definition any more, the following is the code snippet:

```python
def render(request, template_name, context=None, content_type=None, status=None, using=None):
    content = loader.render_to_string(template_name, context, request, using=using)
    return HttpResponse(content, content_type, status)
```

Second example:
```python
import requests
res = requests.get('https://www.google.com')
```
when i use 'ctrl + click' on "get()", it can jump to the get() function, but when 
i click the method "setdefault()" or "request()" inside get() function, it can not jump to definition any more, the following is the code snippet:

```python
def get(url, params=None, **kwargs):
    kwargs.setdefault('allow_redirects', True)
    return request('get', url, params=params, **kwargs)
```

But when i use pycharm, it can jump to the definition of "render_to_string()" function. So everytime i want to dive into code definition, I must toggle between vscode and pycharm, I feel shame vscode does not have this function. If this extension can add this feature, it would be great!

**Comment by jakebailey** [comment]
This is expected behavior for performance reasons. Try setting the setting in this comment and see if it works.

https://github.com/microsoft/python-language-server/issues/840#issuecomment-600907450

**Comment by fitzlm** [comment]
@jakebailey 
Thanks for your help, its useful!

**Comment by fitzlm** [comment]
@jakebailey I have enabled jedi, but its hard to use, because sometimes  it need much time to load the other module when i click 'go to definition'.

**Comment by MikhailArkhipov** [comment]
Did you try setting
```json
"python.analysis.memory.keepLibraryAst": true
```

**Comment by fitzlm** [comment]
Yes, i have enabled the following:
{"python.analysis.memory.keepLibraryAst": true,
"python.analysis.memory.keepLibraryLocalVariables": true,}

**Comment by fitzlm** [comment]
I can't understand the following behavior, even though I have jumped into the code definition, when I try to enter again, it is still very slow.
![image](https://user-images.githubusercontent.com/59076301/84726065-98c64880-afbe-11ea-9200-ffaac7b87201.png)

**Comment by fitzlm** [comment]
I can't understand the following behavior, even though I have jumped into the code definition, when I try to enter again, it is still very slow.
![image](https://user-images.githubusercontent.com/59076301/84726335-3ae63080-afbf-11ea-86e9-1d8a01eae43d.png)

**Comment by fitzlm** [comment]
Even though I have jumped into the code definition, when I try to enter again, it is still very slow, as shown in the following gif.
https://github.com/fitzlm/gifs/blob/master/go-to-definition.gif
