### ISSUE TITLE
Unresolved local imports if Workspace Root is Drive root

### ISSUE THREAD

**Issue by ptyork** [microsoft/python-language-server#2066]
## Environment data
- Language Server version: 0.5.45.0
- OS and version: Windows 10 Pro 19041
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.3 64-bit (doesn't matter)

## Expected behaviour

Finds local packages / modules when opening a project when the workspace root is the root of a drive

## Actual behaviour

Reports local packages / modules as unresolved

## Logs

Nothing of relevance in this.

## Code Snippet / Additional lnformation

I have a hard time believing this has not been found before, so either my search prowess is in question or maybe something odd is happening with my environment. Though maybe it's just really a rare concept to have a Python project start at the root of a drive...in my case it's for a CircuitPython project. Anyway, basically, opening code with a Windows drive root (e.g., "F:\") as the workspace root results in local packages and modules not being resolved. If I clone this same exact directory structure to a subdirectory and open that cloned subdirectory as the workspace root, everything works as expected.

I can resolve this by adding in the drive to the extraPaths. However, it MUST be JUST the drive. e.g., "F:" works, but "." or "F:\\" or "F:/" does NOT work.

**Comment by MikhailArkhipov** [comment]
Yes, it is very unusual setup so it is unlikely to get much attention, especially when workarounds are available. I am going to close it for now.
