### ISSUE TITLE
Allow linting only on save, not while typing

### ISSUE THREAD

**Issue by ilyasotkov** [microsoft/python-language-server#2072]
I'd like to have the option to disable linting while typing.

For reference, microsoft/vscode-eslint allows the user to choose whether linting happens `onType` or `onSave`: https://github.com/microsoft/vscode-eslint/search?l=TypeScript&q=onType

**Comment by MikhailArkhipov** [comment]
This is unlikely to be added. Live checks are fundamental part of how LS works. It has no ability to delay until save.
