### ISSUE TITLE
Feature Request/Question: Extensible Code Inspections

### ISSUE THREAD

**Issue by tonybaloney** [microsoft/python-language-server#2074]
Hey team,

I'm working on [static-code analysis for Python](https://pycharm-security.readthedocs.io/en/latest/), specifically security related.

I've written a plugin for PyCharm, using their PSI API that enables you to traverse documents, and write custom inspections and alerts. For example, this function is a [custom expression visitor](https://github.com/tonybaloney/pycharm-security/blob/master/src/main/java/security/validators/TimingAttackInspection.kt#L26-L40).

I'm trying to figure out if it's possible to write a similar code analysis extension for VScode/Python? So far I've looked at:

- How the existing linters work, but they are spawned processes that the extension parses the text output, not integrated into the LSP
- How the LSP works and the Python Language Server, but this project isn't extensible

Is it possible to write custom visitors that inspect the Python code inside VScode and then issue warnings back to the editor (I guess as another extension?)?

**Comment by jakebailey** [comment]
This seems like general a "writing a analyzer for python in VS Code question". This project isn't extensible in the manner you'd need (and that currently is not planned; we have other things we are trying to sort out).

If you are specifically trying to integrate with VS Code, you'd do this by writing a VS Code extension and using their APIs to fetch documents, subscribe to changes, etc, and do the linting there (in TS, or call out to another tool). This would likely be the shortest path to "just make something work in VS Code".

Or, you write a language server which does a similar thing, and a small extension that just launches a language server. Multiple language servers are allowed to operate on the same files, and if your only goal is diagnostics this would be very workable. There are libraries out there to lower the amount of effort to make a LS, namely the vscode-languageserver packages in TS which do all of the document-management work for you. If you're wanting to use Python itself (makes sense), I'm uncertain if there's something with the same functionality, but LSs definitely exist in Python itself.

In general, the LSP is very close to the VS Code APIs. I think you'll have the most immediate path of just using a VS Code extension to do something similar to what you're doing in PyCharm, and move out to the LSP if needed later.
