### ISSUE TITLE
Hover over type alias does not work with Callable

### ISSUE THREAD

**Issue by pwinston** [microsoft/python-language-server#2076]
## Environment data

-   VS Code version: 1.45.1
-   Extension version: 2020.5.86806
-   OS and version: macOS 10.15.3
-   Python version: 3.8.1
-   Type of virtual environment used: conda
-   Jedi or Language Server?: Language Server
-   Value of the `python.languageServer` setting: Microsoft

## Expected behaviour

Hover over type alias shows the definition.

## Actual behaviour

When I hover over `Type1` in steps below it just shows `Type1`.

## Steps to reproduce:

New Python file type in:

```
from typing import Callable, Dict, List, Tuple, Type, Union
Type1 = Callable[[str], str]
Type2 = Dict[str, str]
Type3 = List[str]
Type4 = Tuple[str, str]
Type5 = Union[str, int]

Type1
```

Hover over the bottom `Type1` it just shows `Type1`:

<img width="522" alt="vscode - callable2" src="https://user-images.githubusercontent.com/4163446/84580585-3561ce00-ada6-11ea-93ef-f62ef1f00d7d.png">

But if you choose "peek definition" it has full information:

<img width="857" alt="vscode - peek" src="https://user-images.githubusercontent.com/4163446/84580589-427ebd00-ada6-11ea-9efa-915580ee6f55.png">

All other types work (Dict, List, Tuple, Untion) but not Callable.

**Comment by MikhailArkhipov** [comment]
It is known issue. Typings is specialized in code and Callable needs to be implemented, see #535
