### ISSUE TITLE
Steps to download and install and offline version of python language server 

### ISSUE THREAD

**Issue by sourabh2902** [microsoft/python-language-server#2078]
Hi 
I am using VSCODE with the Microsoft Python extension. For IntelliSense I wanted to use Microsoft-python language server (instead of default Jedi server) 
Our project code base is IP protected and can only be accessed on Linux remote machines. 
Hence we have VSCODE and python extension installed in our Linux environment, on these machines we don't have internet access. 
Can someone please help me to learn how I can download and install an offline version of Microsoft python language server? so that I can use it with our VSCODE installation with python extension? 

Today I am facing this error message : 
![image](https://user-images.githubusercontent.com/2882728/84830362-249b9d00-afde-11ea-95f6-aab1c3449093.png)

**Comment by jakebailey** [comment]
To my knowledge, the extension downloads using VS Code's builtin proxy system to handle these cases. Have you configured a proxy to facilitate downloads, or are you saying you have no internet whatsoever?

**Comment by sourabh2902** [comment]
@jakebailey 
Yes since our environment is IP protective we are not allowed to access internet from these machines. 
I can install something manually though (after moving the packages from non IP area to IP area)

**Comment by jakebailey** [comment]
I see. You can feasibly manually download and copy files by running VS Code on another machine with python and moving the `languageServer.<version>` folder to the other machine.

**Comment by jakebailey** [comment]
Though I will point out how odd it is that the extension is able to know which version to download, as that too is an internet access.

**Comment by sourabh2902** [comment]
> I see. You can feasibly manually download and copy files by running VS Code on another machine with python and moving the `languageServer.<version>` folder to the other machine.

So, this folder language server.<version> will be inside the extensions folder ?

**Comment by jakebailey** [comment]
Inside the `ms-python.python` directory, yes.

**Comment by sourabh2902** [comment]
Hi @jakebailey 
Thanks for sharing the info, I followed the steps below to install the language server but looks like there is a failure at the start of the client. 
Steps: 

1. Downloaded the Python-Language-Server-win-x64.0.5.45.nupkg 
2. Created the following directory called languageServer in the ~/.vscode/extensions/ms-python.python-2020.5.86806/
3. Unzipped the contents of the downloaded pkg into the directory from step 2 . 
4. Changed the access of the following using chmod +x. 
-rwxrwxr-x 1 msourabh users  73K Mar 20 16:00 Microsoft.Python.LanguageServer.pdb
-rwxrwxr-x 1 msourabh users 176K Mar 20 16:00 Microsoft.Python.LanguageServer.exe
-rwxrwxr-x 1 msourabh users 250K Mar 20 16:00 Microsoft.Python.LanguageServer.dll
5. Disabled jedi 

![image](https://user-images.githubusercontent.com/2882728/84960836-9b589900-b0b7-11ea-9372-1461acb20720.png)


6. Relaunched vscode , 
7. I am seeing the following messages in the output for python : 
![image](https://user-images.githubusercontent.com/2882728/84960820-867c0580-b0b7-11ea-9902-8a6db6e4cd99.png)

8. I am seeing the following message in output for python language server 
![image](https://user-images.githubusercontent.com/2882728/84960653-1bcaca00-b0b7-11ea-981e-534aa206ad48.png)


Am I missing any steps ?

**Comment by jakebailey** [comment]
Your logs imply you're not on Windows.

**Comment by sourabh2902** [comment]
Yes, that is correct this is not Windows. For Linux do I need to follow different steps> 
I took reference from here: https://github.com/microsoft/python-language-server/issues/1698

**Comment by jakebailey** [comment]
Each build is platform specific; you'd want to get the linux one, or do my suggested method of letting the extension download the LS and copying it from one to the other (rather than a direct extraction and chmod).

**Comment by sourabh2902** [comment]
I apologize for this silly question, but can I get a link or some info from where I can download the following package: Python-Language-Server-linux-x64.0.5.50.nupkg ? At present I am unable to install this from any of the linux machines

**Comment by MikhailArkhipov** [comment]
https://github.com/microsoft/vscode-python/blob/master/src/client/activation/languageServer/languageServerPackageService.ts

https://github.com/microsoft/vscode-python/blob/master/src/client/activation/languageServer/platformData.ts

URLs: https://github.com/microsoft/python-language-server/issues/1916. Specific version is not guaranteed to exist, we do not keep all versions and old ones are getting trimmed.

URL the same as Windows, package name construction by channel and platform see the code. Example
https://pvsc.blob.core.windows.net/python-language-server-stable/Python-Language-Server-linux-x64.0.5.50.nupkg

**Comment by MikhailArkhipov** [comment]
Closing.

**Comment by sourabh2902** [comment]
Thanks I was able to download and install in IP protected area. 
I am still facing issues related to IntelliSense I will open another issue ticket for that
