### ISSUE TITLE
When can I get the the same intelisense experience like pycharm?

### ISSUE THREAD

**Issue by CatNofishing** [microsoft/python-language-server#2084]
I really like vscode for writing python scripts. I have migrated part of my development work to vscode. I think vscode is great in every aspect except smart completion. Sometimes, the smart completion is often stuck in the loading state without even prompting, or it causes my cpu and memory to be full, which leads to my coding experience is very poor, I have to re-migrate the project to pycharm. This is really troubling me, but I look forward to your work.

**Comment by jakebailey** [comment]
What is "smart completion" or "smart prompt"? We offer completion (that's the core thing in an LS), but can you clarify what you mean?

**Comment by CatNofishing** [comment]
Sorry, I  mean Code IntelliSense like autocomplete，suggestions, snippets.
