### ISSUE TITLE
Platform-Specific Imports - Ignore 'Unresolved Import' for specific package

### ISSUE THREAD

**Issue by jaymegordo** [microsoft/python-language-server#2098]
I have some files which have imports for either mac or windows.

Is there a way to disable the 'unresolved import' warning for specific package imports?

<img width="452" alt="Screen Shot 2020-07-02 at 10 53 24" src="https://user-images.githubusercontent.com/29611875/86393727-52294d00-bc52-11ea-95ac-c72364fa65fc.png">

something like:
"python.languageServer.disabledImportWarnings": ["win32com", "aeosa"]

**Comment by erictraut** [comment]
One option is to replace the `f.is_mac()` and `f.is_win()` calls with `sys.platform == 'darwin'` and `sys.platform == 'win32'` respectively. Pylance will recognize these built-in conditional checks and analyze only the portions of the code that apply to your current platform.

**Comment by jakebailey** [comment]
If you add `# noqa` to the line, does the message disappear?

**Comment by jaymegordo** [comment]
@erictraut @jakebailey Both solutions work, very helpful thanks!
