### ISSUE TITLE
Missing package.json in language server implementation

### ISSUE THREAD

**Issue by kaushalvivek** [microsoft/python-language-server#2104]
Facing issues in setting up the language server implementation on OS X. Following the steps mentioned in the [CONTRIBUTING.md guide here.](https://github.com/microsoft/python-language-server/blob/master/CONTRIBUTING.md)

On executing ```dotnet build```, I am getting the following error:
```bash
Couldn't find 'project.json' in current directory
```
Is there something I am missing?

EDIT : executing this from ```python-language-server/src/LanguageServer/Impl```

**Comment by MikhailArkhipov** [comment]
You need to build solution, so `dotnet build` from `python-language-server/src`.

**Comment by kaushalvivek** [comment]
@MikhailArkhipov , thanks for your reply, but there isn't a ```package.json``` file in ```python-langugage-server/src``` either, and hence, ```dotnet build```, as you'd expect, doesn't work.

**Comment by MikhailArkhipov** [comment]
`dotnet build` recognizes VS solutions.

![image](https://user-images.githubusercontent.com/12820357/88079301-5dc1b280-cb32-11ea-9a77-85b09d673bb5.png)

**Comment by MikhailArkhipov** [comment]
Usually we build from VS during development. Automated pipeline does `dotnet publish src/LanguageServer/Impl/Microsoft.Python.LanguageServer.csproj`

**Comment by MikhailArkhipov** [comment]
Tried on Mac, result is identical

**Comment by kaushalvivek** [comment]
Figured it out, thanks for your help @MikhailArkhipov !
