### ISSUE TITLE
Installing packages requires restart in order for autocomplete and no errors

### ISSUE THREAD

**Issue by johntmyers** [microsoft/python-language-server#2107]
Issue Type: <b>Bug</b>

When installing packages, VSCode has to be restarted in order for the import errors to go away and to get autocompletion to work.

Simple example:

```
pip install requests
```

![image](https://user-images.githubusercontent.com/9696606/88201947-2298af80-cc16-11ea-8218-c3f984563a0d.png)

Instant import errors:

Extension version: 2020.7.94776
VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:18:50.054Z)
OS version: Darwin x64 19.5.0

**Comment by jakebailey** [comment]
This is intended behavior, see https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#completions-do-not-update-andor-import-is-still-being-reported-as-unresolved-after-pip-install.

But I would try Pylance, which does not have the underlying issues which prevent this feature from being enabled by default.
