### ISSUE TITLE
How is PythonLanguageVersion set?

### ISSUE THREAD

**Issue by matthuszagh** [microsoft/python-language-server#2109]
The python-language-server linter is emitting errors related 3.x features. For instance: `parameter annotations require 3.x`. The python available in my path is v3.8. I took a quick look at the source code and it appears that this is being caused by `Is2x()` evaluating to true, which in turn is caused by the setting of `PythonLanguageVersion`. However, I wasn't able to figure out how this is set. Presumably, it is not determined by the version of the path python executable. Is it set at build time? I don't have a version of Python available when building this (I use NixOS), so that might explain it. If not, how is it set?

I'm using NixOS to install this and using it with the Emacs-LSP client.

Thanks!

**Comment by jakebailey** [comment]
The canonical way is to provide the version and path in the initialization options, as the version must be known at early initialization (you can see the initialization options in vscode-python as an example). If not provided, it will try and use `python` from PATH, though I'm unsure if the version is read.

**Comment by matthuszagh** [comment]
Thanks @jakebailey!
