### ISSUE TITLE
The setting '"python.autoComplete.addBrackets": true' doesn't work

### ISSUE THREAD

**Issue by Brodersen** [microsoft/python-language-server#2110]
**Product and Version** [VS/VSCode]:
**OS Version** [macOS/Windows]: macOS Catalina, 10.15.6 (19G73)
**IntelliCode Extension Version**: v1.2.9
**Target Platform or Language** [e.g. Node.js]: Python 3.8.5

**Steps to Reproduce / Scenario:**

1. Have the latest version of everything (macOS, vscode, python 3, Python (extension) installed).
2. To go settings and look for "python.autoComplete.addBrackets" and check it (set to 'true').
3. Create a new python file (e.g. hello_world.py)
4. Type on the first line of the hello_world.py file you created "pri" to expect autocomplete to show "print".
5. Click "print" and expect to see "print()".

This does not work. Instead you only get "print" (without brackets) although you enabled python brackets in Settings.

**Comment by MikhailArkhipov** [comment]
This is not Pylance, so the error is unrelated. Brackets issue with this server should be fixed in most recent Python extension.
