### ISSUE TITLE
High memory useage

### ISSUE THREAD

**Issue by grape0919** [microsoft/python-language-server#2116]
I had a memory leak.
I referenced #2007 and fixed it.

But I think `python.analysis.downloadChannel` setting option is deprecated recently
![image](https://user-images.githubusercontent.com/30318115/91649463-92207b00-eaaf-11ea-8ff4-198502500e28.png)

So I have a memory leak again.
How do I fix it?

**Comment by hyq1860** [comment]
this question is again

**Comment by MikhailArkhipov** [comment]
Download channel has never been public option so it is `unknown` by design. There are no updates newer than 0.5.51.
Have you tried `Pylance` language server?

**Comment by grape0919** [comment]
Thanks. I fixed it
