### ISSUE TITLE
Using the language server with sublimetext3 and LSP

### ISSUE THREAD

**Issue by espositofulvio** [Microsoft/python-language-server#212]
This is just a note I leave here for anyone would like to use this server with SublimeText and the LSP plugin, which I managed to setup correctly on SublimeText 3.1.1 on Windows 10 April 2018 update.

**Assumptions**:
* you have the .NET core runtime installed
* you have built the server yourself in C:\python-language_server\ (replace Debug with Release in the path if you build a release).

Add the following to LSP.sublime-settings - User

(replace the Version bit with your system python version)
```json
{
  "clients":
  {
    "mspyls":
    {
      "command": [ "dotnet.exe", "exec", "C:\\python-language-server\\output\\bin\\Debug\\Microsoft.Python.LanguageServer.dll" ],
      "scopes": ["source.python"],
      "syntaxes": ["Packages/Python/Python.sublime-syntax"],
      "languageId": "python",
      "initializationOptions": 
      {
        "interpreter": 
        {
          "properties": 
          {
            "UseDefaultDatabase": true,
            "Version": "3.7"
          }                    
        }
      }
    }
  }
}
```
I figured out the Version isn't inferred by the server, so I had to set it explicitly.
This will use the python interpreter in the path. You can add "PythonInterpreter" in the "properties" section with the path to a different interpreter if you are using, for example, a virtual env.
I usually add this in the project file to enable a virtual env:

```json
    "settings":
    {
        "LSP":
        {
            "mspyls":
            {
                "enabled": true,
                "initializationOptions": 
                {
                    "interpreter": 
                    {
                        "properties": 
                        {
                            "InterpreterPath": "D:\\Work\\RMS\\software\\api_fake\\.env\\Scripts\\python.exe",
                            "UseDefaultDatabase": true,
                            "Version": "3.7"
                        }                    
                    }
                }
            }
        }

    }
```

I hope this could help other people! I don't have a linux or MacOS machine available, but I guess adjusting the paths should be the only change required on those platforms.

**Comment by MikhailArkhipov** [comment]
Awesome. Do you mind adding `using in sublime.md` (or something similar) file with instructions to the root next to the `contributing.md`? :-). Or we can do it ourselves.

**Comment by espositofulvio** [comment]
Will do :) I'll write it up more organically and make a pull request soon

**Comment by MikhailArkhipov** [comment]
Closing since instructions are now up. Thanks!
