### ISSUE TITLE
Improve type hints for builtin types

### ISSUE THREAD

**Issue by cdce8p** [microsoft/python-language-server#2129]
With Python 3.9 it is now possible to use builtin types for type hints, [PEP 585](https://www.python.org/dev/peps/pep-0585/).
Builtin types like `dict`, `set`, `list`, ... could expose additional information like their `typing` counterparts do.

```py
import typing

t1: typing.Dict[int, int]
t2: dict[int, int]
```

![Type_hints_builtin_2020-10-20](https://user-images.githubusercontent.com/30130371/96585597-1b9a3f80-12e0-11eb-942d-edfb84db1463.gif)

--
Tested with:
Python 3.9.0
Language Server 0.5.59

**Comment by MikhailArkhipov** [comment]
Try Pylance language server, it is available on the marketplace, it supports 585.
