### ISSUE TITLE
After pressing enter, Pylance cannot format the code

### ISSUE THREAD

**Issue by zhiyiYo** [microsoft/python-language-server#2132]
## Environment data

- Language Server version: **Pylance v2020.11.0**
- OS and version: **Windows_NT x64 10.0.19042**
- Python version (& distribution if applicable, e.g. Anaconda): **v2020.10.332292344**

## Expected behaviour

When I select Microsoft language server, the code can be automatically formatted by pressing enter.
![自动格式化](https://user-images.githubusercontent.com/65096819/98328814-9928b400-2031-11eb-9fc5-47f773a62fd0.gif)

## Actual behaviour

When I switched to the Pylance language server, the code could not be formatted by pressing enter.
![没有自动格式化](https://user-images.githubusercontent.com/65096819/98328874-bf4e5400-2031-11eb-9e91-353bc7eb8c1c.gif)

**Comment by MikhailArkhipov** [comment]
Please file Pylance issues at https://github.com/microsoft/pylance-release/issues. This is not Pylance project. Thanks.
