### ISSUE TITLE
Dataclass parameters with init=False

### ISSUE THREAD

**Issue by DolajoCZ** [microsoft/python-language-server#2140]
Hello, is it possible to hide parameters of python dataclass which are defined as fields with parameter init=False from class description? In attached picture is par_c shown although init=False. It can be misleading.

![image](https://user-images.githubusercontent.com/23177301/105971775-31f82a00-608b-11eb-9d61-cb0ff2f3e491.png)

Thank you

**Comment by jakebailey** [comment]
Consider trying [Pylance](https://github.com/microsoft/pylance-release), which has dataclass support including what you've described here:

![image](https://user-images.githubusercontent.com/5341706/106036165-ccf00480-6089-11eb-9b03-f7e284f7fd31.png)

**Comment by DolajoCZ** [comment]
> Consider trying [Pylance](https://github.com/microsoft/pylance-release), which has dataclass support including what you've described here:
> 
> ![image](https://user-images.githubusercontent.com/5341706/106036165-ccf00480-6089-11eb-9b03-f7e284f7fd31.png)

Thank you @jakebailey for advice
