### ISSUE TITLE
opencv-python not autocompleting macos Big Sur using Anaconda, python 3.8.5

### ISSUE THREAD

**Issue by KeygenLLC** [microsoft/python-language-server#2167]
## Environment data
Python interpreter path: /opt/anaconda3/envs/MASTER/bin/python
I have set `"python.defaultInterpreterPath": "/opt/anaconda3/envs/MASTER/bin/python3.8"` in settings.json.

I also tried: 
```json
"python.autoComplete.extraPaths": [
        "/opt/anaconda3/envs/MASTER/lib/python3.8/site-packages/cv2/cv2.cpython-38-darwin.so",
        "/opt/anaconda3/envs/MASTER/lib/python3.8/site-packages/cv2"
    ],
```

There is no line that says "Microsoft Python Language Server version X "

```ini
Experiment 'pythonaa' is active
Experiment 'pythonTensorboardExperiment' is active
Experiment 'PythonPyTorchProfiler' is active
Experiment 'pythonDeprecatePythonPath' is active
Experiment 'pythonRunFailedTestsButtonDisplayed' is active
Experiment 'pythonRefreshTestsButtonDisplayed' is active
Experiment 'pythonRememberDebugConfig' is active
```

- Language Server version: ?
- OS and version: macOS 11.6
- Python 3.8.5 shows in Terminal with `python -V` with env active, (displayed on bottom bar of vscode as Python 3.8.9)
- conda 4.10.3

## Expected behaviour

I type `cv2.` and menu should show what is available.

## Actual behaviour

It shows nothing in the autocomplete menu that relates to opencv. It only recognizes `cv2`.

## Logs

"python.analysis.logLevel": "Trace" is not working. The Python Test Log is empty and the setting is grayed out in settings.json

## Code Snippet / Additional lnformation
this code had no autocomplete:
```python
img = cv2.imread(tiff, cv2.IMREAD_UNCHANGED)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
```

<img width="391" alt="Screen Shot 2021-12-04 at 5 14 14 PM" src="https://user-images.githubusercontent.com/92394639/144726393-f223ce82-42e5-459e-bfb0-6a42828b0076.png">
<img width="627" alt="Screen Shot 2021-12-04 at 5 26 04 PM" src="https://user-images.githubusercontent.com/92394639/144726396-5b7a6e8e-f709-40fe-8f77-d1abe31cff29.png">

**Comment by gramster** [comment]
Are you using VS Code? This is the repo for the language server in Visual Studio prior to VS 2022.

**Comment by judej** [comment]
Thank you for the report. This project is no longer active. If you are using the Python language server in VSCode, the language server you are using is Pylance and please the http://github.com/microsoft/pylance-release to report issues. 

If you are using Visual Studio, then, please use http://github.com/microsoft/PTVS to report issues.

thank you
