### ISSUE TITLE
Fix ArgumentException uses with hardcoded paramName

### ISSUE THREAD

**Issue by jakebailey** [microsoft/python-language-server#228]
There are loads of places across the repo which use ArgumentException/ArgumentNullException/etc with hardcoded parameter names. These should be updated to use `nameof` rather than relying on a string literal with the right contents.

**Comment by jamesralstin** [comment]
Hey @MikhailArkhipov, per your suggestion, I am going to work on this issue and submit a separate pull-request for this issue from the pull-request I created for #647 . I need to make two FOSS contribution for a course I am currently taking and this will be a great second issue for me. Thanks for all your help!

**Comment by MikhailArkhipov** [comment]
https://github.com/microsoft/python-language-server/pull/1187 fixed this
