### ISSUE TITLE
Decorator test fails

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/python-language-server#230]
`Message: Expected module2.g to have type 'Function', but it has none.`

**Comment by jakebailey** [comment]
Interestingly, if I set a breakpoint at the first `Should()` line, then debug the test and hit "continue" with a few seconds of delay between each press, the test passes. If I just run the test normally, then the (1, 0) permutation always fails.

**Comment by AlexanderSher** [comment]
This test passes for me on machine with more cores.

**Comment by MikhailArkhipov** [comment]
It just needs to `WaitForCompleteAnalysisAsync`, I have it fixed.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/python-language-server/pull/251
