### ISSUE TITLE
addBrackets adds parens to function override completions

### ISSUE THREAD

**Issue by jakebailey** [Microsoft/python-language-server#241]
Example:

![bad_bracket](https://user-images.githubusercontent.com/5341706/46824222-0aa7b280-cd45-11e8-9b09-0e0f08d10417.gif)

Note the extra parens added after the completed function.

Since this involves override completion, it may be better to wait to fix this until #240 is merged (to prevent conflicts).

**Comment by MikhailArkhipov** [comment]
Probably because snippet already has brackets.

**Comment by jakebailey** [comment]
The string that the override completion code returns doesn't include the extra parens. The parens are being added here, before the editor gets anything: https://github.com/Microsoft/python-language-server/blob/master/src/LanguageServer/Impl/Implementation/Server.Completion.cs#L67
