### ISSUE TITLE
 Settings Go to definition shows module itself as definition

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/python-language-server#247]
Originally reported by @karthiknadig on https://github.com/Microsoft/vscode-python/issues/2867
## Environment data

- VS Code version: 1.28.0
- Extension version (available under the Extensions sidebar): 2018.9.0
- OS and version: windows
- Python version (& distribution if applicable, e.g. Anaconda): 3.7
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Relevant/affected Python packages and their versions: ptvsd==4.1.3

## Actual behavior

Go to definition shows multiple definitions, even though there is only one. See image below.
![image](https://user-images.githubusercontent.com/3840081/46835545-55d0be00-cd63-11e8-9a74-25985e1e919d.png)

## Expected  behavior

Should show single definition.

## Steps to reproduce:

1. Clone `ptvsd` master
2. Create a python file in pytests folder.
3. Add following code:
```python
import pytest
from ptvsd.socket import create_server

class MyTest(object):
    def test_something(self):
        sock = create_server(('localhost', 5678))
        assert sock is not None
```
4. right click on `create_server` and hit 'Go To definition'

**Comment by MikhailArkhipov** [comment]
No longer reproes
