### ISSUE TITLE
Fix List[T] not inheriting list/List methods

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/python-language-server#260]
Microsoft/vscode-python#2446

E.g.
```python
from typing import List

def func(a: List[str]):
    pass
```
Currently `a` has no completions instead of having completions for a list.

See [generics from PEP 484](https://www.python.org/dev/peps/pep-0484/#generics) for some details.

**Comment by MikhailArkhipov** [comment]
![image](https://user-images.githubusercontent.com/12820357/46971582-3c848600-d071-11e8-8e7e-96277ec366b6.png)

**Comment by jakebailey** [comment]
Yeah, this works for both of those two cases:

![list](https://user-images.githubusercontent.com/5341706/46971837-f7ad1f00-d071-11e8-8e9a-1faac9bb634c.gif)

**Comment by jakebailey** [comment]
Actually, reading through that vscode-python bug, the user is expecting to see list functions on a, not just `__getitem__` and `__iter__`. I'm not sure if that's exactly correct, though, since I don't think the generic type assumes anything other than "I can be indexed" and "I can be iterated over".

**Comment by jakebailey** [comment]
Reading through that thread also shows that `def func(a: List)` will show completions for `a` as though it were `list`, but `def func(a: List[str])` will not, which seems to indicate that there's something else going on here.

**Comment by jakebailey** [comment]
`typing.py` says:

https://github.com/python/typing/blob/9443f261f5b03c2f0535cdd9c1e7a14c0fdb5952/src/typing.py#L1883-L1891

Which to me implies that it should be inheriting everything from `list`.

**Comment by brettcannon** [comment]
I have updated my comment to drop the `a[0]` case as that case works as demonstrated, but as @jakebailey realized the `a` case is not working as it should be showing all completions that `list` would show.
