### ISSUE TITLE
Question: download location

### ISSUE THREAD

**Issue by yyoncho** [Microsoft/python-language-server#267]
I am interested in testing in in Emacs `lsp-mode`, can you point me to the download location?

**Comment by MikhailArkhipov** [comment]
Download is performed by the Python extension to VSC so it stores URLs. The code is in

https://github.com/Microsoft/vscode-python/blob/master/src/client/activation/languageServer/languageServerPackageRepository.ts
https://github.com/Microsoft/vscode-python/blob/master/src/client/activation/languageServer/languageServerPackageService.ts

**Comment by yyoncho** [comment]
Thanks!

**Comment by MikhailArkhipov** [comment]
Please note that those can change at any time. We will try and set up nuget feed when we deem LS is ready to general consumption.
