### ISSUE TITLE
Huge memory usage when analysis 9 lines python code

### ISSUE THREAD

**Issue by jxww** [Microsoft/python-language-server#278]
Hi everyone,

I am writing some python code using vscode with python-language-server extension and just find out  `Microsoft.Python.LanguageServer.exe` eat all of my memory (over 8g) when I open a specific file. I finnally reduced the problematic file to the following 9 lines and the language server still use over 2.6g memory. 

Python code:

    class A():
        def test(self, test):
            return test
    class B():
        def test(self, test):
            return test
    class C():
        def test(self, test):
            return test

The interesting thing is that if I remove any of the class/method or change any of the `test` token in the code, then the language server will run normally with only 100+m memory cost.

My environment is as follow:

- vscode 1.28.2
- python extension 2018.9.0 with language server 0.1.42
- windows 10 pro 64 bit
- python 3.6

![image](https://user-images.githubusercontent.com/26917526/47133809-f6cbf580-d2dc-11e8-95e5-8bdcdf08f428.png)
![image](https://user-images.githubusercontent.com/26917526/47133818-021f2100-d2dd-11e8-9f5a-cdf9e39fbe44.png)

I think the may be something wrong in code analysis. Anyone can fix it? Thanks very much.

**Comment by jakebailey** [comment]
I can reproduce this against both the released version (on my personal machine) and master (on my dev machine). Sometimes I can cut and paste the code a few times to make it go past the ~2.5GB of usage, or even drop down to ~40MB.

I did a memory snapshot when usage is high, and it seems like most of the memory is storing JSON-related objects (`Newtonsoft.Json.Linq.Property`, `JValue`, `JObject`, dicts/arrays of those objects). AFAIK the only place we're using JSON is for RPC.

Actually looking at some of the objects shows that they're cyclic. Maybe they're not getting GC'd properly.

**Comment by jakebailey** [comment]
I'll look at this more tomorrow (so it's not midnight), but after following the "path to root" for many of these objects, they all seem to lead up to Actions in StreamJsonRpc which are holding onto JsonRpcMessages with their status set to "RanToCompletion".

**Comment by jakebailey** [comment]
#280 fixes it. Your example now sits at a nice 26MB on my system. 😄 

Thanks for providing a concise way to reproduce the issue.

**Comment by jxww** [comment]
Thank you for all of your nice and quick response. 
I updated my python extension to 2018.9.1(with python language server 0.1.42) just now and still found this problem. Is this fix merged to the new release version?

**Comment by MikhailArkhipov** [comment]
@jxww - no. Extension only updates LS with stable releases while this change is less than a day old. The change will be available for insiders build of the extension some time in the next few days. We do not push beta bits to stable releases.
