### ISSUE TITLE
Add support for Implicit Namespace Packages

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/python-language-server#288]
- Specification: https://www.python.org/dev/peps/pep-0420/
- General information about packages: https://docs.python.org/3/tutorial/modules.html#packages
- Import on Case-Insensitive Platforms: https://www.python.org/dev/peps/pep-0235/

**Comment by AlexanderSher** [comment]
**First key difference:** namespace packages can be presented in several directories. Consider the following folder structure:
```
├─ package1
│  └─ parent
│     └─ child
│        └─ one.py
├─ package2
│  └─ parent
│     └─ child
│        └─ two.py
└─ root
   └─ app.py
```
If `app.py` contains the following code:
```python
import sys
sys.path += ['path_to_project\\package1\\', 'path_to_project\\package2\\']
import parent.child.one
import parent.child.two

print(parent.child.__path__)
try: 
    print(parent.child.__file__)
except AttributeError:
    print("parent.child have no __file__ attribute")
print(parent.child.one.__file__)
print(parent.child.two.__file__)
```
executing `python root\app.py` will show
```
_NamespacePath(['path_to_project\\package1\\parent\\child', 'path_to_project\\package2\\parent\\child'])
parent.child have no __file__ attribute
path_to_project\package1\parent\child\one.py
path_to_project\package2\parent\child\two.py
```

**Comment by AlexanderSher** [comment]
**Second key difference**: `from package import *` doesn't import anything unless other imports provided information for the namespace. If `app.py` contains the following code:
```python
import sys
sys.path += ['path_to_project\\package1\\', 'path_to_project\\package2\\']
from parent import *

print(child.__path__)
```
executing `python root\app.py` will produce an error:
```
  File "root\app.py", line 8, in <module>
    print(child.__path__)
NameError: name 'child' is not defined
```
However, changing it to 
```python
import sys
sys.path += ['path_to_project\\package1\\', 'path_to_project\\package2\\']
from parent.child.one import *
from parent import *

print(child.__path__)
```
works normally:
```
_NamespacePath(['d:\\Work\\Temp\\PEP0420\\package1\\parent\\child', 'd:\\Work\\Temp\\PEP0420\\package2\\parent\\child'])
```

**Comment by AlexanderSher** [comment]
**Conflict resolution:** if both regular and namespace packages are presented in search paths, namespace packages will be ignored:
```
├─ package1
│  └─ parent
│     └─ child
│        └─ one.py
├─ package2
│  └─ parent
│     └─ child
│        └─ two.py
├─ package3
│  ├─ parent
│  │  └─ child
│  │    └─ three.py
│  └─ __init__.py
└─ root
   └─ app.py
```
For `app.py`
```python
import sys
sys.path += ['path_to_project/package1/', 'path_to_project/package3/', 'path_to_project/package2/']
import parent.child

print(parent.child.__path__)
```
executing `python root\app.py` will produce
```
_NamespacePath(['path_to_project/package3/parent/child'])
```

**Comment by AlexanderSher** [comment]
**Functions can affect the import**. A bit of edge case. Consider the following code in `app.py`:
```python
import sys
sys.path += ['path_to_project/package1/', 'path_to_project/package2/']
from parent.child import one
from parent.child import two
print(one.__file__)
print(two.__file__)
```
Execution of `python root/app.py` will produce:
```
path_to_project/package1/parent/child/one.py
path_to_project/package2/parent/child/two.py
```
If imports are moved into scope (i.e. function), there will be an error:
```python
def add_imports():
    from parent.child import one
    from parent.child import two
    pass

import sys
sys.path += ['path_to_project/package1/', 'path_to_project/package2/']
add_imports()
print(one.__file__)
print(two.__file__)
```
```
Traceback (most recent call last):
  File "root/app.py", line 12, in <module>
    print(one.__file__)
NameError: name 'one' is not defined
```
However, `from parent.child import *` will now import modules that were found while `add_imports` was executed:
```python
def add_imports():
    from parent.child import one
    from parent.child import two
    pass

import sys
sys.path += ['path_to_project/package1/', 'path_to_project/package2/']
add_imports()
from parent.child import *
print(one.__file__)
print(two.__file__)
```
```
path_to_project/package1/parent/child/one.py
path_to_project/package2/parent/child/two.py
```

**Comment by AlexanderSher** [comment]
Namespace packages can resolve dependencies through relative imports. For example, in a project structure:
```
├─ package1
│  └─ parent
│     └─ child1
│        └─ one.py
├─ package2
│  └─ parent
│     └─ child2
│        └─ two.py
└─ root
   └─ app.py
```
and file contents:
- one.py:
```python
from ..child2.two import f2
def f1(): f2(); pass
```
- two.py:
```python
def f1(): print("F1"); pass
def f2(): print("F2"); pass
```
- app.py
```python
import sys
sys.path += ['path_to_project/package1/', 'path_to_project/package2/']

from parent.child1.one import *
f1()
```
executing `python root/app.py` prints `F2`

**Comment by jakebailey** [comment]
Do you know if anything you're updating will handle `__all__`? I've been going through the Django stuff, and found that they make use of `*` imports and `__all__` modification quite a bit. See:

- https://github.com/django/django/blob/master/django/db/models/__init__.py
- https://docs.python.org/3/tutorial/modules.html#importing-from-a-package

**Comment by AlexanderSher** [comment]
This is actually the opposite task - support of the `__init__.py`, which can be only in ordinal packages. `__all__` isn't the only option, you can simply define imports there.

**Comment by addisonElliott** [comment]
👍 Interested in this PR

In many Python projects, it's typical to alter the sys.path in unit tests to include the Python package.

**Comment by MikhailArkhipov** [comment]
Issues applicable to GA in this Epic are closed. So I am going to disconnect to remaining issues since they are not prioritized to GA and close the Epic.
