### ISSUE TITLE
Is it possible to use .pyi files alongside analized code?

### ISSUE THREAD

**Issue by lostmsu** [Microsoft/python-language-server#296]
I am analyzing a project, that does not have embedded typings, and but there are separate typings for it in .pyi files.

How can I make PythonAnalyzer use those typings?

What I've tried so far:
1. just parse and add typings to analysis queue
2. put typings into a separate directory `Typings` like `Typings\mymodule\mysubmodule.pyi`, and use `PythonAnalysis.SetTypeStubPaths` to `Typings`.

In both cases, when walking `mymodule\mysubmodule.py` file after analysis, and trying to `GetValues(Expression, ...)` I get the same values as if there's no matching typings file.

**Comment by MikhailArkhipov** [comment]
Technically they are used, however, there may be bugs in parsing pyi. 
Related
https://github.com/Microsoft/python-language-server/issues/301
https://github.com/Microsoft/python-language-server/issues/300
https://github.com/Microsoft/python-language-server/issues/254

Try using pyi with simple syntax first, to be sure basic scenario works.

**Comment by lostmsu** [comment]
@MikhailArkhipov but which one is the correct way? And how do I ensure, that it is even loaded?

**Comment by lostmsu** [comment]
Started working on this as a feature here: https://github.com/losttech/PLS/tree/features/AlongsideAnnotations

So far, added parallel annotations AST to `AnalysisUnit`s, and `ProjectEntry`. With this change, it can take annotations file in `AddModule`, and let user supply its Tree to `IPythonParse`. The tree will even be used in multiple places in `FunctionInfo` and `FunctionAnalysisUnit`, however, all evaluation will happen within the context of the main file, which basically means, that all imports in .pyi will be ignored.

I'll try to have analyzer walk over annotations, and let `DDG` have a separate evaluator for them.

**Comment by MikhailArkhipov** [comment]
Correct, they are only used in library analysis since it is too expensive to run full analyzer on such large bodies of code and stub files bring clear benefit.

**Comment by MikhailArkhipov** [comment]
We are doing major rework of the analysis engine and https://github.com/Microsoft/python-language-server/pull/546 supports them.
