### ISSUE TITLE
Symbol (function/method) identification is incorrect

### ISSUE THREAD

**Issue by bharath144** [Microsoft/python-language-server#308]
Issue Type: <b>Bug</b>

If a method or function is decorated, when that method is looked up, the location is shown incorrectly. 

#### This works
```
def some_func()
  ...
```

#### This doesn't
```
@some_decorator()
def some_func()
  ...
```

Some other line in the code gets highlighted when the method is selected from the list (```Ctrl + Shift + O```). Also, the method is incorrectly identified as a dictionary.

Extension version: 1.0.5
VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2683 v3 @ 2.00GHz (4 x 1998)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|16.00GB (11.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

</details>

**Comment by MikhailArkhipov** [comment]
@jakebailey - does this still apply with the indexer driving the symbol list?

**Comment by jakebailey** [comment]
Because of the way we parse decorators, the function will appear to begin at the `@`, but other than that I'm not sure there's any issue. It certainly will not show as a dictionary.

**Comment by MikhailArkhipov** [comment]
Close then?

**Comment by jakebailey** [comment]
Yeah.
