### ISSUE TITLE
StackOverflowException being triggered by large files

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/python-language-server#309]
Microsoft/vscode-python#3011

I've asked the OP for more details, but something is triggering the exception to be raised.

**Comment by pankajp** [comment]
This is with a workspace with many large python files ( ~20kloc ). The files aren't clean and depend on non-existing modules (private extension modules embedded in python which are not available on windows).
A dump from sysinternals procmon shows the "Microsoft.Python.LanguageServer.exe" process restarting after "WerFault.exe" (which is probably the process reporting the error dialog) following a scraping of the module win32security with command line `"C:\Users\ppandey\AppData\Local\Continuum\Anaconda3\python.exe" -B -E c:\Users\ppandey\.vscode\extensions\ms-python.python-2018.9.1\languageServer.0.1.48\scrape_module.py -u8 win32security C:\Users\ppandey\AppData\Local\Continuum\Anaconda3\lib\site-packages\win32` . The same procmon dump shows two crashes both following the scraping of this module.
What more details can I provide? Any diagnostic tools or lsp debugging utilities which I can run. Unfortunately I can't share any of the python files.

**Comment by MikhailArkhipov** [comment]
No longer applies after https://github.com/Microsoft/python-language-server/pull/546
