### ISSUE TITLE
Inheriting collections.namedtuple and calling super(C, cls).__new__(cls, ...) results in empty analysis set

### ISSUE THREAD

**Issue by lostmsu** [Microsoft/python-language-server#312]
Sample code:
```python
import collections

class A(collections.namedtuple('A', [])):
  def __new__(cls):
    return super(A, cls).__new__(cls)

a = A()
```

Possibly related to #15, #174

**Comment by lostmsu** [comment]
I am also unsure why in the following:
```python
class B(object):
  def __new__(cls):
    return super(B, cls).__new__(cls)

class A(B):
  def __new__(cls):
    return super(A, cls).__new__(cls)

a = A()
```
`a` ends up possibly being either of `A` and `B`.

Initially I thought, that is because of my previous change to propagate return types, but if I comment it out, the result does not change.

**Comment by lostmsu** [comment]
I suspect a similar issue would happen to any non-specialized "built-in" function. I made a really dirty workaround for internal purposes here: 645da6408642b16332d6bc6c8a96ba24dcc27e94

**Comment by jakebailey** [comment]
I think these specific cases aren't broken now, though I'm not sure if we do anything interesting with `__new__`.

![image](https://user-images.githubusercontent.com/5341706/53202658-f077be00-35db-11e9-973a-1ed6c27f4201.png)

![image](https://user-images.githubusercontent.com/5341706/53202707-0c7b5f80-35dc-11e9-96f3-0ce0fbda8467.png)

**Comment by lostmsu** [comment]
@jakebailey I suggest to cherry-pick the test still. :) 010a67e
