### ISSUE TITLE
Dataflow analysis

### ISSUE THREAD

**Issue by lostmsu** [microsoft/python-language-server#313]
```python
a = None
if condition():
  a = True
else:
  a = False
a
```
Desired: analysis of `a` in the last line should only return `bool`
Actual: it returns `bool` and `None`

That's a huge feature request, mostly for tracking purposes.

**Comment by MikhailArkhipov** [comment]
New LS no longer collects combinations of types. In the example above a will be just `bool`.

**Comment by lostmsu** [comment]
@MikhailArkhipov out of curiosity: what would the new LS say about

```python
if condition():
  a = "1"
else:
  a = [1]
```

**Comment by jakebailey** [comment]
In that example, `list`, because we take the final assign:

![image](https://user-images.githubusercontent.com/5341706/58840443-8e871580-861a-11e9-8c4f-2b3f7efddbc0.png)

You couldn't represent that code within the python `typing` world.

However, we do handle something like this:

![image](https://user-images.githubusercontent.com/5341706/58840487-aeb6d480-861a-11e9-9755-29664f390e29.png)

**Comment by lostmsu** [comment]
@jakebailey why not? What is the difference between `b` and `a` in this case? Why can't `a` be `Union[str, list]`?

**Comment by jakebailey** [comment]
I overstated; you're right, we could potentially merge those multiple assigns (without dataflow analysis). The returns work because we can find every type returned and do the union then (which is less complicated).

**Comment by lostmsu** [comment]
@jakebailey the older analysis would collect types from both branches. So that later it could strengthen the union as in `Union[XDerivedFromBase, YDerivedFromBase]` -> `Base`. Is this now completely ignored within a single function body?

**Comment by jakebailey** [comment]
Currently, the new analysis doesn't do any sort of unioning or strengthening at all, other than the return type case I gave above. You can specify the type using a type annotation (so, say that something is `Base` explicitly), but we currently don't do anything special to handle multiple assignments over variables besides normal scoping rules.

**Comment by MikhailArkhipov** [comment]
Analysis no longer collects unions of possible combinations of values for performance and memory consumption reasons. Similarly, it no longer collects or stores all possible function return types with various arguments.
