### ISSUE TITLE
Documentation on analyzer internals

### ISSUE THREAD

**Issue by lostmsu** [Microsoft/python-language-server#315]
The analyzer is quite complicated project, and it would not hurt to have some documentation on its internals compiled. That would make potential contributors much more engaged and productive.

For instance, despite my recent pull requests for parameter type propagation getting accepted, more and more I work with the analyzer, makes me think, that they were sloppy band-aid patches rather than proper feature implementations. In particular, now I feel (but do not grok yet), that instead of directly adding newly figured out parameter types to `ReturnTypes` of a function, I should have added a dependency between underlying `VariableDef`s.

BTW, I live next door to the main Microsoft campus, and would gladly meet you guys in the Boardwalk or any other cafeteria with a laptop, if you would be willing to ramp me up. Even today )

**Comment by MikhailArkhipov** [comment]
Sure, ping me mikhaila AT ms.
