### ISSUE TITLE
Use TextDocumentClientCapabilities for documentation kind decision

### ISSUE THREAD

**Issue by jakebailey** [Microsoft/python-language-server#319]
We have a custom option to set the preferred documentation kind in `initializationOptions`, but the LS spec provides a way to do this in [TextDocumentClientCapabilities](https://microsoft.github.io/language-server-protocol/specification#textdocumentclientcapabilities-define-capabilities-the-editor--tool-provides-on-text-documents):

```ts
completionItem?: {
	// ...

	/**
	 * Client supports the follow content formats for the documentation
	 * property. The order describes the preferred format of the client.
	 */
	documentationFormat?: MarkupKind[];

	// ...
}
```

Additionally, `MarkupKind` is duplicated, and the logic for choosing which to use seems to be reimplemented in a few different places that produce `MarkupContent`.

**Comment by MikhailArkhipov** [comment]
Yeah, we pass it in init b/c that's the way VS has been doing it. Markdown == VSC, plain text == VS. This can be part of the PTVS update item #32 .

**Comment by jakebailey** [comment]
Yup, I wasn't sure how this would fit with VS, considering that it doesn't actually communicate over RPC. We seem to do a lot of stuff with settings in the language server init/settings change RPC handlers that I wish were placed elsewhere to be more consistent/testable (not to mention the duplication of many structs between the analyzer and LS).

**Comment by jakebailey** [comment]
Closing in favor of #608.
