### ISSUE TITLE
Completion documentation strings sometimes being formatted as code

### ISSUE THREAD

**Issue by jakebailey** [Microsoft/python-language-server#328]
The function signature and docstring are getting mixed together, so the actual text bit is getting syntax formatted. For example:

![image](https://user-images.githubusercontent.com/5341706/47820383-95634800-dd1a-11e8-9ab6-275433311fcb.png)

This only happens with completion, as I can hover and see:

![image](https://user-images.githubusercontent.com/5341706/47820418-b75cca80-dd1a-11e8-8f07-1dab954027eb.png)

Where the docstring isn't being treated that way.

**Comment by jakebailey** [comment]
And just to check, I went back to before my plaintext-as-default fix, and that didn't seem to matter.

The code that generates the completion content and the hover content is different, so the completion part may need fixing.

**Comment by MikhailArkhipov** [comment]
It is VS Code issue. You can observe similar effect in C#. We actually DO terminate code block with signature (bounded by triple-ticks) but VS Code leaks formatting into the subsequent code. I opened https://github.com/Microsoft/vscode/issues/49018 long time ago, but it did not repro in a simple case.

**Comment by jakebailey** [comment]
As of #596 and other tooltip changes, this should no longer be the case.
