### ISSUE TITLE
Taking over 45 minutes to analyze project.

### ISSUE THREAD

**Issue by bob-white** [Microsoft/python-language-server#330]
VSCode version: 1.28.2
Python extension version: 2018.9.2
LanguageServer version: 0.1.52
Python 3.5
I have the following settings enabled.
```
    "python.analysis.logLevel": "Trace",
    "python.analysis.downloadChannel": "daily"
```

After startup in the output window I see all the files in the current workspace directory being parsed and queued up for analysis (1510 files). 
I see one single file get returned with:
> Analysis complete for file://...blah blah blah

The AnalysisLog.txt file is largely filled with `ImportNotFound` lines about 3200 out of the 4000 lines in the file currently.

Is there any way to figure out why this is happening? Just earlier this week everything was working, granted it still took around 5-10 minutes to completely analyze the workspace, but at least it finished.

After about an hour and 15 minutes it finished analysis at version -1, and kicked off version 0.
I have yet to see a single file complete at version 0.

And after another hour and 15 minutes it finally stopped processing everything.

**Comment by jakebailey** [comment]
@bob-white 	Is the codebase you're testing available somewhere so we can try to reproduce this?

**Comment by bob-white** [comment]
Codebase isn't publicly available. Trying to see what the possibility is of getting something you guys can repro with though.

I was able to create a debug build of master and attach to that, and it appears I get stuck in `DGG.Analyzer` the first file has a queue size in the low 20s, and the second time I hit the function the queue has a size of 30k+. 

I did discover that if I create a bunch of stubs using mypy's stubgen utility, after renaming them to .py the analysis seems to follow the same pattern of process one file, and then ALL the files. With approximately the same queue sizes in `DGG.Analyzer`.
Except it handles it in 45 seconds instead of an hour and fifteen.

**Comment by MikhailArkhipov** [comment]
Unfortunately, this is not unusual with 1510 files. We are planning to address this by several changes that are filed in https://github.com/Microsoft/python-language-server/issues/29. However, this is not coming immediately since improvements require significant changes.

**Comment by bob-white** [comment]
So I am kind of confused, I don't see any changes related to #29.
But otherwise this sounds like I should just go back to using Jedi and hope that a future update maybe fixes things?
Should I keep an eye on this issue or just watch #29 so that I can test stuff out if / when improvements start to land?

**Comment by jakebailey** [comment]
We use ZenHub, and #29 is an "epic" which links to 7 other issues, but isn't visible without the extension. I've just tagged them with a "performance" label, which should be easier to look at and check.

I would personally say to use what works for you. There are some changes on the horizon which will improve performance for non-library code, but they haven't been finished quite yet.

**Comment by jeffery9** [comment]
have the same issue.. you can try to analysis https://github.com/odoo/odoo, it never finished the code analysis,  jedi do this very quickly.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/python-language-server/pull/546

**Comment by bob-white** [comment]
If I wanted to test this, would I be able to get it from the daily channel? Or do I need to build from master?

**Comment by jakebailey** [comment]
All of the download channels will still be tracking `release` until we finish out some of the missing features. You can build from `master` if you'd like to test it, but know that some important functionality is still being worked on (#432 is one).

**Comment by MikhailArkhipov** [comment]
And #424 since tooltips are currently raw and appear ugly.

**Comment by bob-white** [comment]
Thanks for the info.
Just to report, I've been testing the build in the daily channel a bit this morning, and while the CPU has been pegged at 15% for the last couple of hours, I am at least getting autocomplete and the outline panel populated. Memory is staying at a pretty constant 2GB (at least according to the task manager)

**Comment by MikhailArkhipov** [comment]
0.2.16 is now available on beta channel. 
```json
"python.analysis.downloadChannel": "beta"
```

**Comment by bob-white** [comment]
With the build from the beta channel, the server no longer locks up a couple of cores, though it does still take up 2GB+ of ram. Though I do get two python processes stuck running while trying to scrape the `wx._core` and `wx._richtext`

Autocomplete seems to function pretty well, though goto-definition fails to find class/instance members from `self`, but is okay at finding top-level objects within various modules. The outline panel does seem to collect this information however.

Also it seems pylint is no longer being run even though it is set as my primary linting tool. Is this intentional? Because whatever is running in its place is only letting me know that it has struggled to import some modules from the standard library, and not anything about the quality of the rest of the code.

**Comment by jakebailey** [comment]
That's an extension configuration; you'd need to check there. As far as I know, they reworked their linting such that you enable linting as a whole, then enable a specific linter. If you never modified your settings, it's likely that the default is not the same. The language server only reports syntax errors and unresolved imports, independent of any other linting.

Can you file a separate issue about the `wx._core`/`wx._richtext` hang?
