### ISSUE TITLE
None is being flagged as used before assignment 

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/python-language-server#335]
Microsoft/vscode-python#3117

When `None` is used in a type hint it gets flagged as being used before assignment. In the following example every use of `None` is being flagged.

```python
def f(b:None) -> None:
    b: None
```

**Comment by jakebailey** [comment]
I can reproduce this. I'll look into it.

**Comment by jakebailey** [comment]
Should be fixed in #336. 😃 

![image](https://user-images.githubusercontent.com/5341706/47882958-7c28cd00-dde8-11e8-8084-b7f8f4050c06.png)
