### ISSUE TITLE
Method `mro` not listed in auto completion list

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/python-language-server#338]
```python
class A:
	pass
A.mro()
```

The item `mro` is not listed in auto completion list.
Note: `__mro__` is listed.

This works in Jedi.

**Comment by MikhailArkhipov** [comment]
As in #337.

`dir(object)` yields

C:\Python3>python
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> dir(object)
['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']

So a) object is not automatically attached as base and b) `mro` and `__dict__` are not in the above list so scraper misses them. They are, however, in the typeshed stub for builtins, so #533 is the actual solution
