### ISSUE TITLE
Completion item insertTextFormat property should be only 1 or 2

### ISSUE THREAD

**Issue by johngalambos** [Microsoft/python-language-server#342]
Completion items are returning with insertTextFormat properties set to 0. For example:

            {
              "label": "and",
              "kind": 14,
              "detail": null,
              "documentation": null,
              "sortText": "1",
              "filterText": null,
              "preselect": null,
              "insertText": "and",
              "insertTextFormat": 0,
              "textEdit": null,
              "additionalTextEdits": null,
              "commitCharacters": null,
              "command": null,
              "data": null,
              "_kind": "keyword",
              "_values": null
            }

The spec is [here](https://microsoft.github.io/language-server-protocol/specification) (Search for `InsertTextFormat`). According to the spec, `insertTextFormat `be either `1` or `2`.

I believe this is the last item that should get completion working in vim/neovim via https://github.com/autozimu/LanguageClient-neovim.

Thank you for this tool!

**Comment by jakebailey** [comment]
Thank you again for taking the time to find this, @johngalambos! 😃
