### ISSUE TITLE
Expose named tuple member in completions

### ISSUE THREAD

**Issue by MikhailArkhipov** [microsoft/python-language-server#343]
```python
from collections import namedtuple
nt = namedtuple('Point', ['x', 'y'])
pt = nt(1, 2)
```

`pt.` should show `x` and `y`.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/python-language-server/pull/546 supports named tuple from typing.

**Comment by jakebailey** [comment]
This example doesn't show `x` and `y` in the completion after the `.`, though.

![image](https://user-images.githubusercontent.com/5341706/52515804-43617680-2bd5-11e9-88d8-9119c8ac3a0d.png)

![image](https://user-images.githubusercontent.com/5341706/52515805-4d837500-2bd5-11e9-87cb-b4e7ad4a25da.png)

Seems to show `tuple`, not a named tuple.

**Comment by MikhailArkhipov** [comment]
I meant NamedTuple from typing should work.

**Comment by judej** [comment]
Thank you for the report. This project is no longer active. If you are using the Python language server in VSCode, the language server you are using is Pylance and please the http://github.com/microsoft/pylance-release to report issues. 

If you are using Visual Studio, then, please use http://github.com/microsoft/PTVS to report issues.

thank you
