### ISSUE TITLE
Syntax errors for unfinished expressions appear on the next line

### ISSUE THREAD

**Issue by jakebailey** [Microsoft/python-language-server#345]
![image](https://user-images.githubusercontent.com/5341706/48029046-1eef8d00-e102-11e8-97ca-b802b804c3a3.png)

I think the syntax error should be on the line where the `.` access isn't finished yet, like what you get if you remove anything following the bad expression:

![image](https://user-images.githubusercontent.com/5341706/48029223-8dcce600-e102-11e8-9225-bc397b0a2cb9.png)

(It's also very strange that only a subset of the comment gets squiggled instead of the whole thing, but...)

**Comment by MikhailArkhipov** [comment]
It basically squiggles next token if available
