### ISSUE TITLE
Functions which return tuples show duplicated return types

### ISSUE THREAD

**Issue by jakebailey** [Microsoft/python-language-server#347]
Start with:

![image](https://user-images.githubusercontent.com/5341706/48030697-be168380-e106-11e8-83e6-c4580d89cbd0.png)

Which is correct-ish, ignoring the missing types (which would be better shown as `Any`, but that's a different issue). Now, add a call, which (in the current implementation) propagates types to the function:

![image](https://user-images.githubusercontent.com/5341706/48030769-f322d600-e106-11e8-8eae-447a5605b5aa.png)

The function does in fact return a tuple with three ints, but it's being shown as `tuple[int, int, int][int, int, int]` instead of just `tuple[int, int, int]`.

Note that if I go and annotate the parameters myself with `int` (restricting the possible types from `Any`), this goes away:

![image](https://user-images.githubusercontent.com/5341706/48030922-60cf0200-e107-11e8-9b94-8333f2c26657.png)

**Comment by jakebailey** [comment]
Also:

![image](https://user-images.githubusercontent.com/5341706/48031252-6bd66200-e108-11e8-848c-45f47f085f7b.png)

The first one shows `?` for unknown types, while the second just shows an empty string. Might help indicate where the extra info is coming from.

**Comment by MikhailArkhipov** [comment]
Let me look at it as it is related heavily to #50
