### ISSUE TITLE
Speed up fetching docstrings for methods

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/python-language-server#351]
Microsoft/vscode-python#3212

The title specific calls out that "pandas, numpy, matplotlib all take a few seconds to load".

**Comment by MikhailArkhipov** [comment]
Is it about specifically doc strings or generally about mentioned libraries?

**Comment by brettcannon** [comment]
@ronglums Please answer Mikhail's question (either here or on the vscode-python issue).

**Comment by ronglums** [comment]
It is about the general language services features (auto-complete, docstrings and such) for the mentioned libraries.

**Comment by MikhailArkhipov** [comment]
Generally initial analysis will always take "few seconds" or maybe a minute on large projects, there is no way around it. :-) But not tens of minutes of course. 

https://github.com/Microsoft/python-language-server/pull/546
