### ISSUE TITLE
All editor-opened file streams have BOM prepended, breaking coding handling

### ISSUE THREAD

**Issue by jakebailey** [Microsoft/python-language-server#355]
Found while debugging #354. Have the file:

```python
# -*- coding: ascii -*-
print "foo"
```

Definitely without a BOM:

```
& 'C:\Program Files\Git\usr\bin\xxd.exe' .\ascii.py
00000000: 2320 2d2a 2d20 636f 6469 6e67 3a20 6173  # -*- coding: as
00000010: 6369 6920 2d2a 2d0a 7072 696e 7420 2266  cii -*-.print "f
00000020: 6f6f 220a                                oo".
```

![image](https://user-images.githubusercontent.com/5341706/48098642-3bf39100-e1d2-11e8-80ae-adec36acd29d.png)

Looking at what happens in the debugger, the BOM gets appended during the reencoding process in ProjectEntry.cs.

This should be fixed to properly handle the incoming stream (not modify it?), or potentially even dropping any special stream buffering to just stick to UTF-8, which we'll have to figure out.

**Comment by qubitron** [comment]
Per conversation with Mikhail
