### ISSUE TITLE
Improve intellisense for common pandas functions

### ISSUE THREAD

**Issue by qubitron** [Microsoft/python-language-server#358]
While pandas does not currently have type definitions, there are a handful of very common pandas methods/patterns that should be easy to provide our own definitions for.

Some examples, read_csv typically returns a data frame:
```
import pandas as pd
df = pd.read_csv('survey2017.csv')
df. # no intellisense, df should be DataFrame
```

The `loc` and `iloc` properties on a DataFrame are also missing, I think they typically return pandas.core.series.Series.

Similarly the index operator of a DataFrame returns a series if it's argument is a single value, e.g.
```
type(summary['percent'])
pandas.core.series.Series
```

If input is a series or a list of values it will return a dataframe:
```
type(summary[['percent', 'count']])
pandas.core.frame.DataFrame

type(summary[summary['percent'] > 0.1])
pandas.core.frame.DataFrame
```

A handful of such definitions would make IntelliSense for pandas much more useful for the most common use cases.

**Comment by MikhailArkhipov** [comment]
![image](https://user-images.githubusercontent.com/12820357/53206226-3d13c700-35e5-11e9-857d-92884443c391.png)

**Comment by jakebailey** [comment]
I assume that's in a future PR? (Since I can't make that show up against `master`.)

**Comment by MikhailArkhipov** [comment]
Yes
![image](https://user-images.githubusercontent.com/12820357/53222395-6acb3100-3622-11e9-9e83-91b32ed5e1d7.png)

**Comment by aykutkilic** [comment]
Pandas autocomplete is very slow. Is this expected? (2019.5.18875)

**Comment by jakebailey** [comment]
Please file a new issue with your language server version and a code sample, this one is very old and applies to not having completion on DataFrames at all. https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#filing-an-issue
