### ISSUE TITLE
Debug.Assert in ModuleAnalysis.ResolveAndAdd

### ISSUE THREAD

**Issue by lostmsu** [Microsoft/python-language-server#359]
Seems to be regressed in 8e61522a, which overrides `BuiltinFunctionInfo.Overloads` with LINQ expression, breaking its own `GetHashCode`.

**Comment by lostmsu** [comment]
There are might be other issues too, as using

```csharp
public override int GetHashCode() => base.GetHashCode()
            ^ Overloads.Aggregate(654754754, (h, o) => h ^ o.GetHashCode()).GetHashCode();
```

Does not solve the problem completely.

**Comment by lostmsu** [comment]
Actually, about recursion tracking in `AnalysisValue`: does it really need to use value comparison as opposed to using reference comparison, similar to the one suggested here: https://stackoverflow.com/questions/1890058/iequalitycomparert-that-uses-referenceequals

**Comment by lostmsu** [comment]
@MikhailArkhipov it creates a new array each time, so its hash code is different on every call.

**Comment by MikhailArkhipov** [comment]
OK, we can cache both.
