### ISSUE TITLE
Add implicit relative path support for python 2X

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/python-language-server#366]
https://chrisyeh96.github.io/2017/08/08/definitive-guide-python-imports.html#absolute-vs-relative-import
https://www.python.org/dev/peps/pep-0328/
https://docs.python.org/2/library/__future__.html: `from __future__ import absolute_import`

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/python-language-server/pull/361
