### ISSUE TITLE
IntelliSense provided for subclass of torch.nn.Module, but not for the class itself

### ISSUE THREAD

**Issue by brettcannon** [microsoft/python-language-server#376]
Microsoft/vscode-python#3241

Using [PyTorch](https://pytorch.org/):

```python
from torch import nn


class Dummy(nn.Module):
    pass


def f(m: nn.Module):
    m. # No autocomplete offered


def g(n: Dummy):
    n. # autocomplete offered
```

**Comment by dumbPy** [comment]
Works for me. 
Also, tried 
```
def someclass(self,f):
    self. # autocomplete works here as nn.Module is inherited
```

**Comment by jakebailey** [comment]
You may want to try the nightly build of Torch; they added stubs to aid in completion (since a lot is hard to inspect). See #690.

**Comment by jakebailey** [comment]
Working in master.

![image](https://user-images.githubusercontent.com/5341706/64741484-9bcf5e00-d4ad-11e9-8a97-91a017aaac1f.png)
