### ISSUE TITLE
Arguments with type hint Optional are incorrect

### ISSUE THREAD

**Issue by jakebailey** [Microsoft/python-language-server#377]
![image](https://user-images.githubusercontent.com/5341706/48234371-3a5ed000-e36e-11e8-8f5c-f04925fd4da4.png)

Should really one of:
```
opt(x: Optional[int]) -> int, None
opt(x: int, None) -> int, None
```

![image](https://user-images.githubusercontent.com/5341706/48234379-4054b100-e36e-11e8-93ab-ac524e4fb380.png)

If I'm following the same format as my previous "should", then this should really be one of:
```
opt(x: Optional[int] = None) -> int, None
opt(x: int, None = None) -> int, None
```

But the latter (for both) is nonsensical and really ambiguous when it comes to parameters which are separated by commas, but likely how we'd render things with our current type system. Type alternatives really shouldn't be rendered like this. Related to #346.

**Comment by jakebailey** [comment]
The return type being `int, None` is probably not PEP 484 compliant either, but I'd need to read the spec to see what's expected there. I'm guessing `Optional[int]` is also the right return type, too...

**Comment by dirn** [comment]
In this particular example, the return type should be wrapped in `Tuple`.

    def opt_none(x: Optional[int] = None) -> Tuple[Optional[int], None]

**Comment by jakebailey** [comment]
Our current way of displaying types separates alternates with commas. The return type should be `Optional[int]` as the parameter has, not a tuple. If I wrote `return x, None`, then it would be `Tuple[Optional[int], None]`.

Forgive my mixing of different syntaxes. There's already an issue open for trying to transition to a more PEP 484 style system rather than our existing one: #346

**Comment by dirn** [comment]
Yeah, sorry for not being clear, I was specifically addressing this part

>The return type being int, None is probably not PEP 484 compliant either

and hadn't seen the other issue. And your example doesn't return a tuple, like you said, so I'm not sure what I was even thinking. Ignore me. :)

**Comment by jakebailey** [comment]
Closing this, since the new language server's typing system is much more aligned with Python's typing and weird things like this don't show up in the analysis anymore. The only things left are small tooltip tweaks, like #603.
