### ISSUE TITLE
Pylint not working when using Python Language Server

### ISSUE THREAD

**Issue by josherickson** [Microsoft/python-language-server#380]
### Issue
When Python Language Server is enabled (`"python.jediEnabled": false`), pylint does not run. 

### Versions
python: 3.7.0
pylint: 2.1.1
VS Code: 1.28.2
Python VS Code Extension (ms-python.python): 2018.10.1

### Steps to Reproduce (hopefully)
- `"python.jediEnabled": true` in User Settings, pylint installed, everything is working properly. My code is being actively linted as I work.
- Change to `"python.jediEnabled": false`. Pylint no longer runs. I do not see any warnings under the "Problems" tab, or any output under the "Output" tab for Python.
- When I use `Shift + ⌘ + P` -> `Python: Select Linter`, it says `current: none`.
- I select another linter such as pep8, which then gives me the message box in the bottom right that says "Linter pep8 is not installed."
- I repeat and now it says `current: pep8` (I have not installed pep8, just FYI), and I select pylint this time. Nothing happens, no message box.
- I repeat again and now it says `current: none`.
- Pylint still not working, no warnings reported, etc.
- Switch back to `"python.jediEnabled": true` and linting is working again.
- Note that pylint was working in the past for me when using the Python Language Server, but over the past few weeks I have uninstalled and reinstalled both pylint and python itself for other reasons. I am not sure if these reinstalls caused the issue, or if this started happening independent of that.

**Comment by jakebailey** [comment]
The language server itself doesn't impact the VS Code extension's pylint support (or any other linter). I suggest you open a bug on their issue tracker: https://github.com/Microsoft/vscode-python/issues

**Comment by josherickson** [comment]
Gotcha, will do. Thanks
