### ISSUE TITLE
Can we add integration tests?

### ISSUE THREAD

**Issue by lostmsu** [Microsoft/python-language-server#381]
Does not seem like its urgent, but running a time-limited analysis on something as big as scikit-learn (see https://github.com/Microsoft/python-language-server/issues/379) before merging pull requests would alleviate some unnoticed regressions.

**Comment by jakebailey** [comment]
You're describing two things:

- Running automated tests on PRs and such, which is already covered by #352, but may need to wait until we simplify things to the point where running the suite doesn't take half an hour.
- Running tests on big complicated codebases like scikit-learn, which we might not really be able to do either until we remove the slow analyzer either (from experience running it on scikit-learn takes a good 20 minutes even when I do it from `/tmp`).

**Comment by lostmsu** [comment]
@jakebailey I think tests can still be run on scikit-learn, or any other large project, as long, as they are time- or iteration-limited. E.g. just have `AnalyzeQueuedEntries` called with a timed cancellation token, or cancel it as soon, as say a 100000 units have been (re-)analyzed.

**Comment by MikhailArkhipov** [comment]
To #352
