### ISSUE TITLE
Ignore "close bracket has no matching open" exception in telemetry

### ISSUE THREAD

**Issue by jakebailey** [Microsoft/python-language-server#388]
This exception gets thrown when the line formatter gets run on code with unbalanced braces/parens/brackets. Since this is a user code error, we should not be recording the event, as it's just noise.

My initial implementation just threw `new Exception(...)`, and should probably be switched to a more specific subclass.

**Comment by MikhailArkhipov** [comment]
Formatter should not be throwing anything. Broken code is normal condition. Parser does not throw on broken code and neither does analyzer. Formatter should simply do nothing or just output message to the console. The only case when we do want to throw exception is when we want client to show something to the user such as ‘cannot rename’. But not every condition deserve notification. VS does not pop up message boxes when it cannot format user code. You may get some status bar message at best.

**Comment by jakebailey** [comment]
That's a fair point. I'll see if I can come up with a way to better handle things (or just not format in the worst case).
