### ISSUE TITLE
DictionaryInfo-related analysis does not fully track account key and value types

### ISSUE THREAD

**Issue by lostmsu** [Microsoft/python-language-server#402]
It starts with `DictionaryInfo` instance equality ignoring those types.

This in turn makes analysis result depend on the order when various `DictionaryInfo` instances are analyzed and/or added to analysis sets. An excerpt from test case:

```csharp
var untypedTyped = new VariableDef();
untypedTyped.AddTypes(entry, untypedDict);
untypedTyped.AddTypes(entry, intDict);
var typedUntyped = new VariableDef();
typedUntyped.AddTypes(entry, intDict);
typedUntyped.AddTypes(entry, untypedDict);

Assert.AreEqual(untypedTyped.Types.ToString(), typedUntyped.Types.ToString());
```

Results in: `Assert.AreEqual failed. Expected:<dict()>. Actual:<dict(keys=(Class int, ), values = ()>.`

**Comment by jakebailey** [comment]
Closing; this code is gone.
