### ISSUE TITLE
Clean up type system

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/python-language-server#404]
Clean interfaces: 
- IPythonType, IPythonClass, IPythonModule,.... 
- Remove obsolete methods.
- Derive implementation appropriately (i.e. function is a type). 
- Drop .NET/IronPython specific code.
- Make variables store `IPythonType` rather than `IMember`. 
- Implement MemberId as function of the BuiltInTypeId so they appear consistent.
- Implement IsBuiltIn as a function of declaring module.

**Comment by jakebailey** [comment]
Related is #346.
