### ISSUE TITLE
Typing just "." offers completion

### ISSUE THREAD

**Issue by jakebailey** [Microsoft/python-language-server#415]
![image](https://user-images.githubusercontent.com/5341706/48733926-cd162f00-ebf8-11e8-9ba4-d252b41812fa.png)

Also happens when you do something like `-.` or `*.`, all of which is a little goofy. This is probably happening because it's not finding any nodes when looking up the location in the AST and therefore treated like completion on an empty line or similar.

Found in #334.

**Comment by MikhailArkhipov** [comment]
This is VS Code feature. We do not trigger anything, VS Code does. We could look into the trigger character theoretically, but, IMO, this is just a cosmetic issue.

**Comment by jakebailey** [comment]
I understand that VSC is what's sending the request for completion, but I'd be curious to know why we actually return something, rather than to, say, look behind the `.`, find nothing, so return nothing. (Not to mention how interesting it is that everything that is suggested is some derivative of `Exception`.)

**Comment by jakebailey** [comment]
Closing this, since #546 doesn't exhibit this behavior.

![dot](https://user-images.githubusercontent.com/5341706/52435172-0490cb00-2ac6-11e9-874b-129360141b39.gif)
