### ISSUE TITLE
Completions missing for pytest

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/python-language-server#420]
No completion is seen after `pytest.mark.pa`. Shows partial completion after the '.'
![image](https://user-images.githubusercontent.com/3840081/48742248-022f7b00-ec13-11e8-9473-27f7d337b063.png)

**Comment by MikhailArkhipov** [comment]
What is expected?

![image](https://user-images.githubusercontent.com/12820357/52893727-8b901400-3154-11e9-97fb-987dd8dad174.png)

![image](https://user-images.githubusercontent.com/12820357/52893844-9ac39180-3155-11e9-8c82-8a0be3865221.png)

**Comment by MikhailArkhipov** [comment]
Appears to work in new LS
