### ISSUE TITLE
Completions not available for imported functions

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/python-language-server#421]
Repro steps:
* Clone the latest ptvsd project https://github.com/Microsoft/ptvsd
* Set PYTHONPATH to point to `src`
* Open up any file under `pytests`.
* Import and use any function from ptvsd, e.g, `from ptvsd.socket import create_server, close_socket`

Actual:
Get no completion. Sometimes you get name completions. Hover info is not available either.

Expected:
Should get completion

**Comment by MikhailArkhipov** [comment]
Probably should be resolved by https://github.com/Microsoft/python-language-server/pull/361 and related

**Comment by MikhailArkhipov** [comment]
Yep

```
[Info  - 7:25:52 PM] SearchPaths:
[Info  - 7:25:52 PM]     c:\python27\dlls
[Info  - 7:25:52 PM]     c:\python27\lib
[Info  - 7:25:52 PM]     c:\python27\lib\lib-tk
[Info  - 7:25:52 PM]     c:\python27
[Info  - 7:25:52 PM]     c:\python27\lib\site-packages
[Info  - 7:25:52 PM]     c:\python3\python36.zip
[Info  - 7:25:52 PM]     c:\python3\DLLs
[Info  - 7:25:52 PM]     c:\python3\lib
[Info  - 7:25:52 PM]     c:\python3
[Info  - 7:25:52 PM]     c:\python3\lib\site-packages
[Info  - 7:25:52 PM]     .
[Info  - 7:25:52 PM]     src
[Info  - 7:25:52 PM]     c:\python3
```
![image](https://user-images.githubusercontent.com/12820357/52894018-dd866900-3157-11e9-84fb-038c1b993cb3.png)

This, however, works

![image](https://user-images.githubusercontent.com/12820357/52894063-99e02f00-3158-11e9-8312-4e6cb9e8dc1c.png)
