### ISSUE TITLE
Crashes on Startup on OS X 10.11

### ISSUE THREAD

**Issue by e-bonner** [Microsoft/python-language-server#427]
After I installed the python VSCode extension, it downloaded and installed the language server, which failed to start with the following error:
`dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Users/elliot/.vscode/extensions/ms-python.python-2018.10.1/languageServer.0.1.60/libcoreclr.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib`

I am running OS X 10.11, which explains why it did not work (since it says it was built for 10.12), but given that VSCode supports 10.11, I expected the server to work as well, since I could not find any documentation listing specific requirements.

**Comment by MikhailArkhipov** [comment]
OSX 10.11 is not supported by the LS. Technically the extension should have warned you. If it didn't, please open a bug there.
