### ISSUE TITLE
Error when changing interpreter

### ISSUE THREAD

**Issue by michaelaye** [Microsoft/python-language-server#430]
I got this log shown when I switched the Python interpreter from what VScode "thought" it was to the correct Python 3.7.

The thing is, sometimes conda suggests a downgrade of the minor python version (something I suggested to them should change: https://github.com/conda/conda/issues/7325)
and if one isn't careful, someone's conda env named 'py37' suddenly becomes a python3.6.

This happened to me in the past at some point, which is when VScode must have scanned by conda environments.
After I put my 'py37' env back to actually being a Python 3.7 env, there was no way I saw to convince VScode that it was indeed a Python 3.7 environment.
Potentially, that scenario lead to this error I got shown today, when I finally could change my interpreter to a Python 3.7 inside my conda py37 env:

<img width="760" alt="screenshot 2018-11-21 15 43 46" src="https://user-images.githubusercontent.com/69774/48872113-f5db2780-eda4-11e8-83a0-d7db7337bdba.png">

**Comment by jakebailey** [comment]
To be clear, are you reporting that stack trace, or some other issue?

This isn't behavior that concerns the language server. This is an error that comes from the library the VS Code extension uses to communicate with the language server. It goes something like this:

1. The VS Code extension starts the language server, providing it the configuration to point to the `py36` interpreter.
2. You selected a different interpreter in the extension (the path changed), `py37`.
3. The extension stops the language server process and disconnects the connection.
4. The extension starts a new language server with the `py37` interpreter configuration.

At some point, the editor tries to use the connection to the first language server, which is no longer connected, and throws the exception you're seeing.

There's nothing we can do about this, as it's not a bug in the language server. It's something that the extension or its library does incorrectly, using an old connection or not ignoring these types of "disposed" exceptions.

If you don't want to see that message, I would suggest opening an issue on the extension's repo.

Also note that the language server doesn't do any sort of detection of python environments. All it does is use the configuration provided to it at initialization, which in your case is being sent by the VS Code extension.

**Comment by michaelaye** [comment]
This log starts with "Starting Microsoft Python language server" and THEN throws an error. How should one infer that this is caused by an extension? Which would it be? Also note that this log was only shown at the exact moment of switching the Python interpreter.

**Comment by jakebailey** [comment]
The stack trace shows the path to the JavaScript files for the extension running in your `.vscode` directory.

The "Python" output window is written to by the VS Code extension, and will include messages from the extension itself, the language server (we pass messages via JSON RPC back to the extension), as well as any Python tooling (like pylint) that the extension runs.

"Starting Microsoft Python language server" is a message the extension prints before it starts the language server process. The "version 0.1.60.0" and "initializing for ..." lines are printed by the language server.

**Comment by jakebailey** [comment]
It's very likely that the documentSymbol call was in progress when the connection was closed, which would also cause this error to appear (as the RPC cannot be completed as the connection disappeared).

**Comment by michaelaye** [comment]
i think that is correct. if i remember correctly, I was waiting for an reply to a call of "Show instances of symbol", which, for some reason seemed stuck.

**Comment by jakebailey** [comment]
That's to be expected in our current implementation, depending on the project size. All of the find symbol calls wait for the analysis to be complete before finishing (otherwise they may give misleading results). It's likely that your project hadn't yet been finished being analyzed.

**Comment by michaelaye** [comment]
Is an ongoing analysis being indicated somehow? It would be important to be aware of the reason for such delays.
