### ISSUE TITLE
High CPU usage when using python.autoComplete.extraPaths on VS Code

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/python-language-server#431]
Microsoft/vscode-python#2838

The use of `"python.autoComplete.extraPaths"` seems to be common with the last two posts.

**Comment by teardemon** [comment]
![image](https://user-images.githubusercontent.com/1568748/49277599-1e59d480-f4bd-11e8-9528-a4eccd768bfa.png)

**Comment by Honzys** [comment]
I've noticed some weird behaviour.

I've set up "python.analysis.logLevel": "Trace" along with "python.analysis.openFilesOnly": true.

After I do any changes and save the changes in opened file, the code analysis is triggered for whole workspace folder, is this correct behaviour? See the log bellow:

```
Waiting for parsing to complete.
Parsing complete. Waiting for analysis entries to enqueue.
Enqueue complete. Waiting for analysis to complete.
Received new analysis for file:///some_python_file.py
Analysis complete for file:///some_python_file.py at version 19
 Waiting for analysis of file:///some_python_file.py to complete.
 Waiting for analysis of file:///some_python_file.py to complete.
... (just to make the log shorter)
 Waiting for analysis of file:///some_python_file.py to complete.
Analysis complete.
Opening document file:///some_python_file.py
Parsing document file:///some_python_file.py
Parse complete for file:///some_python_file.py at version 1
Analysis queued for file:///some_python_file.py
Waiting for parsing to complete.
Parsing complete. Waiting for analysis entries to enqueue.
Enqueue complete. Waiting for analysis to complete.
Received new analysis for file:///some_python_file.py
Analysis complete for file:///some_python_file.py at version -1
Received new analysis for file:///some_python_file.py
Analysis complete for file:///some_python_file.py at version 1
 Waiting for analysis of file:///some_python_file.py to complete.
... (just to make the log shorter)
 Waiting for analysis of file:///some_python_file.py to complete.
Analysis complete.
##########Linting Output - mypy##########
##########Linting Output - flake8##########
```
(I've changed the name of python file to `some_python_file.py`, but the names were unique and it was printed for every single python file in the workspace folder)

Can someone eligible confirm if it's correct behaviour or not?

Thank you very much.

**Comment by jakebailey** [comment]
Currently, the analyzer isn't smart enough to know exactly what all needs to be reanalyzed when something changes, so it may go over unrelated files to make its analysis up to date. Improving this behavior such that we know exactly which files should be reanalyzed on a file change is a work in progress item (#432, #435).

**Comment by MikhailArkhipov** [comment]
To verify with (#432, #435).

**Comment by MikhailArkhipov** [comment]
This should no longer be happening since there is no looping analysis.

**Comment by alecf** [comment]
@MikhailArkhipov  I'm still seeing this in 1.33.0 on OS X

**Comment by MikhailArkhipov** [comment]
Not necessarily same underlying problem. Please open separate issue, tell us what version of the language server (displayed at startup) since it is not connected to extension or VS Code version and what packages are being imported and how long did the analysis take (if it completed). Thanks.

**Comment by alecf** [comment]
```
[Info  - 2:46:36 PM] Microsoft Python Language Server version 0.2.47.0
```

I didn't install this separately or anything, I assume this just comes with the `ms-python.python` extension?

(As an aside for anyone reading: turns out I had disabled "jedi" which in turn enables the python language server - turning jedi back on made everything work without cpu spiking..)
