### ISSUE TITLE
No completions for sys.exc_info with latest typeshed

### ISSUE THREAD

**Issue by huguesv** [Microsoft/python-language-server#434]
With the bundled typeshed on Python 3, you get completions/info tips on these variables:
```
import sys
e1, e2, e3 = sys.exc_info()
```

But if you clone latest typeshed and make vscode use that (I overwrote the languageSever.x.y.z/Typeshed folder) then you no longer get completions/info tips.

https://github.com/Microsoft/PTVS/issues/4877

**Comment by jakebailey** [comment]
This was _almost_ fixed as of #546, but `TracebackType` doesn't seem to get resolved even though it's been imported in the stub.

**Comment by jakebailey** [comment]
Looked at this more closely; `sys.pyi` imports `types` (which would be `types.pyi`) and `types.pyi` imports `sys` (to do those simple if statements).

**Comment by jakebailey** [comment]
This looks to be fixed, though the tooltips could use some work.

![image](https://user-images.githubusercontent.com/5341706/53995474-fa281800-40e9-11e9-9023-24ac7ba6b9d7.png)
