### ISSUE TITLE
No intellisense for files untitled docs (not saved to disc) 

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/python-language-server#438]
Original issue https://github.com/Microsoft/vscode-python/issues/3498

**Comment by MikhailArkhipov** [comment]
This is b/c file without extension '.py' is not considered to be Python in the LS and hence is not loaded. I don't think it is worth fixing as workaround is trivial.

**Comment by DonJayamanne** [comment]
Discussed with @qubitron, this is required.
However, i'll let you prioritize this issue.

**Use case:**
* I think this is an important feature, specially for data scientists or someone starting to code, e.g. sending code to a terminal (or jupyter).
* I.e. important for experimenting, and users do that a lot with Python.

**Comment by MikhailArkhipov** [comment]
#597
