### ISSUE TITLE
Wrong file referenced in Find/List All References and Rename Symbol

### ISSUE THREAD

**Issue by RomanKornev** [Microsoft/python-language-server#454]
## Environment data

- VS Code version: 1.29.1
- Language server version: 0.1.65.0
- OS and version: Win 10 x64 
- Python version (& distribution if applicable, e.g. Anaconda): Anaconda 3.7.1 x64
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
- "python.jediEnabled": false
## Steps to reproduce:
- Create 2 files:
``` python
# foo.py

from bar import baz


class spam:
    __bug__ = 0


def eggs(ham: spam):
    return baz(ham.__bug__)

```
``` python
# bar.py

# comments ########################################
# more commments ##################################
# even more comments ##############################


def baz(quux):
    pass
```
- Hover over `__bug__` and Find All References
- Completely unrelated file `bar.py` is referenced at offset 112 which is exactly the offset of `__bug__` in `foo.py` at line 11
![reference_bug](https://user-images.githubusercontent.com/5807561/49464139-2a21ff80-f80b-11e8-84ce-cb8f9858623c.png)
- List All References behavior is identical
- Trying to rename F2  `__bug__` to `some_random_variable` works fine for `foo.py` but changes `bar.py`:
``` python
# bar.py

# comments ########################################
# more commments ##############################some_random_variable even more comments ##############################


def baz(quux):
    pass

```

**Comment by MikhailArkhipov** [comment]
Related #433
