### ISSUE TITLE
Union[A,B] type hint yields [user class A, user class B] instead of [instance A, instance B]

### ISSUE THREAD

**Issue by lostmsu** [Microsoft/python-language-server#459]
Subj.

```python
from typing import Union
class A:
  pass
class B:
  pass
def a() -> Union[A,B]: ...
def b() -> A: ...
```
Analysis of `a`'s return type gives back a set of user class A and user class B, whereas it should be instance A and instance B.
For comparison, analysis of `b`'s return type gives back a set of instance A.

**Comment by jakebailey** [comment]
As of #546:

```python
from typing import Union
class A:
    def __init__(self):
        self.a = 1234

class B:
    def __init__(self):
        self.b = "1234"

def a() -> Union[A,B]: ...
def b() -> A: ...

aa = a()
bb = b()
```

![image](https://user-images.githubusercontent.com/5341706/52462191-f3c47180-2b26-11e9-9d83-87a0eec6c4e7.png)

![image](https://user-images.githubusercontent.com/5341706/52462212-0048ca00-2b27-11e9-91d0-10f601016d04.png)
