### ISSUE TITLE
Using the collecting variable of iterable unpacking causes "used before definition" error

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/python-language-server#461]
Microsoft/vscode-python#3543

```python
a, *b, c = range(5)
print(b)
```

`b` ends up being reported as used before definition.

**Comment by jakebailey** [comment]
My guess (without looking too hard) is that we aren't handling this style of unpack properly (see #412, #403), and we're considering it to be a use like it's a mul or a args/kwargs unpack.

**Comment by md2perpe** [comment]
I got the same error in a loop construction like

```python
for first, *rest in data:
    use(first, rest)
```

Here, `rest` gets reported as used before definition on the `use` line.
