### ISSUE TITLE
No intellisense for azure package when creating a Python Function App

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/python-language-server#462]
Create an Azure Function App in Python and here's the sample code that gets generated (`requirements.txt` further below):
```python
import logging
import azure.functions as func
import sys

def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info("Python HTTP trigger function processed a request.")
    name = req.params.get("name")
```

There's no intellisense for `azure` package, hence no intellisense for `req`.

I've tried pip installing the following into a separate python environment still nothing:
```
azure-functions==1.0.0a5
azure-functions-worker==1.0.0a6
grpcio==1.14.2
grpcio-tools==1.14.2
protobuf==3.6.1
six==1.11.0
```

Then checking for intellisense for `azure`, the result is nothing.
No errors, nothing, waited for 10 minutes, still nothing.

## Jedi works and its available immediately.

**Comment by DonJayamanne** [comment]
>  you trying to do azure., or something 

Yes

Anyways it works for Jedi

**Comment by jakebailey** [comment]
I guess I'm confused, then. `import azure.functions as func` is what is written. The `azure` package is not in scope. If you have it handy, it'd be good to see what you're seeing from Jedi, but we'll probably test it eventually too.

**Comment by MikhailArkhipov** [comment]
There is completion for azure and its components. However, params don't have sufficient info for 'get'

![image](https://user-images.githubusercontent.com/12820357/52894292-f42ebf00-315b-11e9-8cbe-b8d19e67a822.png)

![image](https://user-images.githubusercontent.com/12820357/52894300-1cb6b900-315c-11e9-81f4-693882844b82.png)

**Comment by MikhailArkhipov** [comment]
@DonJayamanne - what is expected?

![image](https://user-images.githubusercontent.com/12820357/52995341-2eec5d80-33cf-11e9-8261-d2d120774fb3.png)
