### ISSUE TITLE
Fix "go to definition" and resolving imports

### ISSUE THREAD

**Issue by busykoala** [Microsoft/python-language-server#466]
I have `"python.analysis.downloadChannel": "daily"` activated.

The update two days ago broke the 'go to definition' feature for my setup.
I'm using vscode and it's regarding a large plone project using the omelette as described below.

To avoid language server load infinitely (which would be another issue, maybe related to [this](https://github.com/Microsoft/python-language-server/issues/181)), I excluded the `parts/omelette` with `search.exclude`.
Below that in the settings, I added the `parts/omelette` with: `"python.autoComplete.extraPaths": ["${workspaceFolder}/parts/omelette", ],` which seemed to work for the last few days now.
By 'it seemed to work' I mean it could resolve the omelette imports and jump to definitions.
Now it sais 'no definition found for...' and the imports can't be resolved anymore.

For what I can see in the output, before the update, it used to analyse from `autoComplete.extraPath`, which it does not anymore since it updated the language server today.

(`parts/omelette` contains symlinks to cross-project sources in a local directory.)

**Comment by jakebailey** [comment]
@busykoala 	A new build with #467 is in progress and should show up in daily in a bit.

**Comment by busykoala** [comment]
Thank you very much! 

The version I tried now, could resolve imports again with given settings.

Not yet solved in my case is 'go to definition' which once was working properly (about three days ago).
The output I get when trying to jump to a definition is following:
```
[Error - 12:09:05 AM] Request textDocument/definition failed.
  Message: PriorityProducerConsumer`1 instance is disposed
Object name: 'PriorityProducerConsumer`1'.
  Code: -32000 
   at Microsoft.PythonTools.Analysis.Infrastructure.DisposeToken.ThrowIfDisposed()
   at Microsoft.PythonTools.Analysis.Infrastructure.PriorityProducerConsumer`1.Produce(T value, Int32 priority)
   at Microsoft.PythonTools.Intellisense.AnalysisQueue.ExecuteInQueueAsync(Func`2 function, AnalysisPriority priority)
   at Microsoft.Python.LanguageServer.Implementation.Server.WaitForCompleteAnalysisWorker(CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.Server.FindReferences(ReferencesParams params, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.Server.GotoDefinition(TextDocumentPositionParams params, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.GotoDefinition(JToken token, CancellationToken cancellationToken)
```

Rather than [this file structure](https://github.com/Microsoft/python-language-server/pull/467#issuecomment-445364135) `some/other/package_x` only is a symlink. This is pretty handy to have shared packages and is common use in plone projects.
```
root
│   main.py
│
├───project
│       __init__.py
│
└───some
    └───other
        └───package_x -> Users/username/.buildout/eggs/package_x
```
As I mentioned to avoid infinit loading on 'go to definition' it yet (and still) is necessary to search exclude `**/some/other`.
The folder is added again with `"python.autoComplete.extraPaths":["${workspaceFolder}/some/other", ],`

**Comment by jakebailey** [comment]
Is there an error message before that disposed message? That should only occur after an exception occurs in a different part of the code (#448), but the initial error should be in the same output panel.

**Comment by busykoala** [comment]
Well I think it's not really an error message except of 'no definition found for...' in the vscode gui.
```
Getting hover for package_name
Waiting for parsing to complete.
Parsing complete. Waiting for analysis entries to enqueue.
Enqueue complete. Waiting for analysis to complete.
[Error - 12:39:21 AM] Request textDocument/definition failed.
```

**Comment by AlexanderSher** [comment]
@busykoala , I've tried to recreate the file structure with symlink, but for me `go to definition` works as expected. If you have minimal repro, can you pack it into zip or tarball and attach to the bug?

**Comment by busykoala** [comment]
I've just tried different repositories with the same structure.

In smaller project it worked having these two lines in my settings:
```
"python.autoComplete.extraPaths": ["${workspaceFolder}/parts/omelette", ],
"python.autoComplete.typeshedPaths": ["${workspaceFolder}/parts/omelette", ],
```

With bigger projects it's not working. Therefore I guess it is regarding the size of projects. I'm sorry I didn't figure that out before.

Thank you for the help and let me try python language server when it advanced a little more.

**Comment by busykoala** [comment]
I thought I'd give vscode a shot again.

My language server relevant settings are:
```
"python.jediEnabled": false,
"python.analysis.downloadChannel": "daily",
```
using microsoft language server in vscode 1.30.2 and the correct python environment.

I tested with the repository https://github.com/4teamwork/opengever.core/ which has the setup described above and reliably doesn't work (going to definition, completion suggestions).

After indexing (I guess indexing has finished because there are no new logs of indexing anymore) when trying to use `go to definition` the blue loading bar at the top moves around and the log shows:
```
Waiting for parsing to complete.
Parsing complete. Waiting for analysis entries to enqueue.
Enqueue complete. Waiting for analysis to complete.
```
It stays like that for minutes (I only waited around 5') until one quits the program.

I'm not totally sure that the settings are correct, but I couldn't figure out why it shouldn't work like that.

**Comment by MikhailArkhipov** [comment]
To verify perf with https://github.com/Microsoft/python-language-server/pull/546.

**Comment by busykoala** [comment]
It looks like the omelette is being indexed and also does not show any error of not found imports but I'm still not able to make use of `go to definition`.
It does not seems to use much ram anymore as it did previously though.

**Comment by MikhailArkhipov** [comment]
@busykoala - so what is the current problem? Is there particular code/workspace we can use for repro? LS analysis was rewritten so I'd like to verify whatever didn't work for you now does.

**Comment by busykoala** [comment]
I tested the issue again now. The repo I used is https://github.com/4teamwork/opengever.core/

__Steps to get there:__
```
git clone git@github.com:4teamwork/opengever.core.git
path/to/python/env/2.7/without/setuptools/installed bootstrap.py
bin/buildout
```

Now the project should be setup. I open it in code with the python relevant settings and using the same environment as used to bootstrap:
```
"python.analysis.logLevel": "Trace",
"python.jediEnabled": false,
"python.analysis.downloadChannel": "daily",
```

The version of vscode is 1.31.1 and because of `"python.analysis.downloadChannel": "daily",` the version of language server should be the most recent.

__A use case which does not work:__

If I open the file `opengever/api/notifications.py` and `rightclick/Go to Definition` on `interface` https://github.com/4teamwork/opengever.core/blob/447c6e9828afe300bfd3a64165c355136f780d85/opengever/api/notifications.py#L9 I get the output:
```
Hover in file:///Users/busykoala/Documents/Github/opengever.core/opengever/api/notifications.py at (8, 13)
Waiting for parsing to complete.
Parsing complete. Waiting for analysis entries to enqueue.
Enqueue complete. Waiting for analysis to complete.
```

It does not go to the definition and the blue line on top starts going from left to right (indefinitely until closing the application).

![image](https://user-images.githubusercontent.com/29920936/53556555-6338ea00-3b44-11e9-8066-9ddeef10a573.png)

**Comment by aniforprez** [comment]
Just adding that I too am facing this same issue as @busykoala has detailed so well. The blue bar appears on top, keeps "loading" but never stops until you reload the window or quit the appllication. The "ctrl+click" method works fine until some unknown point in time when it stops turning certain symbols into links and then this happens

**Comment by contactr2m** [comment]
This happens in both cases ie. whether jedi is enabled or disabled.
When jedi is enabled:
It takes times hower tooltip to appear also sometimes it doe not even appear and justs loops.

When jedi is disabled: (MS python language server kicks in)
Keeps loading.

**Comment by jakebailey** [comment]
We released a new version of the language server to the beta download channel (0.2.16). You can set this in your VS Code `settings.json` to get it:

```
"python.analysis.downloadChannel": "beta"
```

I'd appreciate it if you could retest with your setup.

**Comment by bcroq** [comment]
@jakebailey I just updated to 0.2.16, "Go to definition" works.

**Comment by busykoala** [comment]
The update was a major improvement. For some imports I can now go to definition now and it stopped the looping thing of the loading bar.

- While some can now be followed, many others still won't work. I'll update if I have a better idea of which work and which don't but strangely I tested some which I thought would act exactly the same.
- Completion while writing still isn't working at all (if I start writing an import path and would like to know the possible options).
- Once in a file from the omelette I couldn't go to definition at all (for my tested cases).

**Comment by jakebailey** [comment]
That is #719.

**Comment by busykoala** [comment]
With these settings it is working perfectly fine for some time (around a minute) and then something breaks (I think this is the initial error):

```
Goto Definition in file:///Users/busykoala/Documents/PythonProjects/opengever.core/opengever/core/hooks.py at (1, 39)
[Error - 3:06:16 PM] Unable to find document file:///Users/busykoala/Documents/PythonProjects/opengever.core/opengever/core/hooks.py
[Error - 3:06:16 PM] Request textDocument/definition failed.
  Message: Object reference not set to an instance of an object.
  Code: -32000 
   at Microsoft.Python.LanguageServer.Sources.DefinitionSource.FindDefinition(IDocumentAnalysis analysis, SourceLocation location)
   at Microsoft.Python.LanguageServer.Implementation.Server.GotoDefinition(TextDocumentPositionParams params, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.GotoDefinition(JToken token, CancellationToken cancellationToken)
```

__settings__

workspace settings (in `${workspace}/.vscode/settings.json`):

```
{
    // python virtual environment
    "python.pythonPath": "/absolute/path/to/venv/bin/python",
    // add the omelette folder
    "python.autoComplete.extraPaths": [
        "${workspaceFolder}/parts/omelette",
    ],
    // for my project python language server would crash and stop restarting
    // without raising the default memory max
    "files.maxMemoryForLargeFilesMB": 8192,
}
```

user settings (`cmd+p` then `Preferences: Open Settings (JSON)`):

```
{
    // exclude omelette (in parts folder)
    "search.exclude": {
        "**/parts": true,
    },
    // to use ms python language server
    "python.jediEnabled": false,
    // for some nice output
    "python.analysis.logLevel": "Trace",
    // to get the most current stuff
    "python.analysis.downloadChannel": "daily",
    "python.analysis.downloadChannel": "beta",
}
```

**Comment by MikhailArkhipov** [comment]
@busykoala - the exception should be fixed in 0.2.36 that is coming out ~ March 29th
`Once in a file from the omelette I couldn't go to definition at all (for my tested cases).` - #840.

Since the item is evolved with many cases fixed, I am closing it. Please open new issues for the cases you still discover. Thanks.

**Comment by erihanse** [comment]
Has this stopped working again? It works with `python.jediEnabled: true`
![image](https://user-images.githubusercontent.com/9251274/56459107-5fc91e80-638f-11e9-97e5-9b387c17fe56.png)

**Comment by jakebailey** [comment]
What is the message being squiggled? If the import isn't resolved, then it won't be able to find the definition.

**Comment by erihanse** [comment]
I believe it's a linter complaining about lack of module documentation. The import should be valid.

**Comment by jakebailey** [comment]
A linter meaning an external linter, or a message generated by the language server? (It'll say `(Python)` in the hover if it's from the LS, otherwise the name of the linter.)

Also, what's in your `.env`? Are you setting PYTHONPATH? Similarly, are you setting extraPaths in your VS Code settings?

**Comment by erihanse** [comment]
It's an external, pydocstyle.
![image](https://user-images.githubusercontent.com/9251274/56512504-da30a480-652f-11e9-8ed9-fcf238a5f8ef.png)
.env: 
```
PYTHONPATH="."
```
I'm not setting extraPaths in vs code settings.

**Comment by erihanse** [comment]
![image](https://user-images.githubusercontent.com/9251274/56512626-35fb2d80-6530-11e9-843e-1dba4d279cda.png)
When I hover it says it sees it as a module.

**Comment by jakebailey** [comment]
You're at the latest version, correct? I recently fixed some things related to setting a path to `.` (which should be redundant, as the opened folder itself is a search path). Are variables from that imported module accessible, or are they not listed?

Since I think it's getting resolved, it's probably not related to the `PYTHONPATH=.` fixes. I'd appreciate it if you could open a new issue with that project attached (zipped, if you're willing to upload it).

**Comment by erihanse** [comment]
I'm running 2019.3.6558 (8 April 2019) of vs code python extension. Not sure if there are any steps I need to do to upgrade LS? I'll create a new issue.

**Comment by jakebailey** [comment]
The LS version is different from the extension; you can find the language server version printed in the Python output panel (or in the directory name for the download inside the Python extension's folder).
