### ISSUE TITLE
Persistent analysis

### ISSUE THREAD

**Issue by MikhailArkhipov** [microsoft/python-language-server#472]
`DocumentAnalysis` can be made persistent and cached on disk.
https://github.com/microsoft/vscode-python/pull/7468

**Comment by MikhailArkhipov** [comment]
Needs results of #1023 first.

**Comment by MrTango** [comment]
It's way better now, thx for your work

**Comment by Congee** [comment]
note of implementation ref https://github.com/microsoft/python-language-server/pull/1224

**Comment by jakebailey** [comment]
For reference, this is a ZenHub epic, so it connects other issues (but isn't visible by default on GitHub, hence why this isn't closed).

**Comment by MikhailArkhipov** [comment]
Caching of system modules analysis is enabled in beta channel as of 0.4.39

**Comment by MikhailArkhipov** [comment]
https://github.com/microsoft/python-language-server/pull/1757

**Comment by MikhailArkhipov** [comment]
```json
"python.analysis.cachingLevel": "None | System | Library",
```
https://github.com/microsoft/python-language-server/wiki/Module-caching

![image](https://user-images.githubusercontent.com/12820357/70638750-4448a780-1bee-11ea-990c-b4c435861115.png)
