### ISSUE TITLE
Unresolved Import w/ VSCode

### ISSUE THREAD

**Issue by mikeerickson** [Microsoft/python-language-server#489]
Is there a way to flag these lines as valid, despite the issue of `unresolved-import`

I have the following

```python
import sys
import os.path
import unittest
import datetime

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from lib.Messenger import Messenger as Messenger
from lib.Messenger import error, success, info, warning, status, notice, log, debug, important, timestamp
```

The two `from...` statements are flagged as `unresolved-imports`

Can these errors be flagged as OK so that I dont seem them in the `Problems` area

![image](https://user-images.githubusercontent.com/183153/49894947-0d398d80-fe04-11e8-8f54-8a3b8ecbdc94.png)

**Comment by jakebailey** [comment]
We don't currently have a way to disable warnings on a specific set of lines (#264), but you can disable the unresolved-import message overall by adding to your settings.json:

```json
"python.analysis.disabled": [
    "unresolved-import"
]
```

Be aware that the most recent stable release made a number of changes to the import system which may help in some cases, though I believe that any sort of at-runtime sys.path modification still will not resolve imports (#458).

**Comment by mikeerickson** [comment]
Awesome, thanks for the update.  I have applied your recommendation for the time being.

Now, if I could just get [Python Auto Formatting](https://github.com/Microsoft/vscode-python/issues/3655)  to work, I would be a happy camper!
