### ISSUE TITLE
Intellisense not showing docstrings from /lib/site-packages modules in Python 2.7 virtual env

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/python-language-server#490]
@darrickyee commented on [Tue Oct 23 2018](https://github.com/Microsoft/vscode-python/issues/2989)

Docstrings do not appear in Intellisense info for modules living in a virtual environment's /lib/site-packages directory for Python 2.7.11 virtual environment.

They DO appear for identical modules in a virtual environment based on Python 3.7.

## Environment data

- VS Code version: 1.28.2
- Extension version (available under the Extensions sidebar): 2018.9.1
- OS and version: Windows 7
- Python version (& distribution if applicable, e.g. Anaconda): 2.7.11
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv 
- Relevant/affected Python packages and their versions: Any in /lib/site-packages

User settings JSON:
{
    "python.jediEnabled": false,
    "python.linting.enabled": false
}

Workspace settings JSON:

{
    "python.pythonPath": [Path to virtualenv python.exe]
}

## Actual behavior

Docstring does not appear in Intellisense info.

![Python 2.7](https://i.imgur.com/tvOMBe2.jpg)

## Expected  behavior

Docstring appears in Intellisense info.

![Python 3.7](https://i.imgur.com/aYRSQnP.jpg)

## Steps to reproduce:
1. Create a Python 2.7.11 virtual environment using virtualenv.
2. Import some module from /lib/site-packages.
3. Type or begin typing an object name from the imported package.
**Result: Docstring does not appear in Intellisense info.**

Modify step 1 by creating a Python 3.7 virtual environment instead and copying the module to that virtual environment's /lib/site-packages.  Docstring should appear in Intellisense after steps 2 and 3.

[Edit] Should add that jedi does show the proper docstrings with Python 2.7, but it is very, very slow.

---

@DonJayamanne commented on [Wed Oct 24 2018](https://github.com/Microsoft/vscode-python/issues/2989#issuecomment-432745726)

> Modify step 1 by creating a Python 3.7 virtual environment instead and copying the module to that virtual environment's /lib/site-packages. Docstring should appear in Intellisense after steps 2 and 3.

Why are you copying the files? Why don't you pip install them?

---

@DonJayamanne commented on [Wed Oct 24 2018](https://github.com/Microsoft/vscode-python/issues/2989#issuecomment-432773510)

Works for me, please could you try the following:
* Open your `settings.json`
* Add the following setting:
```js
"python.analysis.downloadChannel": "daily",
```

* You will get some red squigglys under the above, please ignore.
* Please reload VS Code and a new version of the language server will get downloaded, wait until it gets downloaded and started
* Let me know how it goes.

---

@darrickyee commented on [Wed Oct 24 2018](https://github.com/Microsoft/vscode-python/issues/2989#issuecomment-432810855)

Thanks for the response.  Still not working for me, though.  The log says Microsoft Python Language Server version 0.1.50.0, is that correct?  If not, I might be having network issues at work and could have better luck on my home computer.

I'm trying this:
```
import setuptools.archive_util as au
au.unpack_archive
```
Hovering over "unpack_archive" doesn't show the docstring in the 2.7.11 environment, but it does in 3.7.0.
To answer your question,

> Why are you copying the files? Why don't you pip install them?

In some cases, there isn't a pip install available (e.g., Maya's pymel stubs).  In other cases, I have some of my own libraries that I would like to include in every project that uses the environment.

---

@darrickyee commented on [Thu Nov 08 2018](https://github.com/Microsoft/vscode-python/issues/2989#issuecomment-437046896)

Any updates on this?  I realize Python 2.7 is getting a bit "long in the tooth," but unfortunately we're stuck with it in Maya/UE4/any other VFX software until the [VFX Reference Platform](https://www.vfxplatform.com/) moves to 3.x in 2020...

---

@DonJayamanne commented on [Mon Nov 19 2018](https://github.com/Microsoft/vscode-python/issues/2989#issuecomment-440021152)

Please update your extension to the latest version and remove the following setting `"python.analysis.downloadChannel": "daily",`

The latest version should be >= `0.1.60`

Please let me know if the problem persists.

---

@darrickyee commented on [Thu Nov 29 2018](https://github.com/Microsoft/vscode-python/issues/2989#issuecomment-442926253)

I just ensured my version is 0.1.60, but the behavior is the same as before.  Tested with setuptools.archive_util.unpack_archive as above, plus a couple of different functions.  The docstring appears when 3.7 is my interpreter, but not 2.7.

**Comment by jakebailey** [comment]
I can still reproduce this in the new language server; goto-def in Python 2 brings me to python source with a docstring, which should get rendered, but it is not.

**Comment by MikhailArkhipov** [comment]
Needs #642

**Comment by Ranguna** [comment]
Do we have an update on this ?

**Comment by MikhailArkhipov** [comment]
@jakebailey worked on docs

**Comment by sandipb** [comment]
Still a problem with 0.2.63 and python 2.7.13. Will have to switch back to Jedi because of this even though Jedi is a pain.

**Comment by jakebailey** [comment]
At the latest language server, this seems to be working fine:

![image](https://user-images.githubusercontent.com/5341706/61910885-b4c68480-aeea-11e9-8bb5-b0b8ee171e5f.png)

The recent Python 2 import fixes may have had an impact.
