### ISSUE TITLE
Error pop-up after renameing a Python file

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/python-language-server#496]
@neilsustc commented on [Sat Dec 15 2018](https://github.com/Microsoft/vscode-python/issues/3717)

## Environment data

- VS Code version: 1.31.0-insider
- Extension version (available under the Extensions sidebar): 2018.12.1
- OS and version: Windows 10 build 18298
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.5
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX 
- Relevant/affected Python packages and their versions: XXX

## Expected behaviour

No pop-up

## Actual behaviour

![rename](https://user-images.githubusercontent.com/7588612/50045037-74657500-0084-11e9-9b79-da33acf7aebb.gif)

## Steps to reproduce:

1. Rename a Python file

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
[Error - 3:57:53 PM] One or more errors occurred. (failed to parse file file:///d:/Workspace/vscode-test/test-python/rename.py)
```

**Comment by MikhailArkhipov** [comment]
This is fixed in the upcoming LS 0.2.x

**Comment by LeoJhonSong** [comment]
I got similar issue!

**Comment by jakebailey** [comment]
0.2.16 is now available on beta channel. You can set this in your VS Code `settings.json` to get it:

```
"python.analysis.downloadChannel": "beta"
```
