### ISSUE TITLE
Language server doesn't find Blender modules

### ISSUE THREAD

**Issue by wkema** [Microsoft/python-language-server#497]
After the recent updates, the language server does no longer work with the custom packages in the extraPaths settings. It worked before.

Jedi engine is still working.

This might be a similar case to #462 

Environment data
--------------
VS Code version: 1.30.0
Extension version (available under the Extensions sidebar): 2018.12.1
OS and version: Windows 10
Python version (& distribution if applicable, e.g. Anaconda): 2.7.14 (32-bit)

Actual behavior
----------
![image](https://user-images.githubusercontent.com/12742725/50161309-76f4e400-02a9-11e9-8531-7a33abf1fc3d.png)

Expected behavior
-----------
(Jedi works fine)
![image](https://user-images.githubusercontent.com/12742725/50161346-925fef00-02a9-11e9-9cba-04ae05b692b0.png)

**Comment by MikhailArkhipov** [comment]
@wkema - can you show where extraPaths are pointing? In VS Code they are merged into searchPaths (appended at the end).

**Comment by MikhailArkhipov** [comment]
OK, this is then specific to Blender (changing title). I understand you are trying to author Blender related code outside of the Blender itself. How do you set extraPath exactly?

**Comment by wkema** [comment]
The blender folder looks like this
![image](https://user-images.githubusercontent.com/12742725/50247768-d553bc80-03a6-11e9-8104-e07a92ef8796.png)

and my extraPaths setting is:
![image](https://user-images.githubusercontent.com/12742725/50247836-016f3d80-03a7-11e9-8ea4-f827dd749956.png)

Actually I did another experiment by moving the bpy folder in the blender folder shown above to 
C:/Python27/Lib/site-packages/
Then it works for the bpy package.
![image](https://user-images.githubusercontent.com/12742725/50248036-a8ec7000-03a7-11e9-93ee-0e997fede496.png)

So I still think it is the problem with the path?

**Comment by AlexanderSher** [comment]
Can you try to move the `fake_lib` out of the `Python27` folder?

**Comment by wkema** [comment]
@AlexanderSher Thanks a lot for this suggestion. It solves the problem. I moved the folder to another directory and change the extraPaths accordingly. Now it works like charm, again.

It is not a good practice to directly modify the Python folder I guess. Thank you guys so much!
