### ISSUE TITLE
PTVS-LS Integration: Fix PythonSuggestedActionsSource 

### ISSUE THREAD

**Issue by AlexanderSher** [microsoft/python-language-server#499]
`PythonSuggestedActionsSource` calls `Analyzer.FindNameInAllModulesAsync`, which only accepts text of the import. Instead, it requires span, document and version. Current implementation tries to look for all possible text inclusions, which hangs LS for several seconds.

**Comment by AlexanderSher** [comment]
Currently `PythonSuggestedActionsSource` is disabled

**Comment by MikhailArkhipov** [comment]
Probably no longer applies as PTVS is moving to new LS?
