### ISSUE TITLE
Implement format on type

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/python-language-server#5]
https://github.com/Microsoft/PTVS/issues/4694

Implementation can be borrowed from
https://github.com/Microsoft/vscode-python/blob/master/src/client/formatters/lineFormatter.ts

translate to C#
change it to use LS tokenizer
augment with knowledge of the AST where appropriate (such as checking if = is inside function arguments)
See also Microsoft/vscode-python#1799

**Comment by MikhailArkhipov** [comment]
Reducing cost to actual for this milestone - basically to the PR review.

**Comment by jakebailey** [comment]
Finished in #126.

**Comment by DonJayamanne** [comment]
Would like to discuss this once again:
* Currently indentation of code is implemented within the extension (and buggy, as we do not have the AST information, etc)
* Currently the C# extension supports similar features (indentation changes) when you type the character `}`.
* We need the same thing, when users type the character `:`.

**Comment by MikhailArkhipov** [comment]
Could you please open separate issue. This one was explicitly about moving code from TS to C# and adding additional functionality. This was was completed.

Short answer: TS side does not have AST.
