### ISSUE TITLE
No cross-platform way to define import search paths

### ISSUE THREAD

**Issue by erictraut** [Microsoft/python-language-server#505]
There is currently no way (that I know of) to define import search paths in a cross-platform manner. The recommended approach is to create a ".env" file at the top directory of your workspace and within this file define a PYTHONPATH variable. However, the format of this variable is platform-specific. On MacOS and Linux, it needs to be colon-delimited. On Windows, it needs to be semicolon-delimited. Consequently, there's no way to check in the required PYTHONPATH for a project that works for all developers on a team, regardless of which platform they're using for development.

It would be great to allow specification of the PYTHONPATH in a platform-agnostic way, preferably using a JSON config file or a settings entry that is honored by the PLS.

**Comment by jakebailey** [comment]
If you're using VS Code, this should already be possible by using `python.autoComplete.extraPaths`, which is just a JSON array.

As mentioned on #504, we don't read `.env`, just accept a list of paths from the extension, so you may want to open an issue on the extension instead.

But, I think that the way `.env` is defined (`.env` is a somewhat common thing in places like Ruby, `docker-compose`, godotenv, etc), it may not be possible to define it such that it works cross platform. I know that I use it as a local configuration for projects where I don't want to specify certain secrets and have them be visible as flags in top or in my shell history (like API keys or passwords), and then never commit it. A VS Code workspace configuration may be a better option.

**Comment by DonJayamanne** [comment]
Closing in favour of the answer provided `If you're using VS Code, this should already be possible by using python.autoComplete.extraPaths, which is just a JSON array.`

**Comment by erictraut** [comment]
Ah, I didn't realize that `python.autoComplete.extraPaths` was available. That nicely addresses this problem.
