### ISSUE TITLE
PLS does not resolve base class expressions in correct scope

### ISSUE THREAD

**Issue by erictraut** [Microsoft/python-language-server#508]
Consider the following Python code:

```
class ContainerClass():
    class BaseClass(object):
        def __init__(self, name):
            self.name = name

    class SubClass(BaseClass):
        def __init__(self): 
            super().__init__('')
```

The PLS analyzer logic incorrectly reports that `BaseClass` is referenced before being defined. In looking at the PLS code, `AnalysisUnit.AnalyzeWorker` is calling `EvaluateBaseClass` from within the scope of the subclass rather than its outer (containing) class.

I think this can be fixed by modifying `AnalysisUnit.AnalyzeWorker` to temporarily set the scope of the ddg to the outer scope before calling `EvaluateBaseClass`. Something like this:
```
// Evaluate base classes in the outer scope.
if (_outerUnit.Scope is InterpreterScope) {
    ddg.Scope = _outerUnit.Scope as InterpreterScope;
}
bases.Add(EvaluateBaseClass(ddg, classInfo, i, baseClassArg.Expression));
ddg.Scope = InterpreterScope;
```

**Comment by MikhailArkhipov** [comment]
Comment in #513

**Comment by erictraut** [comment]
I confirmed this bug still exists in the newly-refactored code as well.

**Comment by MikhailArkhipov** [comment]
New code does not report definition order... And there is no language server that uses new code yet. The only thing that exists for the new code is unit tests... I checked this snipped in a unit test to make sure there are no parse errors, there are none.

**Comment by MikhailArkhipov** [comment]
Not applicable after https://github.com/Microsoft/python-language-server/pull/546. The offending code is gone.
