### ISSUE TITLE
PLS doesn't flag error in a relative import if it is found in another root directory

### ISSUE THREAD

**Issue by erictraut** [Microsoft/python-language-server#509]
The analyzer incorrectly accepts relative imports in cases where the path is relative to a root but not to the importing file.

Consider the following case:
Directory structure:
src
|->module
|--->__init__.py
test.py

PYTHONPATH=src

test.py contains the following code:
```
from .module import Foo
```

This import should be flagged as invalid because the path ".module" should be relative to the test.py file. However, the code in `PathResolverSnapshot.GetImportsFromRelativePath` considers all of the root search directories when it performs its search. It therefore finds an import match when it shouldn't.

I think the problem is in `PathResolverSnapshot.RootContains`. It doesn't do anything to validate that the specified lastEdge starts in the same location as the root. If the relative path happens to match items within that root, the method returns true. If the relative path is zero length, all roots return true.

A proposed fix is to add the following piece of code to `PathResolverSnapshot.RootContains` before the while loop:

```
if (root != sourceEdge.Next.Start) {
    rootEdge = default;
    return false;
}
```

**Comment by AlexanderSher** [comment]
The problem isn't related to the multiple roots. With `"python.autoComplete.extraPaths": ["D:\\Work\\Temp\\Issues\\509\\src"]` and the following file structure:
```
├─ package
│  └─ test.py
└─ src
   └─ package
      └─ module
         └─ __init__.py
```
code `from .module import *` in `test.py` is valid.

But, `from .module` is invalid when `test.py` is in root.

**Comment by AlexanderSher** [comment]
We probably should have an exception for the working directory, cause it maybe a top directory of the module.
