### ISSUE TITLE
PLS doesn't resolve relative paths correctly

### ISSUE THREAD

**Issue by erictraut** [Microsoft/python-language-server#510]
The analyzer sometimes does not resolve relative paths correctly. See the screen shot below.

![screen shot 2018-12-26 at 1 53 04 am](https://user-images.githubusercontent.com/7040122/50443381-07d64b80-08b8-11e9-999f-94059790fac9.png)

The problem appears to be in `PathResolverSnapshot.TryFindName` which contains the following lines of code:
```
if (lastEdge.End.IsModule) {
    return false;
}
```
I don't understand why this logic is needed. When I comment out these three lines, the relative paths resolve correctly and other imports also appear to resolve as expected.

**Comment by AlexanderSher** [comment]
> I don't understand why this logic is needed. 

It is required for the case when there is a folder with the name of the module.
For example, for the following file structure:
```
├─ package
   ├─ module
   │  └─ submodule.py
   ├─ module.py
   └─ test.py
```
and `test.py`:
```
from .module.submodule import TEST
```
import should be highlighted as invalid import.

In your case, what is the value of `lastEdge.End.ModulePath` in 
```cs
if (lastEdge.End.IsModule) {
    return false;
}
```

**Comment by erictraut** [comment]
In the example you gave above, if the `module` directory contained an `__init__.py` file, the import from `test.py` should succeed. Would you expect `lastEdge.End.IsModule` to evaluate to false if `__init__.py` is present?

To answer your question. `lastEdge.End.IsModule` evaluates to true in my case, which is what causes the `.exceptions` and '.image_builder` imports to be incorrectly flagged as errors.
