### ISSUE TITLE
Diagnostic list flickers annoyingly when closing a document

### ISSUE THREAD

**Issue by erictraut** [Microsoft/python-language-server#511]
In VSCode, if you display all diagnostics for your project (i.e. set the "python.analysis.openFilesOnly" to "false"), you can view the list in the "Problems" panel. If you open a Python file that contains a reported diagnostic and then close that same document, all of the diagnostics for that file briefly disappear and then reappear.

The problem appears to be in the `EditorFile.Close` method. It unconditionally hides all of the diagnostics for a file when a document is closed, even if the user has requested that diagnostics should be shown for closed documents. I think the correct fix is to change the method to the following, adding a conditional check based on `ShouldHideDiagnostics`.
```
public void Close(Uri documentUri) {
    IsOpen = false;
    if (ShouldHideDiagnostics) {
        _syncContext.Post(_ => HideDiagnostics(documentUri), null);
    }
}
```
When I make this change, the annoying behavior disappears.

**Comment by MikhailArkhipov** [comment]
We no longer provide analysis in closed documents. `Open files only` is the default and the only option.
