### ISSUE TITLE
PLS incorrectly reports error for self-assignment to local variable

### ISSUE THREAD

**Issue by erictraut** [Microsoft/python-language-server#513]
The analyzer incorrectly flags the following (admittedly strange) code with a use-before-def error/warning.

![screen shot 2018-12-26 at 10 45 46 am](https://user-images.githubusercontent.com/7040122/50454433-6d4c2b80-08fc-11e9-975c-3b431227bf41.png)

The problem is due to a somewhat hacky piece of code in `DDG.Walk(AssignmentStatement node)` that attempts to detect the case "fob = fob" and temporarily manipulate the scope before evaluating the RHS of the assignment. This hack is problematic for a number of reasons. For example, it doesn't properly handle other more complex expressions like "fob = fob + 1".

I think the preferable solution is to remove the hack but modify the logic to allow _reading_ of symbols in outer scopes even if `VisibleToChildren` is false. This property should probably be renamed `WritableByChildren` since Python allows reading of symbols from outer scopes.

See the following documentation in [section 2.1 of the official Python docs](https://docs.python.org/3.7/tutorial/classes.html).

![screen shot 2018-12-26 at 10 59 02 am](https://user-images.githubusercontent.com/7040122/50454574-46dac000-08fd-11e9-8b95-2f54d76c73aa.png)

**Comment by MikhailArkhipov** [comment]
We are not actively developing current analysis code as per https://github.com/Microsoft/python-language-server/issues/425 we are replacing DDG analysis (user files) and AST analysis (libraries) by a combination. The new analysis code base is in development, partial is here https://github.com/Microsoft/python-language-server/pull/465. It is a separate code, we just keep existing code around so we can check behavior and port tests.

**Comment by erictraut** [comment]
I confirmed that this same problem exists in #465.
