### ISSUE TITLE
Language Server startup is slow

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/python-language-server#514]
@DonJayamanne commented on [Wed Dec 12 2018](https://github.com/Microsoft/vscode-python/issues/3664)

Starting Language Server has been observed to take over 5s.

---

@DonJayamanne commented on [Thu Dec 27 2018](https://github.com/Microsoft/vscode-python/issues/3664#issuecomment-450213725)

Delay is in `serverReady`
The while statement takes 3 seconds on Mac and 2 seconds on Windows.
I.e. LS is slow.

https://github.com/Microsoft/vscode-python/blob/4f190993af8e131d969abefdf0b0c50f0de4ea2b/src/client/activation/languageServer/languageServer.ts#L189-L198

**Comment by MikhailArkhipov** [comment]
This is for IntelliCode.  They need server to be ready before the extension loads. Technically we could use then rather than await but although _measured_ startup time would improve, time between app start and intellisense available will not change. But it is the latter that matters.

**Comment by MikhailArkhipov** [comment]
This can be redesigned in such a way so only IC waits for the startup but again, availability of the editor features will not improve, only measure time in the typescript. In fact, what matter is time between file is opened and the completion is available. Process startup time is just a fraction and is not something we can fix.
