### ISSUE TITLE
Language Server overhead

### ISSUE THREAD

**Issue by CMLL** [Microsoft/python-language-server#515]
Opening a second window of VSCode and opening a Python File creates a second LanguageServer process that seems to be separated from the one running on the original window and thus will end up analyzing the same opened files if they are duplicated between editors which could lead to an overuse of resources.

I think connecting to an existing language server rather than creating a new one would be a better approach to avoid consuming resources.

**Comment by MikhailArkhipov** [comment]
This is how VS Code works. As it is opens all files again in the second instance, it launches another language server instance. It is not really possible to connect to the running instance as RPC is over stdin/stdout. In addition, nothing prevents from setting Python 2 on one instance of VS Code and Python 3 on another and LS is not designed to handle multiple pythons in the same process. Other LS (C#, C++, ...) operate the same way.
