### ISSUE TITLE
Some class fields not autocompleting

### ISSUE THREAD

**Issue by malmaud** [Microsoft/python-language-server#520]
Note how `b` appears as an autocomplete suggestion but not `a`:

<img width="829" alt="screen shot 2019-01-04 at 4 25 01 pm" src="https://user-images.githubusercontent.com/987837/50711858-7d22e880-103d-11e9-8020-17071cb6c37f.png">

**Comment by MikhailArkhipov** [comment]
With https://github.com/Microsoft/python-language-server/pull/546

![image](https://user-images.githubusercontent.com/12820357/52459679-721b1680-2b1b-11e9-99b7-3487cedc168f.png)
