### ISSUE TITLE
No auto completion for asyncio.get_event_loop()

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/python-language-server#531]
LS Version - 0.1.75
Python Code:
```python
import asyncio
loop = asyncio.get_event_loop()
loop.<no completion>
```

**Comment by MikhailArkhipov** [comment]
For some reason stub was not found in typeshed so this reproes in the new LS as well.

**Comment by MikhailArkhipov** [comment]
![image](https://user-images.githubusercontent.com/12820357/51961324-36909600-2411-11e9-9b32-8166228f0482.png)
