### ISSUE TITLE
Additional typing specialization

### ISSUE THREAD

**Issue by MikhailArkhipov** [microsoft/python-language-server#535]
P2 level - Callable, Generator, IO, etc.

**Comment by jakebailey** [comment]
We may want to consider throwing in some of these as plain objects in the meantime, just to have them listed in the completion (#1607).

**Comment by jakebailey** [comment]
FWIW the new LS we released today has full typing support: https://devblogs.microsoft.com/python/announcing-pylance-fast-feature-rich-language-support-for-python-in-visual-studio-code/

**Comment by HuskyNator** [comment]
This does not work for `Union[List[type], type, None]`, it just assumes it's `list[type]`?

**Comment by jakebailey** [comment]
This project is no longer actively maintained; consider trying Pylance, which has full typing support.

**Comment by judej** [comment]
Thank you for the report. This project is no longer active. If you are using the Python language server in VSCode, the language server you are using is Pylance and please the http://github.com/microsoft/pylance-release to report issues. 

If you are using Visual Studio, then, please use http://github.com/microsoft/PTVS to report issues.

thank you
