### ISSUE TITLE
Duplicate symbols when using list comprehension or isinstance method

### ISSUE THREAD

**Issue by d3r3kk** [Microsoft/python-language-server#539]
@jahan01 commented on [Tue Dec 25 2018](https://github.com/Microsoft/vscode-python/issues/3804)

When using list comprehension in a method, variables assigned inside the comprehension is listed twice in the symbol list / outline view.

Same happens when `isinstance` method is used inside a method. Not sure if it is related to same issue as above because it causes all the symbols inside a function scope to be duplicated.

Sample Code:
```python
class Test:
    
    def method(self, arg1, arg2):
        var1 = {}
        var2 = [_value for _key, _value in arg1.items()]
    
    def method2(self, param1, param2):
        test1 = {}
        test2 = []
        if isinstance(test, dict):
            test3 = 1
```

**Note:** I have disables jedi, and this happens in microsoft language server. Cannot use jedi right now because, jedi doesnt detect functions with return type annotation specified.

## Environment data

- VS Code version: 1.30
- Extension version (available under the Extensions sidebar): 2018.12.1
- OS and version: OSX 10.14.1
- Python version (& distribution if applicable, e.g. Anaconda): 3.6 (Conda)
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Conda

## Expected behaviour

No duplicate symbols

![image](https://user-images.githubusercontent.com/566264/50424462-31cf4400-089f-11e9-8bfa-d1beb322a86f.png)

## Actual behaviour

![image](https://user-images.githubusercontent.com/566264/50424470-575c4d80-089f-11e9-97a0-b84a605e2582.png)

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
tarting Microsoft Python language server.
##########Linting Output - mypy##########
##########Linting Output - pylint##########
************* Module test_symbols
Microsoft Python Language Server version 0.1.72.0
Initializing for /Users/me/anaconda3/envs/venv/bin/python
```   

---

@d3r3kk commented on [Thu Jan 17 2019](https://github.com/Microsoft/vscode-python/issues/3804#issuecomment-455315553)

Thanks for the report @jahan01, I can reproduce this issue on the latest version of our extension + language server given the information you have provided.

## Reproduced in latest insiders against extension version 2018.12.1:

![3804_duplicate_outline_symbols](https://user-images.githubusercontent.com/11466735/51345890-09c3a280-1a51-11e9-912b-e2e04c6368d6.gif)

## Sample workspace:
*Run `conda create -n 3804_dup_sym` to get a conda environment setup beforehand.*

[3804_duplicate_symbols.zip](https://github.com/Microsoft/vscode-python/files/2770413/3804_duplicate_symbols.zip)

**Comment by jakebailey** [comment]
#521 changed the way we discover/display symbols. 0.1.77.0 shows the example code as:

![image](https://user-images.githubusercontent.com/5341706/51346056-7fc80980-1a51-11e9-814b-dfa6fba502fb.png)

Closing this as fixed. I believe insiders edition should download 0.1.77.0 and have this change (at whatever interval the extension checks for updates), as I've already pushed it to the beta channel.
