### ISSUE TITLE
Automatic docstring-template generation

### ISSUE THREAD

**Issue by astier** [Microsoft/python-language-server#542]
When I type in pycharm under a function `"""<cursor>` it first autocompletes it to `"""<cursor>"""` and when I then press enter it automatically generates a docstring-template.
![pycharm_docstring](https://user-images.githubusercontent.com/36510152/51418731-72ac3700-1b85-11e9-991c-357fa5c6f2f1.png)
It would be nice to have such a feature for vscode.

**Comment by astier** [comment]
Would this be possible or should it be handled by a plugin?

**Comment by jakebailey** [comment]
It could be doable in the language server (we have completions for things other than those which end with `.`), but keep in mind that there are many different ways people like to write these comments (Sphinx style, Numpy style, Google style, Javadoc style), so the choice of which to use will end up needing to be plumbed through to the editor settings. We're currently prioritizing the analysis, so this probably wouldn't happen immediately.

I believe that there is a VS Code extension which does what you're looking for already, so perhaps that'd be an option for now.

**Comment by astier** [comment]
Then give this issue a feature-tag if there is chance that this might be implemented in the future otherwise close it.

**Comment by MikhailArkhipov** [comment]
Might be different kind of snippets. We triage at the end of sprints, ~ every 2 weeks. This features exists in multiple products so we unlikely to close this, but you may also consider creating your own snippets, see https://code.visualstudio.com/docs/editor/userdefinedsnippets
