### ISSUE TITLE
Code Completion not working at all with Language Server, Jedi works

### ISSUE THREAD

**Issue by Luux** [Microsoft/python-language-server#547]
With the Python Language Server enabled, the code completion for python doesn't work at all for me:

![image](https://user-images.githubusercontent.com/15156652/51595349-ca84ce00-1ef6-11e9-8e51-950f400d3327.png)
![image](https://user-images.githubusercontent.com/15156652/51596375-1f294880-1ef9-11e9-8133-3444d269c617.png)

When using Jedi instead, it works:
![image](https://user-images.githubusercontent.com/15156652/51596461-54359b00-1ef9-11e9-921c-d49d438a861d.png)
![image](https://user-images.githubusercontent.com/15156652/51596486-61eb2080-1ef9-11e9-8f72-8b2426413e07.png)

Any idea what causes this?

**Comment by jakebailey** [comment]
Can you show what's in your Python output panel? I can't seem to reproduce this.

![image](https://user-images.githubusercontent.com/5341706/51624370-87732c80-1eef-11e9-8b24-bac5eb216293.png)

**Comment by Luux** [comment]
Ok, my bad. I missed that the extension needs to download the language server itself, so it failed because I forgot to set the proxy settings for us at work, so it failed to download. After setting them, it worked.
