### ISSUE TITLE
LS: Extremely high RAM usage (Previous threads no help)

### ISSUE THREAD

**Issue by Jirubizu** [Microsoft/python-language-server#554]
Hello, I have been looking through a bunch of threads about the language server reloading all modules and not actually completing causing RAM overload and my whole machine just takes the shits. It started to only happen recently about a 4 days ago and I cant seem to find a fix. This is my last resort as I didnt want to start another thread about an old issue

**Comment by Jirubizu** [comment]
![image](https://user-images.githubusercontent.com/37895773/51778642-ca552000-20fa-11e9-9d66-5662db485668.png)
Thats the image which shows what the server does on repeat

**Comment by Jirubizu** [comment]
Wish some of the Devs could comment :/

**Comment by jakebailey** [comment]
See: https://github.com/Microsoft/python-language-server/issues/479#issuecomment-453196291

We're working on a restructuring which changes the properties of the language server significantly.

This issue does seem similar to #109, however.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/python-language-server/pull/546 eliminates this code. Closing pending new engine release. The release schedule can be observed in Zenhub extension to Chrome. Thanks.

**Comment by jakebailey** [comment]
0.2.16 is now available on beta channel. You can set this in your VS Code `settings.json` to get it:

```
"python.analysis.downloadChannel": "beta"
```
