### ISSUE TITLE
unresolved import 'json'

### ISSUE THREAD

**Issue by hujianxin** [Microsoft/python-language-server#557]
Hi,

I use mspls in sublime-text-3, and config like blew:
```
		"mspyls":
		{
			"command":
			[
				"dotnet",
				"exec",
				"~/dotfiles/python-language-server/output/bin/Release/Microsoft.Python.LanguageServer.dll"
			],
			"enabled": true,
			"initializationOptions":
			{
				"interpreter":
				{
					"properties":
					{
						"InterpreterPath": "~/.pyenv/shims/python",
						"UseDefaultDatabase": true,
						"Version": "3.7"
					}
				}
			},
			"languageId": "python",
			"scopes":
			[
				"source.python"
			],
			"syntaxes":
			[
				"Packages/Python/Python.sublime-syntax"
			]
		}
```

When I set `InterpreterPath` to a value contains `~` like `"~/.pyenv/shims/python"`, LSP will always complain messages like `unresolved import os`

Is it becase mslsp does not support `~` path?

Thanks

**Comment by jakebailey** [comment]
`~` is expanded by the shell before being passed to another program. You should try an absolute path.

**Comment by hujianxin** [comment]
@jakebailey Thanks for your explanation。

In some cases，configuration will be shared between some computers, an absolute path may cause inconvenience。Is there some method to solve this? Thanks

**Comment by hujianxin** [comment]
Maybe environment variables?

**Comment by jakebailey** [comment]
This option is something we've defined, so theoretically we could expand `~`. This message is typically generated by the editor (so it can switch between interpreters, send user settings as they change, etc), so we hadn't considered it.

One thing you could try for now is to have the python executable you want in your `PATH`, then specify `"python"` as the interpreter. You may even be able to start the editor with `pipenv shell`.

**Comment by hujianxin** [comment]
@jakebailey I understand your meaning, thanks
