### ISSUE TITLE
Imported complex types resolve to unresolved symbols

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/python-language-server#559]
@patrys commented on [Fri Jan 25 2019](https://github.com/Microsoft/vscode-python/issues/4149)

## Environment data

- VS Code version: 1.31.0-insider
- Extension version (available under the Extensions sidebar): 2018.12.1 (language server 0.1.78)
- OS and version: macOS 10.14.2
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.2 from Homebrew
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv
- Relevant/affected Python packages and their versions: N/A

## Expected behaviour

Importing a complex type like `MyType = Callable[Foo, Bar]` works.

## Actual behaviour

Language server reports an error when the type is used: `'Foo' used before definition`.

## Steps to reproduce:

```python
# foo.py
from typing import AsyncIterator, Callable

Foo = Callable[..., AsyncIterator]
```

```python
# bar.py
from .foo import Foo

x: Foo
```

You should get an error reported for the word `Foo` in `bar.py`.

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
Microsoft Python Language Server version 0.1.78.0
Initializing for [redacted]
```   

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
N/A
```

**Comment by jakebailey** [comment]
I believe this is a deficiency in the old analyzer, which I don't believe supports indirect imports of things from `typing`. The new analyzer should handle this better.

**Comment by MikhailArkhipov** [comment]
Most popular types from typing are now specialized. Additional types will come as part of https://github.com/Microsoft/python-language-server/issues/535 eventually.

**Comment by MikhailArkhipov** [comment]
![image](https://user-images.githubusercontent.com/12820357/53678622-aabf9300-3c76-11e9-8b40-c335db6e8066.png)
