### ISSUE TITLE
Code block after return does not move cursor one level back

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/python-language-server#561]
@Khalilsqu commented on [Tue Dec 11 2018](https://github.com/Microsoft/vscode-python/issues/3646)

As far as I know, all statements after return statment are skipped. Wouldn't it be normal for the cursor to move one level back after the return statement in the code block?

Here is the behaviour in vscode
![vscode2](https://user-images.githubusercontent.com/22060413/49840716-86a59180-fdac-11e8-8fbc-d888edf31a22.gif)

Here is the behaviur in Spyder, or even Pycharm
![spyder2](https://user-images.githubusercontent.com/22060413/49840756-accb3180-fdac-11e8-94a0-3a7e8aa63859.gif)

---

@d3r3kk commented on [Mon Dec 17 2018](https://github.com/Microsoft/vscode-python/issues/3646#issuecomment-448017348)

Do we want to enhance  our formatting to match the above issue (I've verified that this happens on Win10). We can probably add it to the enhancement we nabbed a few weeks ago to do with `if/else`.

---

@Khalilsqu commented on [Tue Dec 18 2018](https://github.com/Microsoft/vscode-python/issues/3646#issuecomment-448269879)

I am using windows 10 64-bit

**Comment by jakebailey** [comment]
I forgot to close this after following up; IIRC this is an on-enter problem that will be solved another way than trying to hack the LS to do this with the on-type formatting or other.
