### ISSUE TITLE
IntelliSense/completions not updating after installing package into current virtual environment

### ISSUE THREAD

**Issue by qubitron** [microsoft/python-language-server#562]
Using Microsoft Python Language Server version 0.1.78.0 with 2019.1.0 of the extension, on Windows 10.

Actual:
- Have virtual environment without requests installed
- Type `import requests`, see warning that module is not found (correct)
- Open terminal, `pip install requests` into virtual environment
- Go back to editor and keep typing, module is still not found
- Reload VS Code, intellisense for requests starts working

Expected: after installing requests, the language server picks up completions for newly installed packages without having to restart VS Code.

I believe this is a regression, as this used to work.

**Comment by DonJayamanne** [comment]
Oh, I thought it never did work, as I've been reloading VSC.

**Comment by jakebailey** [comment]
See also Microsoft/PTVS#5026. I think this is a consequence of the module resolution stuff where we don't re-analyze if the packages change.

**Comment by MikhailArkhipov** [comment]
With #611 

![image](https://user-images.githubusercontent.com/12820357/53665635-dd3ea100-3c20-11e9-93c8-1b16cafd7737.png)

![image](https://user-images.githubusercontent.com/12820357/53665684-f9dad900-3c20-11e9-9d03-84fec071489d.png)

**Comment by qubitron** [comment]
This doesn't appear to be working

**Comment by MikhailArkhipov** [comment]
#1076, #1213

**Comment by Hubro** [comment]
This is an *extreme* hassle. There's no way to reload the language server without reloading the entire window, which terminates all processes running in the terminal windows.

**Comment by jakebailey** [comment]
I'm currently working on fixing the file watcher to detect package installs (see those linked issues above), but as a workaround you can also kill the language server process directly. That's obviously not perfect (and after the 5th restart, the VS Code language server client will stop restarting things), but would allow you to not kill your terminal windows.

**Comment by Hubro** [comment]
This still happens :frowning_face: 

After installing package:

![image](https://user-images.githubusercontent.com/597206/75093573-2d75e800-5583-11ea-85f9-b87d547626b8.png)

After reloading the window:

![image](https://user-images.githubusercontent.com/597206/75093576-32d33280-5583-11ea-82b2-93b4f20b5d66.png)

My VSCode version:

![image](https://user-images.githubusercontent.com/597206/75093577-3cf53100-5583-11ea-90e0-06176809595e.png)

Python extension:

![image](https://user-images.githubusercontent.com/597206/75093599-804f9f80-5583-11ea-8c83-b5ba94d40e6a.png)

**Comment by jakebailey** [comment]
We've made this opt-in, as it was causing more issues than it was solving (#1841). If you'd like to restore this, you can see: https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#completions-do-not-update-andor-import-is-still-being-reported-as-unresolved-after-pip-install

**Comment by Hubro** [comment]
> We've made this opt-in, as it was causing more issues than it was solving (#1841). If you'd like to restore this, you can see: https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#completions-do-not-update-andor-import-is-still-being-reported-as-unresolved-after-pip-install

Well it wouldn't be a big deal if I didn't have to reload the entire window. Why isn't there a command to rescan libraries? Or a command to restart the language server?

**Comment by jakebailey** [comment]
A command to restart the LS without a reload would be microsoft/vscode-python#3073.

Feasibly without this directly supported, you can kill the LS process itself and it will be restarted up to 5 times, or you can select a different interpreter and switch back, but these are workarounds.

Again, you can re-enable that option and see if it's stable for you.
