### ISSUE TITLE
file.write is not in the completion list

### ISSUE THREAD

**Issue by qubitron** [Microsoft/python-language-server#563]
A case to test with the new analysis code:
![image](https://user-images.githubusercontent.com/17804393/51939220-c7408500-23c3-11e9-99c5-52e6cd82f948.png)

Jedi:
![image](https://user-images.githubusercontent.com/17804393/51939830-4f735a00-23c5-11e9-9fb0-8e8d036cc0a4.png)

**Comment by MikhailArkhipov** [comment]
![image](https://user-images.githubusercontent.com/12820357/52321792-597bf680-298b-11e9-9907-5dfa34a17952.png)
