### ISSUE TITLE
No completions for requests.Response type

### ISSUE THREAD

**Issue by qubitron** [Microsoft/python-language-server#564]
A case to test with the new analysis code:
![image](https://user-images.githubusercontent.com/17804393/51939305-ffe05e80-23c3-11e9-8288-c37695d25070.png)

requests.get shows it returns a requests.Response type:
![image](https://user-images.githubusercontent.com/17804393/51939350-1a1a3c80-23c4-11e9-9ad1-2b4738b4d1c5.png)

Jedi:
![image](https://user-images.githubusercontent.com/17804393/51939722-04f1dd80-23c5-11e9-81e1-51bd24831da1.png)

**Comment by jakebailey** [comment]
With #546:

![image](https://user-images.githubusercontent.com/5341706/52155595-6a013980-2638-11e9-81bb-22dc8b7e867c.png)

**Comment by qubitron** [comment]
Nice! We are picking up more completions, and have different icons for properties vs. functions (content is a property, close is a function). 

Curious why cookies/elapsed/encoding show as "ABC" vs. the orange icon shown in Jedi. I'm not sure what the icons mean exactly but we might need to double check we're using the right ones in the right places.

**Comment by jakebailey** [comment]
It's just a completion item kind choice which we'd change to match the old LS. In typeshed:

```python
class Response: # truncated
    encoding = ...  # type: str
    cookies = ...  # type: RequestsCookieJar
    elapsed = ...  # type: datetime.timedelta
    def iter_content(self, chunk_size: Optional[int] = ...,
                     decode_unicode: bool = ...) -> Iterator[Any]: ...
    def iter_lines(self, chunk_size=..., decode_unicode=..., delimiter=...): ...
    @property
    def content(self) -> bytes: ...
    @property
    def text(self) -> str: ...
```
The wrench is the VSC icon for property.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/python-language-server/issues/7 currently not GA but can be.

**Comment by qubitron** [comment]
We may not need to block GA on the type hints, but should probably add support for them soon after.
