### ISSUE TITLE
Handle simple if statements when processing stubs

### ISSUE THREAD

**Issue by jakebailey** [Microsoft/python-language-server#569]
Typeshed's stubs contain many if statements to declare things based on the Python version and the system platform. In order to have the right type info, when analyzing stubs we should handle those checks. They're not complicated, and are usually like:

```python
if sys.version_info >= (3, 6): ...
if sys.platform == 'win32': ...
if sys.version_info >= (3, 3) and sys.platform != 'win32': ...
```

See:
- https://github.com/python/typeshed/blob/master/stdlib/3/os/__init__.pyi
- https://github.com/python/typeshed/blob/master/stdlib/3/os/path.pyi

Seems like it's all `sys.version_info` and `sys.platform`.

**Comment by MikhailArkhipov** [comment]
Actually we do, in `ConditionalHandler` but only `sys.version_info`

**Comment by MikhailArkhipov** [comment]
Has to be done for https://github.com/Microsoft/python-language-server/pull/623
