### ISSUE TITLE
Completion shows partial text and old text after rename

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/python-language-server#570]
In the case below the valid values are '_path_mappings' and '_path_mappings_applied'. I had typed, '_path_mappings_set' and then changed it to '_path_mappings_applied'.
![image](https://user-images.githubusercontent.com/3840081/52086126-f2111180-255a-11e9-94d6-7b8ba3638713.png)

**Comment by MikhailArkhipov** [comment]
New LS should not have that as it is not using cached data.

**Comment by jakebailey** [comment]
I believe this is fixed; with the new analysis this information shouldn't persist between different instances of a document's analysis.
