### ISSUE TITLE
Some objects aren't suggesting their auto-complete 

### ISSUE THREAD

**Issue by esn89** [Microsoft/python-language-server#587]
Quick question,

I am using MPLS now and I think I got it working. In my autocomplete, I see entries that end in [LS]. This means that the language server is working, right?

Second, I have seen a strange behavior. In my code when I make a list:

`list2 = [1, 2, 3]`
and I type:
`list2.`, I expect an autocomplete list to pop up showing some operations I can do such as: append(), delete(),
https://i.imgur.com/ILdOJwE.png

However, when I do `import math`

and I type:
`math.`, I _DO_ see operations like cosx(), tan(), cos() all ending with [LS]:
https://i.imgur.com/swPqGO4.png

Any ideas why this is?

**Comment by jakebailey** [comment]
Which editor is that? Emacs or vim? We don't specifically test with things other that VS Code (or VS), and any instructions to run the language server there are unofficial. There may be some incorrect configuration being given to the language server at startup which is preventing builtin scraping (see #469), and you may have built from `master` instead of `release` (the former is a WIP rework of the language server which is not yet complete).

**Comment by esn89** [comment]
That is neovim, yup.  Darn, so I'm sorta on my own for that eh?

**Comment by esn89** [comment]
So I should build with release and test too?

**Comment by jakebailey** [comment]
You should probably use `release`, though we'd probably appreciate testing of `master`. There are a few important pieces not yet reimplemented, but coming soon.

I'm not sure how LSP works in neovim, but I know there are a couple emacs repos which seem to provide the correct options (though also auto-build from `master`). You may want to verify that the correct options are being sent. You can compare to this file: https://github.com/Microsoft/vscode-python/blob/master/src/client/activation/languageServer/analysisOptions.ts

The defaults may improve in the future (that's what #469 is about), but right now we're working on improving the analysis itself.

**Comment by esn89** [comment]
Thanks.

For the meantime while I test master/release are there are args I can pass to the exec command to have the server generate logs?

**Comment by jakebailey** [comment]
The language server does not accept any arguments; all configuration is passed over the LSP.

**Comment by esn89** [comment]
Really?

Not even something like:   dotnet exec Microsoft.LanguageServer.dll --version?  etc?

**Comment by jakebailey** [comment]
No, it does not currently do any argument parsing. https://github.com/Microsoft/python-language-server/blob/master/src/LanguageServer/Impl/Program.cs

**Comment by esn89** [comment]
Thank you for letting me know
