### ISSUE TITLE
Language Server: Is there any status of its progress?

### ISSUE THREAD

**Issue by d3r3kk** [Microsoft/python-language-server#588]
@derekwallace commented on [Thu Feb 07 2019](https://github.com/Microsoft/vscode-python/issues/4314)

Windows 10
Jan 2019 update.

I have a new PC
Installed latest vscode + Python 3.7.2 (python.org) + Python extension.
Disabled Jedi.

I have a workspace (large) on a slow network disk.

WHen i open my workspace and then open a .py file , i see on the status bar some message that "initalizing python/language server" its present for a few seconds at max so i dont have the exact message.
In the Output window for Python i can see this
Starting Microsoft Python language server.
Microsoft Python Language Server version 0.1.78.0
Initializing for C:\Users\derekw\AppData\Local\Programs\Python\Python37-32\python.exe

My issue is that there are no symbols  for my current file in Outline.
"Loading document symbols ...."
They will probably appear in 30 mins after the langague server has analyzed all my files.
(and yes i have ignored lots of files in my workspace to try and minimize)

During this time intellisense is not working
Snippets dont work...

It largely makes all this great capability useless when you open the editor ...
Yes if i leave it open eventually i get some features ...

Is there anywhere that VSCOde will show some status of what the language server is doing?
Its frustrating not knowing what it is doing. I dont know if its working, its crashed, its X % complete .....

In process explorer i can see the langauge server running.

![image](https://user-images.githubusercontent.com/5574230/52429717-8996d700-2afc-11e9-8d0c-2c5b0ce625b2.png)

---

@derekwallace commented on [Thu Feb 07 2019](https://github.com/Microsoft/vscode-python/issues/4314#issuecomment-461523601)

Why would snippets be "blocked" if the langauge server is busy?
Why would  python language intellisense i.e. typing python syntax , be blocked if the language server is busy?
I can understnad that functionality wrt symbols in the file might not be available.

---

@d3r3kk commented on [Thu Feb 07 2019](https://github.com/Microsoft/vscode-python/issues/4314#issuecomment-461570573)

Performance of LS issue

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/python-language-server/pull/546

We are doing major rework of the server. The analysis is different and runs a lot faster. If you install Zenhub extension to Chrome, you can check our progress and projected availability dates, such as Release Report.

https://github.com/Microsoft/python-language-server/issues/588#workspaces/python-language-server-5b897936af3c0a2186966c0f/reports

Thanks.
