### ISSUE TITLE
Support completion in { } in f-strings

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/python-language-server#6]
https://github.com/Microsoft/PTVS/issues/4635
https://github.com/Microsoft/vscode-python/issues/2379

https://user-images.githubusercontent.com/12820357/44060308-1f9d37ce-9f09-11e8-9f0a-62d4a4cf26b8.png

**Comment by MikhailArkhipov** [comment]
Cost needs clarification. May need to be converted to an epic.

**Comment by Astrantia** [comment]
@Mikhail-Pranovich @jakebailey I opened [this issue](https://github.com/Microsoft/vscode-python/issues/2379) more than 2 months ago. Is it not prioritized because of some reason?

**Comment by jakebailey** [comment]
This is still a planned item, just not at this exact moment while we work on the quality of the existing functionality. You can see what we're currently working on by looking at the current milestone.

**Comment by MikhailArkhipov** [comment]
@Astrantia - this is not non-trivial amount of work. If you install ZenHub extension you will see our prioritized backlog and milestones. As @jakebailey mentioned, we are focusing on stability, performance and fundamental scenarios at this time.
