### ISSUE TITLE
Named parameters with types have types overridden by default value in hover

### ISSUE THREAD

**Issue by jakebailey** [Microsoft/python-language-server#603]
```python
from typing import Optional

def opt_none(x: Optional[int] = None):
    return x
```

![image](https://user-images.githubusercontent.com/5341706/52743930-065c0200-2f90-11e9-956b-45c47621da21.png)

This doesn't impact the actual analysis, though.

![image](https://user-images.githubusercontent.com/5341706/52743965-268bc100-2f90-11e9-9dea-a7f3c17e5c9f.png)

Replaces #377.

**Comment by MikhailArkhipov** [comment]
![image](https://user-images.githubusercontent.com/12820357/53603255-c424ea00-3b65-11e9-915c-70c93f2d7349.png)

Fixed in https://github.com/Microsoft/python-language-server/pull/680

**Comment by jakebailey** [comment]
I'm not sure if that's really the right thing to do; shouldn't it remain `Optional[int]`? Or are we intending to drop Optional in places?
