### ISSUE TITLE
Treat default parameter values of None as being unspecified/Optional

### ISSUE THREAD

**Issue by jakebailey** [Microsoft/python-language-server#604]
Take:

```python
def f(x=None):
    return x

f("4")
```

We currently see `None`, then say that `x` is of type `NoneType`, when the user probably actually meant `Optional[_T]` or similar. It'd be better to treat the special case of `None` as though there were no default specified, for example like:

```python
def g(x):
    return x

g("4")
```

![image](https://user-images.githubusercontent.com/5341706/52744532-cd249180-2f91-11e9-9a7d-85c319275bbc.png)

**Comment by MikhailArkhipov** [comment]
Most probably this issue also manifests in #462 since `params` there is declared as 
```python
headers: typing.Optional[typing.Mapping[str, str]]=None
```
and ends up being None in the class.
