### ISSUE TITLE
Improve detection of symbol types for imports

### ISSUE THREAD

**Issue by jakebailey** [microsoft/python-language-server#612]
The symbol index walker doesn't distinguish imports of modules from imports of classes, variables, functions, etc. This is information that would be good to have but would require one of the following (or similar):

- Provide indexed info from the analyzer for analyzed files.
  - Wouldn't be possible as-is, since LSP provides no method to update symbol information; it's request only.
- Add more to the walker to perform imports and check referenced files for their symbols.
  - Seems complicated, would need to build a dependency graph and order the analysis; no longer a pure function.

Alternatively, we could just not treat imported things as symbols at all; this would match the TypeScript outline, which does not include imports.

**Comment by zooba** [comment]
Or just don't return imports in the outline at all. They don't really help navigate the file, which is the point (perhaps a false symbol just labelled "Imports"?)

**Comment by jakebailey** [comment]
Using a fake symbol to collect them is a great idea.
