### ISSUE TITLE
Racy completion shows completions from the wrong scope

### ISSUE THREAD

**Issue by jakebailey** [Microsoft/python-language-server#636]
In this specific example below, delete and replace the `.` at the end after `self` repeatedly (slowly, or quickly), and you'll see a different completion. One comes from the correct scope (shows `v`), but otherwise it gets evaluated in the global scope. It seems to be linked to when the red parse squiggle shows up.

![image](https://user-images.githubusercontent.com/5341706/53111578-280a3b80-34f2-11e9-8e6c-46fe9409e252.png)

The whole code below is required, removing some of this code seems to make the analysis fast enough to not show the issue, which makes me think it's a race.

```python
from typing import TypeVar, Generic

_T = TypeVar("_T")

class Box(Generic[_T]):
    def __init__(self, v: _T):
        self.v = v
    
    def get(self) -> _T:
        return self.v


boxedint = Box(1234)
intval = boxedint.get()

boxedstr = Box("foo")
strval = boxedstr.get()


Box(Box(Box(123))).get().get().get().bit_length()

class UntypedBox():
    def __init__(self, v):
        self.v = v

    def get(self):
        return self.

```

**Comment by MikhailArkhipov** [comment]
Works for me, either #655 or #665 fixed it.
