### ISSUE TITLE
Minor visual defect, if the docstring is present function signatures are rendered in monospace

### ISSUE THREAD

**Issue by d3r3kk** [Microsoft/python-language-server#638]
@Vlad-Shcherbina commented on [Wed Feb 06 2019](https://github.com/Microsoft/vscode-python/issues/4301)

There is a really minor visual defect, though: if the docstring is present, function signatures are rendered in monospace with syntax highlighting, but if it's absent, they appear in proportional font and with no syntax highlighting.
![python_language_server_actual](https://user-images.githubusercontent.com/302938/52365215-0f147b80-2a58-11e9-92d4-8b74a1a0c46f.png)

**Comment by jakebailey** [comment]
This works as expected in the new LS:

![image](https://user-images.githubusercontent.com/5341706/53116569-debfe900-34fd-11e9-9159-428cc93df1c6.png)

![image](https://user-images.githubusercontent.com/5341706/53116594-eaabab00-34fd-11e9-90da-cbd1a2413f29.png)

![image](https://user-images.githubusercontent.com/5341706/53116611-eda69b80-34fd-11e9-8d0b-21b107f0af53.png)

![image](https://user-images.githubusercontent.com/5341706/53116624-f7300380-34fd-11e9-8c1c-51aa4ce687a2.png)
