### ISSUE TITLE
Autocomplete doesn't work on type-hinted module classes as function parameters

### ISSUE THREAD

**Issue by d3r3kk** [Microsoft/python-language-server#640]
@M-Shadow commented on [Mon Feb 11 2019](https://github.com/Microsoft/vscode-python/issues/4357)

## Environment data

- VS Code version: 1.31.0
- Extension version (available under the Extensions sidebar): 2019.1.0
- OS and version: Windows_NT x64 10.0.17134
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.2
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Relevant/affected Python packages and their versions: enum, and any other module that you can import a class from such as json etc.

## Actual behaviour

VSCode doesn't auto-complete the type-hinted function paramater, when you type hint it as module.class such as the enum.Enum as shown below. Pressing Ctrl+Space doesn't add any useful auto-completions:

![problem](https://user-images.githubusercontent.com/20525615/52618551-d46f7080-2ea7-11e9-9de5-1caa553ff398.gif)

## Expected behaviour

I've found that the issue resolves when you import the class from the module directly, although I would wish that the issue didn't occur in the first place, as I tend to use the module directly instead of importing every single class from it. But this is the expected behaviour for the case above:

![solution](https://user-images.githubusercontent.com/20525615/52618720-40ea6f80-2ea8-11e9-9588-2fdd93445d21.gif)

## Steps to reproduce:
1. Import any module that contains a class in it, such as enum.
2. Create a function that has a single type-hinted parameter, but it has to be with the module name, such as enum.Enum.
3. Try to access the variable within the function, and use one of its attributes/functions and wait for auto-complete, it shouldn't work.

```python
import enum

def foo(e: enum.Enum):
    e. # wait here for auto-complete
```

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
None
```   

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
None
```

**Edit:** Apparently this is with Jedi disabled, although when I have it enabled IntelliCode Python won't work. If I enable Jedi the issue resolves itself. 

---

@d3r3kk commented on [Wed Feb 20 2019](https://github.com/Microsoft/vscode-python/issues/4357#issuecomment-465774145)

Verified the issue does happen as stated as of Microsoft Python Language Server 0.1.78.0

**Comment by asavaritayal** [comment]
+1 ; this seems to be relevant to https://github.com/Microsoft/python-language-server/issues/670

**Comment by MikhailArkhipov** [comment]
New LS: 
![image](https://user-images.githubusercontent.com/12820357/53511324-0b7f7d80-3a75-11e9-9bbc-c7c4dea51de9.png)
