### ISSUE TITLE
Missing numpy and tensorflow completion, members not showing up

### ISSUE THREAD

**Issue by jakebailey** [Microsoft/python-language-server#642]
numpy and tensorflow.nn are missing completion.

```python
import numpy as np
np.
```

Nothing shows up after `np.` except some oddball stuff.

Doing this:

```python
import tensorflow
tensorflow.nn
```

`nn` has no completion, and `tensorflow.nn` itself doesn't say that `nn` exists at all.

**Comment by MikhailArkhipov** [comment]
This is about submodules in folders you are working on

**Comment by MikhailArkhipov** [comment]
Related: #490 

```python
from setuptools. # misses `archive*`
```
![image](https://user-images.githubusercontent.com/12820357/53657221-71e9d480-3c0a-11e9-8a0a-084cb384b2b9.png)

**Comment by jakebailey** [comment]
So in looking at #690, I realized that I hadn't checked `__all__` for numpy, and behold:

https://github.com/numpy/numpy/blob/15b092f5541e80d7c3d0108957406c6f8686aba0/numpy/__init__.py#L169

```python
    __all__.extend(['__version__', 'show_config'])
    __all__.extend(core.__all__)
    __all__.extend(_mat.__all__)
    __all__.extend(lib.__all__)
    __all__.extend(['linalg', 'fft', 'random', 'ctypeslib', 'ma'])
```

Which explains why we aren't getting numpy completion anymore; we have the `__all__` filtering.

**Comment by jakebailey** [comment]
Commenting out all of the code in `PythonModule.GetMemberNames` which filters:

![image](https://user-images.githubusercontent.com/5341706/53843552-aab1e280-3f57-11e9-86b5-0e903c6bee0c.png)

It's really show to show up, but it's there. Maybe we need to drop the filters for now until we can better handle `__all__`. The old LS worked because it didn't even do anything.

**Comment by MikhailArkhipov** [comment]
If we drop all filters then all the `typing` and others imported will show up in the completion. But it may be smaller price to pay.

**Comment by jakebailey** [comment]
The above is just:

```csharp
            // Try __all__ since it contains exported members
            var all = Analysis.GlobalScope.Variables["__all__"];
            // if (all?.Value is IPythonCollection collection) {
            //     return collection.Contents
            //         .OfType<IPythonConstant>()
            //         .Select(c => c.GetString())
            //         .Where(s => !string.IsNullOrEmpty(s));
            // }

            // __all__ is not declared. Try filtering by origin:
            // drop imported modules and generics.
            return Analysis.GlobalScope.Variables
                .Where(v => !(v.Value?.GetPythonType() is PythonModule)
                            && !(v.Value?.GetPythonType().DeclaringModule is TypingModule && !(this is TypingModule)))
                // .Where(v => v.Value?.MemberType != PythonMemberType.Generic
                //             && !(v.Value?.GetPythonType() is PythonModule)
                //             && !(v.Value?.GetPythonType().DeclaringModule is TypingModule && !(this is TypingModule)))
                .Select(v => v.Name);
```

So theoretically I'm not leaking typing or modules out.

**Comment by MikhailArkhipov** [comment]
OK, sure
