### ISSUE TITLE
Peeking References for a extended class

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/python-language-server#645]
@manutero commented on [Thu Feb 21 2019](https://github.com/Microsoft/vscode-python/issues/4481)

## Environment data

- VS Code version:  1.31.1 (1.31.1)
- Extension version (available under the Extensions sidebar): 1b8e8302e405050205e69b59abb3559592bb9e60
- OS and version: macOS Mojave 10.14.3
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.1 64-bit
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv 
- Relevant/affected Python packages and their versions: 
    - `Python` 2019.1.0 (microsoft)
    - `python-snippets` 0.2.0 (cstrap)

## Expected behaviour

Peeking References for a Python class might show any class extending it. 

```
Class A():

...

Class B(A): # A is referenced here
```

## Actual behaviour

Picking references of a Python class *does not* list any ussage of that class as parent class.

## Steps to reproduce:

___Prerequisites___

In the code base, we have at least two classes, A & B. B extends A.

***

1. Cursor over Python class A
2. Peek references (via command palette or shortcut or right clicking)
3. A ussage from B class is *not* shown

## Logs

Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

None.

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
2console.ts:134 [Extension Host] Python Extension: Cached data exists getEnvironmentVariables, /Users/martero/workspace/tuenti/flow/flow_core/flow_core/tasks/basetask.py
```

## Relevant user config

```
  "python.linting.lintOnSave": true,
  "python.linting.pep8CategorySeverity.E": "Warning",
  "python.linting.pylintEnabled": true,
  "python.venvPath": "~/.virtualenvs",
  // "python.jediEnabled": false, // TRIED BOTH, TRUE & FALSE
```

**Comment by MikhailArkhipov** [comment]
Should be covered in #577

**Comment by MikhailArkhipov** [comment]
#699
