### ISSUE TITLE
Move strings in parser to resources

### ISSUE THREAD

**Issue by MikhailArkhipov** [microsoft/python-language-server#647]
Currently all hardcoded ENU strings

**Comment by jamesralstin** [comment]
Hello @MikhailArkhipov, I am new to Open Source Software Development (currently taking a class on it), I am trying to get involved and make my first contribution, do you think this would be a good first issue for me to, given I am not that familiar with the project? Thank you for any and all advice!

**Comment by jamesralstin** [comment]
Also, I have forked the project and cloned it locally, I think i found the strings referenced in this issue.

I noticed a number of hard coded strings in C# Library Microsoft.Python.Parsing.Parser.cs, is the hope to move these strings to the Resources.resx file in the same project?

**Comment by MikhailArkhipov** [comment]
Sure, take it. Yes, hardcoded string relevant to user should be in Resources. Not all string, just messages and anything that should be translated. Node names, for example, do not need to move, they are for internal use. But syntax error messages - yes.

**Comment by MikhailArkhipov** [comment]
While you are at it, you can also look at #228 at least in the parser. I.e. change
```cs
throw new ArgumentNullException("text");
```
to
```
throw new ArgumentNullException(nameof(text));
```

**Comment by jamesralstin** [comment]
Thanks for the quick response @MikhailArkhipov, I will get right on this!

**Comment by jamesralstin** [comment]
@MikhailArkhipov I have made these changes, pushed them to my branch, and ran the 'Microsoft.Pythong.Parsing.Tests' unit tests, everything passes except for the 'Microsoft.Pythong.Parsing.Tests.ParserTests.Errors' test. I can't for the life of me figure out why the error is returning an empty string when testing this:

The error message is

"Message: Wrong msg for error 38: expected "new ErrorResult("invalid syntax, class decorators require 2.6 or later.", new SourceSpan(95, 1, 95, 6))", got "new ErrorResult("", new SourceSpan(95, 1, 95, 6))""

The error is coming from the "public void Errors()" method in ParserTests.cs, it seems like it has something to do with line 520:

`new ErrorResult("invalid syntax, class decorators require 2.6 or later.", new SourceSpan(93, 1, 93, 6)),`

In the Parser.cs file, I replaced line 1808 with:

`res = ErrorStmt(Resources.ClassDecoratorsRequireTwodotSixErrorMsg, decorators, cls);`

It was:

'res = ErrorStmt("invalid syntax, class decorators require 2.6 or later.", decorators, cls);'

When I comment out line 520 in ParserTest.cs, then line 521 seems to fail with the same error message. So it almost seems like the test is running out of capacity to process these tests(?). Other than this one error, everything else seems to pass just fine.

I appreciate any and all insites you might have into this, these Unit Tests are a little over my head.

**Comment by jamesralstin** [comment]
I should mention, I revert line 1808 in Parser.cs back to its original state and I still get the error. Thanks,

**Comment by jamesralstin** [comment]
@MikhailArkhipov I found the issue after comparing my branch to master, I simply placed the resource reference in the wrong location of the if statement. Reran the unit tests and everything is passing now. I updated my branch with the changes.

**Comment by MikhailArkhipov** [comment]
https://github.com/microsoft/python-language-server/pull/1150
