### ISSUE TITLE
If user continues editing, analysis never completes

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/python-language-server#650]
```python
import tensorflow
tensorflow.
```
keep deleting and re-typing dot. Analysis keeps running and running. The analysis should complete and then start over so we have at least something. At least first time around.

**Comment by MikhailArkhipov** [comment]
#642 related for tensorflow. numpy appears to be a different issue.

**Comment by AlexanderSher** [comment]
Fixed in #655
