### ISSUE TITLE
Server does not propagate Type Aliases properly

### ISSUE THREAD

**Issue by narfanar** [Microsoft/python-language-server#668]
Of the form:

```py
TypeAlias = Union[First, Second]
```

![image](https://user-images.githubusercontent.com/5769148/53484916-9c625300-3a8d-11e9-955f-3993a2b60b8d.png)

**Comment by MikhailArkhipov** [comment]
Is the issue about tooltip? Upcoming LS does this

![image](https://user-images.githubusercontent.com/12820357/53506218-5ba51280-3a6a-11e9-9077-5a86c1922bbd.png)

**Comment by MikhailArkhipov** [comment]
Related #682
