### ISSUE TITLE
Document LS settings and options

### ISSUE THREAD

**Issue by esn89** [Microsoft/python-language-server#678]
Hi all, 

I can't seem to find much documentation on this repo on how to enable diagnostics.  What are the settings/configs we should be sending to the LS?

Things like linting for example, 2 lines between function definitions, unused imports, etc.

**Comment by MikhailArkhipov** [comment]
Will add document when new LS is published

**Comment by esn89** [comment]
Thanks a bunch @MikhailArkhipov , looking forward!

**Comment by esn89** [comment]
Thanks for the PR.  One thing that is still not clear to me is the:
```
Linting can be controlled via the user configuration. In VS Code, this is settings.json, but other clients would send this via workspace/didChangeConfiguration```

If I have a configuration like this for Sublime Text as seen [here](https://github.com/Microsoft/python-language-server/blob/7d0e3eb4752296fea66c92fa2722f77c1c9820ab/Using_in_sublime_text.md#sublime-text-configuration), will I need to make a new json block INSIDE "interpreter:" like:

```
"workspace": {
    "didChangeConfiguration":  stuffhere
    }
```

Furthermore, the link  for "A full list can be seen in the source code" gives a 404.
This one: https://github.com/Microsoft/python-language-server/blob/446cb262eb4250ce53dc21a03e92c7a7febb7f5c/src%5CAnalysis%5CImpl%5CDiagnostics%5CErrorCodes.cs

**Comment by jakebailey** [comment]
That document was contributed; we don't really maintain it. I can only guess as to what the right way to do it is. `workspace/didChangeConfiguration` is a language server protocol method name, it is not a setting. It's a message that gets sent by the client to the server. You'd need to look at how the Sublime plugin allows you to send that (as there must be a way; that's how configuration works in LSP).

That link should have gone here: https://github.com/Microsoft/python-language-server/blob/master/src/Analysis/Ast/Impl/Diagnostics/ErrorCodes.cs

No idea why GitHub escaped the slashes, but I'll try to figure out a way to fix it.
