### ISSUE TITLE
Intellisense - Function arguments bolded in wrong order

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/python-language-server#679]
@JeffreyCA commented on [Fri Feb 08 2019](https://github.com/Microsoft/vscode-python/issues/4331)

## Environment data

- VS Code version: 1.32.0-insider
- Extension version (available under the Extensions sidebar): 2019.1.0
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.8
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv
- Relevant/affected Python packages and their versions: tensorflow 1.12.0

## Expected behaviour
Function arguments should be bolded in listed order

## Actual behaviour
Function arguments are not bolded in order. In addition only a substring of an argument is bolded in some cases.

## Steps to reproduce:
1. Have the following piece of code:

```py
import tensorflow as tf
from tensorflow import keras

model = keras.Sequential([
    tf.layers.Dense(64, activation = tf.nn.relu, input_shape = [ ]),
    tf.layers.Dense(1)
])
optimizer = tf.keras.optimizers.RMSprop(0.001)
```

Then begin typing the following, filling in the arguments:

```py
mode.compile(
```

## Demo

![20190208at1046am](https://user-images.githubusercontent.com/9157833/52499034-581b1b80-2b8f-11e9-9907-b77f9c0b442d.gif)

---

@DonJayamanne commented on [Tue Feb 19 2019](https://github.com/Microsoft/vscode-python/issues/4331#issuecomment-465196426)

Are you using Jedi or language server?
Please check the output of your `Python` output panel and let me know what you get when you have a python file open and the above issue.
Or let me know if you have the following setting enabled in your `local .vscode/settings.json` or `user settings.json`:
```js
"python.jediEnabled": true|false
```

---

@JeffreyCA commented on [Tue Feb 19 2019](https://github.com/Microsoft/vscode-python/issues/4331#issuecomment-465252156)

```
Starting Microsoft Python language server.
Microsoft Python Language Server version 0.1.78.0
Initializing for C:\venv\Scripts\python.exe
##########Linting Output - pylint##########
************* Module tensor
17,25,error,no-member:Module 'matplotlib.cm' has no 'binary' member

------------------------------------------------------------------

Your code has been rated at 9.11/10 (previous run: 9.11/10, +0.00)
```

I tried with `python.jediEnabled: true` and same issue happens.

**Comment by MikhailArkhipov** [comment]
Needs #642

**Comment by MikhailArkhipov** [comment]
We do not actually bold anything, we report active parameter index to VS Code, that's it. Looks like this is VS Code bug: https://github.com/Microsoft/vscode/issues/68824

**Comment by JeffreyCA** [comment]
Yes, I looked into it a bit and have isolated the piece of code that is causing this bug. See https://github.com/Microsoft/vscode/issues/68824#issuecomment-488171473
