### ISSUE TITLE
System.ObjectDisposedException: PriorityProducerConsumer`1 instance is disposed

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/python-language-server#68]
Microsoft/vscode-python#2387

**Comment by Lawouach** [comment]
Hey there,

It's hard to figure out when this was or will be released, would you mind lcarifying how your release process works? :)

Thanks,

**Comment by jakebailey** [comment]
We weren't able to reproduce it, so it wasn't exactly "released". I was under the impression that this only occurred when the server was already closing, but we've seen this exception still happening for a few users so we may need to reopen this.

**Comment by Lawouach** [comment]
Fair enough :)

I certainly have noticed it recently but it would be hard for me to pinpoint what triggered it. If I can, I'll report it here.
