### ISSUE TITLE
Keep getting errors from Output

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/python-language-server#695]
@SeakyLuo commented on [Mon Mar 04 2019](https://github.com/Microsoft/vscode-python/issues/4643)

## Environment data
Version: 1.31.1 (user setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
Python version (& distribution if applicable, e.g. Anaconda): 3.7.2

## Expected behaviour

No weird outputs

## Actual behaviour

![image](https://user-images.githubusercontent.com/25042708/53773558-c8237580-3e9f-11e9-8e65-67340ad00b43.png)

## Steps to reproduce:
I copied and pasted java code to a newly-created python file. And then I kept getting errors from the output. Cleaning output and closing that terminal doesn't help. It pops up again.  After I converted the code into Python and saved the file, I no longer receive that error message.

**Comment by MikhailArkhipov** [comment]
#597
