### ISSUE TITLE
Support PEP comment type hints

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/python-language-server#7]
https://github.com/Microsoft/PTVS/issues/3917

https://www.python.org/dev/peps/pep-0484/
https://www.python.org/dev/peps/pep-0526/

```
PEP_526_style: str = "hello world"
captain: str  # Note: no initial value!
PEP_484_style = SOMETHING # type: str

 
PEP_484_style.
PEP_526_style.upper()
captain.upper()
```

Type declaration is not recognized as string.

![image](https://user-images.githubusercontent.com/12820357/37684756-45ab901a-2c4e-11e8-851a-c36796548b77.png)

Jedi

![image](https://user-images.githubusercontent.com/12820357/37684806-6cf9af4e-2c4e-11e8-927a-99879058cd2f.png)

Related: https://github.com/Microsoft/PTVS/issues/3674

**Comment by technic** [comment]
It doesn't work for python 2.7.

**Comment by MikhailArkhipov** [comment]
What does not work exactly? Could you give sample of the code?

**Comment by technic** [comment]
> 
> 
> What does not work exactly? Could you give sample of the code?

0. Go to vscode settings and disable jedi.
1. Create new folder and open it
2. Use python 3.6 interpreter ("Python 3.6.6" from Anaconda). It works
![image](https://user-images.githubusercontent.com/1092613/57574587-06a75480-743c-11e9-923c-ae1e278b6f8c.png)
3. Use python 2.7 interpreter  ("Python 2.7.16" from Anaconda). It *does not* work, no popup :(
if I do `y = 3` then it deduces type to int and I see the popup completion again

**Comment by makail** [comment]
I can confirm the absence of type hints in the above example.
Trace output doesn't seem helpful, but included for posterity: 
`Analysis of main(User) queued
Analysis version 9 of 1 entries has started.
Analysis of main(User) completed in 0.1192 ms.
Analysis version 9 of 1 entries has been completed in 0.1974 ms.
Completions in file:///<snip>/main.py at (2, 5)
Completions in file:///<snip>/main.py at (2, 6)
Analysis of main(User) queued
Analysis version 10 of 1 entries has started.
Analysis of main(User) completed in 0.1932 ms.
Analysis version 10 of 1 entries has been completed in 0.3502 ms.`

**Comment by MikhailArkhipov** [comment]
Since this issue is closed, I opened https://github.com/microsoft/python-language-server/issues/1073 for you.
