### ISSUE TITLE
Initial import unavailable, opening file makes it available

### ISSUE THREAD

**Issue by MikhailArkhipov** [microsoft/python-language-server#701]
`one.py`:
```python
from two import X
```

`two.py`:
```python
X = 42
def func(): ...
```

1. Open `one.py`
2. Observer `two` is unresolved. *should it be resolved? it is in the same folder.*
3. Open `two.py`
4. Edit `one.py`
5. `two` is now resolved.

`two` should be either available or not available and should not depend on the open state.

**Comment by steveoh** [comment]
I have a similar issue except opening a file does not make it available. 

You can look at my project structure as it is open source. The following are all marked as python(unresolved-import)

https://github.com/agrc/uic-attribute-rules/blob/master/src/ar.py#L11-L13

**Comment by jakebailey** [comment]
You can find the language server version printed in the output panel (with Python selected).

**Comment by steveoh** [comment]
I see 

```sh
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:27:44) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by jakebailey** [comment]
That is the terminal panel; you need to select the Output panel and then Python from the dropdown at the right.

**Comment by steveoh** [comment]
is the output panel in vs code?

**Comment by jakebailey** [comment]
Yes.

![image](https://user-images.githubusercontent.com/5341706/55584777-e9af9100-56d9-11e9-8d82-0a4561738c2a.png)

**Comment by steveoh** [comment]
I see that, but I do not see a version listed there. Do I need to set

```json
"python.analysis.logLevel": "Trace"
```

**Comment by jakebailey** [comment]
You do not. 0.2.43 is the version we're looking for.

**Comment by jakebailey** [comment]
Did that only appear with trace logging? It should appear regardless of that setting.

**Comment by steveoh** [comment]
I had to add the tracing yes.

**Comment by jakebailey** [comment]
Following the steps above, the module gets resolved just fine.

![image](https://user-images.githubusercontent.com/5341706/64741678-3760ce80-d4ae-11e9-8d2b-7591b0bff01f.png)
