### ISSUE TITLE
Tool tip is slightly different between 100 and 1000

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/python-language-server#709]
![image](https://user-images.githubusercontent.com/3840081/53856511-11022980-3f87-11e9-9db8-93d3ebad7398.png)

![image](https://user-images.githubusercontent.com/3840081/53856524-1cedeb80-3f87-11e9-9c8c-945f779ebea3.png)

**Comment by jakebailey** [comment]
Not in the new LS; we don't return anything when you hover over a constant. (Pretend this image has a cursor)

![image](https://user-images.githubusercontent.com/5341706/53857675-09914f00-3f8c-11e9-913d-9a9f2c3eda6c.png)
