### ISSUE TITLE
Background python parser crashes importing sklearn.cluster in VS2017

### ISSUE THREAD

**Issue by int19h** [Microsoft/python-language-server#713]
@jaybo commented on [Mon Mar 04 2019](https://github.com/Microsoft/ptvsd/issues/1197)

## Environment data

- PTVSD version: 4.2.0 and 4.2.4
- OS and version: Windows 10, 1607, 14393.2670
- Python version (& distribution if applicable, e.g. Anaconda): Anaconda 3.6.8
- Using VS Code or Visual Studio: VS2017, 15.9.7

## Actual behavior

Background code parser crashes importing sklearn.cluster.  

## Expected  behavior

The background code parser should never crash.  On PTVSD 4.2.0 If I dismiss the crash dialog, it will reappear after about one minute, presumably when the background parser is auto-restarted.

## Steps to reproduce:
1. `pip install scikit-learn`

2. Load a python script which can be as simple as:

```
from sklearn.cluster import KMeans
```
3. Wait a moment, then:
![image](https://user-images.githubusercontent.com/1607323/53778229-dc23a300-3eb0-11e9-9457-64b81eafe5ce.png)

4. The program will run successfully.

---

@int19h commented on [Wed Mar 06 2019](https://github.com/Microsoft/ptvsd/issues/1197#issuecomment-470267279)

Could you clarify the steps to reproduce - is there another step there to launch it somehow, e.g. F5? Or by "load", do you mean just opening it in the editor and then waiting?

---

@jaybo commented on [Wed Mar 06 2019](https://github.com/Microsoft/ptvsd/issues/1197#issuecomment-470304660)

Just opening it in the editor and then waiting a moment will trigger the problem.

**Comment by jakebailey** [comment]
Should this have gone to PTVS?

**Comment by int19h** [comment]
It looks like it's the language server itself that's crashing, so probably not VS-specific.

**Comment by MikhailArkhipov** [comment]
But the screenshot shows 'python'? LS process name is not python I believe. @huguesv - have you seen OOP analyzer crashes popping crash box?

**Comment by jakebailey** [comment]
I think I've seen this happen in macOS (a different popup of course), which I believe is stemming from the OS detecting a crash in the scraper, which we are able to handle, but the OS trying to be helpful and showing that something broke/wasn't responding.

**Comment by jakebailey** [comment]
This was fixed in #740.
