### ISSUE TITLE
Unable to find document file

### ISSUE THREAD

**Issue by fenchu** [Microsoft/python-language-server#715]
Hi
VSC output window is flooding with the following errors and no intellisense at all is showing.

https://pvsc.azureedge.net/python-language-server-beta/Python-Language-Server-win-x64.0.2.16.nupkg

(sensiotools) PS D:\sensio-data\sensiotools\sensiotools\test> (pwd).Path
D:\sensio-data\sensiotools\sensiotools\test

Believe it is unable to pick up the path, is it the D: that fails it.

````
[Info  - 12:15:50] Analysis restarted.
Hover in file:///d:/sensio-data/sensiotools/sensiotools/test/testapi-events.py at (314, 31)
[Error - 12:15:58] Unable to find document file:///d:/sensio-data/sensiotools/sensiotools/test/testapi-events.py
Hover in file:///d:/sensio-data/sensiotools/sensiotools/test/testapi-events.py at (314, 31)
[Error - 12:15:59] Unable to find document file:///d:/sensio-data/sensiotools/sensiotools/test/testapi-events.py
Goto Definition in file:///d:/sensio-data/sensiotools/sensiotools/test/testapi-events.py at (314, 31)
[Error - 12:15:59] Unable to find document file:///d:/sensio-data/sensiotools/sensiotools/test/testapi-events.py
````

````
Goto Definition in file:///d:/sensio-data/sensiotools/sensiotools/test/list-alarms.py at (66, 13)
[Error - 12:48:23] Unable to find document file:///d:/sensio-data/sensiotools/sensiotools/test/list-alarms.py
[Error - 12:48:23] Request textDocument/definition failed.
  Message: Object reference not set to an instance of an object.
  Code: -32000 
   at Microsoft.Python.LanguageServer.Sources.DefinitionSource.FindDefinition(IDocumentAnalysis analysis, SourceLocation location)
   at Microsoft.Python.LanguageServer.Implementation.Server.GotoDefinition(TextDocumentPositionParams params, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.GotoDefinition(JToken token, CancellationToken cancellationToken)
````

**Comment by AlexanderSher** [comment]
Hi @fenchu , I assume file is present.

**Comment by fenchu** [comment]
@AlexanderSher They are all present it is the files I have open in editor:
````
ls D:\sensio-data\sensiotools\sensiotools\test\testapi-events.py; ls D:\sensio-data\sensiotools\sensiotools\test\list-alarms.py


    Directory: D:\sensio-data\sensiotools\sensiotools\test


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       07/03/2019     13:59          27747 testapi-events.py
-a----       04/02/2019     11:45           5975 list-alarms.py
````

**Comment by AlexanderSher** [comment]
Does it still show an error if you rename `testapi-events.py` into `testapi_events.py` and `list-alarms.py` into `list_alarms.py`?

**Comment by MikhailArkhipov** [comment]
https://stackoverflow.com/questions/761519/is-it-ok-to-use-dashes-in-python-files-when-trying-to-import-them

**Comment by jakebailey** [comment]
Even though these files are essentially unimportable (as with #727's `1.py`), I think they should probably still work on their own. Having a script like `my-cool-script` which is Python with a shebang is a pretty common case. We could likely allow modules of any name and let the parser decide what can actually be referenced, which would also open the door to handling `__import__` if became necessary.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/python-language-server/issues/736

**Comment by fenchu** [comment]
Thanks for the clarification, it works if I replace '-' with '_'.
I know dash is not allowed in module import filenames, but it is great to use for scripts that should never be used as modules. And other plugins like http://www.pydev.org/vscode works excellent. And pylint do not seem to object.

**Comment by MikhailArkhipov** [comment]
Folding into #736
