### ISSUE TITLE
Question: how do I provide settings if not using VS code?

### ISSUE THREAD

**Issue by emosesPatreon** [Microsoft/python-language-server#717]
I'd like to set the logLevel for the language server to help me debug, but I'm not sure where I can set "python.analysis.logLevel".  I'm using emacs, lsp-mode, and lsp-python-ms; is this something I can send with the initialization options to the server, or put a `config.json` somewhere on the path?  Thanks.

**Comment by jakebailey** [comment]
The current way we determine the log level is by looking at the user settings sent via `workspace/didChangeConfiguration`. In that message, `python.analysis.logLevel` is accessible, which we then read. I'm not sure if lsp-python-ms provides a mechanism to send `didChangeConfiguration` (I'm not super familiar with that codebase), but if you're able to do so then that should work.

I'm working on improving our configuration and startup situation, but we need to read out the user config to configure almost everything that isn't just "here is which Python installation to use" or "this is what the client is capable of"). https://github.com/Microsoft/python-language-server/blob/1072de6454138b3184606eb29aa0e7816cd4f020/src/LanguageServer/Impl/LanguageServer.cs#L94

**Comment by emosesPatreon** [comment]
Great, that exactly what I needed.  `lsp-mode` has a facility to call `didChangeConfiguration`, and I can wire it up for `lsp-python-ms`.  Thanks!
