### ISSUE TITLE
python.autoComplete.extraPaths in user and workspace settings, environment variables

### ISSUE THREAD

**Issue by nilleb** [microsoft/python-language-server#721]
I have just switched to Python Language Server, and I would have a question.

The code of my application is contained in a `app` subfolder, and all the imports in the code are relative to this subfolder. My application uses the Google Cloud SDK.
In my user settings I had a `python.autoComplete.extraPaths` exposing the Google Cloud SDK path (absolute paths, no environment variables).
Jedi was working, but the Python Language server complains about the fact that all the relative imports can not be resolved.

So, I have tried to:
- specify a `"${workspaceFolder}/app"` path as `python.autoComplete.extraPaths` in the workspace settings (this works, but the `python.autoComplete.extraPaths` in the user settings are not anymore loaded, and I can not anymore resolve CloudSDK imports -- please note that this is an enterprise and that everyone stores the CloudSDK in a different path)
- use a `.env` file, containing an `APPENGINE` variable, containing the path to the CloudSDK root, and load the CloudSDK modules specifying `"${APPENGINE}/platform/google_appengine"` paths
 (but at this point both pylint and the language server complain about the missing appengine imports)

Which is the right way to go?

**Comment by MikhailArkhipov** [comment]
First, try 0.2 LS which is in beta.
```json
"python.analysis.downloadChannel": "beta"
```
Ignore squiggle, the setting is dev/non-public. Otherwise, @AlexanderSher owns import subsystem.
