### ISSUE TITLE
Error on importing time

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/python-language-server#726]
```python
import time
```
This fails in the latest version of Language server

<img width="403" alt="Screen Shot 2019-03-09 at 12 27 26 PM" src="https://user-images.githubusercontent.com/1948812/54076976-d1795d00-4266-11e9-8c41-6db60b4445a5.png">

```log
Starting Microsoft Python language server.
[Info  - 10:59:43 AM] GetCurrentSearchPaths /Users/donjayamanne/.local/share/virtualenvs/pythonVSCode-5rU-mS3t/bin/python 
[Info  - 10:59:43 AM] SearchPaths:
[Info  - 10:59:43 AM]     /private/var/folders/22/0kj01mp12l3dsd1vw9vhfs6c0000gn/T/gpd33mwx.z0b
[Info  - 10:59:43 AM]     /Users/donjayamanne/.local/share/virtualenvs/pythonVSCode-5rU-mS3t/lib/python3.7
[Info  - 10:59:43 AM]     /Users/donjayamanne/.local/share/virtualenvs/pythonVSCode-5rU-mS3t/lib/python3.7/lib-dynload
[Info  - 10:59:43 AM]     /Users/donjayamanne/.pyenv/versions/3.7.0/lib/python3.7
[Info  - 10:59:43 AM]     /Users/donjayamanne/.local/share/virtualenvs/pythonVSCode-5rU-mS3t/lib/python3.7/site-packages
[Info  - 10:59:43 AM]     /Users/donjayamanne/.local/share/virtualenvs/pythonVSCode-5rU-mS3t/lib/python37.zip;/Users/donjayamanne/.local/share/virtualenvs/pythonVSCode-5rU-mS3t/lib/python3.7;/Users/donjayamanne/.local/share/virtualenvs/pythonVSCode-5rU-mS3t/lib/python3.7/lib-dynload;/Users/donjayamanne/.pyenv/versions/3.7.0/lib/python3.7;/Users/donjayamanne/.local/share/virtualenvs/pythonVSCode-5rU-mS3t/lib/python3.7/site-packages;
[Info  - 10:59:43 AM]     /Users/donjayamanne/.local/share/virtualenvs/pythonVSCode-5rU-mS3t/bin
[Info  - 10:59:47 AM] Microsoft Python Language Server version 0.2.16.0
[Info  - 10:59:47 AM] Initializing for /Users/donjayamanne/.local/share/virtualenvs/pythonVSCode-5rU-mS3t/bin/python
[Info  - 12:20:37 PM] Reloading modules... 
[Info  - 12:20:40 PM] done.
[Info  - 12:20:40 PM] Analysis restarted.
```

**Comment by AlexanderSher** [comment]
On my machine, it works fine:

![image](https://user-images.githubusercontent.com/8933858/54079325-035ae580-42a0-11e9-902f-9a9852bb8c95.png)

Do you have any exceptions?

**Comment by MikhailArkhipov** [comment]
I think the `/Users/donjayamanne/.local/share/virtualenvs/pythonVSCode-5rU-mS3t/lib/python37.zip;/Users/donjayamanne/.local/share/virtualenvs/pythonVSCode-5rU-mS3t/lib/python3.7;/Users/donjayamanne/.local/share/virtualenvs/pythonVSCode-5rU-mS3t/lib/python3.7/lib-dynload;/Users/donjayamanne/.pyenv/versions/3.7.0/lib/python3.7;/Users/donjayamanne/.local/share/virtualenvs/pythonVSCode-5rU-mS3t/lib/python3.7/site-packages;` 
i.e. unseparated paths are the problem. Old code separated paths itself. Basically part of https://github.com/Microsoft/python-language-server/issues/720

**Comment by DonJayamanne** [comment]
Absolutely no exceptions, reloaded VSC and started working again... Not whole this failed everything else worked with the language server..

**Comment by MikhailArkhipov** [comment]
Most probably #700 then

**Comment by DonJayamanne** [comment]
I think I know whats wrong.
Came across this a number of times yesterday and today.
Today, `import sys` had the exact same problem.
Unfortunately the problem went away before I could grab any screenshots.

I think the problem is, the problems are listed before the module resolution completes.
Came across problems with `import time`, `import sys`
I think this can be quite confusing and annoying to users when there are underlines under such imports that are used and are standard.

**Comment by DonJayamanne** [comment]
Identified in version `Microsoft Python Language Server version 0.2.23.0`

**Comment by MikhailArkhipov** [comment]
@DonJayamanne - is is just a squiggle or completion is missing too?

**Comment by DonJayamanne** [comment]
Happened again for `os, dataclass, etc...`
Didn't check intellisense, will check next time it happens.
![Screen Shot 2019-03-15 at 1 19 23 PM](https://user-images.githubusercontent.com/1948812/54459928-52cc6600-4725-11e9-9372-e8d3950be32c.png)

**Comment by DonJayamanne** [comment]
Just replicated for `import sys`
* No intellisense
* See below

![gotodef](https://user-images.githubusercontent.com/1948812/54460099-cf5f4480-4725-11e9-833b-24996f928d7b.gif)


Here are the logs:
```
##########Linting Output - flake8##########
Starting Microsoft Python language server.
[Info  - 1:15:48 PM] GetCurrentSearchPaths /Users/donjayamanne/.virtualenvs/pythonVSCode-5rU-mS3t/bin/python 
[Info  - 1:15:48 PM] Python search paths:
[Info  - 1:15:48 PM]     /private/var/folders/22/0kj01mp12l3dsd1vw9vhfs6c0000gn/T/thmraoix.apg
[Info  - 1:15:48 PM]     /Users/donjayamanne/.virtualenvs/pythonVSCode-5rU-mS3t/lib/python3.7
[Info  - 1:15:48 PM]     /Users/donjayamanne/.virtualenvs/pythonVSCode-5rU-mS3t/lib/python3.7/lib-dynload
[Info  - 1:15:48 PM]     /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7
[Info  - 1:15:48 PM]     /Users/donjayamanne/.virtualenvs/pythonVSCode-5rU-mS3t/lib/python3.7/site-packages
[Info  - 1:15:48 PM] Configuration search paths:
[Info  - 1:15:48 PM]     /Users/donjayamanne/.virtualenvs/pythonVSCode-5rU-mS3t/lib/python37.zip;/Users/donjayamanne/.virtualenvs/pythonVSCode-5rU-mS3t/lib/python3.7;/Users/donjayamanne/.virtualenvs/pythonVSCode-5rU-mS3t/lib/python3.7/lib-dynload;/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7;/Users/donjayamanne/.virtualenvs/pythonVSCode-5rU-mS3t/lib/python3.7/site-packages;
[Info  - 1:15:48 PM]     /Users/donjayamanne/.virtualenvs/pythonVSCode-5rU-mS3t/bin
[Info  - 1:15:53 PM] Microsoft Python Language Server version 0.2.23.0
[Info  - 1:15:53 PM] Initializing for /Users/donjayamanne/.virtualenvs/pythonVSCode-5rU-mS3t/bin/python
[Info  - 1:18:48 PM] Reloading modules... 
[Info  - 1:18:50 PM] done.
[Info  - 1:18:50 PM] Analysis restarted.
##########Linting Output - flake8##########
##########Linting Output - flake8##########
##########Linting Output - flake8##########
##########Linting Output - flake8##########
11,4,E,E999:SyntaxError: invalid syntax
12,1,E,E402:module level import not at top of file
13,1,E,E402:module level import not at top of file
##########Linting Output - flake8##########
11,4,E,E999:SyntaxError: invalid syntax
12,1,E,E402:module level import not at top of file
13,1,E,E402:module level import not at top of file
##########Linting Output - flake8##########
##########Linting Output - flake8##########
9,4,E,E999:SyntaxError: invalid syntax
10,1,E,E402:module level import not at top of file
11,1,E,E402:module level import not at top of file
13,1,E,E402:module level import not at top of file
14,1,E,E402:module level import not at top of file
##########Linting Output - flake8##########
9,7,W,W291:trailing whitespace
9,7,E,E999:SyntaxError: invalid syntax
10,1,E,E402:module level import not at top of file
11,1,E,E402:module level import not at top of file
13,1,E,E402:module level import not at top of file
14,1,E,E402:module level import not at top of file
##########Linting Output - flake8##########
9,1,F,F811:redefinition of unused 'sys' from line 8
##########Linting Output - flake8##########
##########Linting Output - flake8##########
9,3,E,E999:SyntaxError: invalid syntax
10,1,E,E402:module level import not at top of file
11,1,E,E402:module level import not at top of file
13,1,E,E402:module level import not at top of file
14,1,E,E402:module level import not at top of file
##########Linting Output - flake8##########
10,1,E,E402:module level import not at top of file
11,1,E,E402:module level import not at top of file
13,1,E,E402:module level import not at top of file
14,1,E,E402:module level import not at top of file
##########Linting Output - flake8##########
```

**Comment by MikhailArkhipov** [comment]
Set you `"python.analysis.logLevel": "Trace",` pretty please

**Comment by DonJayamanne** [comment]
Left it on, next time I see it i'll post more information. Try to retrace my steps.

**Comment by DonJayamanne** [comment]
Managed to replicate, though not sure when it stopped working, either way, here are the logs an other info:
* Python Env - 3.7 (using PipEnv)
* OS - Mac
* `import sys` & `import time` not found
* Screenshots
<img width="502" alt="Screen Shot 2019-03-18 at 9 53 23 PM" src="https://user-images.githubusercontent.com/1948812/54581133-87138100-49c8-11e9-834e-861397b277a5.png">
<img width="534" alt="Screen Shot 2019-03-18 at 9 53 27 PM" src="https://user-images.githubusercontent.com/1948812/54581134-87138100-49c8-11e9-8106-4fd0b04f6fbf.png">

* Logs
```
```

**Comment by DonJayamanne** [comment]
s

**Comment by DonJayamanne** [comment]
I haven't been experiencing this issue lately.
Hence closing it, possible some changes in the latest versions have resolved this issue.

**Comment by DonJayamanne** [comment]
Its back, saw this a number of times today.
Here are the logs:

**Comment by MikhailArkhipov** [comment]
May be related. The following test is unpredictable. Sometimes `sys` is unresolved, sometimes it is `compiled builtin` but analysis is empty.

```cs
        public async Task File() {
            const string code = @"
import sys
sys.
";
            var uri = await TestData.CreateTestSpecificFileAsync("a.py", code);
            await CreateServicesAsync(PythonVersions.LatestAvailable3X, uri.AbsolutePath);
            var rdt = Services.GetService<IRunningDocumentTable>();
            var doc = rdt.OpenDocument(uri, null, uri.AbsolutePath);

            var analysis = await doc.GetAnalysisAsync(Timeout.Infinite);
            var cs = new CompletionSource(new PlainTextDocumentationSource(), ServerSettings.completion);

            var completions = cs.GetCompletions(analysis, new SourceLocation(3, 5));
            completions.Should().HaveLabels("argv", "path", "exit");
        }
```

**Comment by MikhailArkhipov** [comment]
See also #779

**Comment by DonJayamanne** [comment]
Same problem with `import sys`.
<img width="394" alt="Screen Shot 2019-03-31 at 10 35 52 AM" src="https://user-images.githubusercontent.com/1948812/55292533-e5fdd080-53a0-11e9-8543-cc1e6897abd6.png">

**Comment by MikhailArkhipov** [comment]
```
[Info  - 9:05:10 PM] Reloading modules...
[Info  - 9:05:12 PM] done.
[Info  - 9:05:12 PM] Analysis restarted.
```
is suspicious. Looks like something is detected and changed and modules getting reloaded triggering the issue.

**Comment by MikhailArkhipov** [comment]
@AlexanderSher - I think https://github.com/Microsoft/python-language-server/pull/871 addressed this?

**Comment by AlexanderSher** [comment]
Yes

**Comment by MikhailArkhipov** [comment]
#871

**Comment by skbobade** [comment]
This needs to be reopened. I see this problem today - 

Version: 1.37.0 (user setup)
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Date: 2019-08-08T02:33:50.993Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by timharris777** [comment]
I agree this needs to be re-opened. I have the problem as well. i am on the latest version of vscode on a mac.

**Comment by timharris777** [comment]
@MikhailArkhipov

**Comment by sadikneipp** [comment]
Same problem here. Apparently happening only in python native libs (sys, traceback, pdb, logging).

```
Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:16:34.800Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.5.0
```

**Comment by eagleamon** [comment]
Same problem

**Comment by gatopeich** [comment]
Still failing for me on "import sys"...
Reloading the window fixes it _sometimes_.
