### ISSUE TITLE
Cannot load tensorflow.keras completions

### ISSUE THREAD

**Issue by rosekc** [Microsoft/python-language-server#727]
Microsoft Python Language Server version 0.1.80.0
![image](https://user-images.githubusercontent.com/17542574/54113848-23b3ad00-4424-11e9-9c13-478a0ea45725.png)

**Comment by jakebailey** [comment]
What are you expecting to see? New LS does this:

![image](https://user-images.githubusercontent.com/5341706/54139983-e7f6f400-43df-11e9-94c7-c772d3e5b50d.png)

![image](https://user-images.githubusercontent.com/5341706/54139998-f0e7c580-43df-11e9-939e-035d3b59c149.png)

Which you can try out by putting this into your VS Code config:

```
"python.analysis.downloadChannel": "beta"
```

**Comment by rosekc** [comment]
I have updated LS to beta version (0.2.17.0), and LS seems not work. I get error below:

```
Starting Microsoft Python language server.
[Info  - 上午9:48:19] GetCurrentSearchPaths C:\Users\rosekc\Anaconda3\python.exe 
[Info  - 上午9:48:19] SearchPaths:
[Info  - 上午9:48:19]     c:\users\rosekc\anaconda3\dlls
[Info  - 上午9:48:19]     c:\users\rosekc\anaconda3\lib
[Info  - 上午9:48:19]     c:\users\rosekc\anaconda3
[Info  - 上午9:48:19]     c:\users\rosekc\anaconda3\lib\site-packages
[Info  - 上午9:48:19]     c:\users\rosekc\anaconda3\lib\site-packages\win32
[Info  - 上午9:48:19]     c:\users\rosekc\anaconda3\lib\site-packages\win32\lib
[Info  - 上午9:48:19]     c:\users\rosekc\anaconda3\lib\site-packages\pythonwin
[Info  - 上午9:48:19]     C:\Users\rosekc\Anaconda3\python36.zip
[Info  - 上午9:48:19]     C:\Users\rosekc\Anaconda3\DLLs
[Info  - 上午9:48:19]     C:\Users\rosekc\Anaconda3\lib
[Info  - 上午9:48:19]     C:\Users\rosekc\Anaconda3
[Info  - 上午9:48:19]     C:\Users\rosekc\Anaconda3\lib\site-packages
[Info  - 上午9:48:19]     C:\Users\rosekc\Anaconda3\lib\site-packages\win32
[Info  - 上午9:48:19]     C:\Users\rosekc\Anaconda3\lib\site-packages\win32\lib
[Info  - 上午9:48:19]     C:\Users\rosekc\Anaconda3\lib\site-packages\Pythonwin
[Info  - 上午9:48:19]     .
[Info  - 上午9:48:19]     C:\Users\rosekc\Anaconda3
[Info  - 上午9:49:02] Microsoft Python Language Server version 0.2.17.0
[Info  - 上午9:49:02] Initializing for C:\Users\rosekc\Anaconda3\python.exe
[Error - 上午9:49:07] Unable to find document file:///c:/Users/rosekc/test/1.py
[Error - 上午9:53:23] Unable to find document file:///c:/Users/rosekc/test/1.py
```

**Comment by MikhailArkhipov** [comment]
Could you try and rename file to `one.py`. File name is a _module_ name and `1` will often fail to work.
Ex, Python console
![image](https://user-images.githubusercontent.com/12820357/54171831-ff160000-4438-11e9-96c9-e4c691617f13.png)

VS Code sees 'name' as number
![image](https://user-images.githubusercontent.com/12820357/54171798-ea396c80-4438-11e9-8337-adf272821aa0.png)

**Comment by MikhailArkhipov** [comment]
Related discussion https://stackoverflow.com/questions/761519/is-it-ok-to-use-dashes-in-python-files-when-trying-to-import-them

**Comment by rosekc** [comment]
> Related discussion https://stackoverflow.com/questions/761519/is-it-ok-to-use-dashes-in-python-files-when-trying-to-import-them

Thank you for your reply. I just use this short filename for runing a test script conveniently rather than importing it to somewhere.

After renaming the file, I got this.

![image](https://user-images.githubusercontent.com/17542574/54183286-c92b5700-44de-11e9-84a4-437134bf0822.png)

![image](https://user-images.githubusercontent.com/17542574/54185115-34772800-44e3-11e9-9bcb-e5ec7dcf4f4a.png)

**Comment by jakebailey** [comment]
That seems to tell me that the analysis isn't complete yet; the first image is a bug, the second I believe is due to the two-pass where after a single pass we know names but not types.

You may want to wait for it to finish and see.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/python-language-server/issues/736
