### ISSUE TITLE
Tooltip gets string wrong when it is following an escape character

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/python-language-server#73]
## Environment data

- VS Code version: 1.27.1 Insider
- Extension version (available under the Extensions sidebar): 2018.8.0
- OS and version: Windows 10 64bit
- Python version: 3.7
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): None

## Actual behavior

![alt text](https://i.imgur.com/wgDYG3v.png "Something is wrong")

## Expected  behavior

Tooltip shows: Word: str

## Steps to reproduce:
1. Use an escape character right before other string characters.
2. Hover over other string characters.

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
None
```   

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`)

```
None
```

**Comment by MikhailArkhipov** [comment]
Related: https://github.com/Microsoft/python-language-server/issues/17

**Comment by romangraef** [comment]
I would like to take on this issue. Since this is my first one: has anybody a few (code-)pointers?

**Comment by MikhailArkhipov** [comment]
This is Jedi, not LS
