### ISSUE TITLE
Autocomplete can't list all attributes in numpy.array even .shape

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/python-language-server#731]
@kondongx commented on [Sat Mar 09 2019](https://github.com/Microsoft/vscode-python/issues/4698)

## Environment data

- VS Code version: 1.32.1 
- Extension version: 2019.2.5558
- OS and version: macOS Mojave 10.14.3
- Python version: 3.7.2; miniconda(python=3.6.3). Both installed by pyenv
- Type of virtual environment used: none venv; conda 
- Relevant/affected Python packages and their versions: NumPy 1.16.2

## Expected behaviour

When I type `np.array().`, I want autocomplete list `reshape()` or `shape` or many other attributes, just like PyCharm:
<img width="559" alt="屏幕快照 2019-03-09 21 02 36" src="https://user-images.githubusercontent.com/28899471/54071935-b7fc0380-42ae-11e9-9910-ad5ecb32f8a9.png">
<img width="559" alt="屏幕快照 2019-03-09 21 02 40" src="https://user-images.githubusercontent.com/28899471/54071938-b9c5c700-42ae-11e9-9e3e-1341ef163d18.png">
<img width="559" alt="屏幕快照 2019-03-09 21 02 44" src="https://user-images.githubusercontent.com/28899471/54071939-bc282100-42ae-11e9-8be8-82e5c27165bf.png">

## Actual behaviour

But I got only `dtype` and some `__xxx__` in VSCode:
<img width="540" alt="屏幕快照 2019-03-09 20 55 57" src="https://user-images.githubusercontent.com/28899471/54071883-ed542180-42ad-11e9-99d0-5fd5b9724b1c.png">
Note that yellow box, no more attributes.
<img width="554" alt="屏幕快照 2019-03-09 21 01 12" src="https://user-images.githubusercontent.com/28899471/54071950-ef6ab000-42ae-11e9-863f-0e0b4fe98a42.png">

## Steps to reproduce:
1. Type these code:
    ```
    import numpy as np
    np.array().
    ```
2. Then press `shift + enter` to trigger autocomplete.

## Logs
```
Starting Microsoft Python language server.
##########Linting Output - pylint##########

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)

Microsoft Python Language Server version 0.1.80.0
Initializing for /Users/kondongx/.pyenv/shims/python
```

---

@artemvalieiev commented on [Sun Mar 10 2019](https://github.com/Microsoft/vscode-python/issues/4698#issuecomment-471338743)

It also happens to me, Microsoft Language Server for Python incorrectly shows return type for numpy.array() as numpy.recarray instead of numpy.ndarray

**Comment by MikhailArkhipov** [comment]
This is b/c `multiarray.pyd` was not imported. PYI file was correctly generated by the scaper and is residing in the cache, so the module WAS found. `numpy.core.numeric` was also found and imported. However, all types from
```python
from .multiarray import (
    _fastCopyAndTranspose as fastCopyAndTranspose, ALLOW_THREADS,
    BUFSIZE, CLIP, MAXDIMS, MAY_SHARE_BOUNDS, MAY_SHARE_EXACT, RAISE,
    WRAP, arange, array, broadcast, can_cast, compare_chararrays,
    concatenate, copyto, count_nonzero, dot, dtype, empty,
    empty_like, flatiter, frombuffer, fromfile, fromiter, fromstring,
    inner, int_asbuffer, lexsort, matmul, may_share_memory,
    min_scalar_type, ndarray, nditer, nested_iters, promote_types,
    putmask, result_type, set_numeric_ops, shares_memory, vdot, where,
    zeros, normalize_axis_index)
```
were resolved as `unknown`.

![image](https://user-images.githubusercontent.com/12820357/54484451-788c6480-4824-11e9-89e2-cd2ee9122756.png)
