### ISSUE TITLE
Memory usage increase

### ISSUE THREAD

**Issue by CMLL** [Microsoft/python-language-server#735]
Testing the 0.2.17 beta release I noticed that the memory footprint for the same project increased pretty significantly.

The first one is the htop output of the server running 0.1.80, while the second one is under 0.2.17. Same project, same files opened and not many changes done in the file.

I took the screenshot on .1.80, switched to beta, removed the folder and reloaded VScode, after a couple of seconds of the language server starting the usage jumped up.

![pythonls-0 1 80_memory](https://user-images.githubusercontent.com/3720126/54211003-6c2ca280-44d8-11e9-84a8-db7f67661e6f.png)
![pythonls-0 2 17_memory](https://user-images.githubusercontent.com/3720126/54211008-6e8efc80-44d8-11e9-982c-3f0faefd1c8e.png)

**Comment by MikhailArkhipov** [comment]
The approach to analysis in 0.2 is very different and hence memory dynamics. It does can consume more on smaller projects but consumes less and does not run away on large ones. We'll be looking into the memory footprint and other optimizations as soon as we are done with more pressing items.

**Comment by CMLL** [comment]
That's great to know. I've noticed while working on the beta channel, that I'm experiencing less complete freezes due to memory with 0.2.17 even though the usage seems to be high, but that's pretty shallow observation.

It could also be that seen I've had more instances of the server losing connection and restarting, and that prevents the server from running away with the memory.

I do use it on a fairly large project, with a large amount of libraries installed in the virtualenv and extraPaths configured.

**Comment by MikhailArkhipov** [comment]
@CMML - is this still an issue with later updates?

**Comment by CMLL** [comment]
Not really, I've had pretty good memory numbers in the last updates. Is still high compared with other applications but is not as big as in previous builds, and it no longers gets so high that it locks down the whole system. Great job on these last updates.

**Comment by MikhailArkhipov** [comment]
OK, closing then, we have couple others active on similar issues but with different configurations. Glad you are set :-)
