### ISSUE TITLE
Decide handling of unusual file names

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/python-language-server#736]
Technically file names are module names and names like `1.py` or `a-b.py` are unimportable. Currently we fail with `Unable to find document` message which is not informative.

Options:
1. Give informative warning message (or make it error and then fail).
2. Make files work in standalone way (with warning).

Related:
https://stackoverflow.com/questions/761519/is-it-ok-to-use-dashes-in-python-files-when-trying-to-import-them

**Comment by AlexanderSher** [comment]
It is actually one fix for this one and #597: file that has name that can't be a module can have name and be analyzed (including absolute imports).

**Comment by jakebailey** [comment]
I'm not sure they're completely identical; I could have a file in some directory called `a.py` and `my-script.py` next to it which does `from .a import foo` and execute the latter just fine, right? The difference I'm seeing is that I think the assumption we'd make for #597 is to pretend untitled files are at the root, but I don't think that's so for the `my-script.py` case. I'd need to test and see what'd happen; this is just my initial thought.

**Comment by AlexanderSher** [comment]
If you do `python my-script.py`, you'll get an error:
```
cannot import name 'a' from '__main__' (my-script.py)
```

**Comment by jakebailey** [comment]
Yes, I did some testing and things do seem to break. Though it looks like you can actually do `python -m my-script` and it works. My choice in using a relative import was probably a bad one; so I tested using absolute which also failed. Maybe it won't matter all that much, I was just worried about removing potentially important info about where a file exists.

For completion's sake, if you're curious:

```
 %  ~/weird2  tree                 
.
├── a│   ├── __init__.py
│   ├── __init__.pyc
│   └── b
│       ├── __init__.py
│       ├── __init__.pyc
│       └── c
│           ├── __init__.py
│           ├── __init__.pyc
│           └── __pycache__
│               └── __init__.cpython-37.pyc
├── runme.py
└── scripts
    ├── __pycache__
    │   └── my-script.cpython-37.pyc
    └── my-script.py

6 directories, 10 files
 %  ~/weird2  python scripts/my-script.py 
Traceback (most recent call last):
  File "scripts/my-script.py", line 1, in <module>
    from a.b.c import foo
ImportError: No module named a.b.c
 %  ~/weird2  python -m scripts.my-script   
/usr/local/opt/python@2/bin/python2.7: No module named scripts
 %  ~/weird2  python3 scripts/my-script.py
Traceback (most recent call last):
  File "scripts/my-script.py", line 1, in <module>
    from a.b.c import foo
ModuleNotFoundError: No module named 'a'
 %  ~/weird2  python3 -m scripts.my-script   
hi from a.b.c.foo()!
```

**Comment by jakebailey** [comment]
#778 too: We should be handling files without `.py` at the end in a similar fashion.

**Comment by tmab2003** [comment]
Files that start with [0-9] also don't seem to be working..Keep getting the following prints:
`[Error - 2:08:08 PM] Unable to find document file:///c:/Users/../../08_HMI/08_011_HMI.py`

**Comment by AngelontheRoad** [comment]
I got the same problem
`Unable to find document file:///d:/A_Items/NP/np.py`

**Comment by kushaldas** [comment]
I am having same problem on a Linux box:

```
Unable to find document file:///home/kdas/code/johnnycanencrypt/johnnycanencrypt/utils.py
```

**Comment by kushaldas** [comment]
```
:CocCommand python.upgradePythonLanguageServer
```

Upgrading to latest stable solved the issue.
