### ISSUE TITLE
Indefinite high CPU usage when analyzing tensorflow

### ISSUE THREAD

**Issue by malmaud** [Microsoft/python-language-server#737]
Using python language server 0.2.17.0 and the tensorflow 2.0 beta installed via `pip install -U --pre tensorflow` on OS X. 

I open an empty workspace and create a single file that only contains

`import tensorflow as tf`

The activity monitor shows the language server consuming 2-3 cores (screenshot attached). This has persisted for 4 hours on a fairly beefy Macbook Pro, which makes me wonder if the analysis is actually proceeding or has entered an infinite loop of some kind.
<img width="912" alt="Screen Shot 2019-03-12 at 2 07 13 PM" src="https://user-images.githubusercontent.com/987837/54224771-9a0de900-44d0-11e9-8260-3ea224782a91.png">

The Python output pane displays

```
[Info  - 2:03:06 PM] GetCurrentSearchPaths /anaconda3/bin/python 
[Info  - 2:03:06 PM] SearchPaths:
[Info  - 2:03:06 PM]     /private/var/folders/t6/ddh10c6j5r54sg19jlc59n580000gn/T/av1j43sm.gyt
[Info  - 2:03:06 PM]     /anaconda3/lib/python3.7
[Info  - 2:03:06 PM]     /anaconda3/lib/python3.7/lib-dynload
[Info  - 2:03:06 PM]     /Users/malmaud/.local/lib/python3.7/site-packages
[Info  - 2:03:06 PM]     /anaconda3/lib/python3.7/site-packages
[Info  - 2:03:06 PM]     /anaconda3/lib/python3.7/site-packages/aeosa
[Info  - 2:03:06 PM]     /Users/malmaud/anaconda3/lib/python3.7/site-packages
[Info  - 2:03:06 PM]     /anaconda3/lib/python37.zip;/anaconda3/lib/python3.7;/anaconda3/lib/python3.7/lib-dynload;/Users/malmaud/.local/lib/python3.7/site-packages;/anaconda3/lib/python3.7/site-packages;/anaconda3/lib/python3.7/site-packages/aeosa;/Users/malmaud/anaconda3/lib/python3.7/site-packages;
[Info  - 2:03:06 PM]     /anaconda3/bin
[Info  - 2:03:11 PM] Microsoft Python Language Server version 0.2.17.0
[Info  - 2:03:11 PM] Initializing for /anaconda3/bin/python
```

**Comment by malmaud** [comment]
This seems to be happening for tensorboardX too, which is a pretty small package.

**Comment by jakebailey** [comment]
Add this to your settings and you should get more info:

```
"python.analysis.logLevel": "Trace"
```

**Comment by malmaud** [comment]
Ah thanks. I see it is making steady progress; it's just that TensorFlow and all its transitive dependencies consists of a huge number of modules that have to be analyzed. 

Is there a way to suppress an import from being analyzed, since I'd rather just not have tensorflow be analyzed then face a long analysis phase whenever I open my workspace?

**Comment by malmaud** [comment]
I also notice that `plotly` alone takes a quite a long time to analyze - 409631 ms  - while fully consuming 6 cores. I don't remember it taking so long on older versions of the language server, but I didn't measure.

**Comment by MikhailArkhipov** [comment]
Older versions simply missed some imports, especially inner relative imports of libraries. So although the analysis is now lighter weight, it sometimes has to handle more. We will be looking into optimizations and caching as we go.

**Comment by malmaud** [comment]
OK, makes sense and thanks for the great work on the new language server!

I'm still curious though if there's a setting to suppress the language server from trying to analyze certain imports, just as a practical step I can take now while optimizations continue to be worked on.

**Comment by MikhailArkhipov** [comment]
There is no specific setting at the moment, but @AlexanderSher who owns import subsystem can check if this is feasible or that `excludePaths` setting might help?

**Comment by jakebailey** [comment]
excludePaths right now is only used for excluding files in indexing. In the new LS, it lost most of its meaning because we don't use a big pattern matcher to choose what to analyze anymore. (This is also related to the initialization/documentation stuff.)

**Comment by MikhailArkhipov** [comment]
@malmaud = 0.2.23 should have analysis time slashed down quite a bit. Restart VSC to get it.

**Comment by MikhailArkhipov** [comment]
I am going to close this as we observe `tensorflow` analysis to complete in ~25s.

**Comment by malmaud** [comment]
Ok, thanks!
