### ISSUE TITLE
Disable autocompletion in unclosed docstring

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/python-language-server#748]
@iansan5653 commented on [Thu Feb 21 2019](https://github.com/Microsoft/vscode-python/issues/4484)

When writing a docstring for a function, lines often end with a period. This can be very frustrating to write in VSCode, because when you type a period and press enter, it tries to autocomplete instead of putting a new line in, as if you are writing code and not text.

Note that this only occurs when the string is open -- not when there are closing quotes.

Here's an example:
![image](https://user-images.githubusercontent.com/2294248/53175639-623f1000-35ba-11e9-9bb6-8be9f8f4c4dd.png)

The best solution would be to disable autocomplete or Intellisense entirely when typing within a string, even if that string has not yet been closed.

**Comment by DonJayamanne** [comment]
I can replicate this on the latest version of LS (`0.2.17`)

**Comment by jakebailey** [comment]
This is #739.
