### ISSUE TITLE
Server is stuck on some file probably

### ISSUE THREAD

**Issue by Yanpas** [Microsoft/python-language-server#750]
I have a project with over a thousand different python files. I can't use this LS there since it stops respond after some time (renames take infinite time): memory stops to grow after 1.5G resident memory is consumed and CPU load is 12% (100% on one cpu core).

There are no guides here how to provide debug info. I have tried to attach with dotnet debugger, but the stack trace is hidden. GDB doesn't show anything meaningful.

Consider add timeout to parsing threads.

![image](https://user-images.githubusercontent.com/7345761/54346129-96f03580-4655-11e9-867d-875fd389d9dd.png)

**Comment by MikhailArkhipov** [comment]
Are you on stable channel or beta? New 0.2+ LS is available at the beta channel.
```json
"python.analysis.downloadChannel": "beta"
```

**Comment by strefethen** [comment]
I'm having a similar problem with a small project where the Microsoft.Python.Language.Server takes a large amount of CPU and never completes. Intellisense gets stuck showing "Loading...".

Where does the above line for the beta channel go? I've tried adding it to both User and workspace settings but I get "Unknown configuration setting".

**Comment by jakebailey** [comment]
Just stick it in your settings.json. You can ignore the warning; it's an undocumented option for testing.

**Comment by strefethen** [comment]
@jakebailey Thanks for the reply. Is that's needed? Is the new LS part of the existing download or should I see some sort of update at some point?

Despite restarted VSC in Activity Monitor I see the LS still chewing away at my CPU.

**Comment by jakebailey** [comment]
You need likely need to restart VSC. If you look at the Python output in the output panel, you should see the LS version being used printed.

**Comment by Yanpas** [comment]
@strefethen did it help you?

I think this setting worth mentioning in README. A way to provide stack trace is good too

**Comment by jakebailey** [comment]
This setting won't be needed for very long, we're going to release this to stable once we have a few last things worked out. We spread this info to various issues to get testers who previously had resource/performance issues before we launch it for everybody at once.

**Comment by Yanpas** [comment]
With beta server doesn't stuck anymore.

Rename still doesn't work at all

And warning `undefined variable` appeared in this context:
```
 with (self.path / 'object.xml').open() as f:
            self.root = ElementTree.parse(f)
```

**Comment by MikhailArkhipov** [comment]
Rename is not implemented yet in the new code base, that is #577

**Comment by MikhailArkhipov** [comment]
Could you give a bit more context to the undefined var message? I can't seem to repro with basic case

![image](https://user-images.githubusercontent.com/12820357/54445703-8d70d700-4702-11e9-85e2-d3632552dd98.png)

**Comment by strefethen** [comment]
@Yanpas I'm still seeing high CPU though I'm not seeing just "Loading..." anymore though I'm not getting identifiers either I just see vars that are in the currently open .py file. It definitely seems like either a) I have some misconfiguration or b) it's just not working. 

I haven't had much time to actually debug what's happening so apologies I can't offer more ATM.

**Comment by MikhailArkhipov** [comment]
@strefethen - are you on LS 0.1 or 0.2 (beta channel)

**Comment by strefethen** [comment]
@MikhailArkhipov I'm sorry, I really haven't dug into the beta channels at all and I'm just using the setting mentioned above so I really don't know. How can I tell? Nothing new seemed to update when I added the above setting AFAICT and I've restarted VSC multiple times. I did get a "VSCode wants to install help..." message this morning but I don't know what specifically updated.

**Comment by MikhailArkhipov** [comment]
There should be a message in the output window telling version of the LS when it starts. Something like
```
[Info  - 10:48:57 AM] GetCurrentSearchPaths C:\Python\Python37\python.exe 
[Info  - 10:48:57 AM] Python search paths:
[Info  - 10:48:57 AM]     c:\python\python37\dlls
[Info  - 10:48:57 AM]     c:\python\python37\lib
[Info  - 10:48:57 AM]     c:\python\python37
[Info  - 10:48:57 AM]     c:\python\python37\lib\site-packages
[Info  - 10:48:57 AM] Configuration search paths:
[Info  - 10:48:57 AM]     C:\Python\Python37\python37.zip
[Info  - 10:48:57 AM]     C:\Python\Python37\DLLs
[Info  - 10:48:57 AM]     C:\Python\Python37\lib
[Info  - 10:48:57 AM]     C:\Python\Python37
[Info  - 10:48:57 AM]     C:\Python\Python37\lib\site-packages
[Info  - 10:48:57 AM]     .
[Info  - 10:48:57 AM]     C:\Python\Python37
[Info  - 10:49:01 AM] Microsoft Python Language Server version 0.2.....
```

**Comment by strefethen** [comment]
@MikhailArkhipov I was seeing that sort of output the other day but I'm not seeing that now. I'm opening VSC in a folder with a Python application running on OSX. I've just uninstall/reinstalled both the MSFT Python extension and the VS Intellicode extension and I get zero content in the Output console opening a .py file. I'm using Python 3.6.5 and VSC 1.32.3.

**Comment by jakebailey** [comment]
Have you selected the "Python" option for the output panel? There's a dropdown on the right.

**Comment by strefethen** [comment]
🤦‍♂️  No.

Here's the output:
`Starting Microsoft Python language server.
[Info  - 11:14:31 AM] GetCurrentSearchPaths /usr/local/bin/python 
[Info  - 11:14:31 AM] SearchPaths:
[Info  - 11:14:31 AM]     /private/var/folders/yp/pq3y7gh534q1ffdmx1gzb4780000gr/T/idpkrest.b0r
[Info  - 11:14:31 AM]     /usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6
[Info  - 11:14:31 AM]     /usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
[Info  - 11:14:31 AM]     /Users/strefethen/Library/Python/3.6/lib/python/site-packages
[Info  - 11:14:31 AM]     /usr/local/lib/python3.6/site-packages
[Info  - 11:14:31 AM]     /usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python36.zip;/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6;/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload;/Users/strefethen/Library/Python/3.6/lib/python/site-packages;/usr/local/lib/python3.6/site-packages;
[Info  - 11:14:31 AM]     /
[Info  - 11:14:31 AM]     /usr/local/bin
##########Linting Output - pylint##########

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
`

**Comment by MikhailArkhipov** [comment]
OK, look into the `languageServer` folder under the extension folder (VSC command 'Open Extensions Folder'), which one do you see Microsoft.Python.Analysis.dll or Microsoft.Python.Analysis.Engine.dll?

**Comment by strefethen** [comment]
I see the following:
```
./ms-python.python-2019.2.5558
    /languageServer.0.1.80
        Microsoft.Python.Analysis.Engine.dll
    /languageServer.0.2.17
        /bin/release
            Microsoft.Python.Analysis.dll
```
I'm guessing having both versions is not a good thing (tm).

**Comment by jakebailey** [comment]
It's fine, the most recent one would be used. You may want to restart your editor (if you haven't recently) to trigger an update to the latest version (0.2.23 at the moment).

In your `settings.json`, add the following:

```
"python.analysis.logLevel": "Trace"
```

You'll get more info in the output panel than before.

**Comment by jakebailey** [comment]
And if the extension doesn't update the language server, you can delete those languageServer directories and the download will be forced.

**Comment by strefethen** [comment]
@jakebailey I now have 0.2.23, my CPU has settled down and Intellisense looks to be working.

Really appreciate your help! Thank you.

**Comment by MikhailArkhipov** [comment]
Closing then
