### ISSUE TITLE
__file__ is marked as an undefined variable

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/python-language-server#761]
Python Version  3.7
LS Version 0.2.23.0
Python code:
```python
print(__file__)
```

<img width="547" alt="Screen Shot 2019-03-15 at 10 15 56 AM" src="https://user-images.githubusercontent.com/1948812/54449714-0294da00-470c-11e9-9081-1aec20e5b2c2.png">

**Comment by MikhailArkhipov** [comment]
Need to add default globals to global scope.
