### ISSUE TITLE
vscode keeps prompt “python quit unexpectly”

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/python-language-server#762]
@iXingo commented on [Sat Mar 09 2019](https://github.com/Microsoft/vscode-python/issues/4701)

## Environment data

- VS Code version: 1.32.1
- Extension version (available under the Extensions sidebar): python 2019.2.5558
- OS and version: macOS X Mojave version 10.14.3
- Python version (& distribution if applicable, e.g. Anaconda): python3.7.2 (installed by Homebrew)
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): integrated terminal
- Relevant/affected Python packages and their versions: removed all the python extension but the python 2019.2.5558

## Expected behaviour

normal

## Actual behaviour

keeps prompt me "python quit unecpectly"

## Steps to reproduce:
1. install python3 using home-brew (python3.7.2)
2. open a python3 file (.py)
##actually I can get expected result using debug, but the prompt still keeps remind me, when I switch to Jedi, vscode can work fine##

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
nothing
```   

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
Nothing
```
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/3634305/54080682-55e3e280-4330-11e9-8e9b-ae4fa1364f08.png">

---

@mdalpi commented on [Mon Mar 11 2019](https://github.com/Microsoft/vscode-python/issues/4701#issuecomment-471685464)

I'm experiencing what it appears to be the same thing, here's my report: https://pastebin.com/t1HM4Z54

---

@iXingo commented on [Tue Mar 12 2019](https://github.com/Microsoft/vscode-python/issues/4701#issuecomment-471959676)

> I'm experiencing what it appears to be the same thing, here's my report: https://pastebin.com/t1HM4Z54

Can not open your link...

**Comment by jakebailey** [comment]
#740
