### ISSUE TITLE
[PTVS] Python background analyzer is locking files

### ISSUE THREAD

**Issue by huguesv** [microsoft/python-language-server#767]
With the latest preview, I keep encountering a case where I attempt to save one of the files in my solution and get the warning tht is is locked by another process. To fix this I need to go into task manager and I kill the "Visual Studio - Python background analyzer" processes

Reported at https://developercommunity.visualstudio.com/content/problem/483802/python-background-analyzer-is-locking-files.html

User says there's no reliable way of reproducing, and I can't reproduce myself.

Inspecting all the code that opens files/streams, I have a suspicion of https://github.com/Microsoft/python-language-server/blob/ptvs/src/Analysis/Engine/Impl/Intellisense/ProjectEntryExtensions.cs

Both `ReadDocument` and `ReadDocumentBytes` return an object that is disposable but isn't disposed by the callers in ProjectEntryExtensions.cs

And those disposable objects would in turn dispose a stream that was opened with `PathUtils.OpenWithRetry(FilePath, FileMode.Open, FileAccess.Read, FileShare.Read)` which means anyone else can't write to the file until disposed.

**Comment by MikhailArkhipov** [comment]
So what is expected from LS? The code above no longer in use in LS. The only case of `WriteTextWithRetry` I see is in https://github.com/microsoft/python-language-server/blob/a6e31c83054a9d423b658858661877a448cbf907/src/Core/Impl/Extensions/IOExtensions.cs#L124 and it is disposed. It is used to write stubs, not user code.
