### ISSUE TITLE
Prebuilt binary for linux/macOS system?

### ISSUE THREAD

**Issue by wookayin** [Microsoft/python-language-server#770]
This language-server implementation is amazing, and thank you for your hard work.

I wonder if you can provide a pre-built binary that can work out-of-box. It is somewhat complicated to build from sources in linux or macOS systems.

**Comment by MikhailArkhipov** [comment]
There is no single pre-built binary. However, there is a prebuilt package that Python extension downloads and unpacks. It is nuget (zip). Extension source is

https://github.com/Microsoft/vscode-python/blob/master/src/client/activation/languageServer/languageServerPackageRepository.ts
https://github.com/Microsoft/vscode-python/blob/master/src/client/activation/languageServer/languageServerPackageService.ts

Example URL for Mac
https://pvsc.blob.core.windows.net/python-language-server-beta/Python-Language-Server-osx-x64.0.2.25.nupkg

**Comment by wookayin** [comment]
This is working. Thank you for the information!

**Comment by contrun** [comment]
How do I get the latest release version?

**Comment by MikhailArkhipov** [comment]
@contrun - prebuilt binary or in VS Code or... ?

**Comment by contrun** [comment]
@MikhailArkhipov Sorry for the ambiguity. prebuilt binaries.

**Comment by MikhailArkhipov** [comment]
URLs are as above and there is Python extension sample code linked there. Extension downloads latest available.

**Comment by teto** [comment]
The previous url my linux distribution was using was:
https://pvsc.azureedge.net/python-language-server-stable/Python-Language-Server-linux-x64.0.3.40.nupkg which fails.
I tried bumping the version number to 0.3.66 to no avail. Our build infrastructure relies on fetching a nuget file so I would like to find a nuget but I have no idea where to look: I thought https://www.nuget.org/packages?q=python-language-server would give me some results but I couldn't find anything, please help :)

**Comment by jakebailey** [comment]
Those links are only intended to be used for the VS Code Python extension to install/update the language server, not general consumption (note "pvsc" in the URL). We periodically remove older builds from the bucket once we know that the extension will not download them anymore.

The latest stable version is 0.4.24, so you may be able to bump it for now, but if you need to depend on a specific version, you'll likely want to be building it from source or mirroring the file in a more stable location. We may consider publishing on nuget for full persistence at some point, but we still haven't fully "released" the language server and haven't had the time to get that fully set up and versioned.

**Comment by MikhailArkhipov** [comment]
Alternatively, you can look at how extension picks the latest here https://github.com/microsoft/vscode-python/tree/master/src/client/activation/languageServer
