### ISSUE TITLE
Unresolved Imports

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/python-language-server#779]
@Astrantia commented on [Fri Mar 15 2019](https://github.com/Microsoft/vscode-python/issues/4784)

```py
from .common.desired_capabilities import DesiredCapabilities
from .common.action_chains import ActionChains 
from .common.touch_actions import TouchActions
```

```
[Info  - 1:57:57 AM] Microsoft Python Language Server version 0.2.23.0
[Info  - 1:57:57 AM] Initializing for C:\Python37\python.exe
```
Extension compiled from master.

Clicking CTRL and hovering over DesiredCapabilities, ActionChains, etc will not resolve. `from . import A` doesn't work in general with latest LS and latest extension

---

@Astrantia commented on [Sat Mar 16 2019](https://github.com/Microsoft/vscode-python/issues/4784#issuecomment-473565539)

@DonJayamanne can you reproduce this?

---

@Astrantia commented on [Sat Mar 16 2019](https://github.com/Microsoft/vscode-python/issues/4784#issuecomment-473575105)

This is critical because most modules are written like this, meaning that intellisense cant be used for those modules

**Comment by need47** [comment]
```python
import logging
import os
import shutil
import stat
import sys
import time
import traceback
from typing import List
from contextlib import contextmanager
from functools import partialmethod```

Among the above imports, I only got `unresoved import` for `sys` and `time`. Others are OK.

Python 3.7.0 64-bit
VSCode 1.32.1
VSCode-Python 2019.3.6139

**Comment by Vict0rSch** [comment]
Same here I have `unresolved import 'sys'`

VSCode 1.32.3
Python 3.6.4

**Comment by MikhailArkhipov** [comment]
Folding into #726

**Comment by skbobade** [comment]
I still face this problem today. 
Version: 1.37.0 (user setup)
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Date: 2019-08-08T02:33:50.993Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
