### ISSUE TITLE
Autocompletion Options Problem

### ISSUE THREAD

**Issue by RealFeorache** [Microsoft/python-language-server#781]
### **Basic Information**
---------------------------------------
Product: VS Code, version 1.32.3
OS: Windows 10 build 17763.379
Intellicode Extension Version: 1.1.4
Language: Python

Enabled extensions:
1. Bracket Pair Colorizer 2
2. GitLens — Git supercharged
3. MagicPython
4. Material Icon Theme
5. Python
6. Todo+
----------------------------------------
### **Steps to Reproduce / Scenario:**
1. Enable the Visual Studio IntelliCode - Preview Extension
2. Confirm the change from Jedi to Microsoft Python Language Server (Preview)
3. Use the following code as a test:
```
import turtle

ttl = turtle.Turtle()
wn = turtle.Screen()
```
4. Next, try to check the autocompletion for ttl:
![Annotation 2019-03-18 205534](https://user-images.githubusercontent.com/47661811/54561091-1bc7b000-49c4-11e9-9db5-f77b5f1bfc79.png)
----------------------------------------
### **Expected behavior:**
Suggestions for the possible autocompletions. Works with Jedi as IntelliSense Engine instead of Microsoft Python Analysis Engine:
![Annotation 2019-03-18 210050](https://user-images.githubusercontent.com/47661811/54561097-1f5b3700-49c4-11e9-88a2-78e5f2d0824d.png)

----------------------------------------
The problem is not with Visual Studio IntelliCode - Preview Extension, as was confirmed here:
[MicrosoftDocs/intellicode/Issue#75](https://github.com/MicrosoftDocs/intellicode/issues/75)
Full reinstall didn't change anything.
I am not sure, but it looks like it's the same as issue #731

**Comment by jakebailey** [comment]
Please retest with the beta build by adding this to your VS Code settings:

```
"python.analysis.downloadChannel": "beta"
```

(Note that IntelliCode may not work with this build quite yet.)

**Comment by RealFeorache** [comment]
@jakebailey 
The autocompletion is back to normal, works with "turtle", "tkinter", no errors in the output, unless IntelliCode is turned on, as you have said.
Thank you for the current solution.

**Comment by jakebailey** [comment]
We did a big rewrite of the language server, but haven't yet pushed it to stable (hence the temporary configuration change for testing stuff like). This will come to stable fairly soon.

Closing for now.
