### ISSUE TITLE
Connection got disposed

### ISSUE THREAD

**Issue by luabud** [Microsoft/python-language-server#801]
VSCode version: 1.32.3 
Python extension version: 2019.3.5917-rc
Microsoft Python Language Server version 0.2.29.0

Not sure if it's relevant but I had "python.analysis.downloadChannel": "beta" on the settings file and right before starting recording the GIF below I removed it and reloaded VS Code. 

LanguageServerConnectionBug](https://user-images.githubusercontent.com/45497113/54725554-c0fd9800-4b2c-11e9-92c7-d82de7edbe8c.gif)

Freezing the error:

![image](https://user-images.githubusercontent.com/45497113/54725650-23569880-4b2d-11e9-935b-3c392ab78ff6.png)

**Comment by jakebailey** [comment]
This is my fault; I completely forgot about `:` being in `C:\` in paths (in #793). Sending a PR now and I'll merge and build.

**Comment by jakebailey** [comment]
I've removed 0.2.29 from the beta channel. If you delete the language server folder in your extension folder, you should be able to redownload to 0.2.28 for now. 0.2.30 will come fairly soon.

**Comment by luabud** [comment]
I had it again
![image](https://user-images.githubusercontent.com/45497113/55017874-e831ea80-4fae-11e9-838e-a05137945e0c.png)

using a venv environment (Python 3.7.1)
