### ISSUE TITLE
extraPaths doesn't supersede modules found on the pythonPath

### ISSUE THREAD

**Issue by monkeez** [microsoft/python-language-server#803]
I'm having an issue with autocomplete not doing what I expect. I'm working with Autodesk Maya so I have my workspace settings file set up as such:
```
{
    "python.pythonPath": "C:/Program Files/Autodesk/Maya2018/bin/mayapy.exe",
    "python.autoComplete.extraPaths": [
        "${env:MAYA_DEVKIT}/other/pymel/extras/completion/py"
    ]
}
```
This used to work fine for me with the language server a number of months ago when I was last coding.

But now this happens:

![image](https://user-images.githubusercontent.com/5214414/54727976-07a3ce80-4bcf-11e9-9260-1c66c427f852.png)

When I'm expecting to get this:

![image](https://user-images.githubusercontent.com/5214414/54728024-518cb480-4bcf-11e9-8740-d1ad3245f398.png)

The contents of the `maya.api.OpenMaya` module look like this:

```
import maya.api._OpenMaya_py2

ourdict = globals()
py2dict = maya.api._OpenMaya_py2.__dict__

for (key, val) in py2dict.iteritems():
    if key not in ourdict:
        ourdict[key] = val

```
Which makes sense as to why I'm getting the result I am. But previously the autocomplete has looked at the extraPath I've given and used the contents of that to provide autocompletion for `maya.api.OpenMaya`.

`"${env:MAYA_DEVKIT}/other/pymel/extras/completion/py"` contains stubs of all the functions found in the `maya` module and all of its submodules.

As I said, this used to work and doesn't anymore. Has something changed under the hood?

**Comment by jakebailey** [comment]
I don't think `extraPaths` does any sort of variable substitution (and I don't think `${env:SOMETHING}` is the right syntax either way). The language server just accepts what the extension gives it; no substitution done. Unless you have switched to the beta or daily download channels for the language server, then the language server wouldn't have changed either, though stable is soon to be updated.

You may also want to try out setting PYTHONPATH in a `.env` file in your workspace, as an alternative method.

If you set `"python.analysis.logLevel": "Trace"` in your VS Code settings, then you should see more info in the Python output panel.

**Comment by monkeez** [comment]
It's just strange because this was an old project I had set up this way, now that I've gone back to it it isn't working.

**Comment by monkeez** [comment]
I tested with `"python.analysis.logLevel": "Trace"` and `${env:SOMETHING}` does work correctly and is picking up my `extraPaths` correctly. It's still not using the files found there though.

If I turn the language server off and use Jedi it is working the way I want (although Jedi is quite slow).

I've now tried this on the stable and beta language servers with no luck.

**Comment by jakebailey** [comment]
@monkeez It's been a bit, and the way we handle extraPaths/PYTHONPATH has changed. Is this still an issue for you?

**Comment by jakebailey** [comment]
Closing; we can reopen this if you still have an issue with the latest version.
