### ISSUE TITLE
Autocomplete Can't List all Attributes in np.random.

### ISSUE THREAD

**Issue by Anapo14** [Microsoft/python-language-server#804]
VSCode Version: 1.32.3
Extension Version: 2019.2.5558
OS: Windows 10
Python 3.7.2 
LS Version: 0.2.28.0 
Using Conda virtual environment

Working with [this ](https://www.machinelearningplus.com/plots/matplotlib-histogram-python-examples/) example step-by-step script, and the autocomplete dropdown gives the following output: 
![image](https://user-images.githubusercontent.com/10341823/54731562-23b25c00-4b4c-11e9-9342-956d029fb4cc.png). 
Maybe this is potentially linked to #731?

**Comment by MikhailArkhipov** [comment]
Please provide complete code with imports

**Comment by Anapo14** [comment]
```
import matplotlib.pyplot as plt 
import numpy as np 


# Plot Histogram on x

x = np.random.normal(size = 1000)
plt.hist(x, bins=50)
plt.gca().set(title = "Frequency Histogram", ylabel = 'Frequency')

# Pandas script example from tutorial

import pandas as pd 
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/diamonds.csv')

x1 = df.loc[df.cut=='Ideal', 'depth']
x2 = df.loc[df.cut == 'Fair', 'depth']
x3 = df.loc[df.cut=='Good', 'depth']

kwargs = dict(alpha = 0.5, bins = 100)

plt.hist(x1, **kwargs, color='g', label='Ideal')
plt.hist(x2, **kwargs, color='b', label='Fair')
plt.hist(x3, **kwargs, color='r', label='Good')
plt.gca().set(title='Probability Histogram of Diamond Depths', ylabel='Probability')
plt.xlim(50,75)
plt.legend()
```

**Comment by MikhailArkhipov** [comment]
![image](https://user-images.githubusercontent.com/12820357/54881397-bed95900-4e0c-11e9-8e40-e57a85249b41.png)

**Comment by Anapo14** [comment]
Can confirm that I am now getting random.* attributes.

**Comment by quatsch83** [comment]
I am having this issue as well.

![image](https://user-images.githubusercontent.com/50018762/79489165-e3d8d500-7fe8-11ea-8a91-2b4ff800af78.png)

I am using Python 3.8.2 and the Microsoft Language Server.  I don't know how to tell what version, but everything seems to be up to date.

My Python Extension is at 2020.3.71659.

**Comment by autoscraper** [comment]
I have this problem as well!!

![image](https://user-images.githubusercontent.com/81045987/111887519-551cc700-89b4-11eb-866b-d01789e88fa0.png)
![image](https://user-images.githubusercontent.com/81045987/111887529-61088900-89b4-11eb-892b-330e313585bb.png)
