### ISSUE TITLE
No correct completion for df.loc

### ISSUE THREAD

**Issue by Anapo14** [microsoft/python-language-server#805]
VSCode Version: 1.32.3
Extension Version: 2019.2.5558
OS: Windows 10
Python 3.7.2
LS Version: 0.2.28.0
Using Conda virtual environment

Working with [this example tutorial](https://www.machinelearningplus.com/plots/matplotlib-histogram-python-examples/). Expected df.loc to give me a full list of options (df.loc[] was the option I was after), but I only recieved 2 as in the below figure (analysis had finished completing):

![image](https://user-images.githubusercontent.com/10341823/54731687-e4383f80-4b4c-11e9-939a-43769464690d.png)

**Comment by MikhailArkhipov** [comment]
Please provide complete example with imports. Thanks.

**Comment by Anapo14** [comment]
```
import matplotlib.pyplot as plt 
import numpy as np 


# Plot Histogram on x

x = np.random.normal(size = 1000)
plt.hist(x, bins=50)
plt.gca().set(title = "Frequency Histogram", ylabel = 'Frequency')

# Pandas tutorial example script 

import pandas as pd 
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/diamonds.csv')

x1 = df.loc[df.cut=='Ideal', 'depth']
x2 = df.loc[df.cut == 'Fair', 'depth']
x3 = df.loc[df.cut=='Good', 'depth']

kwargs = dict(alpha = 0.5, bins = 100)

plt.hist(x1, **kwargs, color='g', label='Ideal')
plt.hist(x2, **kwargs, color='b', label='Fair')
plt.hist(x3, **kwargs, color='r', label='Good')
plt.gca().set(title='Probability Histogram of Diamond Depths', ylabel='Probability')
plt.xlim(50,75)
plt.legend()
```

**Comment by Anapo14** [comment]
@Anapo14 retry this.

**Comment by MikhailArkhipov** [comment]
Folding into #981
