### ISSUE TITLE
No completions for df.reset_index()

### ISSUE THREAD

**Issue by Anapo14** [Microsoft/python-language-server#806]
VSCode Version: 1.32.3
Extension Version: 2019.2.5558
OS: Windows 10
Python 3.7.2
LS Version: 0.2.28.0
Using Conda virtual environment

Was working through this quick, easy tutorial [here](https://pythonprogramming.net/data-analysis-python-pandas-tutorial-introduction/). Was expecting df.reset_ to at the very least yield df.reset_index(), a common operation when using Pandas. However, I got the following display: 

![image](https://user-images.githubusercontent.com/10341823/54731924-329a0e00-4b4e-11e9-99ba-9922bb69a6a0.png)

**Comment by MikhailArkhipov** [comment]
Please provide complete code with imports.

**Comment by Anapo14** [comment]
```
import pandas as pd 
import datetime 
import pandas_datareader.data as web 

start = datetime.datetime(2010, 1,1)
end = datetime.datetime.now()

df = web.DataReader("MSFT", "yahoo", start, end)

df.reset_index(inplace = True )
df.set_index("Date", inplace = True)

import matplotlib.pyplot as plt
from matplotlib import style

style.use('fivethirtyeight')


df['High'].plot()

plt.legend()
plt.show()
```

**Comment by MikhailArkhipov** [comment]
![image](https://user-images.githubusercontent.com/12820357/54881288-a4eb4680-4e0b-11e9-8c20-f750dff287a0.png)

![image](https://user-images.githubusercontent.com/12820357/54881294-b16f9f00-4e0b-11e9-92ea-d203616997db.png)

Did analysis actually finished? Duplication probably should be addressed by https://github.com/microsoft/python-language-server/issues/620

**Comment by Anapo14** [comment]
Yes. I reproduced the same process this morning and i only get: 

![image](https://user-images.githubusercontent.com/10341823/54935949-9c177500-4ede-11e9-9b0f-e64fd6717f2c.png)

**Comment by Anapo14** [comment]
Figured out my issue here as well. Was accidentally using an environment in which the _pandas_datareader.data_ module wasn't detected.
