### ISSUE TITLE
Latest version of LS fails to load

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/python-language-server#809]
* `0.2.30`
* Open the `pytest` repo in VS Code
* LS fails to start

<img width="792" alt="Screen Shot 2019-03-21 at 10 19 25 AM" src="https://user-images.githubusercontent.com/1948812/54771781-36b44300-4bc3-11e9-916e-27b49e50b09d.png">

**Comment by jakebailey** [comment]
Is this with my PR to the extension? The language server is showing nothing in the search paths, which isn't good.

**Comment by jakebailey** [comment]
Not that the PR causes this; the search path logging happens after we call our script to get the search paths.

**Comment by jakebailey** [comment]
So I think what's happening is that the interpreter path specified doesn't exist. There's a log message missing which is printed after the interpreter is checked which is not in your output above.

**Comment by DonJayamanne** [comment]
Oops, agreed no interpreter was selected (in fact a non-existent interpreter was selected), & the extension does display a warning message about that & i ignored it.

**Comment by MikhailArkhipov** [comment]
Should now show clear error
