### ISSUE TITLE
Dict literal considered a "field"

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/python-language-server#81]
Microsoft/vscode-python#2535

The Outline view in VS Code flags the following:
```python
a = {}
```
as a "field" which I assume represents an attribute and not a dictionary.

**Comment by MikhailArkhipov** [comment]
`{ }` means object/unknown

**Comment by MikhailArkhipov** [comment]
Changed dictionary to instance

**Comment by brettcannon** [comment]
Is that what lists and tuples are specified as?

**Comment by MikhailArkhipov** [comment]
There are no python-specific things in VS Code so

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/python-language-server/issues/87

**Comment by brettcannon** [comment]
Great! I was just checking for consistency is all across the built-in types.
