### ISSUE TITLE
Focus is constantly switched to the Output window

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/python-language-server#810]
@luabud commented on [Wed Mar 20 2019](https://github.com/Microsoft/vscode-python/issues/4868)

Microsoft Python Language Server version: 0.2.29.0
Python extension version: 2019.3.5917-rc

If you watch the GIF below, you'll see the output window opens even before the package finishes installing in the terminal:

![LanguageServerOutputBug](https://user-images.githubusercontent.com/45497113/54725159-484a0c00-4b2b-11e9-95b7-dd6939b21c52.gif)

This is happening quite constantly and it can be very annoying when you need to use the terminal

**Comment by jakebailey** [comment]
The exception is a bug which should be filed separately, but VS Code switching panels if we print something that's an error doesn't seem like something we have any control over (and probably want to make sure the error becomes visible).

**Comment by DonJayamanne** [comment]
If thats the case, please do not flag it as an error or similar.
Please file an issue with VSC, as from a users perspective we don't want the panel stealing focus from the user (when they're in the terminal).

**Comment by jakebailey** [comment]
I don't understand; this is an error in the language server that we want to know about and fix. No exceptions should be thrown unless there is something wrong; silently hiding them does not seem like a good idea.

**Comment by luabud** [comment]
I opened #811 for the exception

**Comment by DonJayamanne** [comment]
> this is an error in the language server that we want to know about and fix. 

I think we still need to pay attention to the over all `User Experience`

> No exceptions should be thrown unless there is something wrong; silently hiding them does not seem like a good idea.

* Over all, this is a PM decision
* Here's another problem:
	* Users open terminal, and pip install a package
	* Output panel appears and steals focus
	* User is confused and files a bug
	* Now they have to live with this poor UX for weeks til the issue is resolved.

> silently hiding them does not seem like a good idea.

We might want to re-evaluate how errors are surfaced to the user, in a non-intrusive way. But that's my opinion.

**Comment by jakebailey** [comment]
I understand, but also know that we might not be able to control the level of that message. This is an exception which gets caught by the JSON-RPC library we use, which sends a JSON-RPC error response for the request being served, which the vscode-languageserver client then does something with. We might be able to modify the error code (similarly to how we modify the error body to work around other vscode-languageserver shortcomings), but we may be breaking the JSON-RPC specification by doing so.

**Comment by MikhailArkhipov** [comment]
`Output panel appears and steals focus` sounds like VS Code UI issue. Big VS has flag that controls focus transfer so output does not auto-steal it.

**Comment by gramster** [comment]
Is this something we can handle on the extension side? Throwing an exception seems reasonable on the LS side, if it is a bug; the LS does not control the UX (and shouldn't be expected to - the extension has a dependency on the LS, not the other way around).

**Comment by DonJayamanne** [comment]
Unfortunately we're not displaying this, VSC is displaying this.
Will file an issue upstream with VS Code.

**Comment by DonJayamanne** [comment]
Ok, found that this behavior can be controlled from within the extension. Apologies for the hassell.
