### ISSUE TITLE
Unable to determine URI from file path during indexing

### ISSUE THREAD

**Issue by luabud** [microsoft/python-language-server#811]
![image](https://user-images.githubusercontent.com/45497113/54773387-b55eaf80-4bc6-11e9-9b91-777a89b16ef9.png)
![image](https://user-images.githubusercontent.com/45497113/54773505-f656c400-4bc6-11e9-9f9d-0803de877900.png)

**Comment by jakebailey** [comment]
@luabud 	There's a new version in the beta and daily channels which should modify the way this exception is handled and provide more context for us to fix the problem. I'd appreciate it if you could retest.

**Comment by MikhailArkhipov** [comment]
Been a while, closing.
