### ISSUE TITLE
[Question] Locally disabling warnings (in Visual Studio Code)

### ISSUE THREAD

**Issue by jfthuong** [Microsoft/python-language-server#820]
I have recently installed Python Language Server in Visual Studio Code.

I sometimes have some warnings that I want to locally disabled

For example, le'ts assume I have the following code:

    import org.sikuli.script.SikulixForJython
    from sikuli.Sikuli import *
    from guide import *

It is normally run from Sikulix, which uses Jython libraries. Since my favorite editor cannot load this module, it would raise a warning:  
`unresolved import 'org.sikuli.script.SikulixForJython'      Python(unresolved-import)`

With `pylint`, that would be something like:
```python
# pylint: disable=unresolved-import
```

How to do something similar with Python Language Server?

Thanks

**PS**: I know that I can disable the warnings via the settings (`"python.analysis.disabled": ["too-many-function-arguments", "parameter-missing"]`) but I am looking for a local way to disable a warning (for example in a class, function, or conditional block).

**Comment by jakebailey** [comment]
There's no such way, no; that's #264.

If you believe that the language server should be able to detect the module you're importing, you may want to file a bug on it, and also try out the beta build if you haven't already:

```
"python.analysis.downloadChannel": "beta"
```
