### ISSUE TITLE
Failed to debug in Docker

### ISSUE THREAD

**Issue by xiaofeng0123** [Microsoft/python-language-server#824]
Visual Studio Code - Insiders: 1.33.0-insider
python-insider: 2019.4.6071-alpha
python version: Python 3.7.3 64bit
Make sure docker installed
Repro steps:
1.Git clone https://github.com/qubitron/pydemo
2.Open Anaconda Prompt window
3.Cd pydemo
4.Run py -3 setup.py
5.Open "stackoverflow-flask" folder and open "app->main.py"
6.Set a breakpoint in line 6
7.Switch to "dockerized" branch
![image](https://user-images.githubusercontent.com/41426540/54988470-77f88880-4ff1-11e9-849e-08cf1ce56525.png)
8.Change "DEBUG" configuration to "Python: Run in Docker"
![image](https://user-images.githubusercontent.com/41426540/54988487-83e44a80-4ff1-11e9-9652-50ec06484366.png)
9.Start to debug
Expect Result:
Debug in Docker successfully
Actual Result:
Invalid link shown
![image](https://user-images.githubusercontent.com/41426540/54988642-d887c580-4ff1-11e9-8b33-711bce70e001.png)

**Comment by MikhailArkhipov** [comment]
LS does not have any debugger related functionality. This should go either to https://github.com/Microsoft/vscode-python or https://github.com/Microsoft/ptvsd

**Comment by gramster** [comment]
Issue moved to [Microsoft/ptvsd #1264](https://github.com/Microsoft/ptvsd/issues/1264) via [**ZenHub**](https://www.zenhub.com/)
