### ISSUE TITLE
Always analyzing in background on start up

### ISSUE THREAD

**Issue by marpala** [Microsoft/python-language-server#848]
Is the language server supposed to analyze in background for several minutes every time I open VS Code? 
Every time I open a project it starts analyzing thousands of items for several minutes. I have only recently noticed this behavior and was wondering if it was normal.

![image](https://user-images.githubusercontent.com/439204/55260769-910b6e80-5269-11e9-919d-780c2371dab4.png)

**Comment by jakebailey** [comment]
It depends heavily on what you have imported and what is installed in your environment. The old version of the language server likely also was running in the background, the difference is that the new language server reports progress (so this is more visible). See also #832 (particularly https://github.com/Microsoft/python-language-server/issues/832#issuecomment-477688703).

Regarding "every time I open VS Code", yes, the LS does not persist its analysis (that's #472).

**Comment by jakebailey** [comment]
There are some other performance bugs we're working on as well, particularly one that for some libraries makes the LS enter essentially a busy loop for a good amount of time. But, a few minutes isn't unexpected at this point.

**Comment by MikhailArkhipov** [comment]
Analysis at startup is expected, there is no persistent database or anything along these lines yet.
