### ISSUE TITLE
Language Server does not work with PYTHONPATH=./

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/python-language-server#849]
@DonJayamanne commented on [Sun Mar 31 2019](https://github.com/Microsoft/vscode-python/issues/5036)

* Open the [behave](https://github.com/behave/behave) repo
* Use python 3.7 
* OS Mac
* Enable the following in `settings.json`
```js
	"python.analysis.downloadChannel": "daily",
	"python.analysis.logLevel": "Trace",
```
* Add a `.env` file with the following contents:
```
PYTHONPATH=./
```

## **Delete the above `.env` file then it works**

**None of the Language Server functionality works**

<img width="1127" alt="Screen Shot 2019-03-31 at 7 32 02 PM" src="https://user-images.githubusercontent.com/1948812/55300341-d8216d00-53eb-11e9-95ff-a3b277d1fe25.png">

**Comment by vivlim** [comment]
I encountered this with a project that had two adjacent delimiters in PYTHONPATH, i.e. `PYTHONPATH=::`.
There was no clear way to tell what was happening, all I could observe was that I had a cpu core pinned by the language server & no completions were working. That core continues to be 100% utilized until the vscode window closes. I've observed it running for at least 20 minutes of cpu time, though it's probably run for longer.

(I ended up having adjacent delimiters because I was trying have a single PYTHONPATH that would work across windows & linux which both use different os.pathsep.)

**Comment by jakebailey** [comment]
@vivlim Did you also encounter this on Mac/Linux?

**Comment by vivlimmsft** [comment]
@jakebailey yes, I saw this on an Ubuntu 18.04 machine

**Comment by jakebailey** [comment]
This should be fixed in 0.2.55+, if you'd like to retest.

**Comment by vivlimmsft** [comment]
Sure, I'll try it tonight. Thanks!!

**Comment by vivlim** [comment]
@jakebailey On 0.2.58, the language server no longer pins a cpu core at 100% when `PYTHONPATH=::`, which is a better, but it still seems to be stuck initializing. I do not get any completions or any analysis status in the status bar.

```
Starting Microsoft Python language server.

Linter 'pep8' is not installed. Please install it or select another linter".
Error: Module 'pep8' not installed.

Linter 'pylint' is not installed. Please install it or select another linter".
Error: Module 'pylint' not installed.
[Info  - 6:20:32 p.m.] GetCurrentSearchPaths /home/vivlim/.local/share/virtualenvs/py-test-wKGYf3-f/bin/python 
[Info  - 6:20:32 p.m.] Python search paths:
[Info  - 6:20:32 p.m.]     /home/vivlim/.local/share/virtualenvs/py-test-wKGYf3-f/lib/python3.6
[Info  - 6:20:32 p.m.]     /home/vivlim/.local/share/virtualenvs/py-test-wKGYf3-f/lib/python3.6/lib-dynload
[Info  - 6:20:32 p.m.]     /usr/lib/python3.6
[Info  - 6:20:32 p.m.]     /home/vivlim/.local/share/virtualenvs/py-test-wKGYf3-f/lib/python3.6/site-packages
[Info  - 6:20:32 p.m.] Configuration search paths:
[Info  - 6:20:32 p.m.]     /home/vivlim
[Info  - 6:20:32 p.m.]     /home/vivlim/.local/share/virtualenvs/py-test-wKGYf3-f/lib/python36.zip
[Info  - 6:20:32 p.m.]     /home/vivlim/.local/share/virtualenvs/py-test-wKGYf3-f/lib/python3.6
[Info  - 6:20:32 p.m.]     /home/vivlim/.local/share/virtualenvs/py-test-wKGYf3-f/lib/python3.6/lib-dynload
[Info  - 6:20:32 p.m.]     /usr/lib/python3.6
[Info  - 6:20:32 p.m.]     /home/vivlim/.local/share/virtualenvs/py-test-wKGYf3-f/lib/python3.6/site-packages
[Info  - 6:20:32 p.m.]     /home/vivlim/.local/share/virtualenvs/py-test-wKGYf3-f/bin
<no output below this line, including the LS version number.>
```

If I comment out the line in .env that sets `PYTHONPATH`, it can initialize normally and I get completions.

**Comment by jakebailey** [comment]
Can you show what the output for "configuration search paths" is with and without that variable set? Your home directory probably shouldn't be showing up there.

**Comment by vivlim** [comment]
Hm, I rebooted my machine and it no longer repros. I'm not sure what changed, the installed LS version is still 0.2.58.0 and I was getting a consistent repro before whenever I set `PYTHONPATH=::` in addition to it working consistently when I *didn't*.

Regarding the configuration search paths, I think they contain my home dir because I'm using pipenv to manage virtual environments. Pipenv places them in ~/.local/share/virtualenvs.
```
[Info  - 9:51:42 p.m.] GetCurrentSearchPaths /home/vivlim/.local/share/virtualenvs/py-test-wKGYf3-f/bin/python 
[Info  - 9:51:42 p.m.] Python search paths:
[Info  - 9:51:42 p.m.]     /home/vivlim/.local/share/virtualenvs/py-test-wKGYf3-f/lib/python3.6
[Info  - 9:51:42 p.m.]     /home/vivlim/.local/share/virtualenvs/py-test-wKGYf3-f/lib/python3.6/lib-dynload
[Info  - 9:51:42 p.m.]     /usr/lib/python3.6
[Info  - 9:51:42 p.m.]     /home/vivlim/.local/share/virtualenvs/py-test-wKGYf3-f/lib/python3.6/site-packages
[Info  - 9:51:42 p.m.] Configuration search paths:
[Info  - 9:51:42 p.m.]     /home/vivlim/.local/share/virtualenvs/py-test-wKGYf3-f/lib/python36.zip
[Info  - 9:51:42 p.m.]     /home/vivlim/.local/share/virtualenvs/py-test-wKGYf3-f/lib/python3.6
[Info  - 9:51:42 p.m.]     /home/vivlim/.local/share/virtualenvs/py-test-wKGYf3-f/lib/python3.6/lib-dynload
[Info  - 9:51:42 p.m.]     /usr/lib/python3.6
[Info  - 9:51:42 p.m.]     /home/vivlim/.local/share/virtualenvs/py-test-wKGYf3-f/lib/python3.6/site-packages
[Info  - 9:51:42 p.m.]     /home/vivlim/.local/share/virtualenvs/py-test-wKGYf3-f/bin
[Info  - 9:51:43 p.m.] Microsoft Python Language Server version 0.2.58.0
[Info  - 9:51:43 p.m.] Initializing for /home/vivlim/.local/share/virtualenvs/py-test-wKGYf3-f/bin/python
```

**Comment by jakebailey** [comment]
To be clear, the path I'm saying probably shouldn't be there is `/home/vivlim`, stuff that's in directories in the home are alright, but the actual `$HOME` shouldn't be a place where we're searching for Python code (unless that were explicitly stated, as weird as it would be).

**Comment by chdsbd** [comment]
I just ran into this issue. Before an update that happened today, PYTHONPATH worked. Now with `Microsoft Python Language Server version 0.2.59.0` it seems to be ignored.

I don't know what my version language server version was before the update today.

**Comment by jakebailey** [comment]
Can you be more specific? What was working before that wasn't? If you set `"python.analysis.logLevel": "Trace"` and reload, do you see the paths you specified appear as "configuration search paths"?

**Comment by chdsbd** [comment]
The paths that I want do appear as "configuration search paths", so I'm not sure what's going on. I'll try to make a repo that exhibits this behavior.
