### ISSUE TITLE
Getting EOF Error in string/list slice inside f-string

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/python-language-server#854]
@Veinz commented on [Sun Mar 31 2019](https://github.com/Microsoft/vscode-python/issues/5040)

## Environment data

Version: 1.32.3 (system setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
OS: Windows_NT x64 10.0.17763
Python: Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32
Python Ext: 2019.3.6215 (28 March 2019)

## Expected behaviour

No error

## Actual behaviour

unexpected EOF while parsing

## Steps to reproduce:
1. Create string/list slice inside f-string
![Screenshot (12)](https://user-images.githubusercontent.com/17838613/55303197-098f4c80-546f-11e9-92f8-ee1a8dd0507d.png)

![Screenshot (13)](https://user-images.githubusercontent.com/17838613/55303180-e2d11600-546e-11e9-91d7-e0a88c9a1d4e.png)

**Comment by jakebailey** [comment]
@brianbok Seems like the way we're handling colons isn't right. Only colons at the top level should be used to split.

```
Python 3.8.0a3 (tags/v3.8.0a3:9a448855b5, Mar 25 2019, 23:22:01) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> x = [1, 2, 3]
>>> f"{x[1:]}"
'[2, 3]'
```
