### ISSUE TITLE
Imported variables should not be linted as undefined

### ISSUE THREAD

**Issue by jakebailey** [Microsoft/python-language-server#856]
![image](https://user-images.githubusercontent.com/5341706/55351278-ba4b1b00-5472-11e9-859f-8e6f385263ae.png)

`.x` doesn't exist, so we report an unresolved import, but `cool`'s uses should not be marked as undefined because it's still "declared" at the import.

**Comment by MikhailArkhipov** [comment]
#955, in favor of user-reported issue.
