### ISSUE TITLE
"datetime - datetime" is timedelta, not datetime

### ISSUE THREAD

**Issue by ericsnowcurrently** [Microsoft/python-language-server#860]
(from https://github.com/Microsoft/vscode-python/issues/4983)

The result of subtracting one datetime.datetime from another is a datetime.timedelta.  However, the language server is inferring that it is actually a datetime.

```python
from datetime import datetime
date1 = datetime.strptime('2019/3/12', '%Y/%m/%d')
date2 = datetime.strptime('2019/3/19', '%Y/%m/%d')
diffDate = date2-date1  # Intellisense shows this as a datetime.
```

I'm guessing that the default inference for subtraction is the same type as the two arguments.  FYI, there may be other types beside datetime.datetime where that does not hold true.

**Comment by jakebailey** [comment]
Yup, we need to defer binary operations to calls as a backup. Typeshed has these hints for us:

https://github.com/python/typeshed/blob/f11d061849c89a8e28809e52b71a80f0e329cb7d/stdlib/2and3/datetime.pyi#L75

**Comment by forthnight** [comment]
Is this issue closed and fixed? As a newbie with github and python, I still find that "datetime - datetime" is a datetime object with no ".days" in Intellisense as the original problem (issue 4983) stated. I am running python 3.8.2 and VS Code 1.44.2 with python extension version 2020.4.76186.

**Comment by jakebailey** [comment]
As far as I know, this should work fine. We have this specific case in our test suite as it's a core example of custom operators. Consider filing a bug with the info the template requests.
