### ISSUE TITLE
wxWidgets missing completion

### ISSUE THREAD

**Issue by gramster** [microsoft/python-language-server#870]
@CoderJason123 commented on [Tue Apr 02 2019](https://github.com/Microsoft/vscode-python/issues/5080)

I have followed the guidance in the article below. The part of Intellisense that is not working with Python is the wxWidgets library. I have added the path directly to the wx folder under site packages. I have also tried at the root of site packages.

To be honest, it seems to work intermittently, which is very odd, and only on certain methods.

Any other ideas that I could try? I am on a Mac OS Mojave with the 1.32.3 of VS Code. Thank you kindly!

https://stackoverflow.com/questions/50389852/visual-studio-code-intellisense-not-working

**Comment by jakebailey** [comment]
@CoderJason123 Is the import resolved, or is it just empty and not providing any completion?

The other thing to try would be a `.env` file with PYTHONPATH set, but things in site-packages should be appearing without any special configuration.

**Comment by CoderJason123** [comment]
For the record -- I tested this today on windows, and it worked just like you said, without any special consideration.  On a Mac, also, it is very slow to pop up.  But the bigger issue is that while it does seem to "resolve" the namespace, many of the methods to not show any IntelliSense on a Mac.

**Comment by jakebailey** [comment]
@CoderJason123 	The LS has had quite a number of updates in the meantime, including some fixes to imports which may have affected this. Do you have any issues in the current LS? If so, could you provide some examples of completions that don't appear?

**Comment by CoderJason123** [comment]
It's been a few months since I looked at this, and I think the last result I had was that it was working on the latest code.  thank you.

**Comment by jakebailey** [comment]
Thanks for the update!
