### ISSUE TITLE
Infinite analyzing of airflow

### ISSUE THREAD

**Issue by Yanpas** [Microsoft/python-language-server#880]
I'm using apache airflow and beta version of a server takes infinite time to analyze it. (at least one night)
![image](https://user-images.githubusercontent.com/7345761/55545862-cf27e880-56d6-11e9-8ca2-34d470a93887.png)

`AIRFLOW_GPL_UNIDECODE=1 sudo -E pip3 install apache-airflow`

**Comment by AlexanderSher** [comment]
@Yanpas , can you please enable full logging ("python.analysis.logLevel": "Trace"), copy log from output and attach it as a file to this bug?

**Comment by Yanpas** [comment]
Hm. I've disabled and enabled python ls (python.jediEnabled), it was redownloaded and seems like this version doesn't stuck.

> Analysis of PyQt5.QtWidgets(Compiled) completed in 79379,6379 ms

Here is a log: https://gist.github.com/Yanpas/adc8a7bd00df8e6ae850d6a5bdfc9524

**Comment by AlexanderSher** [comment]
Thanks.

Yes, `PyQt5.QtWidgets` is a huge 5MB module, so its analysis is slow.

**Comment by Yanpas** [comment]
I do not import Qt anywhere, don't know why is it analyzed

**Comment by jakebailey** [comment]
@Yanpas See my comment here: https://github.com/Microsoft/python-language-server/issues/832#issuecomment-477688703

**Comment by MikhailArkhipov** [comment]
But library you do import may import other libraries which may end up importing Qt.
