### ISSUE TITLE
Incorrect undefined variable on return statement

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/python-language-server#882]
@jamesstidard commented on [Wed Apr 03 2019](https://github.com/Microsoft/vscode-python/issues/5105)

## Environment data

- VS Code version: Version 1.32.3 (1.32.3)
- Extension version (available under the Extensions sidebar): Python Version 1.32.3 (1.32.3)
- OS and version: macOS 10.14.4
- Python version (& distribution if applicable, e.g. Anaconda): N/A
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A 
- Relevant/affected Python packages and their versions: N/A

## Expected behaviour

No problem reported

## Actual behaviour

Undefined variable problem reported

## Steps to reproduce:
```python
def _():
    return [int(x) for x in range(5)]
```

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
Starting Microsoft Python language server.
[Info  - 10:23:15 PM] GetCurrentSearchPaths /usr/local/bin/python3 
[Info  - 10:23:15 PM] Python search paths:
[Info  - 10:23:15 PM]     /private/var/folders/5v/x8dcvr4n2wl0dlq2pxd35y2w0000gn/T/4p2tms4o.xpz
[Info  - 10:23:15 PM]     /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7
[Info  - 10:23:15 PM]     /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload
[Info  - 10:23:15 PM]     /usr/local/lib/python3.7/site-packages
[Info  - 10:23:15 PM] Configuration search paths:
[Info  - 10:23:15 PM]     /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python37.zip
[Info  - 10:23:15 PM]     /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7
[Info  - 10:23:15 PM]     /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload
[Info  - 10:23:15 PM]     /usr/local/lib/python3.7/site-packages
[Info  - 10:23:15 PM]     /usr/local/bin
[Info  - 10:23:15 PM] Microsoft Python Language Server version 0.2.42.0
[Info  - 10:23:16 PM] Initializing for /usr/local/bin/python3
```   

---

@DonJayamanne commented on [Wed Apr 03 2019](https://github.com/Microsoft/vscode-python/issues/5105#issuecomment-479669692)

Where is this `Undefined variable problem reported` reported.
Please provide a screen sample.

---

@jamesstidard commented on [Wed Apr 03 2019](https://github.com/Microsoft/vscode-python/issues/5105#issuecomment-479683830)

@DonJayamanne Oh yeah :). I did take a screenshot and forgot to attach it.

<img width="641" alt="Screenshot 2019-04-03 at 10 00 37 pm" src="https://user-images.githubusercontent.com/1797906/55517769-75d5a000-5669-11e9-916e-80eddbdc04c0.png">
<img width="378" alt="Screenshot 2019-04-03 at 10 00 29 pm" src="https://user-images.githubusercontent.com/1797906/55517770-75d5a000-5669-11e9-835a-0b08bde9eda0.png">

---

@dvdma commented on [Thu Apr 04 2019](https://github.com/Microsoft/vscode-python/issues/5105#issuecomment-479866329)

I have the same issue with:

- VS Code version: 1.30.0
- ms-python.python version: 2019.1.0
- OS: Linux

The issue comes up every time there is some code in the form of:
```python
def f():
  return [g(idx) for idx in some_list]
```

**Comment by jakebailey** [comment]
This is #830.
