### ISSUE TITLE
Python Language Server Logging Information Not Written To Output

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/python-language-server#883]
@mobiusklein commented on [Thu Apr 04 2019](https://github.com/Microsoft/vscode-python/issues/5112)

## Environment data

- VS Code version: 1.32
- Extension version: 2019.3.6352
- OS and version: Windows 10 Pro 1809 
- Python version (& distribution if applicable, e.g. Anaconda): Anaconda Python 2.7/3.68
- Type of virtual environment used: conda

## Expected behaviour

When the Python Language Server starts up or begins an analysis, if the log level is set to `Trace`, incremental progress information will be displayed as it analyzes files in the `Output` tab in the terminal panel.

When vscode-python lints a file, it will indicate that it ran the linter in the `Output` tab in the terminal panel.

## Actual behaviour

No content is written to the `Output` tab. 

## Steps to Reproduce

1. Open a file with the extension `.py` with vscode
2. Wait for extension to active, monitoring both the status bar and the `Output` tab

**Comment by MikhailArkhipov** [comment]
Not sure what is expected. By default tracing is not produced because it slows down analysis quite a bit (~20%).

**Comment by mobiusklein** [comment]
When the log level is configured to be `Trace`, I thought that would enable the trace messages. Is there another configuration I need to modify to get that information?

**Comment by jakebailey** [comment]
If you set `"python.analysis.logLevel": "Trace"`, then you should be getting lots of stuff into the output panel.

**Comment by mobiusklein** [comment]
The `"python.analysis.logLevel"` key is set to `"Trace"`, and still the output is empty.

**Comment by jakebailey** [comment]
You are in the Output panel with Python selected in the dropdown at the right, correct?

**Comment by jakebailey** [comment]
i.e.:

![image](https://user-images.githubusercontent.com/5341706/55585523-b4a43e00-56db-11e9-95f8-8283b51419b3.png)

**Comment by mobiusklein** [comment]
Apparently not, thank you. I was seeing it in what I thought was the default tab for some period of time. I do see the tracing statements, and the linting banner, though no linting output is shown below the banner nor problems published, even when there are undefined top level symbols.

I'll try to find an explanation for that separately, so this can be closed.

**Comment by MichaelSchmidt82** [comment]
But I'm still seeing this on VS Code 1.63.2

the test:
```
def test_foo(self):
    LOGGER.critical('critical')
    LOGGER.error('error')
    LOGGER.warning('warning')
    LOGGER.info('info')
    LOGGER.debug('debug')
    LOGGER.fatal('fatal')
```
and the setting:
```
"python.analysis.logLevel": "Trace",
```

and the output:
![image](https://user-images.githubusercontent.com/5676834/152250533-682e6e29-73c0-4aa2-8601-14ae3b492589.png)

???
