### ISSUE TITLE
Heavy CPU usage

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/python-language-server#891]
@ctivanovich commented on [Fri Apr 05 2019](https://github.com/Microsoft/vscode-python/issues/5124)

Following the advice from this thread which was closed prematurely [https://github.com/Microsoft/vscode-python/issues/2149](https://github.com/Microsoft/vscode-python/issues/2149), I switched to the Microsoft Python language server, but the same explosion in CPU/memory use I noted before disabling both Jedi and Pylint continued unabated using this server. My .py file is about 1200 lines of code, but it's the only one open and being linted/checked. This doesn't even consider what affect attempting to tab-complete or inspect a module might have.
![Screenshot (32)](https://user-images.githubusercontent.com/7261199/55609918-6e6edd80-57b4-11e9-803b-49519891ac0c.png).

**Comment by MikhailArkhipov** [comment]
@ctivanovich - length of your code is, it is typically libraries you import that can be very large. Please specify which packages you import, what is the version of the LS (displayed at startup) and how long did you wait. Thanks

**Comment by MikhailArkhipov** [comment]
@ctivanovich - has it improved since? Thanks

**Comment by ctivanovich** [comment]
It seems, at least for now, the language server has calmed down, thanks.
