### ISSUE TITLE
Unresolved builtin libraries.

### ISSUE THREAD

**Issue by CMLL** [Microsoft/python-language-server#892]
Sometimes the language server marks builtin libraries as unresolved, stuff like datetime.datetime, or sys, and when I see ones it doesn't marks all of the builtin ones as unresolved. In the following example is marking datetime and sys but os is not.

![image](https://user-images.githubusercontent.com/3720126/55652759-059b5b80-57dc-11e9-90f9-78f773dff0ae.png)

Usually a reload window fixes the issue, I'm assuming 'cause it restarts the language server. I'm using the extra paths setting to have the language server scan some libraries I have setup. Using the beta version of the language server 0.2.43.

It doesn't happen much often, but I've seen it some times. I think the longer the language server has spent opened the higher the chance of it happening, but I have no hard evidence to back that statement.

Otherwise thanks a bunch for your hard work, the latest beta version is behaving pretty damn smooth for me.

**Comment by jakebailey** [comment]
I believe this is the same as #726.

**Comment by CMLL** [comment]
Yep, seems to be the same. I'll close it down. Thanks.
