### ISSUE TITLE
Save analysis graph for the working directory

### ISSUE THREAD

**Issue by AlexanderSher** [microsoft/python-language-server#894]

**Comment by DonJayamanne** [comment]
See here [ExtensionContext.storagePath](https://code.visualstudio.com/api/extension-capabilities/common-capabilities#data-storage)

Not sure whether this information is available to the LS, if not this can be easily passed from the extension to LS.

**Comment by MikhailArkhipov** [comment]
There are 

a) Data per project. We want something that is available in all clients. So we should have a setting and if it is empty we can try and save per-project in, say, `.pylsCache` folder.
b) Data that is common such as persisted stubs for libraries that can be used in multiple projects. .NET Core `LocalAppData` looks appropriate. Also should be a setting that user can adjust.

Third setting is to disable caching completely. Useful when analysis is used for type checks in command-line or CI scenarios.

**Comment by jakebailey** [comment]
Regarding B, it'd be best to do:

- `%LocalAppData%` on Windows
- `$HOME/Library/Caches` on macOS
- `$XDG_CACHE_HOME` or `$HOME/.cache` on Linux

LocalAppData points to `$HOME/.local/` something on Linux which isn't a place applications typically put stuff; the XDG standard is the way to go.

Generally deprecating the "database path" thing in favor of a real cache directory (with config) would be best, but that's another issue entirely.

**Comment by MikhailArkhipov** [comment]
I don't think we need this anymore since we are going to persist the end analysis rather than intermediate stage data.
