### ISSUE TITLE
Python rename broken with new Language Server

### ISSUE THREAD

**Issue by h-bex** [Microsoft/python-language-server#896]
**Product and Version** [VSCode]: 1.33.0
**OS Version** [Windows]: Windows 10 (Windows_NT x64 10.0.17763)
**Target Platform or Language**: Python
**Installed Extensions**: Python 2019.3.6352; Vim 1.3.0; IntelliCode

**Steps to Reproduce / Scenario:**

1. Set `"python.jediEnabled": true`
2. Open an empty folder an enter a new python file (see Attachement MyTestFile.py)
3. Try to rename function `function_to_be_renamed` to `renamed_function` (set cursor to function name and press `F2` enter new name and press `Enter `--> Rename works as specified.
4. Set `"python.jediEnabled": false`; Reload the folder.  Do the same steps as in Step 3: --> Nothing happens **BUG**
5. Restart VSCode and repeat Step 3: --> Nothing happens **BUG**
6. Set `"python.jediEnabled": true` again (NOTE: NO RELOAD REQUESTED) and repeat Step 3: --> Nothing happens **BUG*
7. Reload Window (`Developer: Reload Window`) and Repeat Step 3: --> rename works as specified.

**NOTE:** I first detected this bug with the **Intellicode** Extension ([https://github.com/MicrosoftDocs/intellicode/issues/84](https://github.com/MicrosoftDocs/intellicode/issues/84)). This extension automatically sets `"python.jediEnabled": false`. This setting is a requirement of this extension.

[MyTestFile.py.txt](https://github.com/Microsoft/python-language-server/files/3052086/MyTestFile.py.txt)
[IntelliCode-Output.txt](https://github.com/Microsoft/python-language-server/files/3052088/IntelliCode-Output.txt)
Python output window:
`Starting Microsoft Python language server.
[Info  - 00:26:50] GetCurrentSearchPaths C:\Program Files\Python37\python.exe 
[Info  - 00:26:50] Python search paths:
[Info  - 00:26:50]     c:\program files\python37\dlls
[Info  - 00:26:50]     c:\program files\python37\lib
[Info  - 00:26:50]     c:\program files\python37
[Info  - 00:26:50]     c:\users\h-bex\appdata\roaming\python\python37\site-packages
[Info  - 00:26:50]     c:\program files\python37\lib\site-packages
[Info  - 00:26:50] Configuration search paths:
[Info  - 00:26:50]     C:\Program Files\Python37\python37.zip
[Info  - 00:26:50]     C:\Program Files\Python37\DLLs
[Info  - 00:26:50]     C:\Program Files\Python37\lib
[Info  - 00:26:50]     C:\Program Files\Python37
[Info  - 00:26:50]     C:\Users\h-bex\AppData\Roaming\Python\Python37\site-packages
[Info  - 00:26:50]     C:\Program Files\Python37\lib\site-packages
[Info  - 00:26:50]     .
[Info  - 00:26:50]     C:\Program Files\Python37
[Info  - 00:26:50] Microsoft Python Language Server version 0.2.44.0
[Info  - 00:26:50] Initializing for C:\Program Files\Python37\python.exe
##########Linting Output - pylint##########

--------------------------------------------------------------------

Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
`

**Comment by MikhailArkhipov** [comment]
Rename is not yet implemented in the new code base. This is reflected in known issues for the LS and the extension. The implementation is coming soon. Please see

https://github.com/Microsoft/python-language-server/issues/699
https://github.com/Microsoft/python-language-server/issues/577
https://github.com/Microsoft/python-language-server/pull/819

Thanks
