### ISSUE TITLE
Add option to limit transitive dependency analysis

### ISSUE THREAD

**Issue by gramster** [microsoft/python-language-server#898]
I can see at least two useful limits:
- skip third party imports
- skip transitive third party imports

**Comment by qubitron** [comment]
The ability to exclude specific packages may be helpful as well as a workaround if future problems arise

**Comment by MikhailArkhipov** [comment]
Since we now have depth setting it is doable, but per @AlexanderSher typically graph is much wider than deeper so depth limit may or may not help much.

**Comment by MikhailArkhipov** [comment]
Probably not very pressing at the moment after all the major work. Removing from epic, but leaving open for consideration.

**Comment by MikhailArkhipov** [comment]
Closing in favor of #472
