### ISSUE TITLE
Language Server errror:  Request textDocument/definition failed.

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/python-language-server#899]
@derekwallace commented on [Sun Apr 07 2019](https://github.com/Microsoft/vscode-python/issues/5153)

VSCode 1.33.0
Win 10
Python 3.7.2 

Language server generataing errors in console.
The file is in the Open Editors.
If i click on the file:///p:/perforce_Playground/derekw_de02-1777_rce_dev/tools/crp/bin/crp.py
it jumps to the file in the

[Error - 07:13:17] Unable to find document file:///p:/perforce_Playground/derekw_de02-1777_rce_dev/tools/crp/bin/crp.py
[Error - 07:13:17] Request textDocument/definition failed.
  Message: Object reference not set to an instance of an object.
  Code: -32000 
   at Microsoft.Python.LanguageServer.Sources.DefinitionSource.FindDefinition(IDocumentAnalysis analysis, SourceLocation location)
   at Microsoft.Python.LanguageServer.Implementation.Server.GotoDefinition(TextDocumentPositionParams params, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.GotoDefinition(JToken token, CancellationToken cancellationToken)
[Error - 07:13:17] Unable to find document file:///p:/perforce_Playground/derekw_de02-1777_rce_dev/tools/crp/bin/crp.py
[Error - 07:13:17] Request textDocument/definition failed.
  Message: Object reference not set to an instance of an object.
  Code: -32000 
   at Microsoft.Python.LanguageServer.Sources.DefinitionSource.FindDefinition(IDocumentAnalysis analysis, SourceLocation location)
   at Microsoft.Python.LanguageServer.Implementation.Server.GotoDefinition(TextDocumentPositionParams params, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.GotoDefinition(JToken token, CancellationToken cancellationToken)
[Error - 07:13:18] Unable to find document file:///p:/perforce_Playground/derekw_de02-1777_rce_dev/tools/crp/bin/crp.py
[Error - 07:13:58] Unable to find document file:///p:/perforce_Playground/derekw_de02-1777_rce_dev/tools/crp/bin/crp.py
[Error - 07:14:02] Unable to find document file:///p:/perforce_Playground/derekw_de02-1777_rce_dev/tools/crp/bin/crp.py
[Error - 07:21:51] Unable to find document file:///p:/perforce_Playground/derekw_de02-1777_rce_dev/tools/crp/bin/crp.py
[Error - 07:21:54] Unable to find document file:///p:/perforce_Playground/derekw_de02-1777_rce_dev/tools/crp/bin/crp.py
[Error - 07:21:55] Unable to find document file:///p:/perforce_Playground/derekw_de02-1777_rce_dev/tools/crp/bin/crp.py
[Error - 07:21:56] Unable to find document file:///p:/perforce_Playground/derekw_de02-1777_rce_dev/tools/crp/bin/crp.py
[Error - 07:21:57] Unable to find document file:///p:/perforce_Playground/derekw_de02-1777_rce_dev/tools/crp/bin/crp.py
[Error - 07:21:59] Unable to find document file:///p:/perforce_Playground/derekw_de02-1777_rce_dev/tools/crp/bin/crp.py
[Error - 07:29:52] Unable to find document file:///p:/perforce_Playground/derekw_de02-1777_rce_dev/tools/crp/bin/crp.py
[Error - 07:30:33] Unable to find document file:///p:/perforce_Playground/derekw_de02-1777_rce_dev/tools/crp/bin/crp.py

**Comment by MikhailArkhipov** [comment]
Most probably fixed by https://github.com/Microsoft/python-language-server/pull/1002

**Comment by MikhailArkhipov** [comment]
Feel free to reactivate if it is still broken.
