### ISSUE TITLE
Stubs aren't analyzed before their modules

### ISSUE THREAD

**Issue by jakebailey** [microsoft/python-language-server#907]
This affects PyQt5 pretty heavily.

![image](https://user-images.githubusercontent.com/5341706/55762241-1a176800-5a17-11e9-8cdd-c8d135e29adb.png)

![image](https://user-images.githubusercontent.com/5341706/55762253-21d70c80-5a17-11e9-91b3-17c8fa7abafa.png)

This module has a stub next to it, which was added to the module by `TryCreateModuleStub`, but this stub was never analyzed (the state is at `Analyzing`) and has an empty analysis. This leaves the LS to spend all its in the ModuleSymbolTable with 30k+ evaluators to process.

**Comment by jakebailey** [comment]
The underlying issue for PyQt5 actually seems to be the size; we'll probably start treating library stubs specially to help this (but this issue still stands).

**Comment by AlexanderSher** [comment]
No repro so far. Feel free to reopen it if you see it.

**Comment by MikhailArkhipov** [comment]
I can repro it in tests.

![Uploading image.png…]()

**Comment by MikhailArkhipov** [comment]
I think this might be because producer in the walker has all modules in the same list and may happen to produce module before its stub. Perhaps separate higher priority queue of stubs would help or making graph of stubs for the graph of modules and processing it before modules?

**Comment by AlexanderSher** [comment]
Modules can't be produced before stubs unless there is a loop from some stub to that module, which is unlikely. Analysis will be empty if there is an error in analysis itself. In this case, we don't crash LS or terminate analysis session, but there should be a record in the log.

**Comment by MikhailArkhipov** [comment]
Events:
1. Load user module that has `import logging`
2. Module finds `logging` dependency.
3. `logging` dependency loads stub via 
```cs
            if (!TryCreateModuleStub(name, moduleImport.ModulePath, out var stub)) {
                // If nothing found, try Typeshed.
                stub = _interpreter.TypeshedResolution.GetOrLoadModule(moduleImport.IsBuiltin ? name : moduleImport.FullName);
            }
```
4. Stub is loaded and parsing starts. But since there is no await, parsing and analysis of `logging (Library)` starts in parallel.

**Comment by MikhailArkhipov** [comment]
Add
```cs
Debug.Assert(!(_stubAnalysis is EmptyAnalysis))
```
to `ModuleWalker.MergeStub`. Test:

```python
import types
```
![image](https://user-images.githubusercontent.com/12820357/62171183-f38d7d80-b2e2-11e9-975d-7261977cd3ed.png)

**Comment by MikhailArkhipov** [comment]
Need to check with https://github.com/microsoft/python-language-server/pull/1470, may have been fixed.

**Comment by MikhailArkhipov** [comment]
Haven't seen it for a while, there is an assert there that does not trigger.
