### ISSUE TITLE
Problems working with this project on VS Code with a Mac

### ISSUE THREAD

**Issue by Jma353** [Microsoft/python-language-server#911]
Hi all.

I'm trying to build this project from source and work with it on a Mac with VS Code + C# extension.  

I'm having particular difficulty getting C# extension to index the project and provide IntelliSense / other rich editing features when editing the main sub-project of this repo: `LanguageServer`. Other sub-projects in this repo don't have this problem (e.g. I get full IntelliSense when editing `Core` files). 

My situation mirrors this exact issue filed on the OmniSharp extension: https://github.com/OmniSharp/omnisharp-vscode/issues/2763 - in particular, a lot of resources are consumed by `mono` when I open up the `LanguageServer` sub-project.  

Are others having this problem when working with this project on a Mac?  Do most work on this project on a PC?  Is there a configuration issue here?

**Comment by Jma353** [comment]
cc: @MikhailArkhipov.

**Comment by MikhailArkhipov** [comment]
I primarily use Visual Studio on PC or in Parallels on Mac. Sometimes VS for Mac. I do occasionally use VS Code + C# primarily for debugging on Mac and Linux, but not for my main code writing. Yes, I did observe from time to time excessive CPU usage by mono. Reported bugs, some cases did improve, but it still happens.

**Comment by MikhailArkhipov** [comment]
Closing since this is a question rather than a bug in LS.
