### ISSUE TITLE
Throws an exception if workspace/didChangeConfiguration settings is empty/null

### ISSUE THREAD

**Issue by Kaali** [microsoft/python-language-server#915]
It tries to get `python` key from settings even if settings is null. Which makes `Newtonsoft.Json` throw an exception (`Newtonsoft.Json.Linq.JToken.get_Item(Object key) InvalidOperationException`).

**Comment by MikhailArkhipov** [comment]
LS can't work without proper settings such as interpreter path, etc. So this is expected.

**Comment by Kaali** [comment]
I'm sending those in initializationOptions, so the server starts. It just doesn't enable the defaults in didChangeConfiguration because of this exception.

**Comment by MikhailArkhipov** [comment]
OK, it was not clear from the title. Which field is specifically null in your case?

**Comment by Kaali** [comment]
Ah sorry about the unclear report. It happens in `DidChangeConfiguration(JToken token, CancellationToken cancellationToken)` function at line `pythonSection = rootSection?["python"];`, which is `settings["python"]`.

**Comment by MikhailArkhipov** [comment]
@jakebailey worked on settings and related.

**Comment by MikhailArkhipov** [comment]
Hm 
```cs
var rootSection = token["settings"];
var pythonSection = rootSection?["python"];
```
seems to be handling null. Or the `settings` is missing too?

**Comment by Kaali** [comment]
Yes, it fails when the settings is null. It happens for example when using with LSP modes for Emacs.
