### ISSUE TITLE
Runaway memory usage when working with msticpy

### ISSUE THREAD

**Issue by jakebailey** [Microsoft/python-language-server#923]
To reproduce:

1. Clone https://github.com/Microsoft/msticpy
2. Install dependencies in a venv (`pip install -r requirements.txt`)
3. Open `msticpy\nbtools\__init__.py`.

Memory is stable until a point (I think when analyzing plotly) when the memory usage just grows and grows.

**Comment by MikhailArkhipov** [comment]
`Plotly` is the root case.
