### ISSUE TITLE
AstTypeStubPaths* tests produce different analysis results

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/python-language-server#93]
Following #90. During different test runs, produced `ModuleAnalysis` may contain different values for child modules.

**Comment by MikhailArkhipov** [comment]
Actually, many tests that handle references pass on re-run. Most probably b/c there is no sync point on module import completion.

**Comment by MikhailArkhipov** [comment]
Incorrect setting of analysis (old version wins) due to threading issues.
