### ISSUE TITLE
Language server crashes due to Collection was modified exception

### ISSUE THREAD

**Issue by jarshwah** [Microsoft/python-language-server#943]
I'm using the nightly release of the language server, but after spinning up to 100% cpu (400% of 8 cores, 4 of which are dedicated to docker), the server crashes with a `System.InvalidOperationException: Collection was modified; enumeration operation may not execute`

Unfortunately I just lost the stacktrace, because I reloaded the project to see if it was repeatable. It doesn't seem to be repeatable every time, but I've had the server crash twice today already.

From memory, it stalled at "27 items remaining", and just before the crash the log was warning of 4 unused variables.

VSCode Version: `1.33.1`
Python Extension Version: `2019.3.6558`
Language Server Version: `0.2.53`

If the problem happens to me again, I'll add the stacktrace to this issue. I know not working with a trace would be fruitless.

**Comment by MikhailArkhipov** [comment]
Most probably collection of scopes. Looks like module analysis still runs (and adding scopes) while scheduler thinks it is completed and started dependent analysis which led to concurrent access.

**Comment by MikhailArkhipov** [comment]
Or #946

**Comment by MikhailArkhipov** [comment]
Still a problem with https://github.com/Microsoft/python-language-server/pull/947 applied? Should be in 0.2.55+ I believe.

**Comment by jarshwah** [comment]
I haven't seen the collection modified exception since the first time, though the frozen analysis (and high CPU) continued. I see the frozen analysis has been dealt with separately, so let's close this one off.

**Comment by MikhailArkhipov** [comment]
Fixes for looping analysis went in today so 0.2.58+ hopefully resolves your CPU case.
