### ISSUE TITLE
Rename Symbol not working at global scope of a module due to task cancellation

### ISSUE THREAD

**Issue by brettcannon** [microsoft/python-language-server#949]
I have a brand-new module, not referenced anywhere with the following code:
```python
x = 42
```
Unfortunately I can't rename `x` and if I hover over the variable I get a message saying the "task was cancelled".

**Comment by MikhailArkhipov** [comment]
Which download channel?

**Comment by brettcannon** [comment]
beta

**Comment by MikhailArkhipov** [comment]
Appears to be working, rename went long way since.
