### ISSUE TITLE
Add installation instructions to README 

### ISSUE THREAD

**Issue by jgbradley1** [microsoft/python-language-server#953]
I've seen the [build instructions](https://github.com/Microsoft/python-language-server/blob/master/CONTRIBUTING.md). Is it possible to just install this implementation of the python-language-server via pip? If so, can more instructions be added to the README?

This is all great work, but in general, this project has less documentation than the [other](https://github.com/palantir/python-language-server) python-language-server implementation, making it harder to use.

**Comment by MikhailArkhipov** [comment]
Depends what are you trying to install it for. Which editor? LS is not a Python package, it is a .NET Core application. I can be used with clients that support [Language Server Protocol](https://microsoft.github.io/language-server-protocol/) and it is up to the client to decide how to install it. 

We do not provide official downloads for the installation yet (although download URLs are not secret but they can change). So it is recommended for clients to build their own. One of the reasons is that build we use is only tested with VS Code. 

Other clients may not be installing certain dependencies that LS needs on specific OS. For example, some Linux distros require installation of specific dependencies manually or may requite installation of the complete .NET Core Runtime. See https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x.

**Comment by jaybo** [comment]
I second the request.  Or at a minimum provide a some help so users can discover when a show stopper bug in LS (for us it's [#995](https://github.com/Microsoft/python-language-server/pull/995) makes it to the larger world.  Is the latest LS included in every VSCode drop?  In every Visual Studio drop?  
How do we check LS versions?

**Comment by jakebailey** [comment]
There are currently three download channels: daily, beta, and stable. The VS Code Python extension will download the latest version of the language server if is enabled and an update is available for the selected channel (at some interval); it is not included with the editor itself. The decision to create a build and move that build to specific channels is a manual process. (PTVS uses the version in the `release` branch, which is very different and not compatible with `master`, something we're going to remedy.)

You can check the language server version in use by looking in the Python output panel in VS Code; the version is printed at startup. If not, you can find the downloaded build inside the extension's folder.

As for #995, are you saying that the fix itself is a show stopper bug, or what it fixes? (The underlying issue in Cython has been around for a few years and was seen before, perhaps more often now that the new analysis can handle many more cases and potentially looks at more compiled code.)

I think these details are distinct from "installation instructions" in general; it's a bit difficult to describe an "installation" when things are initiated by editors directly. We can certainly improve the build instructions if that's a pain point, and improving the configuration setup is something that is also being worked on (see #469, but we have many other things we're also trying to do).
