### ISSUE TITLE
"Undefined variable" with list unpacking

### ISSUE THREAD

**Issue by tpajenkamp-dspace** [Microsoft/python-language-server#954]
**Environment**
Visual Studio CodeVersion: 1.33.1
Python Extension Version: 2019.3.6558
OS: Windows 10
Python version: 2.7/3.6
Language Server Version: 0.2.47.0

**Actual Behavior**
Given the Python script
```python
def foo():
    [a, b] = (1, 2)
    x1 = a

    (c, d) = (1, 2)
    x2 = c

    e, f = (1, 2)
    x3 = e

    return (b, a)

if __name__ == "__main__":
    print(foo())
```
The line `x1 = a` reports the problem "Undefined variable: 'a' Python(undefiend-variable) [3, 10]".

**Expected Behavior**
No problem.
Interestingly, the other lines do not trigger warnings and even `return (b, a)` is accepted.

**Comment by jakebailey** [comment]
Can you try out the beta build? This should be already fixed there.

```json
"python.analysis.downloadChannel": "beta"
```

**Comment by tpajenkamp-dspace** [comment]
you are right, no problem with 0.2.55.0
