### ISSUE TITLE
python crash

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/python-language-server#957]
@abraham2512 commented on [Thu Apr 11 2019](https://github.com/Microsoft/vscode-python/issues/5222)

Issue Type: <b>Bug</b>

I get python has stopped working message when i see analyzing in background message at the bottom. I only have python extension installed. I assumed it could be because of pylint and disabled but it persists even after that. It pops up multiple times, even though it doesnt affect functionality, its an annoyance. 

Extension version: 2019.3.6558
VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Memory (System)|15.88GB (7.94GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by jakebailey** [comment]
I believe this is #713/#740.
