### ISSUE TITLE
Completion and go-to-source not working right for stdlib socket module.

### ISSUE THREAD

**Issue by ericsnowcurrently** [Microsoft/python-language-server#961]
See https://github.com/Microsoft/vscode-python/issues/5152.

**Comment by MikhailArkhipov** [comment]
#840

**Comment by ericsnowcurrently** [comment]
What about completion?

**Comment by MikhailArkhipov** [comment]
Please specify what completion. Inside the `socket`? Same thing. We are not getting `open file` b/c of the extension. Or usage of the socket in user code?

**Comment by ericsnowcurrently** [comment]
I just thought it was weird that it is showing part of the namespace for completion.  I would expect the #840 bug to result in 0 completion.

**Comment by jakebailey** [comment]
That bug is an extension issue, and doesn't affect completion. Microsoft/vscode-python#5132
