### ISSUE TITLE
“No result" when "peek reference" or "find all reference" in Python file

### ISSUE THREAD

**Issue by karrtikr** [Microsoft/python-language-server#963]
@futurehome commented on [Fri Apr 05 2019](https://github.com/Microsoft/vscode-python/issues/5125)

Issue Type: <b>Bug</b>

No specific operation, just launch code, and open an Python file, when I try to use "peek reference" or "find all reference", it shows "no results". These feature can be used before, maybe 2 months ago. I've disabled all other extensions, it still doesn't work.

![image](https://user-images.githubusercontent.com/6230304/55634987-3e462f80-57f2-11e9-94fd-7ceaeed4af92.png)

Extension version: 2019.3.6352
VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.84GB (9.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

---

@karrtikr commented on [Mon Apr 08 2019](https://github.com/Microsoft/vscode-python/issues/5125#issuecomment-480932738)

Please inform if you are using `jedi` or `language server` as intellisense (i.e check the value of `python.jediEnabled` in settings.json)

---

@Alex206 commented on [Tue Apr 09 2019](https://github.com/Microsoft/vscode-python/issues/5125#issuecomment-481128498)

I have the same problem. Jedi enabled in default, but disabled in user and workspace settings.

---

@karrtikr commented on [Wed Apr 10 2019](https://github.com/Microsoft/vscode-python/issues/5125#issuecomment-481891855)

> I have the same problem. Jedi enabled in default, but disabled in user and workspace settings.

Can you please elaborate? Do you see this issue while using Language server or Jedi. Please paste your `'Python' Output Panel`.

---

@Alex206 commented on [Thu Apr 11 2019](https://github.com/Microsoft/vscode-python/issues/5125#issuecomment-482028157)

I am not using Jedi. Here is the python Output Panel. I removed username and the long search path list:

Starting Microsoft Python language server.
[Info  - 10:36:32] GetCurrentSearchPaths C:\Users\XXX\python.exe 
[Info  - 10:36:32] Python search paths:
[Info  - 10:36:32]     d:\software\XXX_python\python34_original\dlls
[Info  - 10:36:32]     d:\software\XXX_python\python34_original\lib
[Info  - 10:36:32]     d:\software\XXX_python\python34_original
[Info  - 10:36:32]     c:\users\XXX19_2_pure
[Info  - 10:36:32]     c:\users\XXX19_2_pure\lib\site-packages
[Info  - 10:36:32] Configuration search paths:
[Info  - 10:36:32]     C:\Program Files\XXX\bin
[Info  - 10:36:32]     C:\Program Files\XXX\APIs\Python\lib
And so with all the paths...
[Info  - 10:36:36] Microsoft Python Language Server version 0.2.47.0
[Info  - 10:36:36] Initializing for C:\Users\XXX_19_2_pure\Scripts\python.exe
##########Linting Output - pylint##########

--------------------------------------------------------------------

Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)

**Comment by MikhailArkhipov** [comment]
0.2.47 does not have rename or find all references. https://github.com/Microsoft/python-language-server/pull/819 has been only in beta and daily channels until 0.2.55 which was published to stable today.
