### ISSUE TITLE
Analysis continues on old content if file content is replaced by unrelated code

### ISSUE THREAD

**Issue by MikhailArkhipov** [microsoft/python-language-server#975]
Start with
```python
import plotly
```
when analysis starts running, paste over code from #960
```python
import sys
from collections import defaultdict

def xx():
    dmap = defaultdict(list)
    sizes = {db:int(sz)//(1 << 20) for sz, db in [ln.split() for ln in open(sys.argv[1]).readlines()]}
    return {srv:sum([sizes[d] for d in dbs]) for srv,dbs in dmap.items()}
```
Observed: analysis never completes. If there is progress it stops at the same number of items. Or it continues analysis `plotly`

![image](https://user-images.githubusercontent.com/12820357/56255078-4d41a300-6078-11e9-9212-8c67424493d7.png)

**Comment by AlexanderSher** [comment]
Yeah, we aren't unloading modules that aren't referenced anymore. Should we do this btw?

**Comment by MikhailArkhipov** [comment]
Technically yes since otherwise memory consumption will be growing indefinitely. Not super urgent though.
