### ISSUE TITLE
Library function is renamable

### ISSUE THREAD

**Issue by jakebailey** [microsoft/python-language-server#979]
Open `proj` in VS Code. The values from `lib` should be resolved.

Rename `make_foo` in main.py succeeds, but should not.

[librename.zip](https://github.com/Microsoft/python-language-server/files/3091225/librename.zip)

**Comment by jakebailey** [comment]
Debugged the call, `make_foo`'s declaring module is null, which means that it gets treated as an empty analysis, which means that it isn't library code. It should have a declaring module.

**Comment by MikhailArkhipov** [comment]
Goto definition is acting up too.
