### ISSUE TITLE
'Undefined variable' when the variable is defined in the same block or passed as argument

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/python-language-server#980]
Everything in the else block show up as undefined.
```py
try:
    import dis
except ImportError:
    def _get_code_lines(code):
        raise NotImplementedError
else:
    def _get_code_lines(code):
        if not isinstance(code, types.CodeType):
            path = code
            with open(path) as f:
                src = f.read()
            code = compile(src, path, 'exec', 0, dont_inherit=True)
            return _get_code_lines(code)

        def iterate():
            # First, get all line starts for this code object. This does not include
            # bodies of nested class and function definitions, as they have their
            # own objects.
            for _, lineno in dis.findlinestarts(code):
                yield lineno

            # For nested class and function definitions, their respective code objects
            # are constants referenced by this object.
            for const in code.co_consts:
                if isinstance(const, types.CodeType) and const.co_filename == code.co_filename:
                    for lineno in _get_code_lines(const):
                        yield lineno

        return iterate()
```

![image](https://user-images.githubusercontent.com/3840081/56319330-36ea2480-6116-11e9-98e7-176dc31414f7.png)

**Comment by marvingreenberg** [comment]
![undefined](https://user-images.githubusercontent.com/216707/56810329-02582600-6804-11e9-925b-6c45dc45ab0e.png)

This demonstrates the same issue - it seems to be any function definition in any conditional clause.

**Comment by marvingreenberg** [comment]
![more_examples](https://user-images.githubusercontent.com/216707/56810936-8bbc2800-6805-11e9-9e53-4eafbf12fa3f.png)

I think the issue title should be "Undefined variable when defining methods in conditional".  This shows some more examples

**Comment by jakebailey** [comment]
Found it; the undefined variable walker walks the top level suite statement only, which means that when it recurses to look inside other nodes, it doesn't see anything below it, so never opens the scope for the nested function. Any scope creating node (class, function) that's not at the top level won't have its scope opened so its variables won't be defined.

**Comment by jakebailey** [comment]
For what it's worth, if you'd like to disable this in the meantime you can throw this into your config:

```json
"python.analysis.disabled": [
    "undefined-variable"
]
```

**Comment by yaay1010** [comment]
my code also does the same :(

example = 0

def foo():
      example += 1
