### ISSUE TITLE
Class construction should show arguments from __init__

### ISSUE THREAD

**Issue by karrtikr** [microsoft/python-language-server#983]
@JulianS-Uni commented on [Fri Apr 12 2019](https://github.com/Microsoft/vscode-python/issues/5223)

## Environment data

- VS Code version: 1.33.1
- Extension version (available under the Extensions sidebar): XXX
- OS and version: Windows 10 1803
- Python version : 3.7.2
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): None
- Relevant/affected Python packages and their versions: every package

## Expected behaviour

When importing a class and creating an instance/object of this class we got a small preview how to use this object. (This is from Python extension for Visual Studio Code Version 2019.3.6352)
![Unbenannt](https://user-images.githubusercontent.com/38244898/56020310-26e1d780-5d07-11e9-88be-373cd9c90dda.png)

## Actual behaviour

With Python extension for Visual Studio Code Version 2019.3.6558 (most recent build) it does nothing.
![Unbenannt2](https://user-images.githubusercontent.com/38244898/56020701-07977a00-5d08-11e9-9897-b70f526779e6.png)

## Steps to reproduce:
1. Type following code and look if youget the preview:
```
import threading

threading.Thread()
```

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
None
```   

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
None
```

---

@DonJayamanne commented on [Fri Apr 12 2019](https://github.com/Microsoft/vscode-python/issues/5223#issuecomment-482724841)

Looking at the screenshot you haven't clicked the `Reload Required` button.
Please reload VS Code and test once again.

---

@phizaz commented on [Sun Apr 14 2019](https://github.com/Microsoft/vscode-python/issues/5223#issuecomment-482936547)

@DonJayamanne I can confirm this. This happens to me lately (I'm using 2019.3.6558). Interestingly, it only happens to classes, not functions.

---

@JulianS-Uni commented on [Sun Apr 14 2019](https://github.com/Microsoft/vscode-python/issues/5223#issuecomment-482944705)

@DonJayamanne Yes you are right, but thats not the issue. I just upgraded back to 2019.3.6558 for the screenshot but had the "bug" before.
@phizaz Thanks for your confirmation. Strangely I have the behaviour now with 2019.3.6352 too. Maybe it is something else causing this issue. Do you use platformIO too? Thats the only thing i changed recently.

---

@phizaz commented on [Sun Apr 14 2019](https://github.com/Microsoft/vscode-python/issues/5223#issuecomment-482961898)

@JulianS-Uni  No, I don't use platformIO. I also tried to disable many other extensions but to no avail. 

---

@karrtikr commented on [Mon Apr 15 2019](https://github.com/Microsoft/vscode-python/issues/5223#issuecomment-483349950)

Please inform if you are using Language server or jedi as intellisense. (i.e check the value of `python.jediEnabled` in settings.json)

---

@phizaz commented on [Mon Apr 15 2019](https://github.com/Microsoft/vscode-python/issues/5223#issuecomment-483489936)

@karrtikr  I use the Language Server (`python.jediEnabled = False`).

---

@JulianS-Uni commented on [Mon Apr 15 2019](https://github.com/Microsoft/vscode-python/issues/5223#issuecomment-483535129)

Without checking i am pretty sure i am using languageserver aswell. It tells me that it is building vor downloading languageserver in the statusbar from time zto time.

**Comment by MikhailArkhipov** [comment]
OK, `threading` appears to work for me in the current master

![image](https://user-images.githubusercontent.com/12820357/58056699-ef8cf480-7b16-11e9-871d-5595afd5dbe4.png)

and so is example from #996 and #1104

![image](https://user-images.githubusercontent.com/12820357/58056887-98d3ea80-7b17-11e9-9e5c-addc5d7780f1.png)

![image](https://user-images.githubusercontent.com/12820357/58056895-a8533380-7b17-11e9-8dd3-7c5b7fb9d27c.png)

**Comment by jakebailey** [comment]
No luck for me:

![image](https://user-images.githubusercontent.com/5341706/58057294-2fed7200-7b19-11e9-8dcf-f5046f9df05a.png)

The class itself has docs in the completion:

![image](https://user-images.githubusercontent.com/5341706/58057317-4a275000-7b19-11e9-8178-567e9bca49ee.png)

No signature help happens; if I manually trigger a completion with Ctrl-Space, I get the global scope completion:

![image](https://user-images.githubusercontent.com/5341706/58057352-6aefa580-7b19-11e9-8212-29f394cab11f.png)

```
[Trace - 4:08:15 PM] Sending request 'textDocument/signatureHelp - (50)'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Users/jabaile/test_projects/tentest/main.py"
    },
    "position": {
        "line": 10,
        "character": 23
    }
}

[Trace - 4:08:15 PM] Received response 'textDocument/signatureHelp - (50)' in 1ms.
No result returned.
```

Using 3.6.6.

**Comment by jakebailey** [comment]
Stepping through shows that in SignatureSource, `value` comes out to be the class Conv1D, but since it's not IPythonFunctionType, `ft` is null and the return happens early.

**Comment by jakebailey** [comment]
With a fix (PR coming):

![image](https://user-images.githubusercontent.com/5341706/58058383-9d9b9d00-7b1d-11e9-9f4c-8a1b709b8cbf.png)

**Comment by aaveidt** [comment]
@jakebailey it doesn't work like function?
When typing function name, it displays arguments on the popup, with class it shows class only.

<img width="621" alt="Screen Shot 2019-05-24 at 3 03 40 PM" src="https://user-images.githubusercontent.com/5781080/58312326-46efd500-7e35-11e9-8087-7c30b1594a3a.png">
<img width="655" alt="Screen Shot 2019-05-24 at 3 03 32 PM" src="https://user-images.githubusercontent.com/5781080/58312327-46efd500-7e35-11e9-9295-5a6fbcd20600.png">

**Comment by jakebailey** [comment]
Those are completion items, rather than "signature help". We don't show any signature information for the class because we're only "completing" the class name; so we only show documentation for the class. When you go to "call" it, you get the info then (add `()`).

We can likely change this to include that information, but it's more complicated from the perspective of the class having a docstring, the initializer having a docstring, and the initializer having a signature. For functions, we can show the signature and "the" docstring, but on classes with two docstrings, presenting the initializer docstring unconditionally means that the class docstring will never be shown. Right now, you can get all of them in their respective contexts.

**Comment by aaveidt** [comment]
@jakebailey Hi Jake, it's nice to have you to reply. Can we show docstring if it exists and show argument if itsn't. 
Besides i can't see the argument completion while typing argument on Class, but method does have it

<img width="617" alt="Screen Shot 2019-05-26 at 4 56 31 PM" src="https://user-images.githubusercontent.com/5781080/58380117-64f53b00-7fd7-11e9-95ed-28550c763353.png">
