### ISSUE TITLE
os.getenv signature help misses second argument

### ISSUE THREAD

**Issue by Yanpas** [microsoft/python-language-server#985]
`Ctrl+Shift+Space` hotkey shows you function signature, but `os.getenv` has two arguments:
![image](https://user-images.githubusercontent.com/7345761/56359291-cca2b400-61e9-11e9-863c-871328d8c5ba.png)

Real signature `os.getenv(key, default=None)`

using beta

**Comment by jakebailey** [comment]
We're pulling those signatures from typeshed, which specifies two overloads. When you look at the second of the two (note the "1/2" at the left), does it look more reasonable?

https://github.com/python/typeshed/blob/f06f2e97bb57e06d6a790f8a1dcf305d055bfc8c/stdlib/3/os/__init__.pyi#L356

**Comment by Yanpas** [comment]
The second is weird
![image](https://user-images.githubusercontent.com/7345761/56376587-f0c5bb80-6210-11e9-8296-28e259544a6e.png)

**Comment by jakebailey** [comment]
Currently, we have:

![image](https://user-images.githubusercontent.com/5341706/67509314-95550a00-f647-11e9-8429-914b8c02f235.png)
