### ISSUE TITLE
Provide a way to determine the version/date of the latest release of Language Server

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/python-language-server#99]
This is necessary to enable the following (https://github.com/Microsoft/vscode-python/issues/2580).

Basically all we need is:
* Is there a new version of the language server published online?

**Proposal:**
* Upload a text file `latest_version.txt` with the version info, to the location https://pvsc.blob.core.windows.net/python-language-server
* When ever VSC downloads a language server we can capture the latest version info from the `latest_version.txt` file
* Next time we just download the `latest_version.txt` and compare it against the previously downloaded info.
* If the new version is **DIFFERENT**, then we download the packages.

This sounds like a KISS solution. I don't think we should complicate it.
Either way, i'd like a very simple and easy way of determining this from the extension, hence the suggestion for the text file.

Also, I believe generating and uploading the text file can be automated into the CI pipeline. I.e. no coding, just CI.

**Comment by DonJayamanne** [comment]
@MikhailArkhipov 
Please change the priority as you see fit.
I'd like to complete the VSC side of things early next week, if not monday :)

**Comment by MikhailArkhipov** [comment]
@AlexanderSher handles the build definition so I am passing it over :-)

**Comment by MikhailArkhipov** [comment]
It is implemented
