### ISSUE TITLE
Regression in PYTHONPATH support

### ISSUE THREAD

**Issue by chdsbd** [Microsoft/python-language-server#993]
It seems that it is no longer possible to set PYTHONPATH and have that respected for imports.

Here's a small repo that should reproduce the issue: https://github.com/chdsbd/vscode-pythonpath-reproduction

I think this may be related to https://github.com/Microsoft/python-language-server/issues/849

**Comment by jakebailey** [comment]
I'm a bit confused by this test case; should `test_foo` have read `from core.foo import Animal`?

![image](https://user-images.githubusercontent.com/5341706/56392831-62890f80-61e7-11e9-8321-894e03628827.png)

**Comment by chdsbd** [comment]
This is what it looks like for me: 
<img width="337" alt="Screen Shot 2019-04-18 at 5 38 11 PM" src="https://user-images.githubusercontent.com/1929960/56392930-d2f05a80-6200-11e9-8a34-facf78da5661.png">

**Comment by jakebailey** [comment]
I know, but there is no such module `core.fields`. It's in `foo.py`.

**Comment by chdsbd** [comment]
whoops, yeah, that's from me trying to cut this down. I'll reopen this when I fix the reproduction.

**Comment by jakebailey** [comment]
No problem. I'd also like to know your OS, as we might have different setups.

I also run using the `master` branch of the extension directly, not the release, which may impact things as well. I made a PR there a few weeks ago which modifies the startup process when it comes to these sorts of paths.

**Comment by chdsbd** [comment]
I'm running macOS 10.13.6 with Python 3.7, VSCode 1.33.1, and python language server 0.2.59.0

Fixing the typo apparently still leads to an unresolved import issue:

<img width="364" alt="Screen Shot 2019-04-18 at 6 04 38 PM" src="https://user-images.githubusercontent.com/1929960/56394244-b48c5e00-6204-11e9-9ee8-4a2e4478ff58.png">

I've push the fix to [the repo](https://github.com/chdsbd/vscode-pythonpath-reproduction) I linked above.

**Comment by jakebailey** [comment]
With what you have in that repo, it works for me. My OS is Windows, but I'm willing to bet that it's an extension version difference that's doing this and not the OS (but I'll be checking). Would you be willing to try out running the extension at `master`? See: https://github.com/Microsoft/vscode-python/blob/master/CONTRIBUTING.md

You might also be able to test the "development build", though I don't know which revision it's built from.

**Comment by chdsbd** [comment]
I just tried it with the `2019.5.6925-dev` [development build](https://github.com/Microsoft/vscode-python/blob/master/CONTRIBUTING.md#development-build) and everything seems to work well now. 
Thanks for the help.

**Comment by jakebailey** [comment]
That's good news; thank you for checking.
