### ISSUE TITLE
Can't Autocomplete Class init parameters

### ISSUE THREAD

**Issue by zhen8838** [Microsoft/python-language-server#996]
os : ubuntu 18.04.2
vscode version : 1.33.1
It can't autocomplete the `init` parameter, I cost much time in reading python lib's documents. 
![](https://i.ibb.co/b6Qgng0/clsparam.gif)

**Comment by billlu1984** [comment]
I have the same issue. It seems unable to pick up class constructors

**Comment by MikhailArkhipov** [comment]
Folding into #987
